<?

// https://archive.org/stream/danishspeakerpro00bojeuoft/

	$danishLines = array(
"Glorious unity.",
"This writing is small.",
"An important thing. A parliament. A witness.",
"Peace of the heart.",
"The girl's wit.",
"The fire sparkles.",
"The wind howls.",
"The prosperity was short",
"there will be a meeting of clergymen to-morrow.",
"The spot will disappear.",
"His word is my shield.",
"The soldiers were well paid,",
"An old he-goat, he made a deep bow,",
"to bow before a he-goat.",
"The dog's master.",
"The Lord's commandment.",
"The week of sighing.",
"The quickness of sound.",
"The thief's luck.",
"A shadow of probability.",
"The calf of the leg is different from a dogs-ear,",
"A lash can give a slash.",
"The guardian has a weapon,",
"the watchman is a guardian and has a weapon.",
"He has a pain in his limbs",
"He is a donkey,",
"the boy has a fine donkey,",
"The bad consequences,",
"the splendid retinue,",
"the consequences of the retinue's behaviour.",
"The darkness of the death.",
"The children's need.",
"put the key and the reel together.",
"put a nail in that seam.",
"the counsellor gave bad advice.",
"A year, about a year, year after year.",
"the cover of a cushion is useful also in the spring.",
"A ray in the hut of poverty.",
"The child prays.",
"The flower smells.",
"The peasant builds.",
"The christening of a child.",
"A bed of flowers.",
"A peasant's farm.",
"The brewer's order.",
"the Bride's castle.",
"the break of the wave.",
"The boy is idle.",
"The day is divided.",
"Virtue is blamed.",
"Death and judgment.",
"The daughter's death.",
"The fool's dream.",
"The father remonstrates;",
"The prisoner escapes;",
"The enemy is embittered;",
"danger of relations.",
"The falcon's flight.",
"The peace of the author.",
"The fruit of industry.",
"The Count reflects.",
"The tomb conceals.",
"The miser's gold.",
"The researcher's tomb.",
"The gardener digs.",
"Fulness of the Godhead.",
"The way of the marriage.",
"The house sinks.",
"The horse takes rest.",
"The puppy whines.",
"A heartfelt grief.",
"
The sea's secret.",
"The stag's horn,",
"The hunter is cheerful",
"The young gentleman's gun.",
"Christmas-cheer.",
"The girl's guiding star.",
"The church calls.",
"The woman kneels.",
"The man-servant grumbles.",
"The well of strength.",
"The sound of the bell.",
"The laws guide.",
"The reward attracts.",
"The King lives.",
"The warbling of a lark.",
"A refreshing beverage.",
"A village church.",
"The life's pleasure.",
"The noise of the lion.",
"The artifice of mountain-sprites.",
"The man paints.",
"The mother measures.",
"The miller grinds.",
"A maternal language.",
"Man's courage.",
"
The man's pity.",
"The lameness of the lamb.",
"Nature maintains.",
"Want depresses.",
"The key is useful.",
"A gracious gift.",
"Any whatever.",
"The news of night.",
"The nature of brownies.",
"The first moonlight in the year.",
"The peacock parades.",
"The clergyman preaches.",
"The letter carrier is accustomed to.",
"The cover of a pot.",
"The girl's guinea-hen.",
"The poodle's paw.",
"The state is raised.",
"The fox robs",
"The robber is furious.",
"Drizzling rain.",
"The colour of the currant.",
"The rich man's troubles.",
"The sun shines.",
"Destiny is deceitful.",
"The son writes.",
"The bounds of grief.",
"The singers of the forest.",
"The tree grows.",
"The time is threatening.",
"The advocate of discord.",
"The servant's thanks.",
"The consolation of faith.",
"The weather is changeable.",
"The wind waves.",
"The world is busy.",
"Witness.",
"An omen of good-will.",
"The cradle of eloquence.",
"The wise man's way.",
"The happy boy's game.",
"The learned man's advice.",
"the old promise.",
"A foot and a hand.",
"A cow and a sow.",
"A claw and a toe.",
"Old cards.",
"Bad things, worst things.",
"money, more money.",
"I read, we read.",
"Thou readest my book.",
"You read our books.",
"He reads thy book.",
"She reads thy books.",
"They read your books.",
"Hast thou my knife?",
"Has she my basket?",
"Have they my money?",
"We have not your paper.",
"You have not their knowledge.",
"They will not stay:",
"She bathes.",
"They bathe.",
"They bathe them.",
"They dress.",
"They dress them.",
"He saw his own children.",
"He saw another person's children.",
"She took her money.",
"She took another person's money.",
"I beat them.",
"They beat me.",
"He praised her.",
"She praised him.",
"Thou lovest her.",
"She loves thee.",
"That man,",
"What book?",
"The one which you know.",
"What country?",
"That towards the North.",
"People, whose hope is on the earth.",
"Books whose contents are useful.",
"They say.",
"Every one is happy.",
"All pray.",
"Thou drinkest,",
"they drink.",
"She prays,",
"we pray.",
"He asked, she listened, they grumbled.",
"I have taken my dinner.",
"We have taken our tea.",
"Thou hadst read the letter.",
"You had slept.",
"He is going to fight.",
"They may fight, struggle.",
"I should sail.",
"We should be obliged to throw.",
"Go!",
"eat!",
"Think!",
"He comes willingly.",
"She will soon go away.",
"They read well.",
"Everywhere and nowhere.",
"Upwards and downwards.",
"At home and homewards.",
"He can not come.",
"Have you been here long?",
"The picture is behind the door.",
"Go away from the window.",
"Come to me.",
"The book lies upon the table.",
"My wife and my child.",
"He is always too late.",
"Either you or I may call on them.",
"Neither my pen nor my purse are to be discovered.",
"If you see her, pray remember me kindly to her, though she now is a great Lady.",
"the beams or rays of the sun.",
"a flash of lightning.",
"thunder.",
"a thunderclap.",
"Is Mr. A. at home?",
"I believe he is.",
"May I ask your name?",
"Here is my card.",
"Walk in, if you please,",
"Please, walk in.",
"Excuse me, Sir.",
"I beg you to excuse me.",
"Will you do me the favour?",
"Wait a moment.",
"I shall be with you in  a moment.",
"Good morning, my friend.",
"Good morning, good morning!",
"May I trouble you for a moment?",
"Excuse my troubling you, Sir",
"I beg you a thousand pardons.",
"May I believe my eyes.",
"I am delighted to see you.",
"Where do you come from?",
"You have chosen your time well.",
"You wish to speak to me?",
"I urgently want to speak to you.",
"I am at your service.",
"With pleasure;",
"What do you want?",
"I am waiting your commands.",
"I am very much obliged to you.",
"I am very much obliged for your kindness.",
"You are very kind.",
"Remember me to your mother.",
"My compliments to Mrs. A.",
"My compliments to your mother.",
"Will you give my kind regards to your grandfather.",
"Certainly.",
"I thank you very much.",
"Remember, it always gives me great pleasure to see you.",
"Good bye.",
"How do you do?",
"Thank you, I am quite well, and you?",
"I am suffering from a cold.",
"Pray sit down;",
"Are you not fatigued?",
"No, not at all.",
"How is your mother?",
"Pretty well.",
"I thank you.",
"And your dear old aunt?",
"She is but poorly.",
"Her cough is very troublesome and her state of health is uncertain.",
"She is not longer young.",
"She is seventy years of age.",
"Indeed, she does not appear to be so old.",
"In two months she will be seventy one years old.",
"I took her to be ten years younger.",
"Appearances often deceive.",
"My grandfather is only sixty-four years old and has a strong constitution, but he nevertheless looks older than my dear aunt.",
"Your father will soon be back, I hope?",
"It depends upon circumstances.",
"Now I must wish you good bye",
"I am very glad to have seen you.",
"Remember that I am an old friend of your father, and your godfather.",
"Certainly;",
"You are very kind, good bye.",
"Pray, ring the bell if the servant is not in the hall, and he will attend you directly.",
"Do you think of going abroad this year?",
"To be sure, we intend to go to the North of Europe.",
"Will you go with us?",
"I should be happy to do so, if the time of your departure will suit my business arrangements.",
"I believe we shall leave England in a fortnight.",
"What a fortunate thing!",
"it is just the time when I shall take my holydays.",
"Where shall you stay during the summer?",
"We intend to stay for some months at the sea-side in Denmark.",
"At what Danish sea-coast, pray?",
"I think on the Sound.",
"Do you believe there are some good and comfortable bathing-places?",
"Yes, I am quite sure.",
"A Danish artist, for the moment in London, told me there are several.",
"Do you know the names of some of them?",
"I remember the names of Marienlyst and Klampenborg.",
"And may we expect to find ourselves comfortable there?",
"I have his word for it.",
"As far as I understand, Marienlyst is the best spot as far as comfort is concerned.",
"How far is it from Copenhagen?",
"About twenty five English miles.",
"And Klampenborg?",
"Is only five or six miles.",
"Are these two the only bathing-establishments on the Sound?",
"I think so; but my Danish friend told me that along all the coast there are villas and small fishing-towns, and that almost each villa and each little village is a bathing-place.",
"Capital, then we may make a choice.",
"Do you think living is expensive in Denmark?",
"Not so expensive as at the sea-side in England.",
"My friend promised me some days ago to put down some of the most common expenses, by which I may estimate, what we shall have to pay.",
"And what are the means of conveyance?",
"There are railways in the island of Sealand;",
"you know this is the main island.",
"Are there railways only on this island?",
"There are also in Jutland but only for some short distances, but before the end of this year, I understand, more railways will be finished there, as well as in the beautiful island Funen.",
"This will not help us this summer, if we intend to travel about Denmark.",
"But it will be profitable to us next year, and an English author says, that the Danish sea-baths once tried and their invigorating qualities felt, nobody will hesitate to go there again.",
"Do you know anything about the arrangements of steamers in Denmark?",
"To be sure.",
"The arrangements are capital, for as Denmark partly consists of islands, every part of it is encircled with a network of steamers.",
"And we can glide on the surface of the Sound whenever we like to do so?",
"If not at any hour, at least several times in the day.",
"Well, and how are the steamboats?",
"Of course, they are very small.",
"Not so large as the boats running along the Thames.",
"About of the same size as the penny-boats, and good boats, I understand.",
"Will these boats go from Copenhagen to Marienlyst in an hour?",
"No, if I remember, it takes two hours, as the boats stop at many places.",
"I suppose, there is a landing-pier at Marienlyst?",
"Not close to the place, but a very short distance from it.",
"The steamers stop at Elsinore, about half an English mile from Marienlyst, and every quarter of an hour there is a conveyance between the two places.",
"How are the environs of Marienlyst?",
"Rich in natural beauties and historical monuments.",
"I know, the last are no less an attraction for you than the first.",
"And you are right.",
"Tell me the names of any historically remarkable spots, if you know.",
"I know some few.",
"That of Kronborg, you know yourself.",
"Else I should not know anything about the Sound duty or about...",
"About what?",
"About a young unhappy Danish Queen, before her marriage an English princess.",
"Some more names, please!",
"The castle of Gurre in the most charming landscape, Odins hill, Frederiksborg, Fredensborg and Soøborg; these names I know, but undoubtedly there are many more interesting and remarkable places.",
"And Sweden is a very short distance off?",
"I have been told that the Sound is so narrow there, that one may see very distinctly the buildings in Helsingborg.",
"Indeed!",
"How long does it take to cross?",
"In twenty minutes one may run across.",
"Well!",
"that may justly be called neighbouring states.",
"So they are!",
"Amongst the delightful attractions at Marienlyst, Klampenborg or some other places near the Sound, are to be named the numerous vessels gliding at all times along the coast;",
"sometimes several hundreds in one day.",
"To be sure, it must be a charming sight.",
"They glide with their expanded sails along the soft blue waters like a flock of white swans.",
"A delightful sky above, a beautiful sea beneath them.",
"You make me long for yonder sea-side in the North, and I have quite made up my mind to go with you, please God.",
"And I will take care to get the information about travelling expenses before we meet again.",
"Well, now we are at last on board to cross the North-Sea.",
"When shall we be in Hamburgh?",
"Generally the crossing takes from 40 to 48 hours.",
"And how shall we go from Hamburgh to Copenhagen?",
"For years steamers run daily between Kiel, a town on the north coast of Holstein, and Korsoer in Sealand.",
"And from Hamburgh to Kiel?",
"The railway will carry us in 3 hours 15 minutes.",
"How long will it take to cross from Kiel to Korsoer?",
"About 6 hours.",
"Korsoer is a large town, I suppose?",
"No, one of the small Danish towns;",
"as a thoroughfare it is convenient as possible, for the steamers stop opposite the hotel \"Store Belt\" and at the back of the building lies the railway.",
"Very good!",
"How's the hotel?",
"A very good one; and Mr. Petersen, the proprietor, is an obliging man, ready to assist passengers in every way.",
"How long does it take to travel from Korsoer to Copenhagen?",
"The passenger train takes 3 hours 15 minutes, and the luggage train about 4 hours 30 minutes.",
"What is the distance?",
"About 60 English miles.",
"I see that they travel very slowly on the Danish railways.",
"No doubt, but one is safe there.",
"As for me, I prefer the English quickness to the Danish slowness.",
"So I do, but one's life is never secure on the English railways;",
"on the Danish an accident very seldom happens.",
"I dare say you have got very distinct information from your Danish friend.",
"Are you acquainted with the value of the Danish coins compared with the English, and with the small current expenses of the journey?",
"To be sure;",
"but now I must look after my luggage and pay the passage.",
"It is 2£ for the first cabin, I know.",
"Yes, and if you wish to pay for the board during the crossing, you are allowed to do so.",
"What is the amount?",
"Twelve shillings, about 5 Rd. 40 ß Danish money.",
"Everything included?",
"All the meals, but wine and ale are to be paid for extra.",
"Do you think, we shall be sea-sick?",
"It is impossible for me to tell you.",
"Is this the first time you have been at sea?",
"Not exactly, but I have never made so long a voyage before.",
"Are you given to sea-sickness?",
"Alas!",
"Just now I feel unwell.",
"And we are still in the harbour.",
"But the sea is very rough.",
"Methinks, it is very calm, but I give you advice to lie down immediately.",
"If I have only a good berth.",
"I will call the steward;",
"he must bring you a glass of brandy and water;",
"it is a capital remedy as you now are.",
"I think the motion is less.",
"You have slept for several hours and I think you find it so, because you are in the berth.",
"We are now entering the Elbe.",
"How long will it be before we are in Hamburgh?",
"Seven or eight hours, I believe.",
"Thanks.",
"Now the steamer stops; do you hear they are letting off the steam.",
"The voyage has not been so unpleasant as I supposed.",
"When will the train start?",
"In ten minutes.",
"Will you take our tickets?",
"Certainly!",
"Please to give me two second class tickets for Kiel.",
"Why do you not take first class tickets?",
"Because second class in Denmark and Germany is as good as first class in England.",
"What does the ticket cost?",
"What is the prize for the ticket?",
"Three Prussian dollars, about 9 shillings.",
"How much luggage have we free?",
"Fifty pounds weight.",
"My luggage consists of one trunk and a carpet bag.",
"And mine is a trunk and a hatbox.",
"Take your seats, gentlemen!",
"Here we are at the first station.",
"How long do we remain here?",
"Ten minutes.",
"This is the last station.",
"Tickets, please.",
"Are we already at Kiel?",
"Here are our tickets.",
"Now we are in a carriage again after crossing the Baltic.",
"What is the fare for the passage from Kiel to Korsoer?",
"Four Rigsdalers.",
"And from Korsoer to Copenhagen the ticket costs 3 Rd. 40 ß, as you said;",
"I don't know what this sum is in English money.",
"I will teach you.",
"In a few words I will tell you distinctly what the Danish coins are worth in English money.",
"I am very much obliged to you for this trouble;",
"it will be a useful lesson.",
"In Denmark they only have paper, silver and copper money.",
"No gold?",
"Only in foreign coins.",
"A Specie is 2 Rigsdalers, a Rigsdaler contains 6 Marks, and a Mark 16 shillings, half a Mark is 8ß and so on.",
"Is that all?",
"Then there are paper-notes worth 5 Rd., 10 Rd., 20 Rd., 50 Rd. and 100 Rd.",
"How many Rigsdaler is the Sovereign worth?",
"Nine.",
"Thank you!",
"Now I dare say I shall not be mistaken in these foreign coins.",
"I dare say you will not.",
"Our luggage will be examined in the custom-house, I suppose.",
"Of course.",
"I have my own wearing apparel, nothing more.",
"Have you anything to declare?",
"Nothing whatever.",
"Open your trunk, if you please.",
"As far as I know I have nothing to declare.",
"Now I think we may lock it again.",
"How long it is before our luggage is examined.",
"People in this country are not quick-runners, you see.",
"Will you get us a good cab, please.",
"To which hotel shall we go?",
"You know, that three hotels have been recommended to us as very good ones: Hotel d'Angleterre, Hotel Royal and Hotel Phoenix.",
"Well, I think we will go to the Phoenix.",
"Have you any rooms?",
"Yes, Sir.",
"We want a sitting-room and two bed-rooms.",
"Very well.",
"Sir.",
"We are willing to take a double-bedded room on the second floor, but the sitting-room must be on the first.",
"I will give you the choice of the best apartments.",
"Will you take the luggage to our rooms, please.",
"In a minute, Sir.",
"We should like to go to bed early and beg you to let us have a good fire.",
"Certainly.",
"Let us be called at 6 o'clock, please.",
"At 6 o'clock?",
"Yes, we are early risers;",
"at 8 o'clock we shall be ready for our breakfast.",
"Pray, will you order your breakfast now.",
"We want coffee, bread and butter, two boiled eggs and broiled bacon.",
"Very well, Sir, I shall remember.",
"Don't give us buttered bread, pray, but bread and butter.",
"You understand?",
"Perfectly.",
"No meat?",
"Thank you, we also want some cold meat.",
"Very well.",
"Can we dine at table d'hote, and at what o'clock?",
"Wait.",
"At three o'clock.",
"But I suppose we can dine a la carte.",
"If you please.",
"Waiter, give me the bill of fare.",
"Have you no list of wines?",
"Give us for our dinner a good soup, some roast meat, a leg of mutton we prefer, some vegetables, potatoes, cauliflower and pease for instance, and as delicious a pudding as you are able to make.",
"You can have what you like, Sir.",
"For our supper we shall want tea, cold meat, lobster, cheese, bread and butter.",
"Pray, give us some candles of the best quality.",
"We wish to have some gold changed into Danish coin.",
"Will you change 20 sovereigns partly in Danish banknotes, partly in silver?",
"Immediately, Sir.",
"We wish to see some of the curiosities in Copenhagen;",
"can we have a valet-de-place or guide?",
"Certainly.",
"A man to depend upon?",
"Of course.",
"What does he charge the day for his services?",
"From 1 to 3 Rigsdaler according to time.",
"He must be well acquainted not only with the town, but also with the environs.",
"And so he is.",
"We wish to see the different museums, Copenhagen boasts of, and to spend there the hours in which they are open to the public.",
"If you please",
"To which can we go to-morrow after breakfast?",
"to Thorwaldsens?",
"If you please, Sir.",
"When will it be allowed to visit the ethnological Museum, the Museum for the natural history, and that for the northern antiquities?",
"Generally they are open from 12 to 2.",
"Every day?",
"Yes, but not all on the same days.",
"And then we wish to be acquainted with the different libraries in Copenhagen.",
"Very well, Sir.",
"We also intend to visit the most remarkable churches, some public buildings and statues.",
"The guide is acquainted with them all.",
"Is it allowed to visit the Royal palaces?",
"I really don't know, Sir.",
"At what time are the picture-galleries open?",
"In the morning, I believe.",
"We intend to go by rail to the park tomorrow, from thence further on towards the North to enjoy the beautiful scenery, and at last sleep at night at Frederiksborg.",
"Very well, Sir.",
"We must not forget to visit the benevolent institutions and the hospitals.",
"Ah!",
"Don't forget to let us take a trip to Amager;",
"we want to see that island, the kitchen garden of Copenhagen, and the descendants of the Dutch who retain the habits and dress of their forefathers to this day.",
"Is the island far away?",
"I don't think so.",
"Waiter, can you tell us something about the island of Amager?",
"Indeed, I don't know.",
"How far away from Copenhagen is the island?",
"How far away?",
"Yes; or how long will it take to go from this hotel to Amager?",
"How long time?",
"Of what size is the island?",
"Of what size the island is?",
"There is a knock at the door.",
"You are mistaken, for the door stands ajar and nobody is to be seen, but there is a ring.",
"Shall I lock the door?",
"Never mind it; but tell me something about Amager, please.",
"Willingly, if only I knew.",
"But is there not another knock?",
"I don't think so, but the bell has rung twice.",
"I know, it is Nr. 14; but the gentleman there must learn to wait.",
"Learn to wait, you say?",
"I beg your pardon!",
"I suppose — I meant — the island of Amak, you said!",
"Indeed, I don't know, I have never been there.",
"Fortunately the proprietor of the hotel is coming just now;",
"he may be able to tell you every thing you wish to know better than I.",
"The English gentlemen want to speak to you, Mr. King.",
"The waiter was happy to see you, Mr. King.",
"I am afraid he has been very much puzzled about some questions I put to him concerning the island of Amager.",
"Why do you think so, Sir?",
"Because his answers were but a repetition of my questions.",
"Without the least information.",
"I am quite sure he did not intend to be uncivil, poor fellow; but he is rather awkward, and perhaps he does not know anything about the island.",
"But he knows the name at least.",
"Of course.",
"I dare say he also knows some \"Amagerpiger\".",
"What does that word mean, please?",
"Women from the island, a sort of wandering greengrocers.",
"How singular.",
"I shall be much obliged to you, Mr. King, if you will be so good as to tell me something about the island and its inhabitants.",
"Willingly!",
"I shall be happy to give you every information as far as I am able to do so.",
"Thank you.",
"Pray, tell us first, if the inhabitants really retain the ancient costume as worn by their Friesland forefathers, and if they maintain the same high reputation for industry as the first colonists.",
"They do;",
"as for the dress, it is a very becoming one.",
"Do steamers run between Copenhagen and Amager?",
"Not at all.",
"How can we go thither, please?",
"If you take a walk, you will be there in a quarter of an hour.",
"Indeed!",
"What is then the communication with the metropolis, what is the island itself, and why have these foreign people sought a home in Denmark?",
"The island itself is flat, but rich and fertile, covered with comfortable farmhouses and large gardens.",
"It is connected with Copenhagen by two bridges, Knippelsbro and Laugebro and a town on the island, called Christianshavn is, properly speaking, but a continuation of the metropolis.",
"But why did the waiter not tell us that?",
"I fancy he said, I have never been there, and yet the island is connected with Copenhagen.",
"People in a low condition of life are not accustomed to reflect about things not belonging to their occupations.",
"I dare say be has been in Christianshavn more than hundred times in his life, but perhaps he never has been in the Amagerland as it is called, and therefore he does not think he has been on that island in the Baltic.",
"Will you be kind enough to tell us, why and when the Netherlanders settled there, and if they intend to remain.",
"Certainly!",
"The island was colonized in l5l6 during the reign of Christian II, so far as to when.",
"As to why, I have to tell you, that they are indebted to the Queen Elisabeth for their invitation; for this Princess, sister of the Emperor Charles V, finding the arts of horticulture much neglected in Denmark, obtained the favour of her Royal husband, that a party of Dutchmen, who were skilful in making butter and cheese and who were especially good gardeners, were invited to Denmark to encourage the inhabitants in the neglected art.",
"Sometimes we meet in the streets with young persons dressed in ancient costume and carrying baskets of oranges, apples, cucumbers etc.",
"I wonder, if those girls are the \"Amagerpiger\".",
"They are, and the girls are rather pretty.",
"Some of them are nice-looking, but I also have seen some wornout faces.",
"No doubt most of them are hardworking people.",
"Pray, are the inhabitants of Amager on friendly terms with those of Copenhagen?",
"Certainly; why do you ask this question?",
"Because your waiter did not like to give us any information about the island; this was but too clear.",
"Poor fellow, his geographical knowledge may not be very extensive.",
"To him Amager is very far away, but Christianshavn is in the immediate vicinity.",
"But why is the island not frequented by the Copenhageners?",
"Because it is not fashionable to spend a holiday there.",
"And why not?",
"I dare say, it is because there are not places of amusements and refreshment places enough, no public amusements as theatres, Tivolis and Alhambras.",
"Nowadays every one and the lower classes especially long for excitement and merriment.",
"And the Danes are made of this material.",
"I am sorry to hear this.",
"The Danish nation I always looked upon as a serious and progressive race;",
"but our age is full of difficulties and temptations, and indeed it is no wonder if the Danes for the moment put the cup of oblivion to their lips.",
"The better part of the nation will never do so, for a draught of that cup will be but too dangerous.",
"So I should think!",
"As to the island of Amager, I should like to make an excursion there some day, to drive along the seaside and in every direction of that \"kitchen-garden\", converse with the population and enjoy its beautiful scenery.",
"Will you be so good as to provide us with a carriage during our stay in Copenhagen, Mr. King?",
"With pleasure!",
"But don't expect too much from your trip to Amager, gentlemen, for then I am afraid you will be disappointed.",
"You think so? Well, if you wish the waiter to extend his geographical knowledge of his native land, then let him go with us, Mr. King.",
"With pleasure, and thank you, Sir, on his behalf.",
"How do you like the Danish fare?",
"Like you I am accustomed to the English.",
"That is to say, you prefer our old English dishes and the way in which our dinners are prepared.",
"So I do.",
"I am not so fond of boiled meat as the Danes, for generally we have roast meats in our country, and as I don't like the vegetables stewed as we get them every where in Denmark, I should very often make a poor dinner, if it were not for the beef-tea, we take before the meat.",
"It is called soup here, you know, but it is well made and the taste is delicious.",
"As for me I prefer however the old English soup, quite unknown in this country, I think.",
"I wonder why the cook puts those small swimming puddingballs into the soup.",
"The dumplings you mean;",
"they make a rich soup, and are in some way an embellishment as well as the carrots and celery-roots, cut into stars and flowers.",
"You defend the Danish cooking, I see.",
"But how about the vegetables?",
"Oh, the vegetables!",
"They indeed lose their original flavour by the addition of boiled milk and flour.",
"Our vegetables, pease for instance, are more delicious and have a finer flavour, the same applies to our spinage, as well as other vegetables boiled in the natural way, without the Danish or German stew",
"As for me, I dislike the milk-soups, sweet soups and those different sorts of Grød the Danes are accustomed to and fond of.",
"Except their Rødgrød.",
"Once known in England this national dish of the Danes would be much favoured and patronized in English families, and I am much obliged to our kind landlord for the recipe to make Redgroats he has got me from the cook.",
"How astonished I was when you asked the waiter if he were not able to instruct you how to make Redgroats",
"I wonder if he supposed you intended to turn cook.",
"Very likely, especially as I also asked about another thing concerning the art of cookery — the Danish puddings.",
"And you have got the information bow these delicious puddings are made?",
"Capital!",
"It is of such importance to me, that I should be very sorry if I happened to lose them in our rambling about, for I know, that my dear aunt will be glad to get them, and therefore I intend to copy them instantly.",
"And I shall be glad if she sometimes will be kind enough to treat us with Redgroats or a Danish pudding when she sends one of her friendly invitations to dine with her.",
"I shall give her a hint by and by, depend upon it.",
"Thank you, dear!",
"And if you will allow me to copy the recipe you have got, I shall be much obliged to you.",
"You know, I am the favourite of our hereditary family-cook, and I can scarcely bring her a more welcome gift than such an addition to her knowledge in the noble art of cookery.",
"Willingly, then I will read it and you may write it down word by word;",
"but take care of the copy.",
"That I will!",
"Well: to make Redgroats.",
"You must take three pints of the juice of currants, raspberries or cherries and two pints of water;",
"add to this as much sugar as you please and a small piece of vanilla, put it all on the lire, and when it boils then add 14 or 16 ounces of ground-rice, sago-meal or starch-meal.",
"Now it must boil for ten or twelve minutes and be slowly stirred.",
"Afterwards it is poured on large plates or into forms, bowls or teacups, which previously have been well wetted inside with cold water, that the Rødgrød may easily be turned out of the form, when it is cool.",
"It is served with cream and sugar.",
"Cream and sugar.",
"Stop!",
"There is still something to add.",
"The Redgroats will be most delicious if ⅔ of the juice is of currants and ⅓ of raspberries or cherries.",
"Some people add instead of vanilla 3 or 4 ounces of pounded almonds, both bitter and sweet, and half an ounce of pounded cinnamon.",
"The taste of all these ingredients in the juice of fruits is very nice, but the vanilla is the most delicious flavouring.",
"To be frank, I don't take much interest in writing notices about \"l'art culinaire\".",
"Never mind.",
"Now you have to write about \"making a good Danish pudding\".",
"You are rather cruel.",
"Well! the pudding then.",
"Bake over a slow fire eight ounces of the best and finest flour poured in a pint of boiling cream or pure milk, in which eight ounces of butter have been melted, and a few ounces of white sugar.",
"It must be frequently or incessantly stirred, till the wooden spoon used for stirring slips the dough.",
"The yolks of twenty or sixteen eggs, as you please, (if the eggs are scarce twelve will do) must be added, one by one stirred in the cooled pudding, and at last all the whites whipped in a foam.",
"The form, well covered inside with butter and pounded biscuits or bread, before the dough is put in, is then covered and put in the oven to bake, or in a large deep saucepan with boiling water, where the pudding boils in 1½ or 2 hours.",
"The saucepan may be taken off the fire some few minutes before the pudding is served, but the form must remain in the boiling water till the last moment and fire be put on the cover.",
"The sauce is made of juice of preserved fruits.",
"Now I dare say, you will allow me to say stop.",
"Certainly!",
"And besides I will give you a good character for attention.",
"How do you like to study the Danish language?",
"Thank you, pretty well.",
"Can you speak the language?",
"I speak it a little, but I understand it.",
"Then you have learnt the language before your arrival in this country.",
"Certainly, but only for six weeks.",
"A Danish gentleman was introduced to me by a friend a short time before I left England, and during my stay in London and a trip to Scotland we have always been together, and I found pleasure in studying the Danish language.",
"You pronounce well, and before long you will speak fluently.",
"Do you think so?",
"it is a great encouragement to me.",
"How long have you been in Copenhagen?",
"About three months.",
"And you intend to stay here for years, I understand?",
"At least for a twelvemonth, therefore I am anxious to have a thorough knowledge of the language.",
"Do you find it difficult to learn Danish?",
"Certainly, I find it very difficult.",
"But you like the language itself, I suppose.",
"Yes, very much.",
"Correctly pronounced it sounds well",
"Do you know anything of Danish literature?",
"Only the works of some few authors, but these books I have read with great pleasure and interest.",
"You often read aloud I suppose, to get a pure accent.",
"I always do so, when the Danish professor comes to me.",
"He is a good teacher, I know.",
"An excellent one;",
"I am much obliged to him for all his kindness to me.",
"But tell me, why do you find the Danish language so difficult?",
"The pronunciation gives me some trouble.",
"I felt convinced before my arrival that if I only spent a few months in Denmark itself, I should be able to acquire the best pronunciation and a pure accent.",
"And you have been disappointed?",
"Certainly.",
"But you have some talent for languages and are accustomed to go abroad, I know.",
"So I am, more than people generally I dare say, and I have studied several foreign languages, partly by lessons and self-instruction in my native-land, partly by staying in the different countries and conversing with the natives there.",
"But nowhere have I found making progress so difficult as in Denmark.",
"Indeed! Is it the pronunciation you find difficult?",
"In the beginning of my studying the language I did not think so, but since I am here, I find it sometimes impossible to understand even the most common expressions.",
"This you will always find, when you go to a foreign country;",
"our ears are not accustomed to the accent.",
"Don't forget, I knew something of the Danish language before my arrival;",
"I have even been able to converse tolerably well with my teacher, the Danish gentleman, whose pronunciation is the most desirable and the purest, I am sure, as I was able to understand every word of his.",
"Besides you know Sir, my ear is accustomed to the pronunciation and accentuation of foreign nations.",
"Pray, why are the difficulties so much greater in Denmark?",
"To be quite open, it is — as far as I believe at least — because the Danes generally don't pay due attention to proper and distinct pronunciation.",
"They leave out the final consonants but too infrequently, and this makes the language rather difficult to understand, if one is accustomed to a good and pure pronunciation only.",
"Did you never before hear such complaint made by foreigners?",
"I have, it cannot be denied.",
"But generally such carelessness is met with only in the lower classes.",
"In this supposition you are quite wrong.",
"Sir, and I will try to prove you my remark.",
"To tell the truth, I have never reflected seriously upon the matter.",
"In our daily conversation we understand each other perfectly well, if even the pronunciation is neglected.",
"But I shall be very much obliged to you, if you will tell me some of our mistakes in the language.",
"Foreigners often know how to open our eyes and ears better than the natives.",
"Indeed it is an audacious attempt to criticize where I have rather to study, but nevertheless I will mention some of my observations.",
"And you will allow me to make objections, if you are wrong.",
"Of course, and with my best thanks.",
"Well, the consonants ending the syllable or word are not kindly treated by your countrymen, I understand, for very often they are omitted.",
"I am sure you know, that after a sharp consonant the \"d\" is very indistinctly pronounced, as it is difficult to give this letter its original sound there.",
"Foreigners generally pronounce the \"d\" in such words like a \"t\".",
"I know this rule well, but \"d\" is often left out even after a soft vowel, and this you will agree with me is very wrong.",
"How often have I caught the words of Brø', virkeli' and so on instead of Brød, virkelig.",
"But this principally by people only, who unfortunately have not even acquired the common rudiments.",
"At least it should be allowed to such people only to pronounce badly.",
"But even persons well educated leave out the consonants and frequently they say ska', ve' and so on, instead of skal, vil.",
"Such omissions and the inevitable combining of the words offend the euphony of the language and makes it difficult to understand.",
"Certainly.",
"But it cannot be denied, that the higher classes of society pay more attention to a pure and distinct pronunciation than the middle classes.",
"Of this I have already been convinced since my arrival in Denmark.",
"Neither can it be denied, that imor'en, Bor'et in all classes is more frequently heard than the proper pronunciation of the words imorgen, Bordet.",
"I hope, you also will agree with me in this.",
"I am obliged to do so because it is the truth.",
"But don't believe that such indifference is not highly disapproved.",
"We all pretend, and I don't think we are wrong, that the intellectual culture and literary capacities of persons are shown by the manner in which they pronounce their native language.",
"I am quite sure, that such a view is right!",
"If you knew, how the combination of words and omissions of consonants have puzzled me, how carefully I have searched Dictionaries and Vocabularies to find the expressions, I did not understand, then you would either consider me silly or the pronunciation ridiculous.",
"Pray, tell me some of these puzzling expressions.",
"Willingly!",
"I often listened for instance to the words \"skaviedde\", \"devejeegge\", \"lavær\" to remember the pronunciation and look for the signification in the dictionaries, of course without finding them, till at last I have been obliged to consult the gentleman, I call my Danish teacher.",
"And how astonished I have been to be told, that such expressions were not one word, but several, and signify \"skal vi ikke\" (shall we not), \"jeg veed det ikke\" (I don't know it), \"lad være\" (leave off).",
"I comprehend your astonishment, Sir;",
"But don't you think the Danish language is well pronounced in the theatres and the churches?",
"As far as I am able to judge, I don't think so.",
"Such an accusation I should wish you to prove, Sir!",
"As for the theatres, I don't know much of them, but I dare say, that they, not even the Royal theatre, are such schools for language as the \"Théatre français\" in Paris.",
"The churches I know better, for I have been at the service in most of them, but I have more than once been astonished to hear some clergymen pronounce, even when they read the Gospel, ha'de, sa'e, instead of havde, sagde.",
"Will you allow me to say, that it is only clergymen belonging to \"a certain party\", who pronounce in this way.",
"They suppose, that a number of persons in the congregation belong to the lower classes, and that they, to make the sermon thoroughly comprehensive, are obliged to pronounce as badly as common people.",
"How wrong these ideas seem to me.",
"Would it not be better to raise common people to themselves than to descend to them.",
"Undoubtedly.",
"But for the newspapers.",
"I hope you look over the best of them?",
"I do so, of course.",
"How do you find the language written there?",
"Well, so well in some few of them, that I study them partly to improve myself in the language.",
"Did you never find any mistakes there?",
"Sometimes, but rarely.",
"I have found a blunder very common when people speak, and I have found it more than once.",
"It hurts my eyes to read it, still more than my ears to hear it in daily life, for I pay attention just as little children do in their spelling-books.",
"It is the two Imperfect tenses used immediately one after the other, instead of the Infinitive left out, as: \"jeg gad vidst\" instead of \"jeg gad video\" (to know).",
"This is an offence against the language in more than one way.",
"You are an excellent student, well versed in languages, I see, and you remind me of a renowned linguist who once said, that there is one way in which every one can prove his veneration and his love for his native land, and this is to speak his mothertongue purely, for the language is one of the best treasures of a nation.",
"And the renowned linguist is quite right.",
"If only every man and every woman would bear in mind — in all countries — that they have some responsibility for the indifference and offences against the mother tongue, then the younger generations will learn imperceptibly, to support and encourage the national cause and the national feeling even in that way.",
"But above all it is desirable and to be prized if the mothers, the first teachers and best friends of the rising generation, will understand in future better than hitherto, that they also have part and lot in the affairs of language.",
"You are fatigued with our ramblings and searching after curiosities, I see.",
"Not fatigued from our ramblings, my dear friend, but tired with the interpretations and explanations of the guides.",
"And so am I.",
"Nothing is so tiresome as those drawling or hasty explanations given by persons without intelligence, without due perception of eminent natural gifts and masterworks.",
"It is enough to put one out of patience.",
"On the other hand, these poor people are obliged to explain the same topics day by day.",
"And repeat the explanations in the same expressions, I dare say.",
"I wish we could do without a guide.",
"So do I.",
"Don't you think we might try to find our way without such a companion?",
"Certainly;",
"I hope we shall try and succeed.",
"But the attendant is engaged for a fortnight, you know.",
"So he is, but if we pay his wages, I suppose he will have no objection to leave us, if even we ask him as a favour",
"I intend to put down the names of the principal streets, places and squares, and how to find the public buildings, scientific institutions and museums, then we shall not only be able to find our way in Copenhagen, if we return some day or other, but perhaps our notices may be welcome to English, and Scottish tourists, visiting the Danish metropolis.",
"Capital!",
"I will ring for the waiter, that we may at once make some arrangements with our engaged companion.",
"My friend and I are much obliged to you for your readiness to put us in the right way during our stay in Copenhagen;",
"some strolls at our own risk however will not be unpleasant, and we intend to try our luck.",
"We pay your wages, of course, but then we beg for your help to make a sort of guide or directory for our own use;",
"will you do us the favour to answer the questions we put to you concerning such a guide?",
"Willingly, Sir!",
"I shall be happy to explain every matter.",
"I thank you very much.",
"First I wish to put down the names of the principal streets.",
"If for instance we start from the handsome and convenient landing-place and have done with the custom-house, what streets will take us to Kongens Nytorv (the King's New Market) the centre of the metropolis, I understand.",
"From the Toldbodvej (custom-house street) to Kongens Nytorv a very broad street conducts strait on, it is the Bredgade (broad street) or Norgesgade;",
"in a line with the Bredgade is the Ameliastreet, divided by the Ameliaborg Place.",
"St. Anne's Place and the Strandstreet reach from Ameliagade to Kongens Nytorv.",
"And what streets will take us from Kongens Nytorv to the railway station?",
"The Østergade (East Street) leads from Kongens Nytorv to Amagertorv, whence Vimmelskaftet and Nygade reach to Gammeltorv, and Frederiksberggade further on to Vesterbro, where on the right, opposite the Obelisk called Frihedsstøtten (the pillar of liberty) you will find the entrance to the railway-station, a newly erected large and comfortable building.",
"I understand, thank you.",
"But some long streets extend from Kongens Nytorv to the North-West part of the town, I believe?",
"Yes.",
"Gothersgade (the Gothic street) leads to the Norrevold and Store Kongensgade (Great King Street) to the Østerport.",
"Still there is one street well situated, I know, along the Rosenborg garden.",
"I wonder that the inhabitants of Copenhagen don't prefer that street to all other large streets, as the opposite neighbours are the fine trees, shrubs and flowers of the extensive garden.",
"They do so;",
"the houses in Kronprindsessegaden (the Princess Royal Street) are in no less demand than the houses in the squares.",
"And now give me the names of the chief public places or squares, please.",
"Frueplads you said.",
"Pray, will you allow me to interrupt you for a moment.",
"Willingly, Sir.",
"Why, is there, do you think, more wind at the corner of the square by the Frue Kirke than anywhere else?",
"I will tell you.",
"One day the Devil and the Wind took a walk together, and when they came to the corner of this place, the Devil said to the Wind: Wait a little for me, for I have some business in the Bishop's palace, I must slip in for a moment.",
"He went in, but found himself so much at home and so comfortable there, that he forgot to come out again, so the Wind is still waiting for him at the corner.",
"Thank you;",
"who told you that curious story?",
"A gentleman at the table d'hote some days ago.",
"But although the Wind is still waiting at the corner, he added, the Prince of the infernal regions is no longer in the Bishop's palace; but is running through the metropolis, blowing, hissing and whistling in all directions, more busy than ever sowing dissension and quarrels among the inhabitants.",
"And the Copenhagners don't know how to put the evil spirit in irons?",
"I know no more than I told you.",
"Thank you, dear friend.",
"If you know some other curious anecdotes, pray, let us have a lot of them.",
"I know very little of tales and legends, Sir, and I never before heard the anecdote the gentleman told us just now;",
"but it reminds me of another story about the infernal Prince;",
"should you like to hear that tale, gentlemen?",
"Certainly, thank you!",
"A street in Copenhagen is called Laxegade (Salmon Street) and no lawyer is allowed to live there;",
"it is even strictly forbidden for such professional men to take up their abode there.",
"Only listen!",
"Centuries ago the inhabitants of the street were very much annoyed by the noise and the hubbub, which the frequent visits of his black Majesty caused, when he either walked or drove in a red-hot carriage drawn by six black horses, with fiery tongues lolling out of their mouths, to see some lawyers in the street, with whom be was on very intimate terms.",
"At last the friends moved or died away, and the place became quieter as the Devil only called now and then trying to make friends with the new lodgers.",
"But no sooner did a lawyer settle himself in Laxegade, which neighbourhood seems to have a great attraction for the Devil, than the old uproar and noise was renewed at midnight, all doors and windows flying open of their own accord when the mysterious walker, or the dreadful vehicle appeared.",
"The inhabitants complained and the police interfered, but, of course, the chief of the fallen angels cared little about such remonstrances, and the street threatened to become quite deserted.",
"At last to avoid this, the arrangement was made, that no lawyer should be allowed to settle in Laxegade.",
"Capital Mr. NN.",
"Thank you!",
"Now will you allow me to ask for the names of the bridges;",
"we have passed several in the vicinity of Christiansborg, of course because the palace is built on an island, but we only know the names of the two bridges uniting Copenhagen and Christianshaven.",
"Will you tell us those of the other bridges?",
"Willingly!",
"Hojbro (high bridge) connecting Hojbroplads and Slotspladsen, and Holmensbro leading from that place to Holmens Canal, are the principal;",
"three others lead from the back of Christiansborg palace over the Slotsholm Canal;",
"these are the Storm-Bridge (also known as the English bridge), the Marble-Bridge and the Prince's Bridge.",
"I know the names of the three principal hotels, but I wish to add those of the streets or squares where they are situated.",
"The Hotel Phenix with 112 rooms, is No. 37 Bredgade, at the corner of Dronningens Tvergade (the Queens Cross St.);",
"Much obliged to you.",
"Now we must try to find the way to the principal churches, museums and public buildings we have visited, partly in your company.",
"Where is Frue Kirke (Lady-church) adorned by the masterpieces of Thorvaldsen and I understand, the cathedral.",
"It is situated in Norregade surrounded on three sides by the square called \"Frueplads\", and not far from the church of our Lady is St. Peter's church, the church of the German Lutherans.",
"Then there is the church of the Holy Ghost in Vimmelskaftet, Trinity church with the renowned \"Round Tower\" on the summit of which there was formerly an Observatory, and the Palace church, a large chapel in connexion with the palace of Christiansborg.",
"You also have some churches for the military and navy I know.",
"Certainly!",
"The Garrison church is St. Anne's Place, and the chapel of the Garrison in the Citadel.",
"On the Holm's Canal there is Holmens church, a place of worship for the navy.",
"Then the German and French Reformed communion have a small church in Gothersgade;",
"altogether Copenhagen has 22 churches.",
"Don't let us forget the remarkable church with the external spiral staircase and the steeple 300 feet high;",
"it is one of the curiosities of Copenhagen.",
"It is the Church of Our Saviour in Christianshaven, where also the German residents have a church, the Frederick church.",
"The English Chapel we know, it is 21 Stormgade;",
"we should rather say Divine Service is performed in that street in a building belonging to the Moravians.",
"I wonder, that the English residents in Copenhagen and English travellers who so often frequent that metropolis, do not erect a church of their own, worthy the English name and the English nation.",
"The Synagogue is a very handsome building, Sir, erected some twenty years ago.",
"It is situate in the Crystal Street.",
"Thank you, Mr. NN.",
"enough of the churches.",
"The largest of the palaces is Christiansborg, I suppose; indeed, it is an extensive building.",
"But it is not only a Royal residence, Sir.",
"Both chambers of the Diet, the Lower House and the Upper House, hold their sittings there in different apartments, and the Council Chamber is in that palace.",
"In the upper part is the Royal gallery of paintings.",
"Well!",
"Then you have the four palaces on the Amalienborg Place, one of which I have been told is occupied by the Queen Dowager Caroline Amelia, Granddaughter of Caroline Mathilda, sister of George III, and another by the Landgrave William of Hesse, brother of the Duchess of Cambridge.",
"I think it is on the South side that the handsome octagon is united by a colonnade?",
"Yes, Sir.",
"Where is the Charlottenborg Palace and who lives there?",
"It is on \"Kongens Nytorv\" at the corner of Newhaven.",
"No Royal person lives there for it is the Academy of fine arts.",
"And the Prince's Palace, I understand contains several public collections.",
"Yes, Sir!",
"the Ethnographical Museum, the Royal collection of engravings, the Royal Museum of Northern antiquities and some others",
"The palace is opposite the Marble-Bridge.",
"But the most interesting of all the palaces in Copenhagen is undoubtedly the Rosenborg palace.",
"What splendid contents in the handsome Gothic building.",
"Besides the Crown jewels, and the cabinet of Coins and Medals, hundreds upon hundreds of objects illustrating the history of Denmark are presented to view.",
"I think the Riddersal (Knight's Hall) with the massive silver throne covered with tapestry representing the battles in which Christian the Fourth was engaged is especially to be mentioned.",
"Certainly!",
"It gives an idea of the luxury which once reigned in Denmark.",
"Pray, tell me where is the Exchange?",
"On the Palace Square, Sir.",
"And the National Bank?",
"On the west side of the Exchange and connected with it by a corridor.",
"The Mint, please?",
"Is in Nyhavn.",
"The first and most important of the public collections and Museums in Copenhagen, Thorvaldsen's Museum, we shall be able to find without a guide, as it is situated behind the Royal chapel.",
"What a treasure given to Copenhagen!",
"You will not be annoyed even if I trouble you with some more questions, Mr. NN.?",
"Not at all.",
"I am happy to be of some use to you.",
"Thank you.",
"Pray, where is the Post Office?",
"And there is a post daily to England?",
"Of course.",
"Letters can be posted at the General Post Office till half an hour before the departure of the evening train to Korsoer.",
"It starts at 7 o'clock.",
"And in the letterboxes?",
"There you will be obliged to post them an hour earlier.",
"The postage to England is 30 Shillings (9 d.) for a single letter.",
"Thank you, it is as well to know.",
"Can you tell me, where the public libraries are?",
"I have been told, that books are lent out on application.",
"I think so; of course to well known or well recommended persons.",
"Still it is very liberal.",
"In the British Museum the reading room is open 8 or 10 hours daily, but it is not allowed to carry the books out of the room.",
"Do you know anything about the Athenaeum, a reading-room supplied with most European newspapers and pamphlets, where each member has the privilege of introducing a stranger for 8 days, after which time he can take a monthly ticket for a dollar?",
"I know the Athenaeum is 24 Ostergade, but I don't know anything about it.",
"And the Student's club?",
"A large and handsome building has been erected two years ago for the Student's club, it is situate on Gammelholm, not far from the Holm's church.",
"The Holm's church is the Sailor's church, I think.",
"Did you never hear some low sounds not to be accounted for, when you have passed the sailor's church?",
"Ah, perhaps you don't know where to find the church.",
"Well, but I will tell you that those sounds proceed from the coffin of the illustrious Admiral Peter Tordenskjold, who met with an untimely death, when only 29 years old, from the rapier of a Swedish sharper, a certain Colonel Stahl, on whom he inflicted a sound thrashing for cheating a young Dane.",
"Tordenskjold is buried in the vaults attached to the church, and when Denmark is at war or on the eve of war, he continually knocks at the side of his coffin nearest to the canal, clamouring to be let out, that he may fight the enemy.",
"No wonder if he has been very restless in the past year, my dear friend.",
"And no wonder if he is very restless at the present moment.",
"Pray, Mr. NN, shall we be allowed to visit the charitable institutions and the hospitals?",
"An English medical man describes the Commune Hospital as a model hospital.",
"And so it is, I dare say.",
"If you apply for admittance, gentlemen, you will easily get one both for yourself and for some friends.",
"Then we shall be happy to do so.",
"We wish also to know the establishments of some publishers, booksellers and stationers;",
"but pray, some few names only.",
"And highly respectable establishments, I presume.",
"Of course!",
"We have got the name of Messrs. Reitzel, where is their shop?",
"Charming things we have bought there.",
"Can we find a bookseller or stationer carrying on a larger business in maps and engravings?",
"Mr. Steen, No. 8 in Kronprindsensgade (Prince Royal St.) will provide you with excellent maps, and engravings of all sorts are to be found in a number of shops.",
"Some of the best you will find in Mr. Bing's establishment, nearly opposite to Mr. Steen.",
"We want to know the name of a music dealer;",
"give us the name of a well-known establishment, please.",
"Mr. Lose & Delbanco, 11 Gothersgade, is a highly respected firm.",
"Much obliged to you.",
"Where is the printing-office of Bianco Luno, pray?",
"That establishment is highly recommended to us, not only for excellent workmanship but also for punctuality, and we intend to call there and make some arrangements for printing.",
"Give us if you please the names of some theatres and public places of amusement;",
"we only know the Royal Theatre on Kongens Nytorv.",
"The Casino is 10 Amaliegade, Folketheatret 39 Norregade, the Court Theatre on the left of the spacious riding-ground of Christiansborg Palace, and the Tivoli, a summer place of amusement, on Vesterbro opposite the railway station, immediately after passing over the drawbridge.",
"Upon my word, we are very troublesome with our questions Mr. NN, but you will soon have done with us.",
"The cabs, or Droshkies as you call them, are generally spacious and clean, if not quick, we have tried them from several cabstands.",
"What is the fare from one part of the town to another?",
"Two marks.",
"Sir, about 9 d.",
"And by the hour?",
"Four marks.",
"Every driver is provided with a printed faretable, I suppose.",
"Yes, Sir, and he must produce it when required.",
"Tell me, Mr. NN, if that most delightful walk, along the sea, the Long Line, is the only remarkable promenade in Copenhagen and the immediate vicinity?",
"Not at all.",
"The Ramparts and above all the Citadel Ramparts with their splendid view afford a beautiful and interesting walk.",
"Then the Esplanade extending from the East Gate to the Custom House is very pleasant, as well as the new promenade on St. Anne's Place reaching from Bredgade to the port.",
"Besides we have Rosenborg Garden and the Paths;",
"these are the banks along the three lakes.",
"Common people call them the paths of love, marriage and divorce.",
"And now my last question with my best thanks, Mr. NN.",
"The Barracks, the Royal Arsenal, the Shipyards and the Dockyard, we know about.",
"We also know that Copenhagen from the SW to the SE is enclosed by ramparts and moats, and defended by 24 bastions, besides outworks, and towards the sea by the strong citadel of Frederikshavn;",
"but what are the names of the powerful batteries commanding the entrance to the harbour?",
"There is the Sextus and Trekroner (the three Crowns); in allusion to Scandinavia: the union of Denmark, Norway and Sweden.",
"Scandinavia!",
"All right.",
"killed the parrot.",
"Good morning, good morning!",
"How unexpected to meet you!",
"Did you come by the train or on horseback?",
"I am fond of walking, you know.",
"Well, then you will never be unhorsed.",
"Certainly not, and avoid pick-pockets.",
"Do you know, that my brother has bought an estate?",
"And probably burnt his fingers by the bargain.",
"Not at all, he has been very lucky.",
"You know, he has always been the favourite of our rich uncle.",
"Probably because he tells a good story.",
"You are a very severe judge.",
"never looks too deeply into his glass",
"two flies with one stroke",
"more spotted fowls than the parsons.",
"find my account",
"the book of oblivion.",
"No, because he has some talent for poetry, and my uncle is fond of poetry.",
"Besides, he never takes a drop too much, and is no saunterer.",
"Ah!",
"You kill two birds with one stone, I see;",
"for this is to me and my cousin.",
"There are more maids than Mary and more men than Michael.",
"I tell you that I have made up my mind to care for nothing, and consign all troubles to oblivion.",
"Many men, many minds.",
"Well, as your brother understands how to curry favour with his rich uncle.",
"Then my uncle, who knows well, that fair words butter no parsnips, and that he that goes borrowing, goes sorrowing, has agreed to be his guarantee;",
"and besides he has presented him with two fine horses, to say nothing about a large sum of ready money.",
"Indeed!",
"He has not the least trouble in this world.",
"My brother also has taken it into his head to marry.",
"And he marries a fortune, I dare say.",
"He is to be married to a young lady, dear to him for years, to Miss C, the rich ward of Doctor D., a friend of his earliest childhood.",
"I am astonished, indeed!",
"And you?",
"Relations are not always jealous of each other.",
"But there is the reverse to the page, I find.",
"I don't know what you mean.",
"take the leaf away from the mouth",
"I am sure, you understand me!",
"But you know the proverbial expression, that difficulties and troubles are to be found everywhere.",
"Indeed, I don't know how to solve your riddles.",
"Then I must speak out.",
"It is whispered, that the young lady is the inheritor not only of her mother's large fortune, but also of her talent for talking nonsense.",
"You are in error, quite wrong!",
"She is very lively, but a happy mind can be a very serious mind.",
"Old love will always peep out;",
"a certain person told me that just now.",
"What I know besides is, that you have never been a tedious, narrow-minded person.",
"And neither was my brother ever so.",
"Certainly not.",
"But as he is no chicken, without doubt deeply in debt, as he always was fond of living in style, and as he is acknowledged to be a clever person, then after all, your own home is worth gold.",
"put aside his baby shoes",
"the days of white bread",
"He will be very happy, I dare say.",
"To be sure, he dances well to whom fortune plays the piper.",
"I think I can pay you back in your own coin.",
"Never mind.",
"I have been, as you know, rejected several times, and so I always shall be.",
"But I should like to know where the newmarried folks will spend their honey-moon.",
"They intend to go abroad.",
"Why do you stay at home when your friends have a pick-nick?",
"Necessity has no law.",
"You are more fond of your books than of amusements, I see.",
"Habit is second nature.",
"My brother also is a student, but still be knows how to find time to make a trip.",
"Every shoe fits not every foot.",
"Do you believe, be will succeed?",
"God Almighty is the guardian of fools.",
"My poor brother! His expectations are great.",
"Hoping and waiting makes a fool of many a one.",
"He is happy in life, unacquainted with deceptions.",
"Adversity is useful.",
"I hoped you had forgotten the squabbles of last winter, but I am afraid not.",
"Wrongs and troubles are not forgotten, if even borne secretly.",
"How can you have a grudge against him?",
"Remember, the old Adam is still alive.",
"You know, he is your friend, if his behaviour has even been odd.",
"Gold is tried in fire, friends by misfortune.",
"Besides, he is obliged to be economical.",
"Yes, he is penny wise and pound foolish.",
"Your difference of opinion was not worth the loss of one hour's friendship.",
"Little strokes fell great oaks.",
"And you, you are very abrupt in words and manners.",
"Every bird sings with his own beak.",
"Tell me, please, why your friend, our apple of discord, has very few friends.",
"No money, no friends.",
"Then is he really very poor?",
"It is dreadful!",
"Honourable poverty is no disgrace.",
"You often call on him, it is very kind of you.",
"But this proves, that you can find time.",
"Where there is a will there is a way.",
"How does it happen, that the family is so very much reduced in circumstances.",
"The father was a rich man and in an important situation.",
"One is never above the reach of misfortune.",
"Quite right!",
"Nobody would suppose be bad such trials, for he seems to be happy.",
"To suffer patiently softens grief.",
"But his sisters?",
"They put on a good face.",
"The eldest, I understand, does not care much about their circumstances;",
"she appears to make light of every thing.",
"Still waters run deep.",
"go to bed at the same time as the fowls",
"it rains shoemaker boys",
"Will you promise me to keep on terms with my brother as in former days?",
"To promise is one thing, to perform another.",
"He is very kind to you and always defends his friends.",
"You and the named friend.",
"Well, he knows how to wear two faces on one pair of shoulders.",
"I don't know how to manage you, my dear cousin.",
"Good bye.",
"Good morning, Mr. Dormouse!",
"We can always reckon to find you at breakfast by half past ten, and before that hour to be scarcely dressed.",
"No wonder that you get up at an earlier hour, as you go to bed with the cocks and hens.",
"Not always.",
"Meanwhile I request you to give me shelter during this shower.",
"As you see, it rains cats and dogs.",
"not again hear the cuckoo.",
"I am happy to shelter you;",
"but pray, tell me, who is the lady you walked with yesterday?",
"I was in the company of two ladies, as you passed by, which of them do you mean?",
"Of course, not the lady with grey hair, but the young one.",
"She is a pretty girl.",
"So she is; a pity only that she squints.",
"Besides she is engaged to Captain D.",
"Indeed!",
"he looks so very delicate, as if he would not live to see another summer.",
"It is his brother who looks delicate in health.",
"Her betrothed is safe and sound.",
"Perhaps you know him at the club.",
"Well, I remember to have met with him there.",
"If I mistake not, he looks rather stupid.",
"Donkeys are only allowed to enter the palace court-yard to carry away the heavy bags.",
"give him a finger and he will take the hand.",
"He is an intimate friend of Lord D., I understand.",
"Don't you know, that grand people only permit the middle classes to familiar intercourse in the hope of making them useful.",
"I know my Lord!",
"Are you much together?",
"Very little!",
"a burnt child dreads the fire.",
"You have perhaps bought your experience.",
"Only this: give him an inch and he will take an ell.",
"But then you may claim his assistance, if opportunity presents itself.",
"Don't think so!",
"Old birds are not caught with chaff.",
"He is very selfish, you know.",
"And I know that he is not the only man who remembers, that charity begins at home.",
"we creep to the Lord, but run to the Devil.",
"ten instead of five.",
"Alas!",
"We all of us are more ready to do evil than good.",
"I wonder, if his hand-writing is more legible than formerly.",
"I never saw a more peculiar hand in my life.",
"I only know it as a scrawl.",
"However it is bad enough to deceive any one with.",
"Ah, I understand.",
"You are very sly.",
"Now the rain has ceased and I must bid you good bye!",
"Are you so very busy?",
"Mrs. Brown will soon be in, and I shall be happy if you will take a cup of coffee with me.",
"I am much obliged to you, but I shall only ask for a glass of water.",
"I know your passion for Adams' ale.",
"It is a love which costs no money.",
"Certainly not!",
"but alas!",
"I have many small claims on my purse, and many a little makes a mickle",
"many rivulets make a river",
"One feels inclined to laugh on hearing a young man preach economy.",
"Who laughs last laughs longest.",
"You are right, quite right;",
"but a small debt, a very little one, is not difficult to go on with.",
"Don't forget, that a small weight becomes heavy in time.",
"But also remember, that we must take advice of old people and employ young people to act.",
"We are young and may expect a long life.",
"A long life!",
"Who knows?",
"Well to-day, dead to-morrow.",
"I should rather like to say:",
"I wish you were at Jericho with your remarks.",
"as a cat is afraid of mustard",
"You make me too serious.",
"Better so than if I had to preach to the wind.",
"I adhere to my opinion, that young people should live in the lap of fortune.",
"And I am heartily sick of what the world considers the lap of fortune.",
"But never mind;",
"we still are and will be friends.",
"Good bye.",
"Good bye, good bye!",
"Come again soon.");

function firstDanishLine()
{
	global $danishLines;
	return $danishLines[array_rand($danishLines)];
}

?>