<?

//Hossfeld's Dutch dialogues : and idiomatic phrases indispensable for a rapid acquisition and correct expression of the Dutch language
//1903

$dutchLines = array("Pray tell me.",
"Please to tell me.",
"If you will be so good.",
"If you please.",
"With your permission.",
"I beg your pardon.",
"I want to ask you a favour.",
"I have to ask a favour of you.",
"You would oblige me.",
"I beg you for it.",
"If you please.",
"Willingly.",
"Why not?",
"Very willingly.",
"It gives me great pleasure.",
"I am glad of it.",
"I am glad to be useful to you.",
"Depend upon me.",
"Will you do me the favour?",
"I consent.",
"I have no objection to it.",
"I thank you.",
"I accept it with thanks.",
"You are too kind.",
"May I ask?",
"Have the kindness.",
"Be so kind.",
"Do you understand?",
"I do not understand it.",
"That is a matter of course.",
"Yes indeed.",
"Alas no!",
"On the contrary.",
"It is no matter.",
"It matters not.",
"It is not worth speaking about.",
"Let me alone.",
"I am sorry for it.",
"It gives me great pain.",
"Excuse me!",
"Pardon me!",
"I beg pardon.",
"Be not angry with me.",
"Do not stand upon ceremony.",
"You are welcome.",
"You have no cause.",
"It is impossible for me.",
"It will not do.",
"It cannot be done.",
"It is quite impossible.",
"It is not in my power.",
"I am very sorry.",
"But I cannot do it.",
"I am sorry.",
"It is very unpleasant to me.",
"It is not my fault.",
"It does not depend upon me.",
"It will not do.",
"It cannot be.",
"It does not concern me.",
"It is not my business.",
"What is that to me?",
"Let it be.",
"Do not be vexed at it.",
"It is very vexatious.",
"It is very unpleasant to me.",
"It is true.",
"Is it true?",
"It cannot be",
"It is not possible.",
"It is a falsehood.",
"It is a calumny.",
"It is false.",
"It is wrong.",
"It is indeed true.",
"It is quite right.",
"It is the whole truth.",
"It is proved.",
"It is a fact.",
"This news is not true.",
"Upon my honour.",
"I assure you.",
"As sure as I live.",
"You may depend upon it.",
"You will make me believe it.",
"There is nothing in it.",
"Is it possible?",
"Can it be possible?",
"Are you in earnest?",
"Do you speak seriously?",
"Are you not mistaken?",
"In fact.",
"Truly.",
"Indeed.",
"Be assured of it.",
"You may believe me.",
"It is a story.",
"You joke.",
"You jest.",
"I doubt it.",
"I cannot believe it.",
"I scarcely believe it.",
"I can assure you of it.",
"My brother is witness.",
"My friend can testify it.",
"You are right.",
"Do you think you are right?",
"You are wrong.",
"You are mistaken.",
"I think you are mistaken.",
"Every one will tell it you.",
"The whole world knows it.",
"It is undoubted.",
"Nobody doubts it.",
"The whole story is nonsense.",
"What do you say?",
"What do you wish to say?",
"You were pleased to say.",
"It is incredible.",
"It is inconceivable to me.",
"You have been imposed upon.",
"It is unheard of.",
"It is beyond my conception.",
"I cannot understand that.",
"I cannot comprehend it.",
"I have no notion of it.",
"You cannot imagine.",
"What is to be done?",
"What do you intend to do?",
"I do not know.",
"I have not made up my mind yet.",
"I shall reflect on it.",
"What do you think of it?",
"What do you say to the matter?",
"I can say nothing.",
"It is a vain talk.",
"It is a report.",
"No such thing.",
"What do you advise me to do?",
"How is it to be remedied?",
"What is your opinion?",
"Wait a moment.",
"Remain here until I return.",
"Do not go away.",
"When shall yon return?",
"Do return soon.",
"I have business to do.",
"I am going to town.",
"Whither are you going?",
"Whence do you come?",
"I come from the theatre.",
"Who knocks?",
"Come in.",
"What does it mean?",
"What do you mean?",
"What do you mean by it?",
"I shall go home.",
"I am at home.",
"Approach.",
"Do not stir.",
"What do you desire?",
"What do you want?",
"Speak.",
"Speak out!",
"Answer me.",
"What did you ask?",
"Be gone.",
"Be silent.",
"I am not well.",
"Are you unwell?",
"What is the matter with you?",
"I am quite charmed.",
"I am glad of it.",
"It is indeed admirable.",
"Do you speak Dutch?",
"I learn Dutch.",
"I speak it a little.",
"I will not hear anything of it,",
"The thing speaks for itself.",
"Excellent!",
"It is astonishing.",
"I am quite astonished.",
"It is a very singular thing.",
"How happy I am!",
"It grieves me.",
"How unhappy I am",
"It is a sad accident.",
"With God's help.",
"Heaven be praised.",
"There is no doubt of it.",
"You doubt it?",
"Why do you doubt it?",
"How far shall we go?",
"Come this way.",
"Quickly!",
"Make haste!",
"He came just at the right time.",
"She died suddenly.",
"Are you in earnest?",
"I only said it in jest.",
"On foot.",
"On horseback.",
"Be it as it may.",
"He will probably do it.",
"It cannot well be done.",
"It cannot be done.",
"Do it as well us you can.",
"I insist upon it.",
"I know nothing about it.",
"He arrived before me.",
"Forget it.",
"It is easy to forget.",
"Have patience.",
"With all my heart.",
"I have nothing to say to it.",
"Circumstances are not favourable.",
"Never mind!",
"He did it on purpose!",
"Did you do it purposely?",
"I will not do it.",
"I do it reluctantly.",
"It is time.",
"It is not yet time.",
"It is all the same to me.",
"I knew it before.",
"I told you so before.",
"So much the better.",
"I do not care about it.",
"I do not trouble myself about it.",
"I care nothing about it.",
"It is indifferent to me.",
"Are you speaking to me?",
"To whom is he talking?",
"He would not tell me it.",
"What do you say?",
"What do you mean?",
"What did you say?",
"What has he said?",
"I did not hear it.",
"He said nothing.",
"We have told it to him.",
"I heard it said.",
"Do you know him?",
"Yon seem to know each other.",
"I never heard anything like it.",
"Somebody told me.",
"From whom did you hear that?",
"I do not know.",
"What do you mean by that?",
"What is the meaning of that?",
"Between ourselves.",
"That is nothing.",
"I grant it.",
"1 remember it.",
"I will remind you of it.",
"I cannot recollect it.",
"Let me alone.",
"Let it be.",
"What is your opinion of it?",
"It is not my business.",
"Who would have thought it?",
"It will come to nothing.",
"As much as is in my power.",
"I say it is.",
"I say it is not.",
"Once for all.",
"Neither more nor less.",
"I know him.",
"I have known him for years.",
"He has long been known to me.",
"It is fortunate that I meet you.",
"I wished to speak to you.",
"I wanted to speak to you urgently.",
"I have no time.",
"I am in a hurry.",
"Call on me.",
"Where do you live?",
"I live in King Street.",
"What do you say?",
"What do you wish to say?",
"What do you mean by that?",
"What do you want?",
"Why do you say that?",
"What shall I do?",
"What do you mean?",
"What would you do in my place?",
"I do not know what to do.",
"You have chosen your time badly.",
"You must have patience.",
"It just occurs to me.",
"That is a good idea.",
"I am of your opinion.",
"Where are you going?",
"I am going to town.",
"I am going into the country.",
"I am going home.",
"We are going on the Continent.",
"He is going to Germany.",
"From whence do you come?",
"I come from Hamburg.",
"We are returning from a walk.",
"He comes from your house.",
"Come in.",
"Walk slower.",
"You walk too fast.",
"I cannot keep up with you.",
"Let us rest a little.",
"I will go with you.",
"Follow me.",
"Come this way.",
"Come nearer.",
"Go on straight.",
"Turn to the right.",
"Turn to the left.",
"Make room.",
"Let me pass.",
"To whom are you speaking?",
"Do you speak to me?",
"Speak loud.",
"You speak too low.",
"Why did you not speak before?",
"Do not speak to me of it.",
"I will not hear of it.",
"Speak rationally.",
"I call that speaking out.",
"What nonsense he talks.",
"He speaks very well.",
"He has a pure accent.",
"He speaks Dutch very correctly.",
"Does he speak Dutch well?",
"He has the dialect of the South of Holland.",
"He makes many mistakes in speaking.",
"I am hungry.",
"I am thirsty.",
"I am very hungry.",
"I have an appetite.",
"I have not eaten anything yet.",
"We are thirsty.",
"I am very thirsty.",
"I must drink something.",
"I should like to drink.",
"Give me something to drink.",
"Give me a glass of water.",
"Pour me out a glass of beer.",
"I should like to drink a glass of wine.",
"I am tired.",
"We are very tired.",
"I am sleepy.",
"I am very sleepy.",
"I am going to bed.",
"I have slept well.",
"I have slept very badly.",
"I could not close my eyes the whole night long.",
"I woke early.",
"Can you read Dutch?",
"What do you read?",
"I am reading the newspaper.",
"I am reading Goethe's Egmont.",
"Where did you read that?",
"I read it in the newspapers.",
"Read aloud.",
"We always read aloud.",
"Continue to read.",
"I have read the whole of this work.",
"I have read it through.",
"I have read it with pleasure.",
"I read the book on the journey.",
"I am now reading the book.",
"I shall not read the book, for it is too difficult.",
"You read very well.",
"You read better than I thought.",
"I can read exceedingly well.",
"Do you want a pen?",
"Give me a steel pen.",
"I wish to write.",
"Give me the ink.",
"What are you writing?",
"I am writing to my brother.",
"I am writing a letter on business.",
"I have a letter to answer.",
"You write a good hand.",
"You write the German character very well.",
"Do you speak Dutch?",
"Can you speak Dutch?",
"Do you understand Dutch?",
"I speak it a little.",
"I speak Dutch well.",
"You express yourself clearly.",
"I understand better than I speak.",
"You pronounce pretty well.",
"You have a good pronunciation.",
"How long have you learnt Dutch?",
"A short time.",
"I have learnt it for six months.",
"That is a very short time",
"You speak Dutch very fluently.",
"You have a very pure accent.",
"Does your brother also understand Dutch?",
"He does not understand one word.",
"My sister has a thorough knowledge of Dutch.",
"He has made great progress.",
"You must always speak Dutch.",
"How do you do?",
"How are you?",
"How do you feel?",
"Pretty well.",
"Very well, I thank you.",
"How is your wife?",
"She is very well indeed.",
"You appear to be very well.",
"I am really very well.",
"I do not feel very well.",
"I am unwell.",
"My health is variable.",
"I feel unwell.",
"I am very poorly.",
"I have had a cold for some days.",
"My cough does not leave me.",
"I feel rather better.",
"My cough is less troublesome.",
"I have a headache.",
"I have a sore throat.",
"I am hoarse.",
"I have a cold.",
"I have the toothache.",
"You look very well.",
"You have a strong constitution.",
"Your son appears to be weak.",
"I do not thing that he will live long.",
"How old are you?",
"I am twenty years old.",
"I am only fifteen.",
"You are still very young.",
"Still so young?",
"Already so old?",
"You are in your best years.",
"How old is your sister?",
"She is eighteen years old.",
"I thought she was already of age.",
"No, she is still a minor.",
"And your nephew?",
"He is only six years old.",
"He is but a child.",
"This is my birthday.",
"I was born on the 10th of August, 1852.",
"In two months I shall be fifty years old.",
"My youngest son is only four years old.",
"He grows visibly.",
"He is growing very much.",
"Your aunt appears to be very old.",
"Yes, that she is; she was 82 last month.",
"She does not appear to be so old.",
"One would take her to be 10 years younger.",
"She seems healthy.",
"How time passes.",
"My father is already 60.",
"He carries his age well.",
"My grand-father is still alive.",
"He must be very old.",
"He is entering his 93rd year.",
"That is a great age.",
"A few days ago.",
"A short time since.",
"One of these days.",
"It is scarcely two days",
"It is hardly three days ago.",
"Last week.",
"A week ago.",
"A fortnight ago.",
"It is at least a month ago.",
"This day week.",
"To-morrow three weeks.",
"That was three or four days ago.",
"It was some time before.",
"At about this time.",
"Near Christmas.",
"In a month's time.",
"The first of next month.",
"The tenth of next month.",
"In six weeks.",
"On the last day of the month.",
"At the end of this month.",
"Towards the middle of January In a fortnight.",
"Next week.",
"In the course of a week.",
"From time to time.",
"From day to day.",
"From one day to another",
"Till another day.",
"The last day.",
"What o'clock is it?",
"Tell me what o'clock it is.",
"Is it late?",
"No, it is still early.",
"It is 2 o'clock.",
"It will soon strike six.",
"It has just struck five.",
"It is no longer early.",
"It is time to rise.",
"It is day.",
"It is yet early in the day.",
"It is five minutes after seven.",
"It is ten minutes past seven.",
"It is a quarter past one.",
"It is twenty minutes past six.",
"It is five and twenty minutes past two.",
"It is half past six.",
"Already so late?",
"It is a quarter to eight.",
"It will soon be nine o'clock.",
"It has just struck.",
"It is time for breakfast.",
"It is not yet two.",
"It is twelve o'clock.",
"It is noon.",
"It is half past twelve.",
"It is afternoon.",
"At what time must you go home?",
"To the stroke of two.",
"It is dinner time.",
"It will soon be night.",
"Night comes on.",
"It is time to go to bed.",
"It is nearly midnight.",
"What time is it by your watch?",
"My watch has stopped.",
"I have forgotten to wind it up.",
"Mine gains.",
"Mine loses.",
"Yesterday it gained ten minutes.",
"To day it has lost more than half an hour.",
"How does your watch go?",
"It goes right.",
"When are you going out?",
"Towards 3 o'clock.",
"Between four and five.",
"You come an hour too late.",
"He was born yesterday morning at five o'clock.",
"He set off this evening at nine o'clock.",
"Is it possible you want to go out?",
"What kind of weather is it?",
"It is beautiful weather.",
"It is bad weather.",
"It is very windy.",
"It is mild weather today.",
"I fear it will rain.",
"It is very warm.",
"Is it windy?",
"No, it is quite calm.",
"The sky is overcast.",
"Perhaps the sky will clear.",
"I doubt it.",
"It grows darker and darker.",
"It is raining already.",
"It will not last long.",
"We had such a beautiful morning.",
"The sun is coming out again.",
"We shall have a fine day yet.",
"It is very unpleasant weather.",
"It is so cold.",
"It is very cold for this time of the year.",
"The spring promises well.",
"The trees are beginning to bud, they will soon blossom.",
"It is already raining again.",
"It has just ceased.",
"It is beginning to rain.",
"What dreadful weather!",
"I am quite wet.",
"I am wet through and through.",
"It is very dirty outside.",
"There is the rainbow.",
"It is now getting fine.",
"It is a pleasant day.",
"Oh, how warm it is!",
"It is a beautiful day.",
"It is exceedingly warm to day.",
"I am very warm.",
"The heat is unbearable.",
"The sun burns.",
"It is oppressive weather.",
"I think we are going to have a storm.",
"I already hear thunder.",
"It hails.",
"It thunders.",
"It lightens.",
"It thunders fearfully.",
"The lightning has struck.",
"It is frosty.",
"Is it moonlight?",
"It is full moon.",
"It is the new moon.",
"The moon is in the first quarter.",
"The moon is in the last quarter.",
"It is becoming very cold.",
"I am very cold.",
"It has been very cold for some days.",
"Has it been freezing?",
"Yes, there has been a hard frost.",
"There is a cutting wind.",
"I am shivering with the cold.",
"Has it been snowing?",
"Yes, it snows fast.",
"Sir, I have the honour to wish you good morning.",
"Your obedient servant.",
"I wish you good morning.",
"I wish you good day.",
"I wish you good night.",
"I have the honour to wish you good bye.",
"I am delighted to see you.",
"I have not had the pleasure of seeing you for some time.",
"Pray put on your hat.",
"You are very kind.",
"Pray come nearer.",
"You do me too much honour.",
"Pray sit down.",
"Have the kindness to sit down.",
"I regret that your visit has been so short.",
"I am rejoiced to see you so well.",
"You are too kind.",
"I am very much obliged to you.",
"It always gives us great pleasure to see you.",
"Willingly.",
"Be it so.",
"Yes, certainly.",
"So it is.",
"Certainly.",
"That suits me.",
"With all my heart.",
"I am at your service.",
"We will not differ about that.",
"I am waiting your commands.",
"You may do as you will.",
"What do you want?",
"Why did you not say so?",
"Not only this, but that also.",
"I am entirely yours.",
"I am content with it.",
"That may be.",
"As you please.",
"When you please.",
"I have nothing against it.",
"Do not spare me.",
"I can refuse you nothing.",
"It is a very small service I ask of you.",
"It is such a trifle that it is not worth while speaking about.",
"I wish I could do more for you.",
"I thank you.",
"I am very much obliged to you.",
"Many thanks.",
"I thank you.",
"I thank you very much.",
"I thank you for your kindness.",
"I am greatly indebted to you.",
"I am very grateful for your kindness.",
"I accept it with thanks.",
"You are very kind.",
"You are too kind.",
"You have forestalled my wishes.",
"That cannot be refused.",
"You confuse me.",
"I cannot thank you enough for it.",
"It is a new proof of our friendship.",
"Nobody understands so obliging a friend.",
"I cannot.",
"It cannot be.",
"It is impossible for me.",
"It cannot be.",
"Do not speak to me of it.",
"It is impossible for me to fulfil your wishes.",
"It is utterly impossible.",
"I will not hear of it.",
"I am very sorry but I cannot do it.",
"I am exceedingly sorry but I cannot do as you wish.",
"I assure you that I will not do it.",
"I will never give my consent to it.",
"I am obliged to refuse you.",
"Would it not be better to apply to Mr. B.?",
"That does not signify to me.",
"It is not my business.",
"I will not mix up in this affair.",
"I will have nothing to do with it.",
"At some other time.",
"You must have patience.",
"Perhaps you may be more fortunate another time.",
"With the best will in the world I cannot do it.",
"Pray excuse me.",
"I beg your pardon.",
"I beg a thousand pardons.",
"Do not be angry.",
"It never occurred to me.",
"I assure you it is not my fault.",
"Excuse me to him.",
"Tell him how sorry I am.",
"Yes, it is true.",
"Certainly.",
"Yes, certainly.",
"That is true.",
"I say yes.",
"It is but too true.",
"The fact is certain.",
"I have it from good authority.",
"You may believe me.",
"I am very certain of it.",
"I will lay a wager on it.",
"I can assure you.",
"Very true.",
"I saw it with my own eyes.",
"I heard it with my own ears.",
"You may believe it.",
"Take it as a warning.",
"I give you my word of it.",
"Be assured of it.",
"I answer for it.",
"Upon my honour.",
"There is not the slightest doubt of it.",
"It is evident.",
"It is official news.",
"All the newspapers speak of it.",
"The whole town knows it.",
"This news has caused the greatest excitement.",
"On my faith.",
"Upon my oath.",
"I swear it to you.",
"By all that is sacred.",
"No, most decidedly not.",
"That is not true.",
"That is false.",
"I say no.",
"It does not signify.",
"That means nothing.",
"I have it only from hearsay.",
"It is a falsehood.",
"It is a calumny.",
"It cannot be.",
"It is impossible.",
"I deny the thing.",
"It is an invention.",
"That is ridiculous.",
"Oh, you jest.",
"It is permitted to doubt it.",
"I have my doubts upon it.",
"It depends on.",
"Oh, nonsense.",
"Are you not mistaken?",
"Is it really true?",
"Can it be possible?",
"Are you really in earnest?",
"It is incredible.",
"Do you speak seriously?",
"How can that be?",
"Is that not an error?",
"It is incomprehensible",
"I do not know what to think about it.",
"I do not believe it.",
"There is really not a word of it true.",
"I am persuaded to the contrary.",
"I have good grounds for doubting it.",
"One does not know what to think of it.",
"What news is there?",
"Is there anything new today?",
"What news is there?",
"What is going on in politics?",
"Have you heard nothing new?",
"Do you know the news?",
"I know nothing.",
"Have you read the newspapers?",
"What news is there in the town?",
"I have heard nothing.",
"Do you know the news of the day?",
"I have been told that.",
"Well!",
"I have important news.",
"Important news has arrived.",
"Marvellous things have happened.",
"Not a word of it is believed.",
"Have you had letters from home?",
"I have had three by the last post.",
"The postman has brought me a letter.",
"What do your letters say?",
"They bring me satisfactory news.",
"Sad occurrences.",
"Bad news.",
"They write sad news to me.",
"That is delightful.",
"That is delicious.",
"Wonderful!",
"That is divine.",
"That is admirable.",
"That is exquisite.",
"That is astonishing.",
"That is charming.",
"I cannot yet recover from my astonishment.",
"I am quite delighted at it.",
"I am astonished at it.",
"My astonishment has arrived at the highest pitch.",
"I am enchanted at it.",
"I am surprised at it.",
"How very beautiful.",
"Can I believe my eyes?",
"Who would have thought it?",
"There is nothing more beautiful!",
"That is what I call speaking.",
"One can have no idea of it.",
"Well, that is right.",
"Very well.",
"What a pleasure!",
"What joy!",
"How pleasant!",
"How happy!",
"I am charmed.",
"I am very glad.",
"I am very much pleased.",
"How charmed I am with this.",
"How glad I am!",
"How happy I am!",
"What a joyful moment!",
"How enchanted I am!",
"That gives me much pleasure.",
"That pleases me exceedingly.",
"I have never yet been so happy.",
"Every thing happens according to my wish.",
"Every thing smiles on me.",
"Oh dear me!",
"Oh, how infamous!",
"How vexatious!",
"How painful!",
"How sad!",
"What a misfortune!",
"How annoying!",
"What a vexatious occurrence!",
"I am very sorry.",
"I am not in a good humour to day.",
"I am in despair",
"I am ennui.",
"How many troubles I have!",
"How that grieves me.",
"That irritates me.",
"That grieves me very much.",
"I am inconsolable about it.",
"That annoys me very much.",
"I lose my patience.",
"It gives me much grief.",
"How unhappy I am!",
"Why have I not known this before?",
"That vexes me most.",
"All is lost.",
"I am irredeemably lost.",
"One must confess that I am very unfortunate.",
"I am inconsolable.",
"I am dying with pain.",
"I cannot bear it any longer.",
"Every thing seems to conspire against me.",
"He is my friend.",
"He is my intimate friend",
"He is my best friend.",
"I really love him.",
"I have a great regard for him.",
"We are very intimate.",
"We love each other like brothers.",
"We are inseparables.",
"We cannot live without each other.",
"I liked him from the first moment I saw him.",
"We are one heart and one mind.",
"I am very glad to have made his acquaintance.",
"His friendship is very dear to me.",
"Such a friend is a treasure.",
"One finds few such real friends.",
"I cannot bear this man.",
"His countenance does not please me.",
"His manner displeases me.",
"He has something in his manner which does not please me.",
"He has not an agreeable expression.",
"His countenance is unfavorable.",
"He appears not to have a good conscience.",
"My aversion to him is unconquerable.",
"His society is a nuisance to me.",
"I avoid him as much as I can.",
"He is an unbearable man.",
"I had much rather see him go than come.",
"His chattering is unbearable to me.",
"She is a gossip.",
"No one can be more tedious than this man.",
"Nobody is so tedious as he.",
"What an unbearable person!",
"Now spring has come.",
"Nature revives again.",
"Spring begins well.",
"It is rather mild.",
"It is still cool.",
"Summer is approaching.",
"It is becoming warm.",
"It is very warm.",
"I feel very warm.",
"The heat is suffocating.",
"Let us go into the shade.",
"These are the dog days.",
"We are in the middle of summer.",
"One does not know how to escape the heat.",
"I am glad that autumn is drawing near.",
"We are approaching autumn.",
"The days are still fine.",
"The days are closing in.",
"The days become visibly shorter.",
"It is beginning to be cold.",
"Winter will soon be here.",
"We must soon begin fires.",
"I am benumbed with cold.",
"I am trembling with cold.",
"I can hardly speak for the cold.",
"Allow me to warm myself a little.",
"I begin to revive.",
"I feel much better now.",
"I am much better now.",
"I am quite well now.",
"We think of starting tomorrow.",
"Where are you going?",
"We are going to pass the summer in Holland.",
"You do rightly.",
"It is a beautiful country.",
"Have you already made your plan for the journey?",
"Yes, we are going via Ostend to Cologne, we shall remain there a few days and then go up the Rhine.",
"How I envy you, I should so much like to see the Rhine.",
"We are going afterwards to Amsterdam, in autumn to Leiden, and then via Utrecht to Rotterdam to pass the winter there.",
"John, are the trunks packed?",
"Every thing is ready.",
"Are the passports vised by the consul?",
"I have just received them.",
"Now we can set off.",
"When does the next train start for Bonn?",
"At 2 o'clock.",
"Then we must make haste.",
"Have you forgotten nothing?",
"Good bye.",
"Adieu, my dear friend.",
"God bless you.",
"I wish you a happy and pleasant journey.",
"Do write to us very soon.",
"Have you every thing ready for the journey?",
"Everything is in order.",
"We go by the railway-omnibus.",
"When do you start?",
"We start in ten minutes.",
"Get in if you please, Gentlemen.",
"When shall we be at the railway station?",
"We shall be there in a quarter of an hour.",
"Here we are already at the station.",
"The train will start in five minutes.",
"Take your ticket quickly",
"Please to give me a first class ticket to Hanover",
"I want a second class ticket for Amsterdam.",
"What does it cost?",
"Three Mark and twenty pfennig.",
"What luggage have you Sir?",
"I have two trunks, one carpetbag, and a hatbox.",
"How much luggage have I free?",
"Five and twenty pounds.",
"For the over weight you have to pay sixty pfennig.",
"Take your places Gentlemen.",
"The train starts.",
"There is the engine;",
"that is the signal for departure.",
"Here comes a train.",
"One goes slower on the Dutch railways than on the English.",
"That is true, but you are safer, an accident is a rare occurrence, whereas on an English railway one's life is never secure.",
"Here we are at the first station.",
"How long do we remain here?",
"Five minutes.",
"There are a great many passengers waiting at the station.",
"What do I see before us?",
"It is a tunnel.",
"We shall soon be at the end of our journey.",
"This is the last station.",
"Tickets, ladies and gentlemen.",
"Are we already at Cologne?",
"Yes, Sir.",
"Here is my ticket.",
"Let us fetch our luggage.",
"When does the steamer start?",
"With the tide at seven o'clock.",
"When must I be on board?",
"I advise you to be here by 6 o'clock at latest.",
"How long shall we take to cross?",
"If the wind be favourable we shall be at Ostend in four hours.",
"I go in the first cabin.",
"Give me a good berth.",
"The sea is very calm.",
"We are still in the harbour.",
"I fear the wind is against us in the Channel.",
"The sea is rough.",
"I feel unwell.",
"You are seasick.",
"Lie down immediately.",
"Steward, bring me a glass of brandy and water",
"Is this the first time you have been at sea?",
"No, but I am always seasick.",
"The wind is going down.",
"The motion is less.",
"Is that land there?",
"Yes, that is land.",
"We are now entering the Elbe.",
"That was a pleasant voyage.",
"We are now anchoring.",
"The steam is already let off.",
"The steamer stops.",
"We shall soon land.",
"The luggage will be taken to the Customhouse.",
"As soon as it is examined we shall receive it.",
"Your passports, Gentlemen.",
"You will find your passport at the police office, send for it there.",
"My trunk is marked M.M.",
"What is in your trunk, Sir?",
"My own wearing apparel, nothing more.",
"Nothing to declare?",
"Not as far as I know.",
"Open, if you please.",
"All right.",
"May I lock it again?",
"Certainly, you have passed.",
"Will you go to the hotel in a cab or in an omnibus?",
"I want a cab.",
"I go by the omnibus.",
"Here is my luggage, two parcels.",
"Why do you not go on?",
"The examination of the luggage is not yet finished.",
"How long will be?",
"We start immediately.",
"We are only waiting for those gentlemen who are going with us.",
"To which hotel do you go, Gentlemen?",
"To the Victoria Hotel.",
"Have you any rooms?",
"For what sort of rooms do you wish?",
"Two bedrooms and a sitting room on the first floor.",
"I want a double bedded room on the second floor.",
"You will find nice rooms and good beds.",
"We hope so.",
"Will you be kind enough to enter the saloon?",
"Take the luggage into my room.",
"Your luggage will be taken care of.",
"Waiter, take the Gentlemen to No. 4.",
"This room does not please me, it is too dark.",
"I want a room overlooking the Rhine.",
"This room I like better, I will remain here.",
"We should like to go to bed early.",
"Make a good fire.",
"Are our rooms ready?",
"Are the beds made?",
"Let me be called at 5 o'clock.",
"Do not forget that I leave at half past 5.",
"I remain here several days.",
"I leave early to-morrow.",
"Be kind enough to bring me the bill, charge the service.",
"What do we owe?",
"Have you made out our bill?",
"How much is the bill?",
"Thirty six mark.",
"A mark is one shilling, English money.",
"Do you take English money?",
"Yes certainly, I take the pound at 20 mark.",
"I wish you a pleasant journey Sir.",
"Have you breakfasted?",
"Not yet.",
"What will you have?",
"I drink tea.",
"Give me some coffee.",
"We have chocolate ready.",
"I should prefer chocolate.",
"We will drink tea.",
"Bring us some tea.",
"I want two eggs boiled soft, with my tea.",
"How do you like the tea?",
"Is it strong enough?",
"I do not like the tea, give me some coffee.",
"The coffee is good.",
"Give me another roll and a little more milk.",
"Do you take milk and sugar?",
"Yes, both.",
"Give me some cold meat with my breakfast.",
"I must make a good breakfast, for I have a long walk before me.",
"The chocolate is excellent.",
"Give me another cup.",
"I thank you, I have enough.",
"I have made an excellent breakfast.",
"Dinner is ready.",
"We dine at the table d'hote at 2 o'clock.",
"I dine with a friend today.",
"I have come to dine with you to day.",
"You are very welcome, but you must take what you find.",
"The table is laid.",
"Please sit down.",
"I am very hungry.",
"I have no appetite.",
"What have we for dinner to day?",
"Waiter give me the bill of fare and the wine list.",
"Do you like soup?",
"Give me a good bouillon, or rice soup.",
"Do you prefer vermicelli?",
"This soup looks very good, it tastes very nice.",
"It wants a little more salt.",
"Will you have some beef with sauce?",
"Give me also the mustard and some potatoes.",
"I must ask you for a piece of this leg of mutton.",
"The roast meat is very good.",
"Pray give me a piece of venison.",
"That is too much, half will be enough.",
"Will you not have some of these vegetables?",
"Cauliflower, green peas or spinach?",
"Help yourself as you please.",
"I should like to taste a piece of that pudding.",
"Give me a glass of water.",
"I prefer a glass of beer at dinner.",
"I should like to have half a bottle of Medoc.",
"Drink a glass of wine with me.",
"Allow me to give you a glass of wine.",
"You do not eat.",
"I do not like the dinner.",
"I liked it very much.",
"I have really dined very well.",
"I thank you, I am quite satisfied.",
"I have almost eaten too much.",
"May your meal agree with you.",
"I wish to have this banknote changed.",
"Can you change me a sovereign?",
"I am sorry I cannot.",
"I have not enough change by me.",
"Where does the nearest banker live?",
"Will you have the kindness to change this gold for me?",
"What is the sovereign worth?",
"In Germany 20 marks.",
"In Austria 10 florins according to the exchange.",
"In France 25 francs.",
"I am the bearer of a bill of exchange which your London correspondent has drawn on you.",
"Here is the bill.",
"It is payable at sight.",
"In what sort of money do you wish to receive the amount?",
"Give it to me in Prussian bank notes.",
"The exchange is not very advantageous at this moment.",
"Then I will take it in florins.",
"I am quite a stranger to this town.",
"Find me a guide.",
"What does he charge a day?",
"From three to six marcs.",
"I wish to have a plan and a description of this town.",
"The guide will serve you well.",
"He will be here in half an hour.",
"Is he well acquainted with the town and environs?",
"Yes, he has served this hotel for twelve years.",
"Well, I will take him for three days.",
"First, we must hire a carriage for a day.",
"Then we must drive to the Museum.",
"From thence to the new Cathedral.",
"Do you know the two private galleries of Mr. Schmidt, the merchant, and Mr. Miller, the chancellor?",
"No, are they worth seeing?",
"You will find there the most splendid paintings.",
"Then let us drive there first.",
"In the afternoon we will go to the Botanical Gardens, afterwards to L.'s Conservatory, and in the evening to the Opera.",
"To-morrow morning I wish to see all the public buildings and statues.",
"I advise you also to see the Royal Palace, the Mint, and the Arsenal.",
"We will leave that till the day after to-morrow.",
"To-day I wish to see the Royal Library, and the Royal Stables.",
"Towards noon we must visit the studios of the sculptor K. and the painter N.",
"We will visit the Church of the Holy Spirit at two o'clock.",
"At 3 we will go to the Promenade.",
"At 4 to the Royal Palace Bellevue.",
"At 5 to the Royal Garden, the Solitude.",
"At 6 o'clock there is a meeting at the Royal Academy at which I wish to be present.",
"At 8 o'clock I shall go to the theatre.",
"Early the day after tomorrow I shall visit the new bridge, the Prince's Palace and the Exchange.",
"Then we will make an excursion to Potsdam, see Sansouci and the new Garden.",
"In the afternoon I wish to see the Pinacothek and the Glyptothek.",
"And at 7 o'clock in the evening I leave by the train.",
"Will you go to the theatre to-night?",
"What play will be acted?",
"Goethe's Egmont.",
"Then I will go.",
"At what time does the theatre begin?",
"At 7 o'clock.",
"Lessing's Nathan will be performed tomorrow for the last time.",
"I must see that, procure me tickets immediately.",
"What seats do you wish for?",
"I wish for three places in the dress circle.",
"Two places in the stranger's box.",
"A seat in the pit.",
"Where are the tickets sold?",
"At the door.",
"Buy a play bill.",
"The curtain rises.",
"The orchestra is excellent.",
"The actors are good.",
"Devrient acts particularly well.",
"This interlude will last a good while, we will refresh ourselves with an ice.",
"The second act commences.",
"The theatre is very full.",
"I am glad that I have so good a place.",
"Who built the theatre?",
"The interior is very tastefully decorated.",
"The scenes are artistically painted.",
"The costumes are very rich.",
"The lighting up of the house leaves much to be desired.",
"Miss N. the actress is very beautiful.",
"That danseuse pleases me very much.",
"What do you think of the play?",
"The piece is interesting and pleases me.",
"The piece was not well performed.",
"The play is over.",
"They say the applause was tremendous, every scene was applauded, at the end there was a storm of applause.",
"Is Mr. N. at home?",
"I believe he is, may I ask for your card?",
"Here it is.",
"Walk in if you please.",
"Come in.",
"Walk in.",
"Good morning;",
"my dear Mr. K, I am delighted to see you so well.",
"When did you arrive?",
"How long are you going to remain?",
"Unfortunately only a few days.",
"I must be back in London the day after to-morrow.",
"How long is it since we have seen each other?",
"I think it must be nearly three years.",
"How time passes!",
"You have not altered.",
"Pray sit down.",
"Now tell me how you like Holland.",
"I like it very much, the Rhine is very beautiful, and the old towns have interested me very much.",
"Amsterdam, Leiden, Rotterdam and Utrecht, with their art treasures have occupied me 6 weeks.",
"I am very much pleased with my journey.",
"Land and people are pleasant, and I like the Dutch living.",
"Unfortunately I must now return to England.",
"When shall we see you again?",
"That is still very uncertain, I hope next summer.",
"Remember me very kindly to your brother.",
"Do not forget me.",
"My kindest remembrances to your mother.",
"My best compliments to Mr. B.",
"Give him my kind remembrances;",
"I wish you will have a pleasant journey.",
"I wish you a very pleasant journey.",
"Farewell.",
"Au revoir.",
"Adieu!",
"Have you apartments to let?",
"Yes, I have several.",
"Can I see them now?",
"With pleasure, be kind enough to follow me.",
"I want two furnished rooms, a bed, and sitting room.",
"I must have a nicely furnished room.",
"The bed room is not light enough.",
"The sitting room is too small.",
"I like the rooms.",
"How much do you ask for these lodgings?",
"I shall remain here at least three months.",
"Then you shall have them for 30 Gulden a mouth.",
"That is too dear for me.",
"Well, you shall have the rooms for 25 Gulden, if you remain longer.",
"Well, I am contented with that.",
"Must I pay in advance?",
"Can you also board me?",
"What do you ask for board and lodging?",
"Can I come in today?",
"Is the bed comfortable?",
"I should like to sleep here to night.",
"Can you give me a latch key?",
"Where is the bell?",
"You can come in when you like.",
"It is a dangerous matter.",
"He has prepared himself well.",
"To turn over a new leaf.",
"The thing is not to be altered.",
"To speak to deaf ears.",
"To be on one's guard.",
"Example is the best teacher.",
"After rain comes sunshine.",
"Many pence make a pound.",
"No one is without any fault.",
"Gold governs the world.",
"Nothing venture, nothing have.",
"Penny wise, and pound foolish.",
"The higher the mountain, the deeper the valley.",
"He is at a loss.",
"He is not right in his senses.",
"As for example.",
"To make both ends meet.",
"Out of sight, out of mind.",
"Much ado about nothing.",
"Every one is apt to fail.",
"Words will not fill a bushel.",
"Hold your tongue!",
"That is not my business.",
"Get you gone!",
"He is an old fox.",
"To put the cart before the horse.",
"Custom is second nature.",
"Half a loaf is better than no bread.",
"Necessity knows no law.",
"First come, first served.",
"To measure another man's corn by one's own bushel.",
"Whatever may happen.",
"The receiver is as bad as the thief.",
"In process of time.",
"Quicken your pace.",
"The pitcher goes to the well till it comes home broken at last.",
"Barking dogs do not bite.",
"It is as dark as pitch.",
"To pay in the same coin.",
"Many heads, many minds.",
"To owe one no good will.",
"To offer for sale.",
"The day begins to dawn.",
"I do not like that.",
"It touches my honour.",
"To frighten some one.",
"At the beginning.",
"He has become rich without knowing how.",
"It is not in his nature.",
"Take care!",
"There is a great difference between him and me.",
"He knows all.",
"For ever.",
"To say yes to every thing.",
"He is as poor as a church mouse.",
"That is his doing.",
"That does not signify.",
"He is badly off.",
"To forsake a friend in need.",
"It is known.",
"As far as we know.",
"Promises must be kept.",
"To let a thing take its course.");


function firstDutchLine()
{
	global $dutchLines;
	return $dutchLines[array_rand($dutchLines)];
}

?>
