<?
// https://www.gutenberg.org/files/11748/11748-h/11748-h.htm

	$french2lines = array(
"His success will depend on his presence of mind.",
"Their adversary was a veteran, distinguished for his courage.",
"We begged the soldiers to take our defense in hand.",
"The terrible cold will increase our sufferings.",
"His eyes were to see the light no more.",
"Our friends will do their utmost to win our case.",
"The memory of my wounds will win me his protection.",
"I will take charge of your defense.",
"Your wounds are terrible but your cause will triumph.",
"When my power was menaced, you showed your bravery.",
"Your appeal has won you my protection.",
"I threw my cloak over my companion.",
"Our neighbors have yielded to our request.",
"Your enemy has exposed his life to save his emperor.",
"His accusation is false, and my cause is in good hands.",
"The doctor is going to see his patients.",
"He meets some friends.",
"They are mounted on their mules.",
"They dismount to talk more conveniently, and let go their mounts.",
"Our mules are going to get into the house, says the doctor.",
"My patient lives on the ground floor.",
"One of the mules enters with a deliberate step.",
"The poor man thinks it is his doctor.",
"He holds out his pulse, without turning.",
"The doctor, frightened, comes in to chase out his mule.",
"I don't know why you want to strike your mule.",
"I am wonderstruck that your mule has cured my illness.",
"Henceforth stay at home.",
"Molière is going to give a sou to the beggar.",
"Honesty is a good thing.",
"He rewarded the beggar's honesty.",
"Voltaire's name is well known.",
"He was Piron's friend.",
"He spent some time at Piron's house.",
"They gave a fête on the occasion of the dauphin's birth.",
"The soldier's appetite was prodigious.",
"The king's officers were at Molière's house.",
"The man with the insatiable stomach approaches the buffet.",
"The beggar notices Molière's mistake.",
"Will you be at the dauphin's castle?",
"I shall be at the queen's castle.",
"Does he give the beggar a sou?",
"The king's officers did not laugh at the joke.",
"The surprise of the old courtiers was great.",
"Voltaire was a famous author.",
"The servant's master will not be at the castle.",
"He wouldn't have gone to see the servant.",
"The man with the yellow mask had gone to the château.",
"The beggar does not notice the mistake at once.",
"I wondered who was the man with the insatiable stomach.",
"The king winked at the prank.",
"They noticed the soldier in the room for the fifth time.",
"When he had eaten, he withdrew.",
"He is mistaken, he did not see the king.",
"I have been to see John.",
"The soldiers disappear in turns.",
"The officer was put in charge of the château.",
"He will see to the replenishment of the provisions.",
"He is the biggest eater I have ever seen.",
"The young women were not at the theater.",
"The king is a ridiculous man.",
"The officer's clothes were very fine.",
"I noticed the absence of the fair sex.",
"French gamekeepers are proud of their lot.",
"Lucas is a homely man.",
"If she could get the empty place, she would be happy.",
"Old women do not go on the stage.",
"Poor Fanny carries the pears to market.",
"The poor man asks for a new place.",
"Bad men are often full of good intentions.",
"Fanny is a pretty woman.",
"She fills a difficult rôle.",
"Old Lucas wore a black hat.",
"Lucas and his wife are very old.",
"What a pleasure!",
"Jean will be mad with joy.",
"I want them to raise the curtain at once.",
"The king must be a ridiculous man.",
"Lucas was a homely man but his little gift must have pleased Fanny.",
"She looked happy, seated by the fireside.",
"Poor Fanny was to carry the beautiful pears to market.",
"I had gotten that far when John arrived.",
"They have let it be understood that they are going to move.",
"I was supposed to fill a hard rôle.",
"The old king must have gotten impatient.",
"You ought to have told me in the first place what was the cause of the delay.",
"They were in the act of raising the curtain, when the king arrived.",
"You will have to hold your tongue, otherwise we will not get along together very well.",
"One ought not to forget one's benefactors.",
"If Jean wanted to get the place, he ought not to have forgotten the pears.",
"Where is Jean?",
"He must be at the steward's.",
"Where have we gotten to?",
"The steward was a worthy man.",
"The new servant must have forgotten her good intentions.",
"The king wanted them to raise the curtain.",
"I am afraid he will leave.",
"I am afraid he cannot get the place.",
"That boat yonder is going to depart.",
"This Irishman is pulling a cable.",
"The length of this cable doubtless must have exhausted his patience.",
"I'd like to leave this evening.",
"The sultan's favorite threw this stone.",
"Is revenge permitted men?",
"If my enemy were powerful, revenge would be imprudent.",
"If I were cowardly, I would throw a stone at that camel.",
"The Irishman was hauling a cable, when he received the order to start.",
"She used to know the queen formerly.",
"If I succeed, I will have the honors of the day.",
"If a man is clever, does he always succeed?",
"If you are happy, your enemy is unhappy.",
"Did he find these stones in his pocket?",
"Are they picking up those stones?",
"If I should succeed, I would be happy.",
"If you are in Hades, I won't be able to get you out.",
"I couldn't possibly tell you.",
"People made fun of the cardinal.",
"Did he learn that the cardinal had fallen into disgrace?",
"He was very shrewd but clumsy.",
"I shall take-care not to fall.",
"If I were to go to work, I should succeed.",
"What has become of the queen?",
"I'd like to know what has become of her.",
"The boat has probably left already.",
"He did not receive the order to depart.",
"This man was a good diver formerly.",
"If she guessed the trick, she would get even.",
"The queen was eating, when she heard a great noise.",
"If this man were clever, he would know how to avenge himself.",
"Marc Antony was a great general.",
"She did not know that he had caught a fish.",
"There is a member of Congress.",
"When the lion is hungry, he roars loudly.",
"I was sleepy, that is why I slept so soundly.",
"There was a revolution in France.",
"You don't need this money.",
"This little girl is six years old.",
"This is the second watch I have bought this year.",
"What-is-the-matter-with-you, young man?",
"Were they not ashamed to fight for money?",
"Pardon me, you are wrong.",
"It will be useless for you to talk.",
"Here are your apples, sir.",
"What's the matter?",
"Are you afraid of the lion?",
"He was very thirsty, and there was no water in the village.",
"There was a lively discussion.",
"One evening, some years ago, he was in a Southern village.",
"Napoleon would rather fight for glory than for money.",
"He has just been listening to the debates.",
"The king wasn't cold because he had on all his clothes.",
"I am always warm when I wear my cloak.",
"I am afraid my watch will stop.",
"I would be afraid if he were not here.",
"I am ashamed that he is not here.",
"There was once a wolf who was looking for adventure.",
"Once he was very hungry.",
"He met a dog;",
"There's my meal,",
"He gets ready to eat this dog immediately.",
"But the dog calls his attention to his leanness, and begs him to wait a while.",
"His master had just inherited property.",
"He was going to give a lot of dinners.",
"The dog couldn't fail to fatten during this time.",
"Then the wolf could eat the dog.",
"I would rather eat you now",
"But the wolf had the simplicity to let the dog get away.",
"He came back to get the dog on the appointed day, but the sly fellow had informed his comrades of the neighborhood.",
"They fell upon the wolf at once.",
"The hare was bigger than a horse.",
"The Garonne is less terrible than the Somme.",
"I have more than 300 sheep.",
"This bridge is not as long as the other.",
"He is the most famous man in the city.",
"Paris is the largest city in France.",
"There is the best servant I have.",
"I shall see the doctor later.",
"This chicken is not so big as the one that we had yesterday.",
"I want the bigger of the two.",
"Jean has the biggest dog of all.",
"He drank more than three glasses of wine.",
"He hasn't more than two dogs.",
"The hare is as big as the one that I killed yesterday.",
"The Garonne is broader than the Somme.",
"Gascons are the biggest liars in the world, they-say.",
"He is the best pupil in the class.",
"The Gascon hadn't the least fear.",
"He hadn't the least recollection of having lied.",
"He wants to make me eat willy nilly.",
"I saw nothing strange.",
"Have you made up your mind?",
"However that may be, I don't believe that he will come.",
"You are pretty hungry, aren't you?",
"So much the better!",
"We will have something good to eat pretty soon.",
"It is important that you eat at the usual time.",
"He asks that we bring the chicken as soon as possible.",
"I killed just now the biggest hare that I have ever seen.",
"The river is more terrible than it seems.",
"The cardinal was more weak than sick.",
"The thing becomes more and more evident.",
"Chirac is the better doctor of the two.",
"He is older by two years than the other.",
"He is a most terrible man!",
"What do you expect!",
"Work has worn him out so.",
"He was in the best humor in the world.",
"The king has good trees but no fruit in his garden.",
"He sent a slave to buy some eggs.",
"One must not attach too much importance to small things.",
"I have no hens, but I have eggs to sell.",
"The king's courtiers have not killed any game.",
"There are big trees and small ones in this garden.",
"There must be good fruit here.",
"The traveler has no provisions and would like something nourishing.",
"Have you anything good to eat?",
"We have meat, bread, fruit, and good eggs.",
"There was no fire in the kitchen, but there were lots of people there.",
"There were large chairs near the fire.",
"The boy brought to the innkeeper six dozen eggs.",
"There isn't enough charcoal, do you want me to bring you some?",
"The servants were not boys but women.",
"These are excellent oysters.",
"There are many people at the inn.",
"We have good inns and bad in France.",
"The servant bought five cents' worth of salt.",
"Many people do not eat oysters.",
"A great many of the king's soldiers were hungry.",
"The house was surrounded by trees.",
"Most kings do not set good examples.",
"Most children haven't so much wit.",
"Many children become stupid in later life.",
"Here is the only fire there is in the house.",
"Do you want my cane?",
"Here it is.",
"I will lend it to you.",
"I need my books;",
"send them back to me when he gives them to you.",
"The bearer of the letter gives it to her.",
"When he found the letter, he sent it to us.",
"Why don't you believe me when I tell you so?",
"I went to the poet's house to look for my servant, and I found him there.",
"Send them there at once.",
"I shall send them there.",
"If she is pretty, talk to her about it, if not, don't talk to her about it.",
"He has already told me something about it.",
"Have you seen the gypsies?",
"There were two of them in front of the church;",
"I spoke to them.",
"They predicted fortune for me, but I told them I didn't need it.",
"But they picked my pockets for me.",
"The servant was leading him by the arm, as you may imagine.",
"If you have good oysters, give me two dozen.",
"Give me also a dozen eggs.",
"There is a bullet in the wound;",
"when you find it, give it to me.",
"The gypsies tell her fine things, but she doesn't believe them.",
"If I had recognized the actors, I would have accosted them.",
"Those rôles are easy, I have played them lots of times.",
"Here are the five louis that I stole from you.",
"I didn't know that you had stolen five.",
"Did you see the words that I carved on the door?",
"If I had possessed a garden, I would have been content.",
"The painter forgot his position.",
"If she had called them, they wouldn't have heard her.",
"They are good troops, but they have been beaten more than once.",
"There are the melons which I received.",
"I have run more than a league.",
"Have you eaten many melons?",
"The melons that I have eaten were good.",
"When he had left the table, the chance was lost.",
"He lost the battle, too, but he wouldn't have lost it if he had finished earlier.",
"When you finish I shall have given the signal to attack.",
"I shall wait until she has finished.",
"A ragged man met the actors.",
"Didn't he recognize the ladies?",
"The count has found his servants sword in hand.",
"They had stolen the five louis d'or.",
"He pulled the money from his pocket.",
"He showed me his gardens.",
"I saw the men appear.",
"He has forgotten his position.",
"He reached the end of the scaffolding.",
"A mason has worked at it.",
"The artist didn't hear the masons.",
"The mason seized the brush.",
"The mason's explanation changed his wrath into gratitude.",
"He would have led the troops against Henry IV.",
"Henry IV's cavalry beat his troops.",
"He had received some good melons.",
"He left the table.",
"He had lost the opportunity.",
"We have gotten rid of our servant.",
"She had already gone to bed.",
"I began to tremble.",
"The soldiers had fled.",
"The boys have gotten lost in the woods and have not yet found their way.",
"Corneille and Racine have appropriated heaven and earth, that's why I have cast myself into Hades.",
"We have been taking a walk.",
"I thought she had drowned herself.",
"They became aware of the absence of the servant.",
"The wretches would have hung themselves, if they had been able.",
"She found herself before a wooden man, and she fled.",
"Why have you given yourself up to sleep?",
"Where did you go walking this evening?",
"The two courtiers have become reconciled.",
"We took a walk.",
"She has not been deceived.",
"It is to be regretted that they have not become reconciled.",
"It is extraordinary that you have gotten lost.",
"My enemies have been humiliated.",
"I have been asked a favor.",
"I was accosted one day by a friend.",
"The watch was repaired by the watchmaker.",
"She was covered with confusion.",
"You have been fooled by somebody.",
"This menagerie is managed by my wife.",
"I have been charged with the matter by my husband.",
"The collection of wild animals has been enlarged.",
"An opening has been made in the wall.",
"The door was opened by a servant.",
"A new word has been invented.",
"She had taken charge of the menagerie.",
"All my mistakes are exposed.",
"The plowman was beaten.",
"The guest was well treated.",
"No bread was served to him.",
"I was not struck by lightning.",
"It is said that he had many enemies.",
"This watch will have to be fixed.",
"A lady has come to see you.",
"They have gone to church.",
"When I arrived, she had already gone out of the patient's room.",
"They have gone out to get some fresh air.",
"His comrades came back at the end of three hours.",
"She would have fallen, if she had gone out.",
"They stopped at the Savoy Hotel.",
"The doctor and his wife came home at midnight.",
"The singer had gone back to bed.",
"All the sailor's ancestors had died in bed.",
"When his wife died, he remained a widower two years.",
"Financial difficulties have arisen, and they have left for Paris.",
"She has gone to get the doctor.",
"When he arrives, the lady will have died.",
"They would have left the chapel, if he and his daughter had not come at that moment.",
"If he had not gone out, he would not have fallen.",
"They will have returned soon.",
"It is necessary that you go out for air.",
"I am astonished that your mother is gone.",
"Rubens had gone out to walk.",
"His comrades had not gone out.",
"They had stayed to look at the pictures.",
"They had drawn near the pictures that Rubens had sketched.",
"They pushed each other.",
"One of them fell on the sketches and effaced them.",
"But they avoided the reproaches of their master.",
"One of them offered to repair the misfortune.",
"The others applauded.",
"Van Dyck went to work.",
"Rubens returned after several hours.",
"He cast his eyes on the pictures that Van Dyck had sketched.",
"He thought that they were his own sketches.",
"He said that they were the best that he had ever done.",
"I am named Jean and he is named Pierre.",
"You and I are going to be questioned by the emperor.",
"What a difference there is between you and her.",
"As for them, they have no brains.",
"He amuses himself more easily than I.",
"I found some burglars at my house last night.",
"When I came home, my husband asked me if it was really I.",
"It is they who were mistaken.",
"I myself looked under the bed.",
"You answered him yourself.",
"I am homelier than you, but you are both pretty homely yourselves.",
"Put on six eggs, three for us, and three for yourself.",
"Is it for me or for her?",
"He alone, of all the audience, did not weep.",
"I, your best friend, forget you?",
"Impossible!",
"They, also, were at church.",
"He could go, but she couldn't, because she had people at her house.",
"Are you bored?",
"Same with me.",
"Did Pope have crooked legs?",
"Was he a hunchback?",
"Did the peasant girl succeed in hiring out?",
"Where did she visit?",
"Wasn't the lady's brain a little \"off\"?",
"Why has the servant come back?",
"I like my profession better than yours.",
"That is because you are a little soft-hearted.",
"When did the doctor put this book into your hands?",
"He has his mind full of the thing, hasn't he?",
"The dog made a severe wound in my arm.",
"Is this cat yours or theirs?",
"I have a dog of my own.",
"Don't stop up your ears, will you?",
"The Spaniard had dirty hands, dirtier even than mine.",
"I am going to take you to my house.",
"You may wash your hands, if you wish.",
"The fan isn't mine, it is my mother's,",
"There is good wine at Choisy, I am going there to get some.",
"There is some missing, and I can't guess the reason for it.",
"My friend is going to give a ball and I am invited to it.",
"If you have any, give me a little.",
"Give John some.",
"Don't give him too much.",
"If I had any horses, I would make a present of them to the army.",
"I didn't do anything of the sort.",
"I had fifty francs and I kept five.",
"They  didn't like my tragedy, and I am very much displeased about it.",
"If you complain about it, they will go away.",
"I went to the University of X to get my doctor's degree.",
"I got it.",
"You have such a fine chance, you ought to take advantage of it.",
"We can't receive you;",
"I am very sorry about it.",
"They tell a funny story about him.",
"Vernet was very famous, but the cavalryman didn't realize it.",
"He didn't disclose himself to the artist.",
"How much was he willing to put into it?",
"Give me some, I beg of you.",
"Think of it!",
"His life is at stake!",
"I can't make head nor tail of it.",
"This wine is diminishing, although it is in a sealed jug.",
"That man who is stopping before the picture, and whose attitude shows contempt, is a celebrated painter.",
"There is the picture that I like most.",
"A horse that had no bit wouldn't have his mouth covered with foam.",
"The coachman whose horse you saw didn't like the picture.",
"The man for whom he made the picture was in the crowd.",
"Here is a salon in which you can admire the pictures about which we were talking.",
"The bourgeois has eaten all he has.",
"I haven't anything to write with.",
"She has enough to live on.",
"The uncle saw which way the wind blew.",
"The wife of the inventor, who wrote me a letter, wishes to see me.",
"The machine that we made use of was invented by Edison.",
"There is the man with whose uncle I was walking.",
"He is a man whose opinion I respect.",
"That person whose aspect is so severe is the grenadier to whom the king spoke.",
"What made me mad, was that they invited me to a dinner at which I found several of my relatives.",
"He fell dead at the moment when I freed my arms.",
"This painter whose uncle I am is a famous man.",
"There is nothing to be astonished about.",
"The city from which he comes is Lyons.",
"Do you see my dogs?",
"These are greyhounds, those are dachshunde.",
"They are good dogs.",
"I hear a noise;",
"it is burglars.",
"It was a burglar, but it seemed to me a little late to go down.",
"I want to learn that one of the sciences which is most difficult.",
"These soldiers are better fed than those of Napoleon.",
"That makes no difference.",
"That's all right but look at this!",
"It would be difficult to imitate the grunt of a pig.",
"No, on the contrary, it would be easy.",
"That is what he said.",
"Was it you who neglected this affair?",
"It was we who did it.",
"I saw an officer and a grenadier;",
"the former was better dressed than the latter.",
"Those who wish to be educated in this school must pay double what those pay who are educated elsewhere.",
"The hardest thing is to learn to keep still.",
"What I ought to do is to learn all that I can.",
"Let my soldiers be well dressed and well fed.",
"I was on the point of greeting him.",
"I have not had the opportunity to see his play.",
"He cannot fail to be surprised.",
"I asked him if he was in the habit of being so polite.",
"It was necessary to stop reading in bed for the doctor had forbidden him to do it.",
"One loses nothing by being polite.",
"He seems to be unaware that it is hard to learn to speak French.",
"French is easier to read than to speak.",
"It is easier to learn it in France than at home.",
"It is hard to govern kingdoms, but they are easier to govern than women.",
"They invited me to dine at their house, but I am too ill to go.",
"He started reading the paper, without thinking of eating, but he was not long in getting hungry, and he finally breakfasted.",
"I expected to see him in Paris, but he had gone to see his father at Lyons.",
"I have just given him his money.",
"He had come to avenge himself, and he wasn't long in doing it.",
"If he happens to lose his saber, he will have to give himself up.",
"I can't keep from telling you that I have succeeded in avenging myself.",
"Are you hard to fool?",
"She was astonished to see him.",
"How do you expect me to give you back your money?",
"Who sent you that letter?",
"Which of the letters did you mail?",
"Do you know to whom it was addressed?",
"Whose valet is he?",
"What did you find on the desk?",
"What was it that the carter said to the culprit?",
"Did he know who had forged the signature?",
"What was the patient's occupation?",
"What!",
"He is gone?",
"I don't know what to think of it.",
"Who is playing cards in that room?",
"I don't know what I was thinking of.",
"Whose is this violin?",
"It is mine, what are you going to do with it?",
"Whom do you wish to see?",
"Which one, the father or the son?",
"It is a difficult thing to learn to write well.",
"Does she know how to play the piano?",
"Don't you know what a forger is?",
"I have no use for your advice.",
"Oh!",
"A fine thing it is to know something!",
"Did the doctor know what instrument he played?",
"The king did not know which country to attack first.",
"Do you see that object?",
"What is it?",
"If I knew him well, I would invite him.",
"Don't speak to me.",
"I didn't speak to you.",
"She hardly pays attention to what people say to her.",
"This table is good for nothing, but never mind, I don't need it any longer.",
"I didn't sleep at all last night.",
"That pig isn't worth the trouble of stealing it.",
"I wrote but a single sentence.",
"Not a one of us was invited to the dinner.",
"No author is more celebrated for his wit than he.",
"Nobody fears him;",
"he never opens his mouth.",
"What have you found?",
"Nothing.",
"Haven't you any confidence in him?",
"None.",
"I asked him if he was satisfied and he said no.",
"Has dinner been served?",
"Not yet.",
"Have they sent for the doctor?",
"I think so.",
"I've only eaten three fish.",
"Nothing is harder than to talk when one would prefer not to utter a single word.",
"He can't and won't learn French.",
"Why doesn't he go get the surgeon?",
"He doesn't know where to find him.",
"He doesn't stop grumbling.",
"Neither the king nor the rustic knew how to keep the pig from squealing.",
"Never will I be able to do it.",
"None of the bombs burst near us.",
"Voltaire ate nothing but fish.",
"Will you kindly not sing so loudly?",
"Will you pronounce this word?",
"Yes, I am willing.",
"It isn't worth the trouble.",
"Piron was a French poet, who lived in the eighteenth century.",
"He was born at Dijon, a city of France, July 9, 1689.",
"His father was an apothecary.",
"Piron was never a member of the Academy.",
"He died January 21, 1773, at the age of eighty-three.",
"She has spent an hour and a half singing.",
"Who is that man?",
"He is a marshal of France.",
"A child seven years old cannot solve these problems.",
"Was he a Frenchman or an Englishman?",
"I only have half a pound of tobacco, but I'll give you half of it.",
"He earns ten francs a day.",
"She always goes out on Sunday.",
"I am going to dine at an author's house Friday.",
"Last Monday I spent the evening at my uncle's.",
"I paid ten cents an ounce for this tobacco.",
"Thank-you a thousand times!",
"She says she is only thirty!",
"The enemy attacked us first.",
"At first I didn't want to sing.",
"What a man!",
"He changes his mind a hundred times a day.",
"The President of the United States receives $75,000 a year.",
"I am going to change my hat.",
"Whatever problem you give me, I can work it.",
"One must amuse oneself.",
"By  telling his stories, the story-teller keeps himself from forgetting them.",
"I have to have a book.",
"It is a question of getting-revenge and there remains only one way.",
"It seems to me that it would be better to avenge yourself by throwing him out of the window.",
"I see the king coming.",
"It is half past seven;",
"there still remains a quarter of an hour for me to work.",
"He was walking in the park, because it was fine weather.",
"It happened that he came to consult me.",
"It is an important matter.",
"Never mind, it is better to wait.",
"We must not strike out the two remaining words.",
"What time is it?",
"Must we be going?",
"It is fitting that she remain here.",
"She must amuse the children by telling them amusing stories.",
"Triboulet knows that his life is at stake.",
"He is sure of dying.",
"Far from amusing me, he angered me.",
"Wishing to buy a hat, he entered the hatter's.",
"The following week it rained.",
"After filling the sack, he started to lift it.",
"Let them not have him hanged.",
"Do not suffer the peasant to approach me.",
"Did you hear him tell that story?",
"Yes, but I had heard it told so often that I didn't laugh at  it this time.",
"Thunder makes milk sour.",
"They are going to have this street paved.",
"Don't let your coat get torn.",
"I saw this man struck.",
"I am going to make him pay for it.",
"He had himself led before the king.",
"The king will have the story told to him(self).",
"Rabelais made the boy write.",
"He made him write some labels.",
"If the king heard this talked of, he would have me arrested.",
"Do you know how to cook eggs?",
"He gets absorbed in his work.",
"I am going to have a coat made for me.",
"I am going to have it made by the tailor.",
"He will charge me 200 francs for it.",
"Unless it is bad weather to-morrow, I shall go walking.",
"The innkeeper asks that he be informed when the king arrives.",
"The servant withdraws, so her master may be alone.",
"He has been in business for two years.",
"How long had you been waiting for me?",
"It was more than a year that he had been busy with that affair.",
"It has been a long time that he has been here.",
"He could hardly finish the service.",
"The curate saw him take the money, therefore he went straight to him and accused him of theft.",
"You have stolen,",
"As soon as I have finished, I shall go and speak to him.",
"I shall stop in Paris for two weeks.",
"I had been there a long time, when he arrived.",
"As soon as I arrive, I shall tell him to start on his way.",
"At the end of a certain time, they gave up the project.",
"In vain did he look for the merchant.",
"Perhaps he will do that for me.",
"Scarcely had he entered, when he saw the lady that he had been looking for so long.",
"When he pays me, I will tell you.",
"How long has he owed you the money?",
"I am looking for a man who knows the road to Constantinople.",
"I stopped so he could talk to me.",
"The merchant fell ill, so he could not go to Constantinople.",
"I am going to pass the winter there, without anybody's knowing it.",
"War is the worst thing that can happen.",
"France is a beautiful country.",
"Horses are useful.",
"I give this fruit to the teacher.",
"The woman's books.",
"Where is John's father?",
"Is he at the teacher's?",
"A good boy, a little woman, the young man, the black horses, the French school, the round table, the open door, an excellent book.",
"The father and his sons are tall.",
"The father and his daughters are tall.",
"The doors and windows are open.",
"A brave man, a worthy man.",
"A handsome boy, man, woman.",
"What book have you?",
"What pen?",
"What men?",
"What women?",
"What a man!",
"Must be, probably is.",
"I am to leave to-morrow.",
"I was to leave yesterday.",
"Will have to...",
"Have had to...",
"Ought to have done...",
"Ought to study...",
"Must have had to...",
"He must have left.",
"Will you do it?",
"Will you do it?",
"Do you study?",
"are you studying?",
"I study;",
"I am studying.",
"I would like to go.",
"They couldn't possibly find the way.",
"He was singing.",
"This boy, man, woman, these books, those pens.",
"Where is your father?",
"There he is.",
"There are many people here.",
"I like apples better than pears.",
"Here is my son.",
"He has just arrived.",
"I am hungry.",
"She is thirsty.",
"They are afraid.",
"We need shoes.",
"John is as tall as I.",
"John is taller than I.",
"John is less tall than I.",
"John is not so tall as I.",
"He is the tallest of all my brothers.",
"He is the most diligent pupil in the class.",
"I have more pencils than you.",
"There are more than ten people here.",
"Give me bread, meat, potatoes.",
"Don't give me any cheese.",
"We have good books and bad.",
"There are few people who believe it.",
"Most people do not believe it.",
"The church was full of flowers.",
"I have bought some flowers;",
"did you see the flowers that I bought?",
"They have washed themselves.",
"They have washed their hands.",
"They have written each other letters.",
"Here are the letters that they wrote each other.",
"The doors have not yet been opened.",
"This book is published in Paris.",
"It is sold everywhere.",
"With me;",
"at their house;",
"by him.",
"I think like they.",
"It is he who did it.",
"No, it is they.",
"Who is there?",
"I.",
"He himself told me so.",
"They alone could have done it.",
"Has he arrived?",
"Does your father know it?",
"Has John any pens?",
"How much do these watches cost?",
"How did your mother learn of the affair?",
"Why has this man come?",
"He raised his head.",
"I am satisfied with my lot.",
"I am satisfied with it, I am proud of it.",
"I went to the theatre;",
"I saw Talma there.",
"Did you go?",
"I have some apples.",
"Give me some.",
"I give you some.",
"Give some to my sister, too.",
"Don't give her any.",
"Etc.",
"The man who is in front of the house.",
"The lady whom I meet.",
"The cow which I am selling.",
"The daughter of the lawyer who is here.",
"The lawyer's daughter, who is here, is ill.",
"The man with whom I speak.",
"The book in which I study.",
"The store to which I go, from which I come.",
"I'll give you what is here, what I found.",
"The book of which I speak.",
"The man whose son is dead.",
"The man whose son I know.",
"The lady to whose son I was writing.",
"The city whence I came.",
"Do you know what it is about?",
"Give me writing material.",
"He has nothing to live on.",
"The city in which he is.",
"The country from which he comes.",
"Here are my books and John's.",
"Here are my pens and those that you bought.",
"I have two watches.",
"Do you like this one or that one?",
"Lamartine and Balzac.",
"The former is a great poet, the latter a great novelist.",
"He is my friend.",
"It is they.",
"It is I.",
"He is a poet.",
"It is difficult.",
"Who is there?",
"Whom did you see?",
"With whom are you speaking?",
"Whose daughter is she?",
"Whose house is this?",
"Guess whom I saw.",
"What did you see?",
"What's to be done?",
"What do you think of it?",
"What are you talking about?",
"What are you thinking about?",
"Do you know what it is?",
"What?",
"Guess what.",
"I don't know what to say nor do.",
"Which of these pens is yours?",
"To which of your friends are you writing?",
"Of which one are you speaking?",
"What is grammar?",
"What is it?",
"What book have you?",
"What pen?",
"I don't know what idea has struck him.",
"What a man!",
"France is a beautiful country.",
"I do not know him.",
"He plays the guitar.",
"Do you know how to play cards?",
"That man is a lawyer.",
"His brother is a celebrated lawyer.",
"He is a Frenchman",
"Lamartine, a poet and politician, was born at Macon.",
"A hundred books.",
"A thousand thanks.",
"What a man!",
"Ten cents a piece.",
"Five francs a pound.",
"Two times a day.",
"Five francs a lesson.",
"She is at home on Thursday every Thursday.",
"He came Monday.",
"He will arrive Tuesday.",
"May first.",
"April second.",
"How old is he?",
"He is ten.",
"A woman thirty years old.",
"A half hour.",
"Half past two.",
"Half the time.",
"One must work to succeed.",
"I shall have to go to-morrow.",
"The child must come back.",
"He needs a new hat.",
"A charming woman.",
"A woman singing the Marseillaise.",
"I saw him work.",
"He has stopped singing.",
"It is better to stay, it is going to rain.",
"It is two o'clock.",
"The weather is fine.",
"I make my son study.",
"I make my son study his lessons.",
"I make him study.",
"I make him study them.",
"She is going to have a dress made.",
"I allow myself to be amused.",
"He lets himself drop.",
"I see them coming.",
"I saw him beaten.",
"He has been here for a month.",
"He talked for an hour.",
"I have been waiting for you an hour.",
"She had been working for an hour.",
"As soon as he comes, I'll tell him.",
"Hardly had my brother gone...");

function secondFrenchLine()
{
	global $french2lines;
	return $french2lines[array_rand($french2lines)];
}

?>