<?
//French Reader on the Cumulative Method by Adolphe Dreyspring
//https://www.gutenberg.org/files/29398/29398-h/29398-h.htm


	$french3lines = array(
"he is less skillful than I thought",
"he is not less skillful than I thought",
"idleness is more dangerous than vanity",
"Vanity is dangerous, idleness more so.",
"I have as much of this as of that.",
"John is the most diligent of my pupils",
"Which one is the least difficult of your lessons?",
"of two evils avoid the worst",
"Being less great is not being small.",
"not the least wind was felt",
"my father, mother, and sister have arrived",
"the year eighteen hundred and ninety-two",
"the 19th of July",
"the 26th of November",
"half an hour",
"an hour and a half",
"in the first place",
"no friend",
"no lady friend",
"no friend has come to see me",
"no lady friend has come to see me",
"Every town, every village was represented.",
"The same person",
"It is the same goodness",
"It is goodness itself.",
"Even the wisest deceive themselves.",
"No son of mine shall become an actor",
"No daughter of mine shall be an actress",
"Not a man, not a woman has come to see me",
"several times",
"several reasons",
"several books",
"several streets",
"What a misfortune!",
"What person, what thing displeases you?",
"What beautiful eyes!",
"What charming manners!",
"I shall feign some kind of business",
"He has some merit",
"I have given him some pieces of money",
"I have lost about three hundred dollars.",
"such works",
"such flowers",
"Every man ought to do his duty",
"Every city has its officers",
"all mankind",
"everybody",
"all the earth",
"all my children",
"all his letters",
"Your garden and mine.",
"Your children and mine.",
"Our house and his",
"Our flowers and theirs.",
"My friend and my brother's.",
"My wife and my neighbor's.",
"Here is my book;",
"this one is yours and that one is his.",
"Here is my room;",
"this one is my brother's and that one is my sister's.",
"it is you",
"take this",
"give me that back",
"The gentleman who entered first was my father.",
"He who does not obey the laws is not a good citizen.",
"Who sings?",
"Whom do you see?",
"The visits that I have made",
"The books which you have lent me",
"What do you wish?",
"What do people say?",
"There was something in his character which displeased me.",
"I know not of what you think",
"I speak of the parents whose child was drowned yesterday",
"Of what you spoke yesterday has happened",
"The florist from whom I have received these flowers",
"Here are two vases;
which one will you have?",
"Which one of your daughters is the eldest?",
"The slave was the master's property, from the power of whom nothing could extricate him",
"The man to whom I have applied",
"The women for whom you make some purchases",
"you speak of it",
"I have some of it",
"I think of it day and night",
"I promise you to be there",
"Do not unto others that which thou wouldst not like to be done unto thee",
"It is folly to grieve at the success of other people.",
"Everybody for himself, and God for us all",
"Each language has its oddities",
"it is said",
"somebody dances",
"No one has told it to me.",
"I have seen but one person.",
"Is there anybody who dares deny this fact?",
"Do you know any one of these ladies, some of these gentlemen?",
"Whoever is born envious and bad is of course miserable",
"Whoever will be strong to encourage her husband and her sons to fight for the common country will be honored",
"The brother and the sister love each other",
"Brothers and sisters should love one another",
"It is a man such as you want",
"Like master, like servant",
"He went to such a city",
"Many a one is rewarded that deserved to be punished",
"Mr. Such-a-one",
"Mrs. Such-a-one",
"All but honor is lost",
"Everything is finished",
"they are astonished",
"they have forbidden",
"they are delighted",
"they would have preferred",
"I have it",
"I have some",
"I have there",
"I have not",
"I have it not",
"I have not any",
"I have not there",
"I have had it",
"I had had some",
"I have had there",
"I have not had",
"I have not had it",
"I have not had any",
"I have not had there",
"Have I it?",
"Have I some?",
"Have I there?",
"Have I not?",
"Have I not it?",
"Have I not some?",
"Have I not there?",
"Have I had?",
"Have I had it?",
"Have I had some?",
"Have I had there?",
"Have I not had?",
"Have I not had it?",
"Have I not had some?",
"Have I not had there?",
"I have been",
"thou hast been",
"he has been",
"one has been",
"we have been",
"you have been",
"they have been",
"thou wast",
"they were",
"thou wast",
"they were",
"thou wilt be",
"he shall be",
"one shall be",
"we shall be",
"you shall be",
"they shall be",
"I had been",
"thou hadst been",
"he had been",
"one had been",
"we had been",
"you had been",
"they had been",
"I had been",
"thou hadst been",
"he had been",
"one had been",
"we had been",
"you had been",
"they had been",
"I shall have been",
"thou shalt have been",
"he shall have been",
"one shall have been",
"we shall have been",
"you shall have been",
"they shall have been",
"I should be",
"thou shouldst be",
"he should be",
"one should be",
"we would be",
"you should be",
"they should be",
"I should have been",
"thou wouldst have been",
"he should have been",
"one should have been",
"we would have been",
"you should have been",
"they should have been",
"let him be",
"let some one be",
"let us be",
"let them be",
"it is supposed",
"they wanted",
"it will be doubted",
"it was thought",
"I have not been",
"I have not been it",
"I have not been there",
"Am I with, of it?",
"Am I there?",
"Am I not?",
"Am I not it?",
"Am I not with it?",
"Am I not there?",
"Have I been?",
"Have I been it?",
"Have I been of it?",
"Have I been there?",
"Have I not been?",
"Have I not been it?",
"Have I not been of it?",
"Have I not been there?",
"thou speakest",
"he speaks",
"one speaks",
"you speak",
"they speak",
"I was speaking",
"thou wast speaking",
"he was speaking",
"one was speaking",
"we were speaking",
"you were speaking",
"they were speaking",
"I have spoken",
"thou hast spoken",
"he has spoken",
"one has spoken",
"we have spoken",
"you have spoken",
"they have spoken",
"I had been speaking",
"thou hadst been speaking",
"he had been speaking",
"one had been speaking",
"we had been speaking",
"you had been speaking",
"they had been speaking",
"I had spoken",
"thou hadst spoken",
"he had spoken",
"one has spoken",
"we had spoken",
"you had spoken",
"they had spoken",
"I shall have spoken",
"thou wilt have spoken",
"he will have spoken",
"one will have spoken",
"we shall have spoken",
"you will have spoken",
"they will have spoken",
"I should, would speak",
"thou shouldst speak",
"he should speak",
"one should speak",
"we should speak",
"you would speak",
"they would speak",
"I should have spoken",
"thou wouldst have spoken",
"he would have spoken",
"one would have spoken",
"we should have spoken",
"you would have spoken",
"they would have spoken",
"let him speak",
"let us speak",
"let them speak",
"they want",
"she has approved",
"I speak not",
"I speak it",
"I speak it not",
"I speak to him",
"I speak not to him",
"I speak to them",
"I speak not to them",
"I speak of it",
"I speak not of it",
"I speak to him",
"I speak not to him",
"I have not spoken",
"I have spoken it",
"I have not spoken it",
"I have spoken to him",
"I have not spoken to him",
"I have spoken to them",
"I have not spoken to them",
"I have spoken of it",
"I have not spoken of it",
"I have spoken to him",
"I have not spoken to him",
"Do I speak?",
"Do I not speak?",
"Do I speak it?",
"Do I not speak it?",
"Do I speak to him",
"Do I not speak to him about it?",
"Do I speak to them?",
"Do I not speak to them?",
"Do I speak of it?",
"Do I not speak of it?",
"Do I speak to him of it?",
"Do I not speak to him of it?",
"Have I spoken?",
"Have I not spoken?",
"Have I spoken it?",
"Have I not spoken it?",
"Have I spoken to him",
"Have I not spoken to him about it?",
"Have I spoken to them about it?",
"Have I not spoken to them of it?",
"Have I spoken of it?",
"Have I not spoken of it?",
"Have I spoken to him about it?",
"Have I not spoken to him of it?",
"some of it",
"we change",
"I changed",
"I am weary",
"I shall be weary",
"I advanced",
"I shall throw",
"it will freeze",
"I receive nothing",
"I receive him no more",
"I receive but little of it",
"I do not receive her",
"I never receive them",
"Receivest thou nothing?",
"Dost thou receive him no more?",
"Receivest thou but little of it?",
"Dost thou not receive her?",
"Dost thou never receive them?",
"I am loved",
"thou art loved",
"he is loved",
"one is loved",
"we are loved",
"you are loved",
"they are loved",
"I was loved, was being loved",
"I was loved",
"I have been loved",
"I had been loved",
"I had been loved",
"I shall, will have been loved",
"I should, would, could, might be loved",
"I should, would have been loved",
"let him be loved",
"let her be loved",
"let one be loved",
"let us be loved",
"let them be loved",
"let them be loved",
"I deceive myself",
"thou deceivest thyself",
"he deceives himself",
"one deceives one's self",
"we deceive ourselves",
"you deceive yourselves",
"they deceive themselves",
"I was deceiving myself",
"thou wast deceiving thyself",
"he was deceiving himself",
"one was deceiving himself",
"we were deceiving ourselves",
"you were deceiving yourselves",
"they were deceiving themselves",
"I did deceive myself",
"thou didst deceive thyself",
"he did deceive himself",
"one did deceive himself",
"we did deceive ourselves",
"you did deceive yourselves",
"they did deceive themselves",
"I hear the hammers striking the anvil.",
"the striking hammers made the building tremble.",
"children obeying their teachers are praised.",
"I hear people vociferating in the street.",
"obedient children are the joy of their parents.",
"I hear vociferating people in the street.",
"These girls, by studying always with the same care, can not fail to succeed.",
"Pupils not studying can never succeed.",
"my friends excepted",
"these facts supposed",
"that hour passed",
"The truths that have been said.",
"The women have left.",
"The business has been settled.",
"What hard truths they have told each other!",
"They have told each other some hard truths.",
"They have pleased each other.",
"They have injured each other.",
"my daughter has written me",
"the children have wept",
"The flowers which she has given me.",
"The letters which I have written.",
"The ladies whom he has known.",
"I have written the letters.",
"He has known the ladies.",
"certainly",
"by no means",
"He spends his time in drinking, eating, and gambling.",
"A house constructed of marble, iron, bricks, and wood.",
"She surpassed all the other girls in beauty, grace, and loveliness.",
"In peace and in war.",
"With a loving wife, with children well brought up, and with good books, one may peacefully grow old.",
"she lives with her parents",
"he seeks to injure me with my uncle",
"he is near his friend",
"it is nearly three o'clock",
"at the price of his honor he has capitulated",
"to your house",
"at home in one's house",
"at his house",
"among the Greeks",
"with a useful end in view",
"to act like a man",
"from south to north",
"from five o'clock till six",
"I have not seen him for a long time",
"the army marches against the enemy",
"who is not for me is against me",
"this is contrary to my advice",
"you are ungrateful toward us",
"she is among good friends",
"the mother holds her child in her arms",
"from New York to Washington",
"he loves even his enemies",
"unto death",
"I am ready to leave",
"he lives opposite the church",
"your behavior toward your brothers is objectionable",
"now, to return to our subject",
"on the contrary",
"unless you are industrious",
"for fear he might complain",
"he called on his teacher in order to obtain his pardon",
"I wrote him so that I might hear from him",
"any work is useless unless well done",
"before dying he sent for the priest",
"I have not dared to do it for fear of displeasing my father",
"The deuce!",
"Ah, indeed!",
"Cheer up!",
"Now, then!",
"Well, now!",
"Well, courage!");

function thirdFrenchLine()
{
	global $french3lines;
	return $french3lines[array_rand($french3lines)];
}

?>