<?

// http://www.gutenberg.org/cache/epub/15127/pg15127-images.html

	$spanishlines = array(
"The father, the mother, and the brother.",
"A pencil, a pen, and an inkstand.",
"The old man and the old woman.",
"A hat and some boots.",
"The shirt and the trousers.",
"I buy the tree.",
"He sells some flowers.",
"I fear.",
"He fears.",
"We sell.",
"We set out.",
"You set out.",
"I buy.",
"He sells.",
"The brother and the sister sell.",
"They speak to the man.",
"We set out for London.",
"The old woman has the hat.",
"The old man has the flower.",
"Who has the ink and a pen?",
"The father has the coat.",
"Gold is precious but virtue is more precious.",
"I sell paper to the woman.",
"You fear.",
"You buy some flowers.",
"She speaks to the sister.",
"The father and the mother of the captain.",
"Do you speak Spanish?",
"No, but I speak Italian well.",
"Do your customers buy goods?",
"They buy machines and ironware, but my correspondent in Havana buys prints in very large quantities.",
"Who sells paper and ink?",
"The old man sells them.",
"Who writes a letter?",
"I write letters.",
"Who drinks wine?",
"I do not drink wine.",
"Do you drink beer?",
"I do not drink beer but I like coffee and tea.",
"Poor John is my friend.",
"What a beautiful rose!",
"Do your brothers study French?",
"Yes, and they study German.",
"Who studies Italian?",
"My sister-in-law studies Italian and French.",
"The merchant was elected a member of your society.",
"Mr. Brown is a captain.",
"John set out for America.",
"I like to study foreign languages.",
"Do you study German?",
"We study French and Italian, but my cousin studies English.",
"Does he understand English?",
"He understands English perfectly, but he speaks Spanish badly.",
"Does your sister speak Italian?",
"No, she speaks only English.",
"What does the Englishman buy?",
"He buys a horse from the Frenchman.",
"My cousin sold his horse to Peter.",
"John looks for his book and his paper.",
"The copy book is on the table.",
"Henry must copy some letters.",
"Who copies the letters here?",
"Peter copies them.",
"Has Henry much paper?",
"Yes, he has much paper but little ink.",
"The roses and violets are in the flower-stand.",
"The merchant has received four bales of silk handkerchiefs and three cases of prints and muslins.",
"Who is a good clerk?",
"My brother-in-law is a good clerk but he is tired of working.",
"The windows and doors are clean.",
"Yes, they are cleaned every morning by the servants.",
"He is speaking to his French friend.",
"He is writing a letter to his mother.",
"They are looking for some handkerchiefs.",
"Have the merchants sold the velvet and the baize?",
"Yes, they sold them yesterday; also the muslin and prints.",
"Who bought them?",
"The Germans are a very active and hard-working nation, and they deserve therefore our sincere admiration.",
"Where are the sealing-wax, the candle and the matches?",
"Here they are on the writing-desk.",
"Does the clerk understand German?",
"Yes, very well.",
"My partner and I will dine at the Royal Hotel.",
"I have some money.",
"What goods do you want?",
"I want some brown prints and some red calico.",
"I have no red calico, but I must buy some.",
"Do you want to sell me any?",
"There are many inkstands in this shop; do you want any?",
"Yes, I want some.",
"Have you any bread?",
"Yes, I have some bread and cheese.",
"Any book will be useful.",
"The teeth and the tongue are inside the mouth.",
"The teeth want great attention.",
"Yes, they must always be clean.",
"We want to study Spanish because it is very necessary in commerce.",
"If you study with attention you will soon speak and write Spanish very well.",
"John speaks French very badly but he is studying it with much attention.",
"Do you understand this lesson?",
"Yes, I understand this lesson well; it is not very difficult.",
"No lesson is difficult if we study with care.",
"Foreigners in England enjoy many advantages.",
"Yes, because England is a free country.",
"Englishmen also enjoy the same advantages in other free countries.",
"Does the teacher help his pupils?",
"He does, but the pupils must study and learn their lessons well and work diligently.",
"This morning I was writing a letter when my sister spoke of the bicycle she wants to buy.",
"Did you sell the muslins and prints you bought last year?",
"The merchant has drawn a bill at three months' date for the velvets he sold to the Spanish customer.",
"Little and good is better than much and bad.",
"John is a partner in that firm.",
"It is necessary to work.",
"This is George's beautiful garden.",
"It is a large garden with many flowers, roses, carnations, violets and other plants.",
"Who is here?",
"Charles and Henry are here.",
"I shall be compelled to abandon this undertaking.",
"It is too difficult.",
"We received a consignment of rice, but the price demanded, 2-15/16d. a lb., is too dear;",
"we shall never be able to get it;",
"a better quality, whiter and stouter, was placed at 2-29/32d. but a few days ago.",
"If you cannot sell your plain and figured drills at the figures quoted it will be necessary to abate the price.",
"I shall accept those bleached linens subject to an abatement of 5 per cent.",
"We shall consult our partners;",
"meanwhile let us leave the matter in abeyance.",
"He has chosen several designs for his lot of prints, but he finds that three of them are wrong.",
"Some firms always give wrong weights in their declarations.",
"He ordered the wrong article.",
"You are wrong, it is the right article.",
"This cloth is finished on the wrong side.",
"We received your favour of 10th instant, enclosing copy of your previous letter 1st ult. and have taken note of its contents.",
"By next mail we shall send you all the details required.",
"We beg to confirm our cable of last week.",
"They calculated their profits and losses.",
"I calculate upon doing it before Easter.",
"This is not calculated to produce any bad impression.",
"He called him to his house.",
"We take the liberty to call your attention to the position of your account.",
"The creditors were called to a meeting.",
"I was called away.",
"I shall call at the exchange.",
"All the old issues were called in.",
"The \"Shannon\" will call at Cádiz.",
"They will make a call of £1 per share.",
"This steel is worth much less than that.",
"It is not worth buying.",
"This limited company is worth £50,000.",
"This scheme is worthy of study.",
"Please protest the bill in case of non-acceptance and then again for non-payment.",
"The law of supply and demand governs the markets of the world.",
"The deeds were all signed by a notary.",
"Kindly take due note of our signature at foot.",
"All our efforts have been of no avail.",
"In vain we tried.",
"Did you see the new Custom House tariff?",
"Yes, I saw it.",
"It is more favourable to us than the old.",
"We sent it to the manager of our Liverpool branch.",
"We sent it to him yesterday;",
"he will return it to us after he has read it.",
"Did you give it to me or to him?",
"I gave it to you, not to him.",
"Well!",
"he says that he will not give it to me until you tell him to do so.",
"He took it with him, and we took it with us.",
"I shall take it with me.",
"Take it with thee.",
"It is a long letter, but it is necessary to write it to-day.",
"Writing it to-day you are in time for the post.",
"Mr. So-and-So gave more money to you than to me.",
"We have taken notice of it.",
"Take due notice of the contents of the letter.",
"Give him notice of the sales you effected on his account.",
"There is nothing worthy of notice in our market to-day.",
"I gave him notice because he is very lazy.",
"This circumstance must have escaped your notice.",
"Do not take any notice of him.",
"I gave notice to my landlord.",
"I flatter myself that you will be pleased with my purchases seeing the firmness of prices at present.",
"We consider ourselves lucky not to have listened to their advice.",
"He is always speaking of himself and of his business.",
"He found himself a loser.",
"They declared themselves bankrupts.",
"They wrote to each other often.",
"He respects himself.",
"He himself respects old customs.",
"We acknowledge we are wrong.",
"We acknowledge receipt of your favour.",
"We shall gratefully acknowledge any help you may render to our friend.",
"We hope you will be very accurate in your figures.",
"The output for the first two months of the current year was 18,668 lbs. dry rubber.",
"The bill market was very firm to-day but there was little doing.",
"Dealers were reluctant to do business in the securities.",
"Rubber shares were lifeless, but prices were maintained.",
"We beg to inform you that your order has been placed at your prices owing to the fall experienced in our market.",
"In our monthly report, which we beg to enclose, we have stated the present position of our grain market.",
"Please forward the enclosed letters to their address.",
"Our risk would be great and therefore we must adhere to our request of an adequate commission.",
"The average having been adjusted we now hasten to enclose our cheque for £59 16s. 9d. in settlement of your claim as per statement enclosed.",
"Trusting you will be satisfied with this result, we are, yours faithfully.",
"We have secured room for the remainder of your machinery in the steamer leaving our port on the 10th prox.",
"We shall ship these iron beams and those steel rails by a sailing vessel which we intend to freight at a lump sum, with at least ten lay days for discharging.",
"This will avoid any difficulty in that respect.",
"A German motor-boat was making this week a trial run in a heavy sea when she capsized.",
"The net profits of this year show an increase of £1,000.",
"The working of those collieries has resulted in a loss.",
"Messrs. Brown & Co. of your city have sent their agent over to make considerable purchases.",
"We hastened to submit to them our best terms offering a credit of nine months against their acceptances.",
"These terms are better than those of our competitors.",
"This is certain.",
"He who robs you of money robs you of little, but he who denies you a debt of well-deserved gratitude robs you of more, which is obvious.",
"Those who deny this have not experienced how painful is the sting of ingratitude.",
"Those who do good should do it expecting ingratitude for their reward, then they will not be disappointed.",
"It is a truth than which no bitterer exists.",
"The steamer I have bought is a first-class boat.",
"The little house I paid for.",
"The firm I made mention of enjoys good credit.",
"I wonder if this is the engineer whose son is a lawyer.",
"Their market is very slack at present, which accounts for the want of their remittances.",
"I acquainted them with all the facts, which made them very cautious.",
"We are acquainted with Mr. McIntyre, who is a Scotchman.",
"He is only an acquaintance.",
"What reduction can you make?",
"Twopence a yard.",
"Which of the two will you have?",
"What orders did you give?",
"Whose goods are these?",
"What a surprise!",
"How much money did you receive?",
"How many lots of white shirting have you placed?",
"Did you answer all his letters?",
"If we bought the produce dearer than the figure you indicated we should have to answer for it.",
"The cotton prints and union drills we sent you will answer your requirements.",
"Mr. Pérez seems annoyed by your refusal.",
"I am very sorry but it is not my fault.",
"I could not accept the rebate under the circumstances.",
"Has the steamer called at Málaga?",
"I believe she has.",
"Somebody thinks that the imports of food-stuffs will increase.",
"Some wheat buyers take little notice of the higher American cable advices.",
"Weavers and spinners are all holding up their prices.",
"Each week shows an improvement.",
"We hear the same reports from all quarters.",
"Neither of these machines will suit our requirements.",
"We accept these bills but refuse the others.",
"Anybody who has his own interests at heart will contribute to the realisation of the scheme.",
"I did all I could so that nothing should be lost.",
"Some say the market will go up, some say it will go down, and such is the position that one does not know what to do.",
"Anything is preferable to this uncertainty.",
"I have not seen anything so pretty before.",
"Mail advices from America report an abnormal curtailment of production in the United States Cotton Mills.",
"They cannot take the risk of piling up stocks when the demand is so slight.",
"A weak tone ruled at the opening.",
"During the later dealings a slight improvement was noticeable.",
"Have you obtained the sole agency for that firm?",
"Not yet, but I hope to get it.",
"How long have you been living in England?",
"Two weeks ago prices were so high that buyers were rushing their orders;",
"now they have suddenly fallen to an unprecedented level.",
"He has examined the samples and found that the designs of the light grounds are not as ordered.",
"He also complains of the checks and stripes.",
"The spot muslins have been delayed owing to a breakdown in the works.",
"The senders are trying to throw the blame on the Railway Company, but we have no right of claim against the latter;",
"it is they who must indemnify us for the loss.",
"It is a well-founded and respectable firm and they will not deny their responsibility.",
"there is no doubt about that.",
"Is it long since you received their last letter?",
"Have they been long established?",
"They have been for 15 years.",
"Our friends have large stocks but they say the market is looking up.",
"We have just received your Price List, but we are sorry to say your prices are too dear.",
"The cylinders and boilers are now ready.",
"Every engine is sent out with its complete equipment, viz., tubes, valves, cocks, etc.",
"The Directors are preparing a balance sheet to be laid before the company at the next ordinary general meeting.",
"It will show the assets and liabilities and a profit and loss account made up to date.",
"There will also be a report on the position and transactions of the company.",
"It is your action which has done us more harm than anything else.",
"It is we who are tired of our agreement.",
"The goods are at your disposal.",
"We think the shares will be inactive.",
"The demand for steel, iron and copper was very steady but it is probable that it will not last.",
"Are you rich?",
"No, I am poor but I am happy.",
"Our quotations will be maintained except in case of strikes or other unforeseen circumstances.",
"The four bales of linens will be delivered to you carriage paid, but the boilers and accessories you will receive carriage forward.",
"The whole will be insured with particular average.",
"Kindly see Mr. Marino and inform him that we shall soon send him a consignment of timber, consisting of ash, beech, birch, fir, pine and oak.",
"We shall instruct our correspondent at Bilbao to forward to Vitoria the brass, lead, tin, and zinc he holds at our disposal.",
"By the boat leaving this week, we shall ship to your consignment the bagging, belting, and bedsteads.",
"The \"María\" docked yesterday with a cargo of broad beans, French beans, green peas, and Spanish or chick peas.",
"She also brings a parcel of jerked beef and canned tongues.",
"I have a friend who is a dealer in billiard tables, balls and cues.",
"The candles and chemicals have been despatched last week.",
"We flatter ourselves that we shall shortly be able to write to each other pleasanter letters.",
"We have insured the china and crockery free of particular average, but we insured them against breakage at a premium of 4%.",
"Herewith please find claim for loss through damage in your last shipment of clocks and watches.",
"Please send by slow train the coats, vests, and trousers and, by passenger train, the remainder of the articles.",
"You have anticipated my wishes.",
"A further decline in prices is anticipated.",
"We overloaded ourselves with stocks in anticipation of large orders.",
"To pay in anticipation.",
"Thanking you in anticipation we remain.",
"The news from the East produced a bad effect on the market.",
"To this effect I wrote him to draw at sight.",
"Our efforts have all been to no effect.",
"His plans have been carried into effect.",
"The sailing vessel carried 800 tons of grapes and raisins, 600 under and 200 on deck.",
"She used 5 lay days in loading, having therefore 3 days left, so that we do not think we shall have to pay demurrage.",
"The captain paid for stowage at the rate of 1s. per ton.",
"The advance on account of freight is £120.",
"I wonder if everything will be in order?",
"I send you several patterns of curtain-lace, damasks, diapers, ribbons, buttons, and brushes.",
"The net revenue for the half-year from the main line amounted to £607,297 as against £743,077 in 1909.",
"The expenditure in England and the Interest on Stores reduce the amount to £594,714.",
"The Stock Exchange will be closed from this evening until next Monday morning.",
"The turnover of the day's transactions has been small.",
"Sentiment turned somewhat bearish during the forenoon, but became decidedly bullish towards the end of the day.",
"The following figures show the amount of bills and cheques which passed through the banker's clearing-house during the week ended April 12th.",
"We must not attach too much importance to the rumours which are circulating in the market.",
"You should take care that the bales are properly packed.",
"I was ignorant of the fact that he had been declared a bankrupt.",
"I shall do all that depends on me to collect the money in full.",
"As far as we are concerned, we have decided not to take any steps in the matter.",
"We do not wish to throw good money after bad.",
"We shall invoice by next mail your glassware and haberdashery.",
"Ham is a drug in the market.",
"A good business is done at present in dry salteries.",
"A good crop of maize is announced from Cape Town.",
"With reference to your esteemed order of 1st inst. for skins and hides, we understand exactly what you want, but we much regret to say that we are unable to get in at your limit.",
"We acknowledge receipt of your favour of the 1st inst. with note of purchase we are to make on your account, and we shall report thereon by our next.",
"We have picked up a few suitable clearing lines, which are awaiting shipment by next steamer.",
"Owing to a breakdown in the works these will not be ready for another fortnight.",
"The goods were packed according to your instructions, but we take no responsibility for sending them in bales instead of cases as usual.",
"We hand you enclosed the invoice amounting to £155 6s. 7d. to the debit of your account, value 15th inst.",
"We can assure you that any orders entrusted to our care will receive careful attention.",
"Our traveller will be in your district by the beginning of September, and he will have much pleasure in waiting upon you with our full collection of dress goods and fancies.",
"We hasten to offer you a lot of cheap mohairs and nankeens and hope they will meet your requirements.",
"I do not consider I have been fairly treated.",
"We note your complaints but you know they were bought as job lots and in buying such lots, one has to put up with some imperfections.",
"The hats and caps have turned out excellently.",
"The former are exactly of the shape and curl you require and the latter include a large variety of designs.",
"They will reach you in plenty of time for the coming season.",
"Please report on samples as soon as received.",
"Reading good papers is necessary to keep oneself posted up, but reading the sensational news of a certain press is wasting one's time.",
"Are you going to Spain this year?",
"I do not think so, my correspondent is coming to England.",
"We shall write to the gentleman acting as secretary to send us a copy of the report.",
"Did you hear him saying that?",
"I regret having to inform you that once I have paid what I owe, I shall not continue my transactions with your firm.",
"We should like to do more business with your firm.",
"You would greatly oblige by sending us a remittance.",
"He would do well to write it to them.",
"Let him write at once.",
"We hope you may arrive safe and sound, and we advise you to take care of yourself.",
"From what we can gather the firm is doing a successful business.",
"We trust this information will be of service to you.",
"The documents appear to be in order and we hope there will be no difficulty.",
"We are glad the goods have arrived before the time stipulated.",
"We do not want you to lose any money;",
"on the contrary, we wish you to realise a substantial profit.",
"Tell the clerk to write more politely.",
"Order them to do it quickly.",
"I may come to-morrow.",
"We notice that the Razors, Scissors, Penknives and Skates are ready to be shipped, and trust that, as announced, they will come to hand without delay.",
"We thank you for the confidence you have shown in us which we hope to justify and you may be sure that we shall do our best for your interests.",
"I request you kindly to insure the cargo against total loss or f.p.a.",
"Sell at 21s. c.i.f.",
"It is impossible for us to obtain the goods.",
"He spoke as if he were sure of it.",
"I may accept your price, provided you pay cash.",
"It is certain the white shirtings have shrunk too much in bleaching.",
"He insisted until he paid him something and now he will continue to insist until he pays him something more.",
"The foreign correspondent did his work so that his employer was satisfied.",
"Write clearly so that people may read your writing without difficulty.",
"Whenever I spoke to him he was very polite, therefore, I shall put a word in his favour whenever I can do so.",
"I reprimanded him notwithstanding that he was my son, and I shall do so whenever it is necessary in spite of his being now a man.",
"The first to come was the office-boy, and he will be the last to go.",
"The first firm that attempts it will burn its fingers.",
"He was the only one who understood us.",
"He is not the only one who is mistaken.",
"They will not be the only persons who will be mistaken.",
"Whoever succeeds in perfecting this contrivance will be sure to make a mint of money.",
"We shall be thankful if you will cancel our order for flax, hemp, Manilla hemp and jute.",
"I believe his behaviour is most objectionable.",
"And I do also.",
"Did you receive the B/L for the cargo of oranges and grapes from Seville?",
"I did;",
"and I expect a good parcel of muscatels from Valencia as well.",
"Are these the lemons, onions and pomegranates you were expecting?",
"They are.",
"I am sorry they were delayed so long because now the market is glutted with fruit.",
"He is my friend and I am his.",
"We received this year three cargoes of bananas from the Canary Islands.",
"Six were consigned to us last year, but we used to receive many more when we sent our traveller in those islands at harvest time.",
"Ten thousand boxes of currants, 3,000 of figs, and 4,561 of dates were sold by auction.",
"There had not been such large quantities offered for a long time.",
"The iron-clad \"Achilles\" left yesterday for Vigo.",
"The sea was perfectly calm although a light breeze blew, or was blowing, from the S.W..",
"The commission-agent went by the three o'clock train.",
"When I went to say good-bye to him he was writing a letter.",
"The cargo was examined and it was found that some of the fruit was unripe, some shrivelled or frost-bitten, and a parcel of garlic was rotten and had to be destroyed.",
"We wrote them nothing to warrant such action.",
"I warranted him this would not be repeated.",
"The cloth was warranted fast colour.",
"He resorted to extreme means in order to bring about a solution of the difficulty.",
"In the past year the climax of prosperity was reached.",
"Large orders for railway rolling stock were countermanded on account of the feared political complications.",
"Velvet and Cord manufacturers have curtailed their production with a view to check the downward tendency of prices.",
"I matched his sample and I secured the order.",
"Did you hear from your traveller lately?",
"They charged us too much, we can buy on spot much cheaper.",
"Spot cotton was quoted yesterday one point higher than the day before, but futures declined 3/32",
"Perhaps there are better prospects of the growing crop at present.",
"Do not be long in making up your mind one way or the other.",
"No, I shall soon decide what to do, but I must have a little time for reflection.",
"I cannot bind myself on the spot.",
"Some of the prints have grease spots and we must refuse to accept them unless under a reasonable allowance.",
"He has a villa in a delightful spot in the country.",
"We shall have to take in the hosiery although it is slightly overdue.",
"We have to give the example of fair dealing ourselves.",
"Who is to decide on the subject of the indemnity due to the captain of the ship?",
"If we want to withdraw the goods without producing a B/L. we shall have to sign an indemnity.",
"We have received the account sale for our wines and oils and regret the venture has not turned out as well as we expected.",
"We found a great difficulty in parting with our surplus stock, of which we had to dispose at prices very much reduced.",
"We are unable to inform you to what extent you may calculate on our remittance, as much will depend on circumstances over which we have no control.",
"The rate of the insurance premium is 6/-per cent. on the outward and 5/-per cent. on the homeward voyage.",
"I very much question the advisability of putting prices up at the present moment when so many adverse circumstances have to be taken into consideration.",
"As a matter of fact most of us think it would be better to reduce them somewhat now that competition is so keen.",
"They vie with each other in cutting prices down with the result that profits are ridiculously low.",
"After writing you by last mail we are informed by the maker of the Brown Linens that he will be able to book your order which will be delivered before the end of next month.",
"The Brocaded Satins will range between 4d. and 5d. a yard, and we shall ship them within six weeks but only after receiving your letter confirming them.",
"These shapes are not worn outside England.",
"Not far from here and next to the Bank there is the Insurance Office, which is much admired for its solidity and fine appearance.",
"It cost £20,000 and they never thought it would exceed half that amount.",
"Perhaps it is too large an outlay for the Company, but there was no money wasted.",
"The columns in the porch have cost so much because they are of the best Carrara marble.",
"Whilst we admit that the prints sent may have been just a little bit off shade your claim is quite out of the question.",
"Towards the beginning of the autumn our Mr. So-and-So will make a trip to your place, and he will have the honour of waiting upon you with our latest novelties.",
"You do not understand how it is possible that your neighbours are able to undersell you, nor can we make it out either.",
"He offers a loan to avoid all risk that the house should fall.",
"It would not be possible for it to fall unless the Textile Bank should stop payments.",
"His office is opposite ours and we have him thus under our eyes.",
"With all the weight of the evidence you have collected, it would be very risky to proceed against him from such a distance.",
"Between one thing and the other I did not know what to choose, so I left them to settle the matter between themselves.",
"These sketches have been made by our draughtsman for our customers, the owners of the Sugar Mill in Parahyba.",
"He did the work for the pleasure of it but would not charge a farthing for it.",
"The packets arrived two by two.",
"I accede willingly for the sake of old friendship.",
"As the time of the year is drawing near when your firms effect their purchases in this country, we beg to address you to renew the offer of our services.",
"We shall be extremely glad if you will avail yourselves of our offers and send us orders for some of your requirements.",
"The adjustment of the average per S.S. \"Nile\" is still hanging fire, but we are pushing the Insurance Co. to our utmost for a speedy settlement.",
"For a foreigner he understands English methods very well indeed.",
"Being so young he shows a good deal of tact and foresight.",
"These 200 pieces will not go in that case, it is too small.",
"I do not think they will, either.",
"I cannot say anything before I see the result, but I shall be able to tell you something definite to-morrow.",
"Not being able to compete, he has withdrawn from the market.",
"I could not confirm the agreement last week.",
"I believe I could buy a parcel of wheat cheaper to-day unless there should be a sudden rise.",
"In spite of all his efforts, he was obliged to file his petition.",
"Although the market here is firm, we have hopes that prices will relax in view of the bearish tone shown in the Liverpool market yesterday.",
"The enclosed pattern is rather poor;",
"still, as it appears to sell well in Central Africa, I should be glad if you would see your way to manufacture it at our price.",
"The new presses work fairly well;",
"there is, however, room for improvement, and our engineer will write you fully on some proposed modifications.",
"He signed the documents without even reading them, so upset was he by the news the mail had just brought him;",
"therefore we shall be obliged if you will kindly send them back for his perusal and return.",
"Provided you take a lease of these premises for a period of ten years, I shall make the necessary alterations, since I am very eager to have you as a tenant.",
"Although the demand for money is no longer so strong, the market is still under the control of the Bank of England, to which it is now indebted for a considerable amount, and dealings are but on a comparatively small scale.",
"An \"iron framing\" is a framing made of iron, but a \"steam engine\" is an engine moved by steam.",
"I had the intention of giving more such examples but I believe one is enough.",
"In the construction of this building the architect had in view both the beautiful and the practical.",
"Yes, see how elegant and at the same time how solid these columns are!",
"Business conducted through us is different from the many advertised systems and promised short cuts to wealth which are dangled before the eyes of the public.",
"Our plan is a plain, straightforward method of operating by which we undertake to implicitly carry out the instructions of our customers.",
"Our best advice and service are always at your command.",
"\"Kaffirs\" have resorted to a state of idleness coupled with steadily sagging prices.",
"Holders of spot cotton have again experienced quite a brisk inquiry from spinners, who have freely covered forward sales of yarn.",
"They also took up large lines of cotton previously contracted for.",
"The total turnover was not quite as good as expected.",
"The steamer ran aground on the Spanish coast but the crew were saved.",
"People are apt to forget the teachings of history.",
"His action has put me in a serious embarrassment.",
"I put it as a condition that the bills be drawn against delivery of B/L and insurance policy.",
"They placed all their trust in their agent.",
"I do not mean to say that they wanted to deceive him.",
"When prices improve we shall be willing to sell.",
"I do not know what effect this had on the market.",
"If I knew, I should be able to act accordingly.",
"I do not think he knows what suits him best.",
"The Directors are not in the least disposed to launch upon a large foreign trade, so that the operations of the concern remain confined practically to the inland market.",
"We received a claim on our last shipment but we refused to entertain it as the goods were jobs and were sold as they were with all faults.",
"We are sorry our customers should have suffered any loss, but we cannot make it good, and we shall stand our ground.",
"If you cannot command cash, we shall have to alter our price lists as our prices will have to be reckoned on a different basis;",
"they will be a little dearer.",
"I am bound to say that there is some very strong opinion on this side against the course your Government intends to pursue in the matter.",
"The situation has been complicated by the breakdown of the arrangement we had made with our carriers.",
"I believe that the reason actuating Mr. Melero's attitude towards us, a reason which he hinted more than once in his correspondence, is that his articles of partnership with his friends in Rosario preclude him from entertaining any new ventures.",
"At the monthly meeting of the Council of the Chamber of Commerce the Japanese tariff was discussed on a communication from the Board of Trade.",
"We have to acknowledge the receipt of your esteemed letter of the 1st inst., which brought us £640 on L. & Sons, payable August 10th.",
"Carried forward.",
"Brought forward.",
"Brown sugars have been rather brisk for some time.",
"The manufacturer has discontinued making the old article.",
"The Directors of the Z Company announce an interim dividend for the first six months of the current year at the rate of 10 per cent. per annum.",
"Reuter's Paris correspondent telegraphs that earnest representations are being made by the British Chamber of Commerce in Paris to the French Customs Administration concerning the recent change in the classification of yarns wound on bobbins, a matter which seriously affects Lancashire interests.",
"The great object the meeting had in view was the promotion of further progress and civilisation.",
"That necessarily implied fewer appeals to the arbitrament of the sword and more frequent appeals to the remedy of reason.",
"I wish to straighten the desk on my table.",
"My pad is full of papers;",
"I must get rid of them.",
"Will you put all those answered letters in that shelf;",
"You will find the pigeon-holes alphabetically arranged, put each letter in the proper bundle.",
"These others are filed away in that letter-file, alphabetically also.",
"Put the file in the safe;",
"we always keep it under lock and key.",
"Now give me a quire of blotting-paper, pens, nibs, paper-fasteners and the stamp-rack.",
"These envelopes go into the waste-paper basket.",
"Fetch that stool, please;",
"place it before that desk.",
"See to the fire, it is going out, poke it a little and add some coal.",
"This is the coal scuttle, the shovel and the poker are near the fender.",
"Hot-water pipes are preferable to fires or stoves.",
"Yes, our chimney always smokes;",
"it is a nuisance.",
"Post these letters.",
"Stamp them and notice there are some to be registered.",
"Do not forget to put the stamp of the firm.",
"If any weigh in excess, it does not matter;",
"put the excess postage.",
"Seal that envelope;",
"here are the seal and sealing-wax.",
"We are open to charter a small steamer or a sailing vessel for St. Thomas in the West Indies.",
"We can offer you a small one for a voyage out and home.",
"The heating surface is 20' X 15'.",
"These warehouses are 30' long, 20' wide and 15 feet high.",
"Some are built with stone and mortar, others with firebricks, and they are the best in the docks.",
"Last week nothing was doing on 'Change, but' to-day leading operators are distinctly bullish and have acquired a further large holding, being more convinced than ever that prices will climb to a much higher level.",
"Meanwhile the market is getting dangerously overbought.",
"He gave me too short a notice and the consequence was 20 bales were short shipped.",
"He now complains of being short of printed linings, jacconets and crimps, also of short measure in some of the cloth invoiced.",
"Their orders fall short of what we expected.",
"We have run short of the raw material.",
"Our correspondents are short-staffed, hence their delaying often to send out our invoices, which is a great inconvenience.",
"It is I who conveyed that information to him.",
"The goods were conveyed by the Ship Canal.",
"Have you made it clear that the risk will be covered whether the casks travel by steamer or other conveyance?",
"Our agent contrived to get the fine refunded;",
"he wrote us so.",
"The vessel sprang a leak and was in danger but she spoke a Norwegian steamer, who gave her assistance and towed her to Havre.",
"The conditions you have put forth are altogether unacceptable.",
"Put him in the way of conducting his business without depending on outward assistance.",
"He conducted his late employer's business quite satisfactorily.",
"Had I feared he would not conduct his own affairs properly I should not have financed him.",
"He puts a wrong construction to my words.",
"He owes us some money and keeps putting us off.",
"He has put off his journey.",
"If you wish me to do business with your good selves you must put me on the best possible terms.",
"The alarming news from India has put our market out of gear.",
"Mr. Núñez was dreadfully put out by the news that the revolution had broken out in Ecuador.",
"We must put up with some inconvenience.",
"We shall put an end to this exercise.",
"I regret having left the newspapers at the workshop, but I shall send for them.",
"He regretted the turn for the worse in the market which compelled him to request us to ask our friend for a guarantee.",
"English manufacturers are not asleep.",
"They have been asleep for many years but now they are wide awake to the necessity of adopting up-to-date methods and adapting themselves to the requirements of the consumers.",
"Manufacturers are selling every day but usually in small lots.",
"Shirting makers want more money and find difficulty in getting it.",
"Dhooties and jacconets are now so well sold that producers will only book at good prices.",
"Heavy textiles are too stiff for general attention but makers are not hungry for orders.",
"Indian business was barely of normal dimensions.",
"Will you set the books on that shelf and set those papers in order?",
"The term you have set me is too short.",
"They ought to set a good example.",
"He set about it at once.",
"Setting aside the fact that he is behind with his payments, he does us great harm by running down our goods.",
"Winter has set in and heavy cloths are in great request.",
"I have set my mind on this venture.",
"A movement has been set on foot to bring about the revision of the bye-laws.",
"The long and short of the matter is that we had agreed he was to do it.",
"This is nothing short of dishonesty.",
"No matter what he will say I am sure he will have to pay.",
"The estimate and the sketches attached reached us just in time.",
"The cloth was run in pieces of 20 yds. exactly, the consequence being that some pieces were found by the customer to be with cuts.",
"It is of no use our struggling any longer against adversity.",
"Your writing in that strain shows plainly that their action has cut you to the quick.",
"By selling in time he managed to minimise the loss.",
"The shocking abuses that existed under the monarchy are being corrected by the Republican Government.",
"We shall show them that our firm is not to be trifled with.",
"These stuffs are too heavily sized and the finish is not sufficiently mellow.",
"Their feel is not clothy.",
"This defect will be made right in future deliveries.",
"The foreman is grateful for his master's kindness.",
"The Director is elaborating a bold scheme for establishing, in a foreign country hedged in by protective duties, a factory worked by native labour under an English manager and experienced English instructors.",
"If this plan reaches concretion he will be going abroad shortly, when he will find that his agents will be taking already the preliminary steps.",
"The Director himself is coming towards us, he will tell you more about it.",
"I am going to attend to several trifling matters which however want looking after.",
"Whenever I decided on a thing, I have always acted on my decision.",
"I tell you if I had a larger stock, I should feel rather uneasy at the prospects of the market.",
"Come and see me to-morrow at my office and we shall come to a friendly understanding without beating about the bush.",
"He told me the figures did not compare well with those of last year.",
"Please go through the accounts again and tell me the result by return of post.",
"Short reckonings make long friends.",
"He lost money as a result of his bad temper.",
"It is I who shall leave for Paris now that the matter is arranged.",
"I am going out as I hear somebody calling me.",
"Go, but do not be long.",
"Yesterday you went for a few minutes but it was an hour before you returned.",
"We have just heard of his approaching visit to England.",
"It happened to be on a bank holiday and our offices were of course closed on that day.",
"We shall be glad if you will kindly instruct your cashier to pay our account.",
"We have the pleasure of enclosing the pro forma invoices.",
"I am incapable of so much greed.",
"I am sorry to have to tell you that the cargo by the s.s. \"Maria\" was lost through the vessel stranding on the Spanish coast.",
"Coming back from having seen the machine working he told us how favourably impressed he had been.",
"He was dazzled by the brilliant prospects set before him.",
"This is nothing to me.",
"There is nothing or very little to be got out of that firm.",
"I have left no stone unturned to squeeze something out of this unfortunate business but it has been of no avail.",
"He thinks nothing of our work.",
"He wants to make us believe that the price at which he sold them barely covers his cost.",
"I do not care whether he gains or loses;",
"I have ceased to take an interest in his affairs.",
"Now I understand, and I shall not fail to take care not to do it in future.",
"He started laughing, and there the matter ended.",
"He was on the point of striking a bargain with him, but it fell through at the last moment and now everything is to be discussed again.",
"He failed to present himself at the creditors' meeting, and he has therefore forfeited his right of opposition.",
"He became very cautious after the experience he had.",
"He became very rich by his fortunate deals in railway shares.",
"The bill falls due on the 15th inst.",
"This proceeding is not becoming a firm of your standing.",
"The deeds are not in order:",
"please do not take amiss my requesting you to have them drawn up again.",
"I expected to see him, but I was disappointed.",
"Do not clamour so much, and try your luck again.",
"I shall make out a list of my book debts.",
"You would break your word if you did not plead for him.",
"He should explain his conduct, otherwise he will be dismissed.",
"We shall oblige him, but it must be under certain conditions.",
"He is sending me to the Court that I may watch that interesting case.",
"He sent his nephew here that he might learn our business methods and perfect his knowledge of the English language.",
"You may see for yourself that the state of the market will not justify buying at present.",
"They might be a little easier in their dealings.",
"Can you claim an indemnity for non-fulfilment of contract?",
"They could square up the account by signing promissory notes at 4 and 6 months' time.",
"They ought to forewarn their agents.",
"He would insist on saying we were in the wrong.",
"Should they acquiesce to the terms of the arrangements, we authorise you to sign it per pro.",
"Had he known the cloth was faded he would not have taken receipt of the bale.",
"Mr. Gómez is to visit the Estate and send a circumstantial report.",
"I shall let him attend the evening classes at the Manchester School of Technology.",
"It is only fair that he should have a chance of mastering the art of spinning and weaving.",
"If he would only devote his attention.",
"I would gladly accede to your request if it were in my power.",
"We are always impressing upon our warehousemen the importance of marking the measurement on the tickets.",
"Besides being loose colours they are not half so bright as they should be.",
"They advertise profusely and from time to time they issue new illustrated catalogues.",
"Soon they will start issuing them in foreign languages.",
"I never saw a better kept set of books.",
"I was nearly caught in the India Rubber boom, but fortunately I managed to get off without burning my fingers.",
"Come here, my friend, and listen to me.",
"Here in England things are managed on a different basis altogether.",
"Take that chair there and make yourself comfortable.",
"How much do you require, £100?",
"About that.",
"I was afraid you were going to ask me for more and that would have drained all our available cash.",
"How much will the packages come to?",
"Say £100 averaging one with the other.",
"This sample looks very nice for an imitation.",
"It being in your line, I thought I ought to give you the first chance in case it would tempt you.",
"To begin with you would have to engage the cloth to us.",
"I have no objection provided you guarantee a certain turnover.",
"He was appointed sole agent for the whole of Mexico through the recommendation of his brother-in-law, and his agreement with the firm is for 3 years certain.",
"That will bring him £500 a year if it brings him a penny.",
"Being such an important concern they do not pay their staff very handsomely.",
"They are too remiss with their payments to be such important people.",
"I very nearly pledged myself to grant him the exclusive sale of my article.",
"These are his instructions for the disposal of his goods",
"However clear they may be, we must have his cable confirmed by a letter.",
"Therefore we cannot entertain your offer for the present.",
"It cannot be helped, otherwise we would do everything for you.",
"They await the result of the inquiry.",
"We forward you the papers relating to the Arbitrator's award.",
"He paid for the Buntings 5d. a yard.",
"In consequence of your having outstepped our instructions, we must decline all responsibility with respect to delivery.",
"We have put boards inside the pieces according to our usual custom;",
"we did not know you wanted them rolled.",
"Our new offices will be next to the Oil and Paint Stores, and opposite the General Post Office.",
"The planks used under the bales for dunnage were sold almost for nothing, in spite of our request to hold them at our disposal.",
"The steamer can carry 4,000 bales a little more or less if she fills her holds and takes cargo between decks.",
"She will take that quite easily and a few hundred bales more in her bunkers.",
"As a mark of our appreciation we authorize a gratuity to the Captain of £5.",
"The salvage has been sold partly by auction and partly by private treaty.",
"To all appearances the corded and frilled wrappers are superior to the scalloped.",
"Whether he puts through my order for leather belts and silk sashes or not, I do not much mind, but if he should oblige me, I would do him a good turn if the opportunity presents itself.",
"If the webbing and down quilts are good, I shall not begrudge the advance in price.",
"Can it be true that the gate or octroi duty is going to be abolished in Spain?",
"Well the Government has presented a bill to that effect and I hope we shall soon see the octroi offices abolished.",
"The broker was warned that the quality was only fair average.",
"Beetroot has been largely planted in the province of Granada and is now in great request for the sugar industry.",
"We strove hard to introduce the new brand and we have gained our point at last.",
"The cloth was folded on the wrong side and we anticipate some difficulty on that score.",
"The consignees claim shortage.",
"They allege that the casks were leaking and that there was consequently a loss of thirty gallons.");

function spanishLine()
{
	global $spanishlines;
	return $spanishlines[array_rand($spanishlines)];
}

?>