<?

$esperantoLines = array(
"the sun shines",
"a boy runs",
"the men are walking",
"the sun and the moon are shining",
"the bird is beautiful",
"the boy seems good",
"the men are strong",
"violets are flowers",
"the dove is a bird",
"roses are beautiful",
"the man has a chair",
"the boy finds flowers",
"the boy finds a beautiful flower",
"the man has beautiful flowers",
"the man has a large chair",
"the man both walks and runs",
"the horse is both large and strong",
"the boy has both roses and violets",
"violets are not red",
"the men are not sitting on chairs",
"the dove is singing, not flying",
"the boy wishes to run",
"birds like to sing",
"the boy wishes to have a horse",
"Is the boy good?",
"Have they flowers?",
"Do the doves sing?",
"they neither walk nor run",
"the man has neither a house nor a garden",
"neither the rose nor the violet is green",
"we are good and happy",
"roses are flowers, they are not fruits",
"Gertrude, you are good",
"I am",
"you are",
"he is",
"we are",
"you are",
"they are",
"I see",
"you see",
"he sees.",
"we see",
"you see",
"they see",
"I was",
"you were",
"he was",
"we were",
"you were",
"they were",
"I saw",
"you saw",
"he saw",
"we saw",
"you saw",
"they saw",
"the tree is in the garden",
"good apples are on it",
"I gave cherries to him",
"the boy is near me",
"under the tree stood a horse",
"the man saw you and me",
"he saw them and us",
"I saw neither him nor her",
"I see myself",
"I said to myself",
"we have a carpet under us",
"we amused ourselves",
"thou findest a house near thee",
"you say to yourself",
"he amuses himself",
"Arthur saw a bird near him",
"she finds a flower near her",
"Mary found herself on a blue carpet",
"the carpet has various colors in it",
"the bird hides itself under the leaves",
"they amuse themselves",
"the men have chairs near them",
"the women find flowers near them",
"the trees have cherries on them",
"under them the children found a soft carpet",
"I amuse myself",
"you amuse yourself",
"he amuses himself",
"we amuse ourselves",
"you amuse yourselves",
"they turned themselves",
"I gladden myself",
"he stops himself",
"the boy praises him",
"she gives apples to her",
"the bird saw it",
"the boys hid them",
"the birds flew to them",
"my house and my gardens are large",
"John is sitting in your chair",
"I have my books on my table",
"John lost his books",
"Mary is in her room",
"the large book is mine",
"yours is large, mine are beautiful",
"they have theirs, but not his",
"he went to the garden",
"the man will go to Boston",
"he was in the garden and ran into the house.",
"it is not on the table, it fell upon the floor.",
"they fell under the table as far as the floor",
"I went through the house into my room.",
"I wash my face.",
"he shakes his head.",
"Father is tall.",
"I gave it to Father.",
"Boston is large.",
"my friend John is tall.",
"the walls of the house.",
"the colors of the flowers.",
"the book of the boy.",
"a branch of the tree.",
"the garden of the men.",
"it rains, it is raining.",
"there are flowers on the table.",
"it was John, not Alfred, in the garden.",
"there is a house in the field.",
"I say that he is good.",
"John says that you came yesterday.",
"she thinks that there is money in the bag.",
"they say that he is rich.",
"one sees that they are friends.",
"I think that people like him.",
"I was told that there is sand in the desert.",
"it is thought that she is happy.",
"Were we seen in the garden?",
"people like agreeable children.",
"I shall be.",
"you will be.",
"he will be.",
"we shall be.",
"you will be.",
"they will be.",
"I shall see.",
"you will see.",
"he will see.",
"we shall see.",
"you will see.",
"they will see.",
"that is yours, and I wish that one.",
"those will be angry with you.",
"that wind will be warm.",
"I see that weathercock.",
"those children are young.",
"I said that he was good.",
"he wonders whether I hear.",
"he wondered whether I heard.",
"will he come?",
"I wonder whether he came.",
"people ask whether he is rich.",
"Pauline, Josephine, Ernestine, Geraldine",
"that one nearby",
"that one here",
"this is mine",
"I saw this one",
"Do you wish these?",
"this girl is my sister",
"I saw these hats",
"these friends will take a walk",
"this person's sons are young",
"I like that one's color, but prefer this flower",
"one sews by means of a needle",
"the birds fly by wings",
"he amuses himself with those pictures",
"by means of",
"that kind of, that sort of",
"I like that sort of meat.",
"such neighbors are pleasant.",
"I wish to hear such birds.",
"at least",
"I almost wished",
"He will come, will he not?",
"The weather is beautiful, is it not?",
"there, in that",
"the books lie here",
"I found you there and him here.",
"he will go there",
"I came here",
"we were there and came here",
"the man came with his friend",
"I shall go walking with you",
"the boy with that man is his brother",
"with, strive with, contend with, withstand",
"I am able to talk, I can talk.",
"I was able to talk, I could talk.",
"I shall be able to talk",
"most beautiful.",
"he is the youngest of those.",
"you are the happiest of us.",
"he took it with the greatest care",
"I heard him with interest and pleasure",
"she is a woman with good taste",
"I have a horse with a strong body",
"he sang",
"with a sweet voice",
"you pushed me with a strong hand",
"talk, to speak",
"I said it to you",
"I talked to you about it",
"therefore the servant went away",
"for that reason I congratulated him",
"most wisely",
"he is less courageous",
"those were least sharp",
"the wind blew less strongly",
"he wrote least carefully",
"I fear them less",
"you will need help least",
"I love them more than she",
"you helped the man less than the boy",
"I came early, for I wished to see you",
"the better he is, the happier he will be.",
"the oftener I look, the more I wish to look.",
"the more beautifully the moon shines, the more one likes the night.",
"the less it rains, the more the flowers wither.",
"the less you help, the less I shall praise you.",
"because you helped, I shall praise you the more.",
"he is sitting between you and me.",
"he is sitting among his friends.",
"the month of May is between April and June.",
"the flowers wilt because of the dry weather.",
"I wrote the letter for you.",
"on account of those clouds I fear that it will rain.",
"people like cherries because of the sweet taste.",
"the cat ran out from under the table",
"he will come out of there",
"from now he will be careful",
"he stood on the right of the road",
"this manner, in such a way, thus, so",
"I wrote it thus.",
"the weather is so beautiful.",
"thus briefly he spoke.",
"I found such a beautiful flower.",
"he took that much.",
"I shall depart about June.",
"from that hour I was your friend.",
"he did not speak to me since from that week.",
"it did not snow in the entire month.",
"I slept until a late hour.",
"until now he did not see you.",
"between March and June I shall go there.",
"at a late hour he went away.",
"I shall go there on Sunday.",
"at that hour he called me.",
"she did not stay there after July.",
"before Sunday I shall go away.",
"I saw him before that hour.",
"he will write it before New Year.",
"many years ago I found it.",
"I broke it a long time ago.",
"you read that book very long ago.",
"he came recently.",
"too, too much.",
"he stayed there the whole week",
"for a long time",
"for a day and a night",
"he escaped",
"I wish to go to Boston on Monday",
"I wish to go to Boston Monday",
"Monday I wish to go to Boston",
"he came a long time before that hour",
"year after year they stayed there",
"this morning",
"this evening",
"last evening",
"last night",
"Sunday morning",
"Monday evening",
"he will go to their house Sunday",
"he goes to their house Sundays",
"he worked a day and a night",
"I have a book for you",
"I have not the time for so long a walk",
"he came while you were away",
"while the seasons quarreled, they forgot about the world",
"I shall depart before you come",
"before you reproached him, he did not weep",
"you hinder instead of helping me",
"we came to help you",
"I am ready to go Wednesday",
"he will have too much to do",
"I shall work before resting",
"before going away, he thanked me",
"God made the world before giving it to the seasons",
"there is a box of cherries there",
"I found a large bag of money",
"he has a plate of meat",
"after hours of joy there often come hours of sorrow",
"a plate of the ripe apples",
"so little time",
"he drank little water",
"there is much sand in the desert",
"in a city one has much noise",
"we heard many noises",
"there one has much pleasure",
"people have many pleasures there",
"that many, that quantity, so much",
"I bought that much meat",
"that many of the books I read",
"Diogenes was such a wise Greek man that Alexander praised him",
"I had so much pleasure that I laughed very much",
"Who calls you?",
"Whom do you call?",
"Which of you called us?",
"Whom did he help?",
"What day will you come?",
"What vegetables do you prefer?",
"I wonder which book you bought?",
"In whose house do you reside?",
"verbal adjective",
"is doing",
"the crying child wishes to sleep.",
"I see the falling leaves.",
"Who is the woman buying eggs?",
"I talked to the men going toward the village.",
"I am asking",
"the man is buying",
"I am seeing",
"you are seeing",
"he is seeing",
"we are seeing",
"you are seeing",
"other, another.",
"what sort?",
"What kind of bread do you prefer?",
"I wonder what sort of a person he is",
"What sort of weather is it?",
"What a pleasure!",
"I was seeing",
"you were seeing",
"he was seeing",
"we were seeing",
"you were seeing",
"they were seeing",
"I shall be seeing",
"you will be seeing",
"he will be seeing",
"we shall be seeing",
"you will be seeing",
"they will be seeing",
"Good morning!",
"Good night!",
"many greetings to your father!",
"Do you know that person?",
"I know that he is our neighbor.",
"I am well acquainted with Boston.",
"he will wonder where his grandson is",
"I do not know where he ran",
"who is the man having greeted us?",
"one forgets the departed persons",
"previously he studied geometry",
"afterwards he studied German",
"he walked in front, not behind",
"meanwhile the men stood roundabout",
"Did he ride north or south?",
"we ran forward, not back",
"the bouquet fell out and underneath",
"he was walking home",
"he went home",
"we shall advance",
"they wonder when he is coming.",
"I have seen",
"you have seen",
"he has seen",
"we have seen",
"you have seen",
"they have seen",
"he lives at my grandfather's",
"they are at the school",
"he will stay with friends",
"he will visit at our house tomorrow",
"I have not much time",
"he came many times, and the last time he remained a long time",
"several times it thundered loudly",
"many times we closed our eyes on account of the lightning",
"I will ask why he noticed it.",
"Is it easy to look at the ceiling?",
"it is well to help oneself",
"I have been here since Monday",
"since March I have been studying that language",
"they have been friends from that day",
"we have been living here since some months ago",
"he lives near by",
"he lived a long time",
"how, in what way?",
"to what degree?",
"How amiable she is!",
"I wonder how the battle happened.",
"How long did he think about it?",
"I had seen.",
"you had seen.",
"he had seen.",
"we had seen.",
"you had seen.",
"some walked, others ran.",
"I took some and left the others.",
"six of the boys came.",
"eight of those books are mine.",
"I am searching for a book, but not the one on the table",
"he walked eleven miles",
"the park is three miles wide and four miles long",
"he is seven years old",
"I was ten years old",
"How much sugar and how many strawberries did you buy?",
"we wonder how much money he will have",
"How much of the lesson did you learn?",
"it is warm in the house.",
"it will be cold tomorrow.",
"it is well that he came.",
"it is amusing that we forgot him.",
"that you came was very wise.",
"two hundred",
"five hundred",
"seven hundred",
"three thousand",
"four thousand",
"six thousand",
"one hundred and thirty-five",
"four hundred and ninety-seven",
"six hundred and two",
"one thousand and eighty",
"the youths who came are amiable.",
"the persons he will see are friends of mine.",
"I calculated the grade he will receive.",
"he is the man whose book you found.",
"I know the children whose father is a friend of yours.",
"I shall have seen.",
"you will have seen.",
"he will have seen.",
"we shall have seen.",
"you will have seen.",
"hundred and eighty-fifth.",
"one thousand eight hundred and fourth.",
"I have such a book as I wish.",
"such friends as you have are amiable.",
"he desires that kind of hat which costs six dollars.",
"I have the same desire as you.",
"I shall go there where you are.",
"I was there where you will go.",
"I shall go to that place to which you went.",
"I found him in the city where he lives.",
"the man going to depart called his servant.",
"the woman about to greet you is very affable.",
"the coming month is March.",
"the coming week I shall depart.",
"I am about to see.",
"I was about to see.",
"I am still sitting here.",
"still he has not come more crafty.",
"I suspected him at the time when he came",
"he defended himself then, when he was attacked",
"I shall still sit there until when you come",
"after he shouted so loudly, he began to cry",
"I defended myself in that way in which he defended himself",
"you are not so cruel as he",
"they beat him in the same way as you",
"they beat him the same as you",
"as I told him, I am happy",
"he spoke as softly as before",
"she is as good as she is fair",
"a dozen.",
"a score.",
"a ten, half a score.",
"a hundred.",
"a thousand.",
"a unit.",
"a four, a quartette.",
"a three, a trio.",
"a dozen eggs.",
"which one of the eggs?",
"the freshest of the eggs.",
"firstly, at first.",
"secondly, in the second place.",
"fifthly, in the fifth place.",
"comrade, companion.",
"farewell, goodbye.",
"just, at the moment.",
"we just came.",
"I have the same opinion as you just gave.",
"I saw him just when he was about to",
"worth reading",
"deserving of love",
"it is the best possible.",
"we shall be as wise as possible.",
"he used the least possible.",
"I wrote as legibly as possible.",
"Goodbye.",
"I do not know that young lady.",
"Where do you wish to go?",
"Mr. A&mdash;&mdash; is very amiable.",
"Doctor, Professor, Madam",
"Mein Herr, gn&auml;dige Frau, gn&auml;diges",
"the cup contained as much coffee as I could drink",
"I shall have as much time as I shall need",
"he sent as much as you wished",
"the boy being praised is happy",
"I shall look for the desired book",
"the clothes being made for you are beautiful",
"the half of six is three",
"he was only half attentive",
"the third part of six is two",
"Have you yet found it?",
"No, I have not yet found it",
"it is not snowing now",
"being undergone",
"I am seen",
"you are seen",
"he is seen",
"we are seen",
"you are seen",
"they are seen",
"the spear is carried by me",
"the books are already being printed by him",
"the roads are being covered by snow",
"she is being praised by the gentleman",
"the tree is far from the house",
"it is near to the garden",
"I take the book away from the boy",
"I take the book of the boy",
"the matter depends upon you",
"I bade farewell to him by a farewell salute",
"we made an immediate exchange",
"Did he write an affirmative or a negative answer?",
"instead of denying, he answered affirmatively",
"tomorrow's celebration will be more pleasant than that of yesterday",
"I have an old hat",
"he is an old friend of mine",
"the Chinese were learned even in the olden time",
"the ancient learned men already knew a great deal",
"the old gentleman with the old clothes is an antiquary",
"all men work all the whole day",
"I saw every face, but I did not see all the face of each man",
"every one who studies will learn",
"I saw each of them, and talked to every boy",
"I thank you all",
"we are all represented",
"all of the sailors arrived",
"he knows everyone's name",
"everybody's opinion was different",
"he walks at the rate of four miles daily",
"I bought coffee at a low price",
"I bought meat at a quarter of a dollar for pound",
"there are all sorts of persons in the world.",
"I was seen.",
"you were seen.",
"he was seen.",
"we were seen.",
"you were seen.",
"it was raining a minute ago.",
"it had snowed a great deal.",
"it is our duty to help one another.",
"they are talking to each other.",
"the men used each other's guns.",
"they fell upon each other.",
"that which contains, bears, or is a receptacle for",
"such men are found everywhere",
"he went everywhere where I had been",
"I shall be seen",
"you will be seen",
"he will be seen",
"we shall be seen",
"you will be seen",
"they will be seen",
"What hour is it?",
"At what time will you come?",
"it is two o'clock",
"it is five minutes past three",
"we went at half past six",
"it is eight forty-five",
"I am always ready to help you",
"for every reason",
"for every reason he is happy today",
"mine is for all reasons the best",
"the price paid by you was too great",
"the punished child is crying",
"I shall buy well-made gloves",
"you have been seen",
"we have been seen",
"he acted in accordance with his own opinion",
"I shall do it according to a good method",
"In what manner did he act?",
"I walked down the street",
"he went along the river by that road",
"black clouds raced along the sky",
"in every way, in every manner",
"he will be helped in every way",
"you had been seen",
"he had been seen",
"we had been seen",
"you had been seen",
"I shall have been seen",
"you will have been seen",
"he will have been seen",
"we shall have been seen",
"you will have been seen",
"the table is made out of wood",
"the table is wooden",
"the children built a house of snow.",
"the table about to be moved away is heavy.",
"I was about to be seen.",
"patience is praiseworthy.",
"life on earth is merely a part of the life eternal.",
"man is stronger than woman.",
"patience is bitter, but its fruit is sweet",
"hope is the poor man's bread",
"I am talking about a certain one whom you know",
"I visited some of your friends",
"I have several apples, but certain ones are not good",
"some bridges are well made",
"I touched someone's arm",
"Is anybody's overcoat lying on the table?",
"someone's playthings are broken",
"I saw some kind of bones on the ground.",
"there is some sort of human being in that tent.",
"anywhere, somewhere, in a certain place.",
"somewhere in that forest is a lion.",
"somewhere behind the soldiers you will find a heap of bullets.",
"the swallow flew somewhere.",
"I am going somewhere, but I do not yet know where.",
"I left the boy calm.",
"I found the hole already made.",
"I left them well punished.",
"God made the happy world.",
"I left the calm boy.",
"I found the already made hole.",
"I left those who had been well punished.",
"she named her daughter Mary.",
"they elected that one representative.",
"I shall see him a conqueror.",
"I found him a thief.",
"she named her daughter Mary.",
"they elected that representative.",
"a king once dwelt there.",
"Did you ever go to law against him?",
"Do you think that for any reason he is suffering unjustly?",
"he made the world glad.",
"he gladdened the world.",
"You do astonish me!",
"he is indeed an upright judge",
"for some reason",
"he does not care about the book",
"he does not care for the book",
"I do not care whether he is coming or not",
"somehow, in any way, in some",
"we shall announce the decision in some way.",
"she will heat some water.",
"that way is a little dangerous",
"the string is somewhat too long.",
"continuous, habitual or",
"two years ago she used to sing very sweetly.",
"a movement",
"a shot",
"a thought",
"the taking of walks gives pleasure.",
"I myself shall accompany you.",
"the guide himself lost the way.",
"I shall give credence to the man himself.",
"the men themselves defended themselves.",
"it hangs on the very wall.",
"she came herself to see you.",
"no one of you understands me",
"I found nobody ready to go",
"he had no honest servant",
"everybody's affair is nobody's affair",
"the man who is talking",
"the boy who will be sent",
"while you waited, he went away",
"because I was happy, I laughed",
"rejoicing, I laughed",
"being about to depart, we bade him farewell",
"after bathing the baby, she put it to sleep",
"being sly, they debased the gold",
"thus helped by you, I shall succeed",
"having been silenced by him, they did not complain",
"being about to be punished, he gave a cry",
"without speaking, he left",
"The youth being young, everyone watched him",
"work being finished, he went away",
"au revoir",
"no one",
"I have no sort of mirror.",
"no sort of problem is too difficult for him.",
"nowhere is there a better machine.",
"an injustice.",
"a marvel.",
"behold, here, there",
"There is the problem!",
"Behold the philosopher!",
"now she plays, now she studies.",
"I did it as follows.",
"I acted in the following way.",
"he is jealous for no reason.",
"in no way",
"there is no wine in his glass.",
"the door closes.",
"the vehicle moves.",
"the branch breaks.",
"a group of persons gathered.",
"the door is closed.",
"the vehicle is being moved.",
"the branch is broken.",
"hardly, scarcely.",
"for no reason",
"in no way",
"what, anything",
"something, nothing",
"this",
"all this.",
"anything, something.",
"What is this, which you say?",
"she saw that which just occurred.",
"everything here, which you see, was done by them.",
"they both came to the temple",
"both made offerings to the gods",
"if he sees that, he weeps",
"if he saw that, he wept",
"he will weep, if he sees that",
"if he came yesterday, he will go away tomorrow",
"if he has seen that, he now is weeping",
"if that is going to be seen, he is going to be punished",
"I should see.",
"you would see.",
"he would see.",
"we should see.",
"you would see.",
"I should be seeing",
"I should have seen",
"I should be seen",
"I should have been seen",
"I should be seeing",
"I should have seen",
"I should be seen",
"I should have been seen",
"I should be about to be seen",
"Less vivid",
"if he should see that, he would weep",
"I would gladly help you, if I could",
"if you should put them on the donkey's back, it would carry them",
"the mischievous youth would torment the monk, if he should return",
"if he should be caught, he would be punished",
"I would gladly help you.",
"Would you kindly tell me?",
"Who would wish to inhale such air?",
"it would be well to keep your own.",
"both will talk further",
"he no longer seemed",
"having become rarefied",
"if you had turned, you would have seen that",
"if the moisture had not condensed, it would not have rained",
"if he had been caught, he would have been punished",
"if he were sitting there, I should see him",
"objects in the air have to fall",
"we had to act according to the laws",
"you must go",
"she does not wish to have to do that",
"they compelled me to go",
"you should go",
"one ought to think before speaking",
"he ought to have come",
"he defined the word without an error",
"the river flows without ceasing",
"that is not only useless but even harmful",
"he is no longer penniless",
"without reading that, I should not understand",
"without reading",
"that, I should not understand",
"he drinks the poison as though it were wine",
"the condemned man walked as if with difficulty",
"he confessed like a culprit",
"he burned his hand",
"they cut his beard",
"she is preparing us a good meal",
"Will you do me a service?",
"I wash my hands",
"they threw themselves at the feet of C&aelig;sar",
"the moon is hidden from us by the clouds",
"it stole the life from me",
"let us see!",
"you see!",
"let them see!",
"first person",
"Let me think about that!",
"I must not forget that!",
"Let us exile him!",
"Let us not sit down there!",
"Let us be dressed in gray!",
"Be calm!",
"Be ready to accompany me!",
"Talk as though you understood!",
"Do not shut that door!",
"Do not be seen there!",
"Let him be careful!",
"Do not let her do that!",
"Let everything be forgiven!",
"People are to let me alone!",
"Let them never return!",
"Stop that noise, I beg!",
"Please do that!",
"May they be happy!",
"God bless you!",
"Think before acting!",
"Well, talk, but I shall not listen!",
"Am I to do that or not?",
"Shall we distribute the books?",
"Shall he be condemned?",
"his majesty",
"his honor the judge.",
"her majesty",
"his honor the mayor.",
"you are welcome",
"he says that you are to go",
"she wrote him to come",
"I forbid you to remain",
"I beg that you do not leave me.",
"I implore you to be calm.",
"he desires that they be enslaved",
"I advised him to go",
"I consented that he remain.",
"he inquires whether they are to go away",
"they asked whether his honor was to enter",
"we intend that you shall be helped",
"his proposal is, that we receive the half",
"his last order was that you come",
"it will be well for you not to mention him any more",
"it is desirable that we have a good emperor",
"it was necessary for everyone to rise",
"he will be pleased to have you go",
"In the name of Heaven!",
"On my honor I will accomplish that!",
"it is two miles long",
"they came in great numbers",
"he is held by the policemen, by the arm, with a strong rope",
"I do it in order that he may help you",
"I cried out in order that you should hear",
"he will come that we may be happy",
"I study that I may learn",
"let them stay for us to punish them",
"his entrance into the city was sudden",
"going thither will be a pleasure",
"he lives an agreeable life",
"she danced a beautiful dance",
"they wept bitter tears",
"the man passed the house",
"there preceded him two slaves",
"let us go up the stairs",
"I attended the entertainment",
"she mourned the dead bird",
"I shall consider the matter",
"we shall talk it over",
"I pardon him",
"I helped him",
"it pleases me",
"he obeyed us",
"she ridiculed my fear",
"in regard to that",
"with the exception of that",
"concerning the affair",
"in comparison with the other",
"in conformity to the law",
"it is not allowed to enter there.",
"perhaps he will obey you.",
"probably he will succeed.",
"you are probably right.",
"they might save him.",
"they surely did not beat him.",
"that can not be!",
"that is impossible!",
"a cur",
"Oh! Ho!",
"Woe!",
"Alas!",
"Look out!",
"Hark!",
"Welcome!",
"Forward!",
"Good!",
"Away!",
"Indeed!",
"There!",
"Behold!",
"ugly bird",
"a sorry nag",
"many villages are situated there",
"Egypt is in the northeastern part of Africa",
"he found himself alone in the desert",
"the city lay between two lakes",
"I wish to see him.",
"he will be able to do that.",
"you ought to eat something.",
"Did you believe it?",
"if he should see me, he would save me.",
"make him",
"pray thee",
"He boils the water",
"He burned the paper",
"He stops the noise",
"He continues the noise",
"He thaws it with fire",
"The man drowned her",
"He will explode it",
"He halted the soldiers",
"He lighted the lamp",
"Thus he passed the day",
"He hung it on a branch",
"They sounded the salute",
"They rang the bell",
"the work is now coming to an end",
"the sword bent",
"the leaves unroll",
"every custom will change",
"the winter is already beginning",
"I shall awake at six o'clock",
"the indicator trembled",
"a vast plain extended before him",
"thanks to you, I succeeded",
"and so forth",
"here above",
"William Tell had a strong flexible bow.",
"He could shoot with a bow excellently, therefore he was a well-known archer.",
"He put six or eight arrows into his quiver, and went with his sons to the village.",
"Possibly he saw the hat upon the pole, but he did not kneel before it.",
"It was being noticed already in the village that Tell hated the tyrant very much.",
"I did not know about this new duty, and could not imagine why the hat was on the pole there.",
"The tyrant replied with angry words, for he hated the proud Swiss whom every one else loved.",
"It is said that you are a praiseworthy archer.",
"Therefore I was wondering whether you could shoot an apple from your son's head.",
"Now we shall see whether you can shoot off the apple, or whether you will touch the child's head.",
"Amid the pleadings of all, Tell successfully shot off the apple.",
"A similar second arrow was ready in his hand.",
"The tyrant saw the remaining arrow, and prepared to punish Tell by death.",
"But he escaped, and the Swiss congratulated each other heartily.",
"After some time they followed him, at the rate of six miles an hour.",
"Because of the request of my friend whose brother died recently, I went last week to visit him.",
"The remaining persons of his family were not at home.",
"I telephoned to find out at what time the train would depart.",
"I was told that it would leave at four twenty-seven.",
"I put enough money into my purse, and carried along a valise into which I had put some clothes.",
"When I entered the station, I hurried past the other people to the wicket, and asked for a ticket to B----.",
"The ticket seller said \"Two dollars and forty cents.\"I could not imagine why it was necessary to pay so much, but I at once pushed that much money through the window, and received the ticket.",
"Persons who go through that gate before the train arrives will be severely punished.",
"So all of us stood near the double gate.",
"The trains are much like each other, and it is better to act as the guards request, and not express impatience.",
"She was pale and tearful when I saw her, and looked in every direction in a most impatient manner.",
"There was an expression of fear upon her face and she went as quickly as possible to a nearby policeman, and said a few words to him.",
"It is now only ten minutes past two.",
"My train will leave at half-past two, so I have time to help.",
"During the next twenty minutes I shall not be busy.",
"Do you desire my help?",
"Yes, you are very kind.",
"The son of that lady has been lost.",
"According to her description, he is a yellow-haired blue-eyed five-year-old, and apparently too restless.",
"I shall find him as soon as possible, nevertheless I shall gladly accept your help.",
"The child is dressed in white and wears a red hat.",
"As I am not at all lazy, I went along the stationary tables as far as the end of the station, and there I saw that sort of child, looking at the magazines and newspapers.",
"My pale delicate little sister is always happy when she has a new toy.",
"Her dolls were made out of cloth when she was a very little girl, because otherwise she could too easily break them.",
"But yesterday my grandmother made a present of a doll to her, and since that moment she has been as happy as possible.",
"I have not seen tears in her eyes, or heard a cross word.",
"This new doll is made out of cloth, and its dress consists of very pretty material.",
"My sister decided that she likes it better than her other playthings, and I think that those poor other dolls will soon have been forgotten.",
"The doll seems in every way more interesting than the little animals made out of cloth or wood, which are on the table with her dolls.",
"She possesses a little dog and a little cat, and a little lion, and until yesterday she had a wooden pony.",
"The pony is already broken, and has been given away to a poor child, the daughter of our laundress.",
"My sister possesses a small train of cars which she can move everywhere, and she is very fond of this toy.",
"There are small sacks of sand in the cars, and usually she is happy when she is pouring the sand out of one of these into another, or putting all of the sand into a box, by means of a small spoon.",
"For every reason I am doubly glad today that she is busied in this manner.",
"I wish to take a walk along that pleasant path toward the hill, instead of waiting for my little sister.",
"I must buy the meat to roast for supper, before I come home from my walk.",
"It is difficult in every way to select a present for a child who already possesses enough toys.",
"In a toy-shop yesterday I examined the dolls made out of woolen cloth and other material, and also looked at the various little animals.",
"There were ponies, little dogs and little lions and camels.",
"There were also little sets of furniture, which consisted of tables, sofas and chairs.",
"On the tables were small plates containing vegetables, fruits and roast meat, entirely made out of colored paper.",
"There were also little cups and tumblers of thin glass, into which one could pour water or milk.",
"As one dollar was all of the money which I had in my purse, I left the shop.",
"I walked along a stony picturesque path toward the lake, swinging my overcoat on my arm, while I thought over the difficulty, and tried to decide what sort of present to choose.",
"The steamboat to B---- was just leaving, so I went across the footbridge on to the pretty little ship, while its bells were ringing, and rode an hour in the open air.",
"The shore which we passed is very picturesque, but its beauty is about to be spoiled, for a large furniture factory is going to be built between that steep hill and the lake.",
"Its proximity to the water is necessary, for water-power will be used.",
"There is a pretty story about a swallow which built its nest for its young on the king's tent.",
"The soldiers who were walking along the steep path past the tent glanced at it, and caught sight of the bird.",
"Some of them burst into a laugh, and gestured toward the bird, to point it out to their comrades.",
"The good-humored king put on a thick woolen overcoat, and came out of his tent, to inquire why his soldiers were conversing so noisily there.",
"The tent was an expensive one, and contained handsome furniture, as well as a bell which always rang as soon as one touched it.",
"Surely such a courageous bird is a worthy guest for a king.",
"The warriors cared for the swallow as much as possible during the course of the war.",
"When the victors departed, they left that tent there.",
"Finally the wind upset it, and it fell to the ground.",
"The young swallows already could fly, by that time.",
"The battleground is covered with bullets, piles of human bones, and similar melancholy signs of war.",
"War is wicked and shameful.",
"Why do kings and princes wish to make war upon each other?",
"When their sons have gone away to war, the mothers of the soldiers are very uneasy.",
"Perhaps those sons will be prisoners of war.",
"The horse caught sight of the twigs with which a passer-by had mended the bellrope.",
"Because it wished to eat the green leaves, it seized the rope, and the bell immediately rang loudly and clearly.",
"The horse almost upset the poles which supported the roof over the bell of justice.",
"Any one had the right to use this bell, to announce any kind of injustice.",
"The judge burst into a laugh as soon as he saw that sort of plaintiff standing there.",
"More often he saw human beings as plaintiffs, instead of animals.",
"When a laborer showed himself unkind to his wife and children, they could announce their sufferings by means of the convenient bell.",
"People called it the bell of justice.",
"According to everyone's opinion, it is the duty of a just judge to punish evildoers and unjust persons.",
"He decided that he would institute proceedings against the owner of the horse.",
"The man had driven away the horse, and it was grazing along the road.",
"It was some one's duty to give some sort of home to his horse.",
"I will find out whose horse that poor beast is, and will put a mark opposite the name of that man.",
"I will not leave him alone, but will show myself very severe.",
"Somewhere in that same town, there lived another youth, who also had an amiable sister.",
"One convenient day, she accompanied him for a ride in a vehicle drawn by a fast horse.",
"When they reached the bridge, this girl also was frightened for some reason, the same as the girl in the other story.",
"I do not intend to complain, but the carriage will certainly be too heavy while we are in it.",
"I am afraid that that bridge is dangerous, so I will jump out and walk.",
"I will also pick some sort of flowers, among the flowers growing there, near where someone's horses are grazing.",
"I will not delay you long.",
"That bridge is entirely safe but instead of explaining to you about it, I will lead the horse across the bridge, while you walk across, for I am not indifferent to your fear.",
"It was not necessary to cross on foot.",
"No, but you showed yourself a courteous brother, and were very patient.",
"Several centuries ago, a rich and powerful king, named Hiero, lived in Sicily.",
"Sometimes he was suspicious about the crown-makers who wrought crowns for him, out of the gold which he himself gave them.",
"He wondered whether these men were honest.",
"He suspected that perhaps they did not use all of the gold which was given them, but kept some of it for themselves.",
"He could not of himself discover whether they were debasing the gold in his crowns, so he summoned a wise man from Greece.",
"To this well-informed man, whose name was Archimedes, he made clear his fears.",
"Archimedes assured the king that he would find out somehow about the matter.",
"He meditated several hours every day, and tried to discover a satisfactory method, but for some reason he did not succeed.",
"One day, however, when he was bathing, he noticed that there seemed to be a little more water in the bathtub when he himself was in it, than before.",
"The rising of the water gave him an idea.",
"He threw the crowns one after another into the water, and noticed how much water each displaced.",
"In this manner he understood how much each had been alloyed by the local crown-makers, whom Hiero soon threw into prison",
"The Greek philosopher Archimedes was not only famous long ago, among his contemporaries, but even today his name is well known everywhere.",
"No one's knowledge about the problems of geometry and physics was greater.",
"No one understood better the properties of the cylinder and the screw.",
"Having studied these properties a long time, and having meditated a great deal about them, he understood them a little better than any one else.",
"The story about the debasing of the gold crowns has already been told.",
"There is another anecdote, namely, that he remarked to Hiero, king of Syracuse, that with a lever he would move the world, as soon as he had a place on which he himself could stand.",
"Having discovered how the sunlight is reflected by a mirror, and heats the wood upon which it shines, he invented a machine made out of mirrors.",
"Aided by this machine, the Syracusans were able to set on fire the wooden ships of the enemy.",
"The enemy, however, were not repulsed from the island, but at once rebuilt and repaired their ships, and sent them back to attack the city again.",
"Finally, having captured the city, they destroyed it, and killed a large number of the inhabitants, also Archimedes himself.",
"Syracuse was the largest city on the island of Sicily.",
"The famous philosopher and physicist Archimedes lost his life when that city was destroyed and entirely burned.",
"At least, no sort of trace of him seems to have been found after that occurrence.",
"Never, perhaps, was there a more learned man in Syracuse.",
"Greece was also famous for its skilled painters, and there are many anecdotes about them.",
"A painter who failed in a certain competition believed that none of the judges had been just to him.",
"Behold this iniquity!",
"Nowhere can I find a human being who is not jealous.",
"Since the paintings are chiefly of horses, do they not require horses for judges?",
"His proposal was accepted, and some horses were led in.",
"Without noticing the other paintings, the horses walked at once to the picture of the unsuccessful artist, and showed immediate recognition of the horses painted there.",
"This act showed which competitor was the most skilful.",
"Animals decide not by rules, but by feelings.",
"One painted a cluster of grapes, so excellently that the birds flew to it.",
"The other deceived his rival himself, by a painting of a curtain.",
"The most famous artists, however, often show their skill by painting pictures of the sunset, chiefly, I think, because of the brilliant colors.",
"In fact, I doubt whether there is a more beautiful sight than the sunset.",
"It is made by the bright rays of the sun, which shine back through the atmosphere, long after the sun itself has passed below the horizon.",
"The more moisture there is in the air, the more brilliant the colors are, and the more beautiful the entire landscape becomes.",
"In tropical lands, night falls very suddenly, and there is almost no sort of twilight.",
"In fact, a twilight scarcely occurs there.",
"In the lands far north, on the contrary, the twilight lasts six months, and the remainder of the year is the day.",
"To dwell in such a land is surely a remarkable experience.",
"It can in no way be understood by persons who have never lived there.",
"Such things increase my desire to visit those northern lands.",
"One often hears the remark \"I will cut the Gordian knot.\"There is an interesting story about this.",
"A wagon whose yoke was tied to the pole by a large knot had been put in the middle of the temple.",
"It was a thank-offering to the sacred gods, by whose help Gordius had in olden time become king.",
"It was said that whoever would be able to untie that rope would no doubt become ruler over the whole of Asia.",
"Alexander the Great, having begun a campaign against Asia, approached the city where this temple was.",
"Having heard the story, he at once had a guide come, and went thither, guided by him.",
"He desired to do everything which was useful to the conquering of Asia.",
"Having examined the knot carefully, he bent over and tried for a few minutes to untie it.",
"Then he chose another method.",
"He seized his sword, and suddenly cut through the whole knot.",
"Having done this, he put the sword back into the scabbard.",
"This he did, instead of continuing his efforts to untie the knot.",
"In fact, having no patience, he had become tired.",
"Perhaps the conquering of Asia did not in any way become possible on account of this, but at least the story is interesting, whatever actually happened.",
"Nothing is impossible, whenever one tries enough.",
"In a tropical country, such as part of Asia is, the landscapes are beautiful.",
"A tropical twilight is very short, however, and the shadows have scarcely become long when the sun seems to sink suddenly below the horizon, although the last bright rays continue to shine back through the atmosphere for a few minutes.",
"If the gods informed them that whatever man would come to the temple first would become their king, they immediately chose the first comer king.",
"Whoever was chosen king made the blessed gods a thank-offering, which consisted of something out of his own possessions.",
"Gordius did not offer to the gods merely the yoke of his wagon, but the whole wagon.",
"A knot of rope was tied between the yoke and the pole.",
"People soon began to say, \"If any one soever can untie that knot, he will become ruler of Asia.\"If any other men tried to untie that rope, they failed.",
"Alexander, though, had scarcely arrived when he drew his sword from the scabbard, and cut the knot.",
"If you will take a seat, I will tell you about the two mischievous monks, returning to the monastery.",
"Both were breathing with difficulty, and stopped to rest.",
"Having noticed a donkey near by, they untied it.",
"One led the long-eared dumb animal away, while the other tied himself in its own place.",
"The credulous peasant believed everything which was told him.",
"Newton was an Englishman who lived three centuries ago.",
"One day he was walking in his orchard, and, noticing the falling apples, he stood still and began to wonder why they fall.",
"He studied the cause of their falling, wishing to discover whatever laws of nature he could.",
"He watched various falling objects, and tried to calculate their velocity.",
"Finally he recognized that force which is called gravitation.",
"Of course gravitation had always existed, but its laws were not noticed or clearly defined until Newton studied the matter.",
"If gravitation should not exist any more, no rain would fall, but instead of condensing, the moisture would remain above our heads in eternal clouds.",
"But gradually the moisture and the air itself, becoming rarefied, would fly away from the earth, being held no longer by the force of gravitation.",
"The water in the rivers would leave off flowing on toward the sea, because now the water flows from high to low places only on account of gravitation.",
"Instead of gravitating toward the sea, in fact, the water would flow in every direction out of the riverbeds, or would remain there, without moving at all.",
"Nothing on earth would remain here very long, but everything would fly off the quickly moving world, and leave it entirely bare.",
"Soon, also, the earth itself would break into pieces.",
"Socrates believed that if one knows about good and evil he will do good, but will not do evil.",
"Therefore he wished to help mankind, teaching them what the good is.",
"He also wished to discover for himself what is right and what is wrong.",
"So he asked every one whom he met his opinions, and the one talking with him would also notice whether his own ideas were right or not.",
"But the fellow citizens of Socrates were jealous, and hated him, because they did not understand him.",
"Therefore they accused him, called him a sinner, and sent around false reports about him.",
"Because he said that conscience guided him, they accused him of introducing new gods.",
"They also said that he was corrupting the youth of the city.",
"If Socrates had pleaded guilty, and begged for a fine instead of the death-punishment, without doubt he would have been pardoned and fined.",
"I have never in my life sinned in any way, and I do not deserve any sort of punishment.",
"So the judges condemned him to death by the drinking of poison.",
"Aristeides had just arrived at the popular assembly when a peasant approached him.",
"If Aristeides had not had a pleasant countenance and musical voice, doubtless the peasant would not have asked his help.",
"Ought Aristeides to have written his own name on the oyster-shell or piece of pottery which was going to be used as a vote against him?",
"Without just this help, the peasant could not have voted.",
"Why do you hate Aristeides?",
"Could you tell me how he has sinned against the city?",
"Oh, I know nothing about him, but I am weary of always hearing him called the just.",
"Ought such persons as that ignorant peasant have the right to vote about important affairs?",
"The ancient law about ostracism was a strange one.",
"The name of the person to be exiled was usually written upon an oyster-shell, and the meaning of the word signifying the custom comes from that.",
"Through ostracism, any leader could be banished, justly or unjustly, without trial of any kind, or explanation of the reasons.",
"The word ostracism comes from the Greek word signifying \"oyster-shell.\"It has its present meaning because oyster-shells or pieces of pottery were used for the voting.",
"The story about Aristeides is interesting, but that about the sword of Damocles is also interesting.",
"His friend, the Syracusan tyrant, had permitted all sorts of injustices, against not only barbarians but even Greeks.",
"Let every inhabitant be sold as a slave!",
"Let me make one sole empire out of Africa, Italy and Sicily!",
"Your royal highness ought to be very happy!",
"Come to a feast tomorrow, and find out.",
"I will give you a seat beside me.",
"Damocles willingly consented, and went thither.",
"Let us eat and drink until midnight, if that would be pleasing to you.",
"Then let us discuss the problem about happiness.",
"Look up and you will see what kind of happiness mine is.",
"Heaven defend me!",
"Cyrus did not desire that his brother should remain king.",
"Let me myself become king!",
"I should much enjoy that!",
"So he asked the Greeks to help him in some battles against nearby enemies.",
"Gradually an army of a hundred thousand men, ten thousand of whom were Greeks, gathered around him.",
"He led them farther and farther, into the middle of Asia, until finally the Greeks suspected his true aim.",
"He did not at first propose that we fight against the Great King.",
"Let us return home without delay!",
"Must I permit you to go back?",
"I implore you to be courageous, and I do advise you not to forget your longing for honor!",
"Only be worthy of your leader, and rely upon me!",
"Do you not wish to return home provided with wealth, beside the money which I shall pay to you?",
"Immediately the soldiers were ashamed of their fear, and advanced by hundreds, full of courage.",
"Soon the brother of Cyrus approached, with eight hundred thousand men.",
"By the aid of the Greeks, Cyrus won the battle, but he himself lost his life.",
"So neither he nor the Greeks could enjoy the result of their efforts.",
"After the death of Cyrus, the leaders of the Greek warriors did not know what to do.",
"In the course of the following day, one of the leaders of the enemy sent a messenger with deceitful promises about help.",
"Assemble in our leader's tent, in order that you may all discuss the matter.",
"The Greek leaders went, although they suspected danger, because they did not know how else to save their men.",
"But they never returned, and soon the Greeks understood that the barbarians had killed them.",
"They wept tears of despair.",
"The barbarians will inevitably destroy us, for we are in a foreign land, where we know neither the languages nor the roads, and the peoples are without exception hostile to us.",
"Obey us and follow us, and we shall do our best to save you!",
"Their return, across hot plains and snow-covered mountains, made more difficult by hunger and by the unceasing attacks of the barbarians, is related in the history written by a famous Greek historian.",
"One can still read this interesting narrative, in Greek or in a translation.",
"Alexander the Great wished to unite the whole world into one vast empire.",
"He intended that all the different peoples should conform to common laws and that their sons and daughters should speak one common language, and in spite of their love for their national languages, should leave off speaking them.",
"Possibly he might have accomplished his object to some extent, if he had not died suddenly when he was only thirty-two years old.",
"His soldiers marched weeping past his tent, to bid farewell to their dying leader.",
"They must have esteemed him very highly!",
"It was Alexander who founded the city of Alexandria, in Egypt, where approximately three hundred years before Christ the famous Alexandrian library was located.",
"It contained an enormous collection of books -- almost seven hundred thousand.",
"Alas, this extensive library was destroyed by fire!",
"Alexander, who \"sighed for other worlds to conquer,\" did not even know of the existence of North and South America, Australia, or even of England and Northern Europe.",
"Beside his Asiatic empire, he knew very little of Asia, even of China, with its millions of inhabitants.",
"How small the world was in those days!",
"The birds have very strong wings on their bodies, but they do not have hands.",
"They will build their nests, and sing about the young birds.",
"Those children were talking to me yesterday about their cat.",
"They said that it likes to catch and eat sparrows.",
"Tomorrow it will hide behind a tree, and will catch a young sparrow.",
"The children will gather peaches in that person's garden, and will put them upon a plate.",
"They will shake the whole tree by means of a branch.",
"The sweet fruit above them will fall upon the soft green grass.",
"The children wondered whether the cherries were ripe.",
"They seem almost ripe, and tomorrow the children will pick them, with the help of their father.",
"It is said that the grain in that man's field very much needs rain.",
"People also think that the flowers will wither, for it did not rain yesterday or today.",
"My careful young friend will carry an umbrella in his hand tomorrow, because he fears the rain.",
"He sees those gray clouds in the sky.",
"He holds the umbrella by its handle.",
"The weathercock is an indicator concerning the weather.",
"One eats meat with a fork, and soup with a spoon.",
"One holds the spoon in the right hand.",
"A knife is sharp, but one does not need a sharp fork.",
"We shall have a very good meal, and also very good coffee.",
"The east wind is dry and the south wind will be too warm.",
"A west wind blew against the weathercock, but the grain needed a south wind.",
"A north wind is blowing and I think that it will soon snow.",
"It will be beautiful weather tomorrow, because a pleasant wind is now blowing.",
"The flowers will wither because those children gathered them.",
"They are talking about that park, but I do not wish to take a walk, because there are clouds in the sky.",
"At least we shall take an umbrella, and my brother will hold it over our heads.",
"Mother and I are afraid that it will rain.",
"My young sister will be careful about that new umbrella.",
"I wonder whether she will take a walk tomorrow.",
"That park is pleasant and the grass is soft and green.",
"The birds are building their nests now, in those branches above our heads.",
"The sky above us is blue, and a west wind is beginning to blow.",
"I can see that weathercock, on that large house near the park.",
"Mother says that my sister will have a new hat tomorrow.",
"She will be careful of that hat.",
"My father's friend is very careful of his son.",
"One sees that he is not a strong boy.",
"One can see that the weathercock points out the winds.",
"They say that the west wind will be a dry wind.",
"The weathercock now shows that an agreeable south wind blows.",
"People will be angry with the weathercock, because it points out a north wind.",
"A north wind is not warm, and the grain and fruit will need a warm wind.",
"It snowed, and the young children were not warm, because the north wind blew.",
"People will like a south wind, but an east wind will carry rain.",
"Can one find money in the desert?",
"Do you think he is in the house?",
"He is said to be on the street.",
"It is thought that the camel is a faithful friend.",
"I am told that the camel has a large body, and a long neck.",
"One can see that it is not beautiful.",
"People do not like to drink warm water.",
"Nevertheless we shall drink warm water in the city.",
"It was beautiful weather yesterday, but today we shall have good weather also.",
"I think that a warm wind will blow soon.",
"My friend has a beautiful new house.",
"Today it is raining, but yesterday it was snowing.",
"Did your friend John carry his chair into the house?",
"I saw your good friends on the way to the city.",
"Is the large sack behind the door theirs?",
"Neither she nor her brother saw the whole city.",
"They went to the city of Boston and lost their way.",
"There are interesting houses across the street.",
"The body of a camel is large, and its neck is long.",
"The camel pushed its head into the house of the arab, and he was angry.",
"On the sand in the desert there lies a sack.",
"In the sack there is money.",
"The arab was warm, and wished to drink water.",
"He also wished to give water to the faithful camel.",
"Nevertheless, he found only money in the sack.",
"He was angry, and did not keep the sack.",
"Yesterday he wished to find money, but today he prefers water.",
"Nevertheless there is only sand in the desert.",
"He wished to come from the dry desert to the house of a faithful friend.",
"Both he and his friends are rich.",
"They went to his house yesterday, and came to theirs today.",
"They do not need money.",
"The cat ran across the street.",
"Across the street it found a sparrow.",
"It caught the bird, but began to wash its face, and the sparrow flew to the nest.",
"I went into the garden as far as the large tree.",
"I did not hold my book, and it fell upon the floor.",
"It began to fall under the table, but I seized it.",
"My brother pushed the books into their box, and put it on the table.",
"We went to the city of Boston yesterday and into a beautiful house.",
"But the camel commenced to go through the door.",
"His remark did not seem to surprise the camel.",
"The camel pushed its head and neck, and soon its whole body into the warm house.",
"It wished to put merely its nose into it.",
"The arab was angry, because it pushed itself into his house.",
"Brother, the house is mine, and I do not wish to have you in it.",
"But soon after the remark, the whole camel was in the house.",
"He pushed the young arab into the street.",
"He went across the street and stood upon the grass under a tree.",
"The boys are not in their house, but they are in his.",
"Is the large beautiful house yours?",
"The woman walked through the door of their house, as far as her room.",
"The room has interesting pictures on its walls.",
"We praised their flowers yesterday, and they gave them to us.",
"Their books are in their box.",
"They are on their table.",
"The gray cat was angry because it did not hold the bird.",
"The sparrow surprised it, and it commenced to wash its face.",
"The sparrow wished to fly as far as the tall tree, but the cat held it.",
"A good cat washes its face, but you are not a good cat.",
"The sparrow was angry because the cat seized it and held it.",
"The bird did not lose its meal, but the angry cat lost its meal.",
"Do you see his cat or hers?",
"I see both his and hers, but ours is not in our garden.",
"My father is a tall strong man.",
"I like to look at him.",
"The children saw the young birds in the nest.",
"The book in the gray box does not belong to me.",
"I found it in front of me, near the door.",
"You began to praise yourselves, but I do not praise myself.",
"They hid themselves, and I stood near them.",
"The birds sit on the tree, because it has ripe cherries on it.",
"Alfred amused himself on the street, but we like to amuse ourselves in the house.",
"The trees have good fruit on them.",
"She found herself in a beautiful light room.",
"The carpet on the floor had various colors in it, and the high wall had pictures on it.",
"The pictures had boys and girls in them.",
"The book belongs to her, but it fell from the box.",
"The table has red and blue and yellow flowers on it.",
"Did you see the doves near the flowers in front of you?",
"The birds saw the fruit on the tree in front of them, and flew to the branches.",
"I sat on the bench in the garden, and began to read an interesting book.",
"They hid themselves in the leaves and began to sing.",
"The child is in a pleasant room.",
"Do the boys and girls wish to be good?",
"They gathered fresh flowers and gave them to the woman.",
"The happy children were in the garden, but now they are in the house.",
"The rooms in the house are light, because they have large wide windows.",
"The doors in the room are wide and high.",
"The carpets on the floor seem soft, and have various beautiful colors.",
"A large strong table stands near the door.",
"We can sit near the table and look through the windows.",
"Gertrude is looking at the various pictures.",
"She looks at them, and seems to be happy.",
"She gave a picture to me and I thanked her.",
"Helen walked near the table and shook it.",
"Arthur did not see the pictures because they were lying on the floor.",
"He looked at the pictures on the wall, but they are neither interesting nor beautiful.",
"Robert looked through the window, and saw us in the pleasant garden.",
"Does Arthur break the branch and gather the apples?",
"No, he shakes the branch, and the apples fall.",
"They are ripe and sweet.",
"Robert, do you wish to stand beneath the tree?",
"No, I do not wish to stand under it, but near it.",
"I wish to give both the peaches and the apples to the woman.",
"She is sitting in the house, near the window.",
"Mary is sitting in a chair near her.",
"Both Mary and the woman are sewing.",
"They prefer to sew, and do not wish to walk in the garden to-day.",
"They are happy because they like to sew.",
"They do not wish to gather flowers, or walk, or see the birds.",
"They have neither apples nor peaches, but they do not wish to eat.",
"They give the fruit to the boys and girls.",
"Have the girls beautiful flowers?",
"No, they have fresh fruit.",
"The boys do not wish to gather flowers.",
"They prefer to break the branches, and find the sweet cherries.",
"Gertrude wishes to eat apples, but Mary has neither apples nor peaches.",
"Do the girls like to sit in the house and eat fruit?",
"Yes, they like to sit in the house, but they prefer to walk in the field.",
"Are ripe peaches brown?",
"No, they are red and yellow.",
"Has the peach a sweet taste?",
"Do the girls see the beautiful black horses in the fields?",
"Yes, they see the horses, but the horses seem not to see the girls.",
"Mary sits on the soft green grass, and eats ripe fruit.",
"Green leaves are on the trees.",
"The boys break branches and gather the apples.",
"They are near the tall tree in the garden.",
"They find leaves on the tree, but they do not see the fruit.",
"The house is long, broad and high.",
"The rooms in the house are both long and wide.",
"The men have strong black horses.",
"The horses eat the fresh green grass in the field.",
"The men sit on benches in the garden.",
"The boys do not sleep, but they lie on the soft grass.",
"They see both the birds and the flowers, and they seem happy.",
"The flowers have various colors, but the grass is green.",
"The doves are not sitting on the tree, they are flying near the trees.",
"Beautiful red roses are lying on the table in the house.",
"The large red apples are near the yellow roses.",
"The trees in the garden are tall and green.",
"The rooms in the house are long.",
"The flowers on the table are red, yellow and white.",
"The leaves are long and green.",
"The men are sitting on chairs in the garden.",
"In the garden are yellow roses.",
"The birds in the field are doves.",
"The boys in the room in the house seem tall.",
"Fresh violets are beautiful flowers.",
"The horses in the green fields seem strong.",
"Doves are singing in the garden.",
"The men in the large house sleep.",
"The house is long and high, and the rooms in the house are large.",
"Red and yellow apples lie on the big table.",
"Green leaves are on the trees in the large garden.",
"A beautiful flower.",
"A good large table.",
"A yellow violet and a white violet.",
"The moon is shining.",
"The good boy is walking.",
"The beautiful yellow bird is flying.",
"The strong man is sleeping.",
"The white bird is singing.",
"A strong horse runs, and a man walks.",
"The sun shines, and the boy is singing.",
"The large yellow apple.",
"An apple large and good.",
"Does one eat potatoes and meat with a fork or a spoon?",
"One puts soup into the mouth by means of a spoon.",
"One cuts fruit with a knife, and puts the fruit upon a plate.",
"The coffee was cold, and I was much dissatisfied.",
"My knife was dull, nevertheless I almost immediately cut my left hand.",
"I was ashamed, but I think that the handle of that knife was very short.",
"The grass is wet today, and I fear that we shall not be able to take a walk, even in that small park.",
"I dislike to go walking upon the hard streets.",
"The courageous young man and his aged friend talked about their enemies.",
"They wished to be careful about their horses.",
"The young man was very sly, and wished to sleep during the night.",
"He said that one can steal a black horse during the dark night.",
"He said that either he or the old man would guard the horses.",
"The old man answered that he would give to him his own white horse.",
"He took that one's black horse.",
"He was ashamed, and was very angry at his faithless friend.",
"But he stayed awake, and guarded the horses.",
"The foolish friends of the young man and his aged father did not stay with them.",
"They did not help them with their swords, but ran away at once, and were not ashamed.",
"The old man heard disagreeable voices behind him, and soon he saw the enemy.",
"The enemy called them, and hastened there.",
"Those sly bad men took the money out of the pockets of the courageous young man.",
"They stood around him, and also around his father.",
"The father and son could not even guard their horses.",
"The enemy did not leave these their horses, but took both the horses and the money.",
"Soon the enemy rode away, during the late hours of the night.",
"The father and son were angry and dissatisfied.",
"We fear and dislike such men.",
"By the help of our neighbors we can find those bad men, and drive them away, out of the desert.",
"Dear Father, such a proposal seems good, and I will help with my long sharp sword.",
"But we are now in the desert, and the road to the city is long.",
"We cannot ride thither, but we can walk thither.",
"Can you not hasten, with my help?",
"Yes, my son, with such help I can walk thither.",
"An interesting story is related about Frederick the Great.",
"His youngest servant stayed outside of the door.",
"The king called him, and he hastened thither and stood before him.",
"Yesterday he did not hear the king.",
"The king called him, but he did not answer.",
"The king thought that the boy had gone away with the older servants, and he was angry.",
"He left his book on the table, and went to the door.",
"Then he saw that the little boy was sleeping there.",
"He looked at him with greater interest, and saw a letter in his pocket.",
"The letter was from the boy's mother.",
"He had written a letter to her, with his pen, and had given her money, because she was poor.",
"He wrote longer letters with pleasure, because he was a most faithful son.",
"The king congratulated the mother of the boy, concerning such a son.",
"King Frederick wished to be kinder to the boy.",
"He placed his book upon the table, near his sword, and talked to the little servant.",
"Then the older servants came, and stood around the king.",
"They walked with great care, and the younger servant did not hear them.",
"They loved the little boy, and wished to help him.",
"I read a most interesting book about Frederick the Great.",
"It relates that he often stayed awake and read with great interest during the later hours of the night.",
"His youngest servant was a small boy.",
"The king loved this boy more than he loved the older servants.",
"The winter is a less pleasant season than the spring, but the summer is more pleasant than that season.",
"During March the east winds blow most strongly, and shake the trees very much.",
"In April one needs his umbrella, for there are often clouds in the sky and it rains a great deal.",
"The streets are very wet, but the water does not seem to wash them.",
"In May one begins to find sweet violets, and the birds in the trees above our heads sing very sweetly.",
"In June the most beautiful roses are seen.",
"July and August are the warmest months of the whole year.",
"The days are longer than the nights, and the weathercock shows west and south winds, instead of those disagreeable north and east winds.",
"One stays outside of the house then with greater pleasure, and goes walking in the parks.",
"I think that I like the summer better than you do.",
"Therefore I praise the summer more than you do.",
"However, I praise you more than I praise your younger brother.",
"He is less wise than you.",
"September, October and November are the months of autumn.",
"In these months, people harvest the yellow grain and gather various fruits.",
"The leaves on the trees around us begin to have red and yellow colors.",
"They begin to fall from the branches and lie upon the ground.",
"The more strongly the cold north wind blows through the branches, the sooner the leaves fall from there.",
"They lie under the bare trees, with the brown grass.",
"The sooner it snows, the sooner the ground will seem to have a white carpet.",
"The snow will completely cover the grass during the months of the winter.",
"These months are December, January and February.",
"From that time the ice and snow will cover the roads, and altogether hide them.",
"There will often be ice on the water of the river.",
"We like this season of the year more than March, April and May.",
"We like it even more than the summer.",
"The months of the latter are June, July and August.",
"The summer is the warmest season of the entire year.",
"Therefore we often say that the summer is the pleasantest season.",
"Because of its many pleasures, the summer is dear to me.",
"It is between the spring and the autumn.",
"Many years ago we had a small house across the river.",
"We did not remain there during the entire year, but only in the warmer months of the summer.",
"Often we stayed until September or even until October.",
"My younger brothers and sisters amused themselves very well there from morning until evening.",
"They amused themselves among the flowers and trees, or went from there into the large fields.",
"Here the men work energetically, and harvest the ripe yellow grain.",
"Only on Sunday do they rest, because on that day one does not work.",
"Between August and November the men work more than in the winter.",
"In December and after that month they rest, for from that time the frost, ice and snow cover the ground.",
"Because of the snow on the ground, long walks are not pleasant in the winter.",
"Recently we went walking in the park across the river, but we were so tired after that walk!",
"The longer the walk is, the sooner one wishes to rest.",
"On Monday it rained, so we read stories and wrote letters, in a pleasant light room in our house.",
"Before evening, however, the sun shone, and the streets were not so muddy.",
"On Tuesday these streets were almost dry, and soon the roads near the river and between the fields will also be dry.",
"A few years ago those roads were very good.",
"Tuesday my brother heard an interesting story, and Wednesday evening after a pleasant walk he related it to me.",
"The story is, that many years ago God made the beautiful new world, and gave it to the seasons.",
"They laughed for joy, and said that they would guard it well.",
"They were ready for pleasure, and also were willing to work energetically for the sake of the new young world.",
"Almost a year they were happy, but these seasons were too diverse, and could not long remain friends.",
"The brilliant summer wept and reproached the tired autumn.",
"The autumn preferred to rest, and disliked the muddy weather of the inconstant spring.",
"The quiet winter concealed itself beneath the frost and soft white snow, and wished to sleep.",
"The longer they kept the world among them, the more they quarreled.",
"We will divide the world.",
"Immediately that morning the seasons divided the world among themselves.",
"The northern and southern lands now belong to the winter, and the middle of the world belongs to the summer.",
"The spring and autumn took for themselves those lands between the winter and summer.",
"Diogenes was a wise man who dwelt in a Greek city, many years ago.",
"In order to show to the inconstant world that one does not need much in order to be happy, he did not have even a house or a bed.",
"He stayed day and night in a big barrel, instead of residing in a house.",
"He preferred to wear old rags, instead of good clean clothes.",
"The less one needs, the happier he will be.",
"While Alexander the Great was visiting that city, people talked to him about Diogenes.",
"Are you acquainted with that wise man?",
"Soon the king went with a number of his friends to that man's big barrel, in the middle of the city.",
"Diogenes was asleep, but the noise of the loud voices waked him.",
"You are standing between me and the sun!",
"Will you not go away at once?",
"We did not come to quarrel with you.",
"I see that you have enough to be happy, so instead of talking and making a noise we shall leave you at once.",
"Before Diogenes could answer, Alexander had quietly walked away. ",
"I shall go to the village today with my younger sister.",
"We wish to buy some eggs, vegetables and fruit for Mother.",
"Mother prefers to remain in the house, because it is raining.",
"It rained on Thursday and Friday, but today it is not raining very much.",
"The air is warm and pleasant, and we shall carry umbrellas with us.",
"We shall buy some new peas, a box of strawberries and several pounds of sugar.",
"Thus we shall have enough for the meals of Saturday and Sunday.",
"I wonder whether we shall see such asparagus and such cabbage on the tables or in the barrels.",
"Although I do not often eat such vegetables, Father and Mother are very fond of both cabbage and asparagus.",
"We shall also buy enough milk for several glasses of milk, and we shall need much cream for the strawberries.",
"It seems that we shall buy such a number of vegetables that we cannot carry them.",
"While we were standing near the door, ready to go toward the village, we heard a loud voice.",
"A child was standing in the street, and crying.",
"He wished to go with his mother to visit some friends.",
"I suppose that a noise on the street waked him, and he did not wish to remain in his bed.",
"Who is the woman sitting on the sofa in the parlor?",
"I can not easily see her, but I hear her voice.",
"I wonder whose voice that is.",
"However, I think that it is the voice of a friend of Mother's.",
"Now I can see her, although she does not see me.",
"I am well acquainted with her.",
"She is a friend of our whole family, and is visiting a neighbor of ours in this city.",
"My sister is sitting on the sofa in another room, and learning her lessons.",
"Soon she will go to school.",
"Whose book is she reading?",
"That thick book is mine, but the other books on the table near her are hers.",
"She prefers to sit in the sewing-room to read or write, because the curtains in front of the windows are not too thick, and so that room is very light and pleasant.",
"She also likes to look at the falling snow, and the men and women walking on the muddy streets.",
"On account of the cold weather, people are wearing thick clothes.",
"The men and boys are keeping their hands in their pockets while they walk.",
"The girls walking toward the school are friends of my sister's.",
"In that school they learn to cook.",
"Soon they will be able to bake bread, and even to cook a whole meal.",
"I think such a custom is very good.",
"Many persons can not cook well enough.",
"What sort of noise do I hear outside the door?",
"Are some of my friends knocking?",
"We were talking yesterday about the examinations in our school, and these boys came home to study with me.",
"I shall go to the door to open it and to greet my friends.",
"Good morning!",
"Did you come to study geometry, or the German language?",
"Which of these is usually more difficult, and in which will the examination be the longer?",
"Well, we brought our German books, because we prefer to study these.",
"We wish to know this language thoroughly.",
"We shall go into the writing-room, for some friends of my grandmother are in the parlor.",
"We can hear their voices here, and we can not study very well while they are talking.",
"They were carrying many flowers, and gave a beautiful bouquet to my grandmother.",
"Many thanks for the sweet violets!",
"In whose garden did they bloom?",
"Her friend's granddaughter is a friend of my youngest sister.",
"Well, shall we begin to study? Have you enough paper, and have you a good pen?",
"I shall close this other door, because they are baking bread in the kitchen, and cooking meat.",
"We shall be hearing the voices of so many persons that I know that we can not study.",
"While we were walking home from school yesterday, it rained very suddenly.",
"What a storm it was!",
"We were talking about the lessons in geometry, and were looking at these books about the German language.",
"So we did not see the clouds in the sky.",
"Well, we forgot about examinations and began to wonder where to go.",
"We did not know whether we had enough time to run even to Grandfather's house before it would rain.",
"Many papers fell out of our books, and the wind caught them.",
"The wind chased them away from us, and they seemed to dance around in the air.",
"However, we easily caught and gathered them, and then we ran forward.",
"Suddenly it thundered very loudly, and we saw the brilliant lightning in the sky.",
"We almost closed our eyes for the lightning.",
"Big drops of rain fell heavily and struck the dust violently.",
"The air was heavy and still then, and the storm immediately followed the few drops of rain.",
"We hastened across the street, and ran faster and faster.",
"We were exhausted and our clothes were exceedingly wet before we were in the house.",
"The rain was dropping from the roof, but we ran through it, and knocked on the door.",
"We rested some time here, before going home.",
"Although the enemies of Robert Bruce conquered him many times, he finally conquered them in Scotland, because he was patient and very courageous.",
"He was sitting in a large stable, to hide, and also in order to look directly from its roof the soldiery of the enemy.",
"At the end of the day he noticed a spider crawling up on the wall.",
"The spider fell suddenly into the dust and lay at the king's feet, but soon began to crawl up.",
"Where does it wish to go?",
"What patience it shows!",
"It has crawled up and fallen down a great many times.",
"Finally however the spider succeeded, and crawled up to the ceiling.",
"The king said that he had learned a lesson from the patient spider.",
"Although the enemy have conquered many times, because they have a larger number of soldiers, I shall finally succeed against them.",
"Soon it happened that the wind blew violently, and a rainstorm occurred.",
"The blast shook the foliage on the trees, and broke away many small branches.",
"A group of soldiers ran right toward the stable, and Robert Bruce was much afraid that they would find him.",
"But they merely stole the horses there, and rode away.",
"Our grandfather is an old man, and they say that he will not live much longer.",
"He is not very strong, and can not take long walks.",
"The mile between his house and ours now seems long to him.",
"He prefers to sit quietly in the house or on the veranda, and think, nearly all day long.",
"He is very amiable, and can tell exceedingly interesting stories, about the victories and defeats which happened many years ago.",
"Such things are wicked I think, and I am very glad that such battles do not happen now.",
"Grandfather has a long white beard and much white hair.",
"It is very interesting to hear his stories, and also to look directly at him while he is telling them.",
"He tells such stories with great pleasure.",
"Although he has lived with us since February, he does not know a great many of the neighbors, or of the other persons living near.",
"Grandmother has blue eyes, red cheeks, and soft white curls.",
"She speaks slowly, with a sweet voice, and is very patient.",
"Good morning, my dear, I have lost my spectacles.",
"Will you look for them for me?",
"I nodded and soon found the spectacles.",
"Three and four make seven.",
"Two and six make eight.",
"Five and six make eleven.",
"Seven and five make twelve.",
"I have been studying geometry since five months ago, and German since January.",
"I have read three German books, but I shall not be able to talk in this language until after August.",
"To learn how to speak such a language is a difficult matter.",
"Nine of the children in our school are now studying German with me.",
"Some learn it easily, others do not like it.",
"Three of the boys and two of the girls in that school are German.",
"They had resided four years in a large city, but I think they live more contentedly in our quiet village.",
"They can not talk with us very well, but merely nod their heads when we talk to them.",
"I had not seen them before they came to school, although they are neighbors of ours.",
"They are amiable children, with blue eyes, red cheeks, and yellow hair.",
"They can ride very well, and often ride eight or ten miles in one day.",
"They usually ride in a park three miles wide and four miles long, where there is but little dust.",
"There are twelve months in a year, and in most of the months of the year there are thirty-one days.",
"There are only thirty days in the months April, June, September and November.",
"There are seven days in a week, and twenty-four hours in a day.",
"Twelve of these hours make the day, and the others make the night.",
"There are sixty minutes in one hour, and sixty seconds in one minute.",
"There are four weeks and also two or three days in one month.",
"In the year there are fifty-two weeks.",
"How many weeks are there in ten years?",
"At least one year in ten years is a leap-year.",
"In a leap-year there are three hundred and sixty-six days, instead of three hundred and sixty-five.",
"Wise men calculated about this matter, many years ago.",
"It is well for us that they liked to study arithmetic.",
"I have often received good grades in this study.",
"I remember it easily, and seldom make mistakes.",
"Before my friend will have finished that mansion, it will have cost twenty thousand dollars.",
"Before coming to visit you, I shall have ridden twelve miles on my horse.",
"The grade which you will have received in arithmetic soon after the first of March will be excellent.",
"You do not make mistakes very often in the lessons.",
"I shall try after a few minutes to translate that Latin book, for it seems interesting.",
"It is necessary to study Latin, for I desire to read the stories which are in my Latin book.",
"The one thousand nine hundred and fourth year was a leap-year.",
"The fourth year after that year was also a leap-year.",
"The 1912th year will be a leap-year.",
"There are three hundred and sixty-six days in such a year.",
"Alfred won the book which his mother had bought.",
"Such a book now costs four or five hundred dollars.",
"Alfred the Great was the last king until many years afterward who could read or write.",
"He was the first king in that land who even wished to be able to read books.",
"We often talk about this same King Alfred, and say that he was the father of the English language.",
"People say so because he translated Latin books into the language of his land, and because he also wrote books in that language.",
"Alfred the Great was a praiseworthy king who lived more than a thousand years ago.",
"People still talk about him because he not only translated many Latin books into the English language, but also wrote in English.",
"He wished to help the peasants still more.",
"But enemies often attacked him, and finally they conquered his soldiers.",
"Then they hastened to where Alfred was.",
"They were about to attack him, when he rode away secretly into a large forest.",
"There he dwelt some time in the house of a poor forester.",
"He wore such rags as a peasant usually wears, and did not tell the forester who he was.",
"Will the enemy have conquered my soldiers next week?",
"Will you sit there yet a while and take care of those cakes?",
"I am about to gather more wood.",
"Certainly, I will try to help you.",
"But when after a few minutes the woman smelled the cakes, she knew that the fire had spoiled them.",
"Oh, what a blame-worthy man!",
"She commenced to beat the king cruelly, but he did not defend himself.",
"Instead, he told her who he was. ",
"My friend likes to live in the city, but his wife prefers to live in their little wooden house in the country.",
"There she can see and smell the flowers, and can take long walks in the adjacent fields and forest.",
"There are often hundreds of persons in a village, but there are thousands of persons in a city.",
"The larger a city is, the larger and better its stores are.",
"In the second place, one can buy better bread, vegetables and cake in the city.",
"Thirdly, one can also find better gloves, hats and shoes there, and the price is often less.",
"Therefore I make use of the opportunity when I go to the city, and usually buy a pair of new gloves.",
"I am still wearing a pair of gloves which the rain spoiled.",
"Notwithstanding their ugly color, they are still thick and good.",
"But soon I shall buy such a pair as is hanging in the window of that store.",
"The price is low, and I need a new pair now, for my cousin has invited me to a small party at his house.",
"I accepted his invitation courteously, and said that I would gladly be his guest.",
"We are good comrades, although he is younger than I am.",
"My cousin, his sister, is older than he is, but he is as tall as she.",
"I was just about to send a letter to him at the minute that he knocked on our door.",
"His visit will take the place of my letter.",
"Just as he was going away, I said goodbye to him, and said that I would meet him in the park tomorrow.",
"I think that we shall have a pleasant walk, although the weather is still remarkably cold, the same as it was two or three months ago.",
"There are dozens of edible fruits, but the fruits of hundreds of trees are not at all edible.",
"The transparent cup and plate upon the table are very breakable.",
"I predict that you will break them as soon as you seize them.",
"That letter is worth reading.",
"But it is difficult to read it, for it is not very legible.",
"It is from my uncle, who wishes to arrive at our house as early as possible.",
"He is still in the city, but soon he will be here, and will go up the steps of our porch and knock on the door.",
"There are very few persons who contradict his opinions.",
"His opinions, however, are worthy of attention and usually I listen courteously while he is talking.",
"Now, however, I prefer to listen to the group of ladies in the adjacent room.",
"They are chattering gaily, and listening to the young lady who is about to sing.",
"Madam, do you feel the wind? I notice that it is blowing the curtains which hang before that window.",
"I will close the window, because I am not very well today.",
"Is that gentleman across the room a bachelor?",
"Yes.",
"He is describing a voyage and the people whom he met.",
"Why are the persons in that merry group laughing and chattering instead of listening to Mr. B----?",
"I think that the doctor is telling stories about a bachelor who was once a good friend of his.",
"The gentleman being talked about will visit us this evening, possibly.",
"My aunt and cousin will come down stairs and converse with him.",
"We shall drink as many cups of tea or of coffee as we wish.",
"How is your health, Madam?",
"My aunt will reply half-angrily that she is seldom ill.",
"We shall sit on the veranda, for the sun is still shining, although it is already setting.",
"That young lady who came with Mrs. C---- relates the best possible stories.",
"She says that the Chinese were already an enlightened nation hundreds of years ago, while other nations were still cruelly fighting.",
"A method for printing the pages of books, instead of writing them, was a discovery of the Chinese.",
"They printed books in their printing-shops, a thousand years ago.",
"They also were acquainted with gunpowder, which they made and used for such fires as we use on national days of celebration, when we have leisure and wish to enjoy ourselves.",
"But the Chinese have not changed these methods.",
"Their ways of commerce, work and pleasure are the same as they were long ago.",
"Such a nation does not progress rapidly, even though its life is very long. ",
"The serious affairs of a republic are managed by persons representing the persons who live there.",
"The inhabitants are well represented, and as free as possible.",
"Enlightened persons often prefer to live in a republic.",
"Persons who have a good king are very happy, but those who have a bad king are as unhappy as possible.",
"Nowadays there are very few tyrants.",
"The majority of the kings of Europe are praiseworthy.",
"That nation which was most enlightened a thousand years ago was the Chinese nation.",
"The Chinese of that time already had good printers among them.",
"It is said that the Chinese drink as much tea as two or three contemporary nations.",
"The oldest republic in Europe is named San Marino.",
"It is near the mountains, in the northern part of the much praised Italian land.",
"It contains only twenty-two square miles, and is therefore one of the smallest republics in the world.",
"Fourteen hundred years ago it was already a republic, and it is still that same republic.",
"The inhabitants are energetic and patient, and have as much to eat as they need.",
"There are bakers and shopkeepers and many laborers among them.",
"They do not think about commerce, or greatly change their customs.",
"They seldom take tiresome journeys, but remain peacefully at home.",
"The day before yesterday my youngest cousin was sitting on my knee, and I told him that a rainbow is made by the sunshine and the rain.",
"My cousin goes to school every day, after he has breakfast in the dining-room.",
"A new school is being built, not far from the home of the judge.",
"It is my cousin's duty to study those books at the rate of ten pages a day.",
"My cousin and I decided last night to buy new hats for ourselves.",
"We intend to go to the hatter's early tomorrow morning.",
"I think that all clothes are being sold at a low price at the present time.",
"During a visit at a friend's, I read an interesting book about ancient Europe.",
"It relates that several centuries ago a severe and cruel tyrant was managing affairs in Switzerland.",
"Once he put his hat on a pole in the market-place, and said that it was the duty of everyone to kneel before it.",
"This serious affair happened in a village one or two miles square, on the lake not far from the mountains through which one goes on the way to the Italian land.",
"William Tell did not kneel or even look at the hat representing the tyrant.");

function esperantoLine()
{
	global $esperantoLines;
	return $esperantoLines[array_rand($esperantoLines)];
}

?>
