<?

// https://archive.org/stream/materialforexerc00horn/materialforexerc00horn_djvu.txt
// Material for exercises in German composition : with a carefully arranged English-German vocabulary
// 1895

	$german1lines = array(
"My father, however, said nothing.",
"He brought me a present, after all.",
"We are reading a newspaper.",
"The lady sings beautifully.",
"We are going home.",
"We shall go to Toronto to-morrow.",
"My brother went to Toronto by train yesterday.",
"When do you go to Toronto?",
"He came home last night.",
"From pure joy the birds in my father's garden sing exquisitely every morning.",
"He said that he would come to-morrow at ten o'clock.",
"The man whom we saw at the station yesterday was a German.",
"I have been advised.",
"The hay has been found.",
"That idea can be entertained.",
"I have been advised.",
"There is dancing.",
"There was a good deal of singing.",
"The houses are being built.",
"The houses were  being built in the 15th century.",
"The door was shut.",
"He was shutting the door.",
"He shut the door.",
"He said he was sick.",
"They said they had seen your father.",
"I have bought a new coat.",
"He told me that he had bought a new coat.",
"There he sat weeping.",
"Having seen them all, he returned home satisfied.",
"Hearing the news, he became very excited.",
"The man carrying the box is a brother of our neighbour.",
"Having suffered great loss, the enemy yielded ground",
"He stood on the bridge, looking down at the water.",
"He remained in his room all day writing letters.",
"I will remain standing.",
"I am going for a walk.",
"The fighting lasted all day.",
"The child stopped laughing.",
"I wish you would write the letter before going down town.",
"The man there yonder is a book-seller.",
"I was in his shop on King Street Monday to buy a grammar dictionary.",
"He showed me some beautiful books at six marks apiece, but the smaller ones cost four.",
"He gets books from England and Switzerland twice a week, and pictures as well, of which he has many in his shop.",
"There were some charming ones of Mount Blanc, of Vesuvius, of France and of sunny Italy.",
"The book-seller is himself an Englishman and was a soldier, but is now well-known in town as a business-man.",
"Well, I hope it will please you here, but the town is really not interesting.",
"The citizens' houses are mostly small and old, the roofs very low and covered with straw, the windows small, and for that reason the rooms much too dark.",
"Besides, the roads are very bad, not only in town but in the whole country generally, so that it is impossible to drive around much in bad weather.",
"The only large and handsome building in town is the town-hall, which was built in the 14th century.",
"It is of red brick, the floors of stone and the roof covered with tiles.",
"The rooms are mostly broad and particularly high and sunny, and the walls hung with beautiful pictures.",
"What was the music in the street last night?",
"O!",
"There was a crowd of people singing and playing in front of Dr. Smith's house.",
"As you know, this famous traveller has been in Asia, and has seen a great many strange people and strange customs.",
"He has just got back.",
"It is quite an honour, isn't it, when people sing and play in front of one's house.",
"Yes, indeed.",
"How long were the musicians there?",
"I suppose about two hours.",
"Dr. Smith was so pleased with the music that he made quite a long speech in returning his thanks.",
"Afterwards he told them much that was interesting about his travels in strange countries, and also showed them some charming pictures of the men and women, towns, houses and shops which are to be seen there.",
"The German Empire, as it now stands, is a glorious realization of the thoughts and hopes which all patriotic Germans had long cherished in their hearts, and for which so many swords were drawn in the war of '70-'71.",
"The names \"Germany\" and \"William\" resound through the whole land in songs full of inspiration.",
"Like sparks they kindle the faith in all young hearts that a still greater glory is in store for the Fatherland.",
"The peasants who live in the Black Forest are strong and tall, and have strongly-marked features.",
"As a rule they are children of the forest, carrying on the same occupations as their fore-fathers.",
"Their clothing is simple and costs very little.",
"They usually wear wooden shoes, and a short jacket instead of a coat.",
"Those who are raftsmen, however, wearing red shirts and top boots.",
"Their houses, though small, are light and sunny, and are patterns of cleanliness.",
"Though in general without education, they are remarkable for a simple childlike faith.",
"Out of their blue eyes shines the firm will and true heart of the good subject.",
"As soldiers, therefore, they are brave and bold, and as neighbours kindly and helpful.",
"It is reported that a burglar once came to the house of the famous savant Afolieres, who was in the habit of retiring early.",
"When the burglar entered the bedroom he found the learned man studying in bed, as he very often did when tired.",
"Who are you, and what do you want here?",
"Never mind my name, I want your money.",
"All I have, and that is very little, is in the right drawer of that table.",
"Open it and take the money, but on no account disturb my papers.",
"After the thief had pocketed all the money, he left the room in such a hurry that he did not shut the door.",
"You didn't disturb my papers, did you?",
"No, of course not.",
"Well, then, please be good enough to close the door.",
"There is a frightful draught here and I don't want to catch cold.",
"Dear Old Boy",
"Where is that wonderful, lovely Utopia, where you are now?",
"You write such long and, I might almost say, such gushing letters about the place and its charms, that I have almost decided to visit it.",
"You say it lies on the bank of a broad, deep river.",
"Is there any fishing there?",
"Are there good boats to rent?",
"Are the hotels good, and is the country around pretty?",
"I always take a holiday in the hot summer season, but am tired of visiting the same old places.",
"I would like to find a new one, and according to your letters, that must be nice and quiet, and that is just what I want and must have.",
"I suppose prices are not high in such a place, and that would please me, too.",
"I have spent a good deal of money this year.",
"I should probably stay five or six weeks, and would like a rather large and sunny room if I could get one.",
"Please let me hear from you soon.",
"Dear Friend",
"In my last letter I described the little village in which I was then staying, and the beautiful scenery around it.",
"I am now in a much larger place where our relatives live.",
"I do not like it as well here as in my former stopping place.",
"The village was on the shore of one of the most beautiful lakes I have ever seen.",
"However, in the town there are larger hotels and  more of them.",
"Most of the landlords are not so obliging as the one in the village.",
"The most interesting building here is the old town hall, though St. John's church is still older.",
"My uncle received me in a most cordial fashion.",
"He is one of the richest men here and has the finest house in town.",
"I am democratic you know, and like best to live very quietly and simply, the simpler the better.",
"I do not like visiting rich relatives and shall get away from here at the earliest possible moment.",
"Good-bye until my next.",
"I would like 2 lbs. of first-class butter.",
"Very well, madam.",
"I have some excellent butter this morning at 18c. a lb.",
"Would you like to taste it?",
"Yes, if you please.",
"This butter really tastes good.",
"I will take 3 lbs. of it.",
"Is there anything else this morning?",
"I would like some strawberries, if you have nice fresh ones.",
"I can recommend the berries out in front of the store.",
"You would find any better ones in town — they are 12c. a basket.",
"Very well;",
"let me have six baskets.",
"You may also send me 10 lbs. of sugar, a lb. of good coffee, and half a lb. of black tea.",
"Will you be able to send them soon?",
"Yes;",
"the boy will go in half an hour.",
"Is there anything else you would like?",
"No;",
"that is all now.",
"How much do I owe you altogether?",
"$2.21.",
"Can you change a bill?",
"I am very sorry;",
"I haven't quite enough change.",
"It doesn't matter;",
"I will pay the boy when he brings the things.",
"My husband will be sure to have change.",
"Good morning",
"I was just going to knock.",
"Is your husband at home?",
"I am sorry, but he is not.",
"He went to town this morning about 9:45.",
"When do you expect him back?",
"He intends coming by train, to-morrow afternoon.",
"He will, I fancy, be here between 5 and 6, if the train is not late.",
"Well, that is often the case you know in summer.",
"There are so many travellers and so much baggage.",
"Yes, and in winter the snow is the hindrance.",
"How are the children?",
"Quite well, thank you.",
"They were very glad to see their mother again.",
"Why, I didn't know she was home!",
"When did she come?",
"Just this morning.",
"We expected her day before yesterday",
"That very morning I got a letter saying that her mother was sick and she could not get away.",
"Surely her mother is not well already!",
"No, not exactly, but she is better.",
"She had caught a slight cold.",
"With elderly people that often means a good deal.",
"Yes, indeed.",
"Well, good-bye.",
"I will try and see your husband the day after to-morrow,",
"In a certain house, which you children have often visited, there lived a very cunning old cat which was the deadly enemy of the poor little mice.",
"Every time they came out of their holes the wicked cat saw them and would try to catch them,",
"a cat can, as you know, see in the very darkest night.",
"So they never had any peace and did not know how to protect themselves from the wicked creature.",
"One day an old mouse called the others together in a quiet corner, where they were safe from their enemy, so that they might consider what they should do in their need.",
"In this council there was a young mouse who was very proud, and thought itself much better than the rest because it was white and had a very long tail.",
"It was in a great state of excitement because it had what it considered was a clever bit of advice to give.",
"As is often the case, however, the little mouse, like a good many people, was not so clever as it thought, as we shall see when the story ends.",
"As I have already told you, the mice were considering what they should do.",
"One said one thing and another another, but none of them had as yet made any sensible suggestion.",
"After the most of the mice had given their opinions, the little white mouse stood up and spoke as follows.",
"My dear friends, permit me to tell you what appears to me to be a good scheme.",
"Indeed, I expected that someone would have spoken of it.",
"Of course all the other mice wanted to hear what the pretty little thing had to say, so they pricked up their ears and listened very attentively.",
"The little creature went on.",
"Would it not he a good idea to hang a bell on the cat's tail?",
"If we did that we would hear the bell every time the sly old enemy crept up and could fly to our holes.",
"I should like to hear what the rest of you think.",
"As you may well believe, the other mice were delighted at the suggestion of their pretty sister, and every one thought that now they might hope to live in peace and safety.",
"They all praised the clever idea of the white mouse, whilst the dear little thing looked very modest and half ashamed because of the many flattering speeches that her companions made.",
"At last, the old mouse called for silence, and as soon as they were all quiet she said:",
"I cannot tell you all how much the counsel of my dear friend pleases me.",
"She is our deliverer.",
"Long live our pretty friend.",
"The other mice cried out as with one voice.",
"Long live the white mouse.",
"In a few moments the old mouse spoke again",
"Who will bring me a bell?",
"I have one",
"And I have a pretty ribbon to hang it on with",
"I found it in a box in the bedroom",
"I believe it belongs to the black doll lying on the bed.",
"So the mice tied the silk ribbon on the little bell, and all that remained to do was to find the cat and hang the bell on her.",
"I cannot describe the joy of the mice as they looked at the bell with its pretty ribbon.",
"Who would have believed that our white sister was so clever?",
"Now we will be safe from our foe!",
"Who will be afraid of her now?",
"Again, the old mouse called for silence",
"Who does not hope that we will now be able to live in peace?",
"What will our old enemy do now?",
"She will no longer be able to catch any of us.",
"But, friends, one thing yet remains, that is, to hang the bell on her tail.",
"Who will do it?",
"Who will thus win our everlasting gratitude?",
"But the mice had not thought of that, and now no one wanted to be eaten up.",
"So they all looked at each other, but no one wanted to undertake the task.",
"And so one by one they crept away from the council until only the poor little white mouse remained behind.",
"Now, children, can you tell me the story of the sly cat and the stupid mice?",
"Where did they live?",
"Why, you didn't tell us the name of the house nor where it was.",
"Well, can't you guess?",
"Say somewhere.",
"No.",
"We never can guess anything.",
"No one could guess.",
"I don't believe mice can talk anyway!",
"Yes, they can;",
"I heard one crying one day!",
"That's no proof, but they must have some sort of language, for they understand one another.",
"Well, children, where was the house?",
"O!",
"I suppose here in this one.",
"Most of your stories begin and end here.",
"Why shouldn't they?",
"Johnnie, can you tell me the story?",
"In German or in English?",
"Doesn't matter which.",
"Begin!",
"The poor little mice in a certain house were never safe from a wicked old cat which was always catching and eating them.",
"So they held a meeting to talk over their trouble, and a brown mouse said that it would hang a bell on the cat's neck.",
"No, that's not right, the brown mouse brought the bell, but it was a white one which made the proposal, only it said to hang the bell on the cat's tail.",
"Papa, wasn't that a bad cat to eat the poor little mice?",
"I don't like such cats.",
"Charlie is right, Johnnie.",
"Go on with the story, Charlie.",
"I have almost forgotten.",
"Oh, yes!",
"the mice all thought that the little white one was very clever, and a brown one brought the hell, and a third had found a bit of ribbon to tie it with.",
"Where did it get the ribbon, Elsie?",
"It was dolly's.",
"Somebody must have thrown it on the floor, and then the naughty mice stole it.",
"Does anyone know that somebody?",
"I guess it was Elsie.",
"She often leaves things lying around like that.",
"Well, finish the mouse story!",
"When they had everything ready an old mouse asked if anyone would try to hang the bell on the cat's tail.",
"No one wished to undertake it, for the old cat would turn around, catch and eat them up.",
"The little white mouse was not so cute after all, was it?",
"I wish I had a nice little white mouse.",
"You have your dollies and doll carriage, and lots of other things,",
"I think you have enough, eh, girlie?",
"Now it's time to go to bed.",
"Good night.",
"I'll tell you something else to-morrow night,",
"When I was calling on a friend of mine yesterday, her daughter came into the room looking so pleased and happy that I asked her what had happened.",
"Last Christmas Grandma gave me a beautiful brooch",
"I was of course delighted and took good care of it.",
"But yesterday morning, when I went to church with mother, I wore it, and when we came home it was gone,",
"I was not sure where I had lost it, on the street or in the church, and I had also been walking about in the garden before church began.",
"When Papa heard about it he was very much annoyed, and said that I certainly did not know how to appreciate his mother's kindness, and that when he was a child he would have been severely punished by his parents for such carelessness,",
"it could not have fallen off if I had fastened it properly.",
"My eldest brother, who is at home for his holidays, helped me to hunt for it everywhere, but all our efforts were in vain.",
"You may imagine, then, how delighted I was when my friend Alice called this morning and brought it to me.",
"She had found it on the street near the entrance of our church and recognized it at once as mine.",
"Why, Charlie!",
"You have got your clothes all wet;",
"where have you been?",
"I was out in the rain.",
"It was great fun.",
"Oh, you naughty boy, how angry your mother will be when she comes home!",
"Go to the nursery at once and change your clothes, then you must do your schoolwork.",
"All right;",
"may I put on Fred's coat?",
"my old one is torn.",
"If Fred is willing to lend it, I have no objections.",
"I suppose I'll have to lend it to him, for if I refuse, he will not help me with my arithmetic.",
"I lent you my knife the other day when you broke yours, so you might lend me your old coat till mine gets dry.",
"Come, boys, don't quarrel, but get to your work.",
"Auntie, will you please lend me a lead pencil?",
"I can't find mine anywhere.",
"Have you seen my reading-book?",
"I am sure I brought it home.",
"You may have mine, Fred, I can spell all the words in to-morrow's lesson.",
"You are a very thoughtless boy, Fred.",
"When will you learn to have a place for your things?",
"He would lose his head, I fancy, if it were not fast on.",
"I do really believe he would.",
"You will he surprised to hear that your cousin has gone to Germany.",
"He could not write to you because he is unable to use his right arm well, so asked me to write to you for him.",
"About four weeks ago he met with a rather bad accident.",
"When walking down town at his usual rapid pace he slipped on a piece of orange peel and fell so heavily that he broke his right arm.",
"As we have a very good doctor in our town, your cousin's arm was all but healed in a comparatively short time, but there was danger now that he might get rheumatism in the injured member",
"Dr. Brown advised him to go to Wiesbaden, and take the mineral baths for about a month.",
"I do not think your cousin could have done better than take this advice",
"I myself have tried the baths there, as you know, and they agreed with me splendidly.",
"I remain.",
"Now, Hermann, do make some suggestions.",
"I do not want to attend the University, so am considering what business or profession I should choose.",
"I was hoping that you would have been able to decide on the University, but am glad in any case that you are making plans for the future.",
"One must no longer spend the time in boyish dreams after twenty years of age, you know.",
"Well, now that I have passed my examination I am to go to the country for the summer, but should first like to decide what I shall do in the autumn.",
"You are quite right.",
"Such matters should be decided in good time.",
"What have you thought of yourself?",
"You ought to know best yourself what you are most fitted for.",
"I should, of course, but there is so much that one cannot think of attempting without having had a University training.",
"I might go after all, only I can pass examinations well.",
"You must not imagine anything of the kind.",
"You were able to pass this last examination, and that without having to work hard, as you say yourself.",
"Why not, then, the University examinations?",
"You can do it, of course, especially if you can make up your mind to be a little bit more industrious.",
"It's all very well to say, \"Be industrious.\"",
"Sit over your books the whole day and every day.",
"Now you know that does not agree with me.",
"If I am to keep my health I must have fresh air.",
"After all, I believe it would he best for me to go into some business.",
"The poor old soldier whom we saw in the park yesterday was sent to me this morning by Dr. Brown, who is very anxious that some occupation he found for him.",
"But I really don't know what can he done for him, as the old man is very lame and weak.",
"I had a very interesting conversation with him, however.",
"He was wounded in the leg at the battle of -----, was taken prisoner and remained in prison several months.",
"The prisoners were much neglected and their wounds were not well attended to, so he became very ill and has been lame ever since.",
"He says they were not given enough to eat, nor were they allowed any exercise in the fresh air.",
"It is no wonder, therefore, that the evil effects of his serious wound could not be prevented.",
"Did you hear of the accident down town last night?",
"No, what happened?",
"Was any one hurt?",
"Yes, a horse ran away, and the man, his wife and little boy were thrown out of the sleigh.",
"How did it happen?",
"I hope they were not badly hurt!",
"Dr. Smith's dog ran out of the garden, and barked so furiously at the horse that it got frightened.",
"I wish some one would shoot that ugly beast!",
"Yes, so do I!",
"The man was thrown out of the sleigh against a tree, his left arm broken, his right wrist sprained, and his face covered with scratches.",
"One eye was also injured.",
"Dear me!",
"I hope the woman got off more easily!",
"She did.",
"She was seen to jump before the sleigh was upset.",
"She fell in some deep snow.",
"Her ankle was sprained and her back hurt a little.",
"What about the boy?",
"The brave little fellow kept hold of the reins for a good while after the sleigh upset, but at last was thrown against the sidewalk and his head badly cut.",
"However, the doctor says he will soon be well.",
"I hear you are about to start on a long sea voyage, so I write to give you a few practical hints about life on hoard ship which I fancy will be of service to you.",
"It very often happens that you leave Montreal in fair weather and hardly notice the motion of the ship while on the St. Lawrence.",
"When, however, you come out on the open sea, a wind springs up, it turns cold, begins to rain, and all at once you notice that the vessel is rocking most uncomfortably.",
"Unless you are a good sailor, you will not feel very well, but if such should be the case, don!t let yourself be persuaded to take brandy, for that will only make matters worse.",
"The best thing for you to do, is to lie down flat on your back on a seat or in your chair, and not look at the water but at the sky.",
"Keep perfectly quiet and do not smoke, not even a pipe, but eat good ripe fruit and don't allow yourself to get annoyed at anything.",
"In case you should get worse, and I hope you will not, don't feel ashamed to apply to the doctor, if this should be necessary.",
"No one has ever had to complain of want of attention on board the \"Vancouver\".",
"On the whole you may hope to have a good, safe and even pleasant journey, which I wish you with all my heart.",
"I shall also send you, in a couple of days, the addresses of two or three of my friends, so that when you reach the end of your journey you will not be quite friendless in a strange city.",
"Call upon them at once and I know they will be delighted to do you any favour they can;",
"they are fine fellows.",
"Our voyage was as pleasant as can he imagined under the circumstances.",
"We had sunshine and fair weather nearly all the time, except near Newfoundland, when a fog arose and lasted a day and a half.",
"The captain introduced us to quite a number of the passengers, whom we found very pleasant and sociable.",
"We were, indeed, almost sorry when we arrived in Hamburg on the 15th of July.",
"You remember we had not planned to stop there at all, but some American friends persuaded us to stay a few days.",
"The first day, we went to the famous Alster basin, a kind of pond in the centre of the city.",
"As it was a fine day we decided to have a sail and hired a boat for that purpose, but a wind sprang up suddenly, as is often the case there, and we were glad to let the boatman take us over as quickly as possible.",
"Afterwards we went exploring in the city itself, and, meeting with several Canadians, we went together to visit the Exchange, in which there is always a great crowd of people.",
"In the afternoon we went to the picture gallery and in the evening to the theatre.",
"The two or three days we spent in that city were very pleasant, but of course we spent money as well.",
"We were very careful, however, not to be too prodigal, for if we follow our present plans we shall find plenty of opportunities to get rid of our ready money, and I daresay we shall need more before we get back home.",
"But I must stop.",
"We are off to Berlin by the next train, which leaves in twenty minutes.",
"I have to pack my valise yet and it's ten minutes' walk to the station.",
"Good bye.",
"Good morning!",
"What are you doing here at this early hour?",
"You don't think I am here merely for pleasure, do you?",
"I have to take this five o'clock train for Montreal.",
"That's fine!",
"we can go together, for I am bound for the same place.",
"Allow me to introduce my friends. Mr. Davies — Mr. Arthur, Mr. Rogers — Mr. Arthur.",
"I'm very glad to make your acquaintance, gentlemen.",
"Thank you, the pleasure is mutual.",
"Well, do you enjoy getting up at four in the morning?",
"I don't, but I had to give in to my friends, who were obliged to take this train.",
"They have been stirring around since half past three and woke me up with their racket.",
"Come, old fellow, get up or you'll go without your breakfast.",
"Davies wouldn't miss his for any money.",
"And such a breakfast!",
"No coffee!",
"no toast!",
"cold milk, bread and butter and a little ham.",
"Don't pay any attention to what he says.",
"Rogers and I noticed that he ate his full share, if not more.",
"I can assure you, he won't die of hunger even if he doesn't get any dinner.",
"I know B. of old.",
"He can take care of himself,",
"Say, Davies, have you looked after the baggage?",
"Here comes the train.",
"It stops but a second or two.",
"Where did you put my valise?",
"Does the train start in front of or behind the station?",
"Right here.",
"All aboard.",
"Last winter when I was on the road to visit a friend of mine, who lives on a farm, I met with a kind of accident which is not uncommon in Canada.",
"I was in the company of two friends of mine, and we had hired a handsome sleigh with a pair of fine horses.",
"We were driving at the rate of ten miles an hour.",
"At first all went well;",
"we were flying through the woods and fields, had left a number of villages behind us, and were approaching the railroad track, when unfortunately the train was just coming in.",
"Our horses, which were not used to locomotives, shied, jumped into the ditch and upset the sleigh.",
"Will and I were thrown to one side, but Charles fell under the sleigh, so that he could not free himself without help.",
"When we found ourselves lying in the cold snow, we did not consider our situation very pleasant.",
"The deuce, this might have been a pretty serious affair.",
"Then turning around, he noticed Charlie trying hard to get out from under the sleigh.",
"Halloa, old fellow, what are you doing there?",
"Waiting for you to come and help me out!",
"So we jumped to our feet, and with united efforts lifted it and released him from his dangerous position.",
"I was reading to-day about Otto of Brunswick and Philip of Swabia, father.",
"How did it happen that Otto called Philip his intimate friend?",
"Were they not rivals for the imperial crown?",
"Yes, my son;",
"they were such noble men, and respected one another so much as knights, that the struggle for the crown did not hinder their friendship.",
"How did it come about that there were two candidates at all, then?",
"Henry IV. died without deciding on anyone as his successor, so the two parties, Guelphs and Hohenstaufens, set up these two princes as candidates.",
"After Otto had gained the victory in the struggle, they were reconciled and looked upon one another as the dearest friends.",
"But I thought Philip was taken prisoner by Otto.",
"That is also true, but Otto did not consider him a prisoner.",
"On the contrary, he appointed him to a most important office in his government.",
"Some servants of a rich nobleman wished to rob him of his money, but his faithful gardener was not capable of such a deed and positively refused to help them, although they threatened and flattered him by turns.",
"I could not be guilty of such a theft, and you will be ashamed of it when you remember all his kindness to us all.",
"Our master has always trusted us and it would be contemptible to injure him in this way.",
"You ought to serve him honestly, instead of wishing to take possession of what belongs to him.",
"For my part, I defy your threats and mistrust your promises.",
"Do not venture to rob him, for you know that he is accustomed to shooting and will protect his property.",
"If you persist in your undertaking you will surely die a violent death.",
"Can you tell me the story of the revolt of Switzerland from Austria?",
"Unfortunately, not very much.",
"Why, haven't you read Schiller's William Tell?",
"Yes, but I don't remember much of the real history.",
"Plays do not in general follow history so very closely.",
"That's true, of course.",
"But a play will sometimes help you to remember history.",
"Can't you think of any names?",
"Who are the principal characters in the play?",
"Tell on the one side, Gessler on the other.",
"What was the cause of the revolt of the Swiss?",
"The many cruel acts of which Gessler and his servants were guilty.",
"Can you mention any?",
"A good example is when Gessler caused the eyes of Melchthal's father to be put out.",
"Any other?",
"Did he injure Tell in any way?",
"He is said to have made Tell shoot an apple from his boy's head.",
"Did the Swiss succeed in the revolt?",
"I think they did, but am not certain.",
"Well, I think you had better read up on these history points before the next lesson.",
"I received a letter a few days ago from my friend in Leipzig, in which he says he intends to spend next term at the University in Breslau, because there are too many Americans and English in Leipzig.",
"He declares he has been forced to put off his examination, because it is impossible to become master of the German in such a crowd of English-speaking students.",
"I suppose, of course, he understands the language when spoken, and can express himself very well in ordinary conversation, for he wrote me that he had been introduced into a good many refined families in Leipzig.",
"I think he had several letters of introduction, and he said the American consul had assisted him and been so kind to him, that he had had no difficulty in getting into German society.",
"What he wanted, however, was a closer acquaintance with German students, and that seemed quite impossible in Leipzig.",
"So he wrote that he was going to Breslau, for he had heard that there were scarcely any English or Americans there.",
"That was my experience, too, and I found I had to talk German whether or not.",
"The students at Breslau are very sociable, and famous singers, so that if he joins any of the numerous student societies, he is sure to have plenty of opportunities to learn the customs and life of German students.",
"He says he finds that one must thoroughly know the students to know the professors and their methods, and so much depends on the professor whether a candidate gets through or is plucked.",
"He is undoubtedly right, and I think he is doing a very sensible thing to make the change.",
"Then there is another advantage.",
"The classes there are smaller and each student gets better acquainted with his professors.",
"As I told you on your last visit, mother and I have come to the conclusion that it would he better for us to move to Toronto, although we like this pretty little town so much and have lived in it so long.",
"Last winter mother was troubled so very much with rheumatism that she was laid up for several weeks, and our doctor said we should move away from the lake as soon as possible.",
"If we could find a suitable house in the northern part of Toronto we would move in September.",
"Do you know of any small house which would be likely to suit us?",
"If I were not afraid of giving you too much trouble, I would ask you to look around a little for us, but not further south than Bloor street.",
"We don't require a large or stylish house, but we want one with good heating so that mother need not suffer from the cold.",
"We don't want to have to make on a fire in the grate every day, as was the case in this house last winter.",
"You see what we want is a snug, warm house.",
"Should you happen to know of such a house, would you kindly let us know the proprietor's address so that we may write to him at once.",
"Well, Charlie, what is your lesson for to-day?",
"We had the poem on page 15 to read, to learn by heart and repeat.",
"How many pages had you to write?",
"The first two pages in the new copybook.",
"Open all copybooks",
"Fred, where is your book?",
"Will you please excuse me, Mr, Smith?",
"I lost mine on the way to school this morning.",
"I'll excuse you this time, but don't be so careless in future.",
"George Brown, sit up straight and stop sharpening your pencil.",
"Harry, don't write so badly next time or you shall stay in after school.",
"Now, put away all copybooks and open your readers",
"You may begin to read, Willie",
"read as distinctly as you can and not too low.",
"That will do.",
"Percy, please continue!",
"Read that last sentence over again, you read too fast.",
"That is better.",
"You should pronounce the final syllables more distinctly.",
"Now we'll have some reading in concert.",
"The class please stand!",
"Be careful to pronounce the same word at the same time!",
"That's fine!",
"Take your seats!",
"Now all scholars may go and play.",
"Hearing that my friend was visiting in a neighbouring town and was going to stay for a couple of weeks, I wrote inviting him to visit me too.",
"How astonished I was, then, an hour after sending the letter to the post office, to see him standing before me.",
"He had come intending to surprise me and he succeeded.",
"Our rejoicing at seeing each other was great, as you may guess, for we had not met for many years.",
"Having talked for some time, we took a walk down to the boathouse, hoping to hire a boat and go for a sail.",
"There being very little wind, however, we were retracing our steps when a little girl, catching sight of us, came running up, crying and begging us to get her hat, which had fallen into the water.",
"Convinced that there was no great danger, even for one who could not swim well, as the water was not very deep, I was going to spring in.",
"A boy, standing on the shore, was, however, quicker and got the hat and gave it to the little girl, who, with beaming eyes, thanked him and ran away to her mother.",
"One morning in winter, it was the month of January, I was sitting in my study, busied with my work, when I heard a knock at the door.",
"On opening it there stood before me a little boy clothed in thin rags, looking half frozen and famished.",
"No kindhearted man can bear to see a child suffering from hunger and cold, so I brought him into the warm kitchen at once and, setting him before the fire to warm himself, I ordered the servant to get him food.",
"It was sad to see the large brown eyes looking so eagerly at the meat and other food she brought;",
"and still more, to see him literally swallowing whole with a famished air all that was set before him.",
"After having eaten his fill he began to talk.",
"Born in Italy, his dark complexion and large brown eyes had already betrayed that, he had come to America with his parents, hoping like them to grow rich in that wonderful country.",
"Not long after arriving in New York, however, his father and mother took sick and died, leaving him alone and without money in a strange city.",
"He could play the violin and sing a few Italian songs, but many others were doing the same thing, so he could not earn much money.",
"Then he started out begging.",
"How he longed to get back to sunny Italy!",
"His whole story was told with such an air of innocence that I, fully convinced of its truth, gave him a dollar to help him on his way, hunting up a warm coat for him as well.",
"I had had a good long conversation in Italian and felt I owed him something for that.",
"Having by this time got thoroughly warm, he went away, but not without thanking me repeatedly for my help.",
"People ought not to be surprised at the many adventures that eager huntsmen go through.",
"They look forward so eagerly to the shooting season that, excited at the sight of some fine game, be it deer, bears or anything you like, they laugh at all hardships, will not he warned of dangers, but rush in headlong until it is all but impossible for them to retrace their steps.",
"They are often seen in the most dangerous places, where it would seem almost impossible for them to be saved from destruction.",
"But they are rich in resource, never show any lack of presence of mind, but patiently wait for relief where necessary, and always hope for the best.",
"They can always he counted on never to play the coward, but to determinedly persist in whatever they once undertake.",
"They are noted for their capacity for hard work, their love for sport, kindness to each other, and their pity for those indifferent to their pleasures.",
"What are you laughing at, my friend?",
"Laughing at you, of course, what else!",
"I'm sure, I hope it amuses you.",
"But what is it all about, pray?",
"Well, do you remember joking over an old man in the car on the way here?",
"Well, what of it?",
"There is nothing to wonder at in that, surely!",
"He was a queer fish, wasn't he?",
"Oh, I am not finding fault with you at all.",
"But do you know who he is?",
"No, nor do I care.",
"I don't want to trouble myself about it.",
"But whom do you take him for?",
"Somebody in high position, doubtless, travelling incognito.",
"I know that he is somebody in high position as you guessed.",
"One can always rely on you to discover something wonderful or tell some fine story of what never happened.",
"However that may be, I can see that you are dying of curiosity to know who he is.",
"Well, I don't know that I did anything to be ashamed of.",
"But you might tell what you heard about him.",
"I really hope you won't be worried about it when I do tell you.",
"But I warn you that you will be surprised when you learn the truth.",
"Well, I am glad that you have got something really good this time.",
"Too often your discoveries are very flat and you know it.",
"Don't make a long story of it, that's all.",
"But I would not like to be in your place.",
"I think you'll be more attentive to old men after this, for I am sure he saw you were laughing at him.",
"Come, come, old fellow, I am getting tired of all this mystery.",
"Well, that old gentleman is a member of the government and the very one who will have most influence in making the appointment you are so longing for.",
"Good heavens!",
"That is bad!",
"What will become of me!",
"I'm afraid I have spoiled my chances altogether.",
"By no means!",
"He doesn't know you by name, and when you visit him to apply personally for the position, be careful not to show any embarrassment.",
"He will hardly remember the circumstance and all will he well.",
"Many people think that those who can pay well should be obliged to do so, no matter what may be the real worth of what they have to sell.",
"So when they have dealings with the rich, or still more with those of high rank, they ask a most exorbitant price for everything.",
"An example of this is found in an experience of Emperor Joseph II.",
"Once, as he was on a journey, he had to pass the night at the inn of a small town.",
"The next morning the host made out such a bill, especially for the eggs the emperor had ordered for supper, that he, in great astonishment, asked if eggs were so scarce in that part of the country.",
"The man was honest enough to answer that eggs were certainly not scarce, but emperors very much so.",
"Are you taking much medicine?",
"are you collecting much money?",
"Only mineral water now, your majesty.",
"The French are famous for their politeness, as everybody knows.",
"We find a good example of this in the story of the mayor, who had to make out a pass for a countess, in whose service he was.",
"Now the countess had unfortunately lost an eye in an accident some time before.",
"How was the poor mayor to describe her eyes so as to flatter instead of offending the lady, for she was coquettish as well as rich and influential.",
"Eyes, light, large, beautiful, very expressive, one absent.",
"As might be expected, even the countess had to laugh at the clever idea of the polite mayor.",
"Among other things, he said he rode into the city on the smallest of mules.",
"The king, laughing loudly at his own wit, remarked that it must have been a most amusing spectacle to see an ass riding on a mule.",
"Whereupon Bassompierre made him a deep bow, and answered that that was quite a matter of course, as he was representing his Royal Highness.",
"The perfect dignity and respectful tone of this answer was a strong contrast to the king's stupid, rude remark, and at the same time it punished the royal joker as he deserved.",
"Customs differ in different lands, and it is often very difficult for a foreigner to know just what to do under certain circumstances.",
"In Germany, for instance, the doctor does not in general send in his bill as is done in Canada, but the patient pays according to his rank, as well as according to the reputation of the physician who has treated him.",
"On one occasion, it is reported that the doctor received only five thaler instead of the six he had expected.",
"He let the pieces fall by accident as it were, and then kept on looking for a sixth piece so long, that the patient was forced to take the hint and add it to the five he had already handed the clever physician.",
"Charles II. of England seems to have been very much inclined to joke with his subjects, if one is to believe all the stories told of him, and they are certainly probable enough, judging by his well-known good nature.",
"It is said that he one day asked a certain bishop why he always read his sermon in his presence.",
"To this the bishop answered that a subject should always cast down his eyes modestly in the presence of a king.",
"And might I ask why your Majesty always reads the speeches from the throne in the House of Commons?",
"I haven't the courage to look them in the face any longer, after having asked them so often for such large sums of money.",
"A good constitution is one of the greatest blessings anyone can enjoy.",
"Even doctors will admit that in many cases it is not the medicine but the constitution that saves the patient's life.",
"Of course it would not do to neglect physicians altogether, for every day the science of medicine is making advances, and the advice of a skilled man cannot but be of use.",
"A famous English physician, sitting over his wine, was telling his colleagues the number of patients he had to visit yet before going home.",
"He kept on ordering bottle after bottle, however, until one of his friends got anxious and asked him if he had not better be looking after his sick.",
"It doesn't matter, for some of them have such good constitutions that they do not need me, and I couldn't help the others if I tried, their constitutions are so bad.",
"Beggars who wander about the streets and ask for alms have very often quite wit enough to earn an honest living if they only had the inclination.",
"You saved my life in battle ten years ago",
"The officer, however, declared that he had never seen the man until that day, and inquired how it had happened.",
"The beggar answered that he had followed the officer's example, when he turned to run, and so had escaped with his life.",
"Another beggar asked a millionaire for alms, and the rich man to get rid of him answered shortly that he hadn't a penny.",
"The beggar then produced a penny from some mysterious hiding-place in his rags and offered it to the millionaire",
"Here, my friend, I have two, and will share with you.",
"Military service is not always a very pleasant thing, especially for the recruits.",
"It seemed so dreadful to a certain young Spaniard that he pretended to be deaf, in order not to be compelled to serve.",
"The doctor, suspecting that the deafness was only pretended, ordered him to the hospital, and observed him very closely for several days, but without being able to quite convince himself of the fact.",
"So he thought out a plan to compel the recruit to show from fright that he could hear perfectly well.",
"On one of his morning visits to his patients, he gave orders to the nurse to send the recruit down stairs immediately after him on some message.",
"The doctor was descending slowly and with a very dejected air.",
"The poor fellow, I wonder if it would, after all, be best to tell him that he took poison by mistake, he has only a few hours to live.",
"The young fellow's cry of horror and despair proved to him at once that his suspicion was well grounded, and he told the pretender sharply that he would find an antidote for the poison and a cure for his deafness, too, at the barracks.",
"We rarely find a courtier so quick to decide against a king as once happened with Louis XVI., king of France.",
"He was very fond of chess, and one day as he was playing with a courtier, he got into a dispute with him about a move the latter made.",
"A certain Count Grammont entered the room just at that moment and noticed the general silence as well as the excitement of the monarch.",
"Here is Count Grammont, he shall decide.",
"Your Majesty is wrong.",
"But you do not know what we are disputing about!",
"Oh, that doesn't matter",
"How in the world can you decide without knowing?",
"does your Majesty suppose for a moment that all these courtiers would say nothing if you had the shadow of a right?",
"Most assuredly not.",
"You are a clever judge",
"A famous general, whose name I have just now forgotten, was once sitting in front of an inn-door and was very much annoyed at an old man who kept walking up and down in front of, and staring hard at him.",
"He had a strong desire to punish the insolent fellow in some way, but finally concluded to write some letters and not pay any more attention to him.",
"No sooner had he commenced one, however, than the man went around behind him and began to read over his shoulder.",
"It is a very pretty place where I am stopping, but the beauty of the place is by no means so striking as the impudence of the inhabitants.",
"One, a stupid, ignorant-looking old man, has stared at me until I really could not endure it any longer without having some occupation for my own eyes, and now, if such impertinence is at all credible to you, he is reading this letter over my shoulder.",
"After writing a few sentences more about his journey hither, he glanced around to see how his letter had pleased the old man, but the latter was nowhere to be seen.",
"The Chinese fable given above is only one of a great number of the kind to be found in Oriental collections.",
"A good many of them seem very improbable, and yet in each one there are elements of truth.",
"We know, for example, that people can live on vegetables alone, for many do so.",
"Whole nights may be spent in reflection, but that any one could do so for years without sleeping is not at all credible.",
"It is doubtless true, as well, that the use of tea was due to accident, for that has been the case with many herbs and plants, as for example, the use of the potato.",
"Krummacher tells the following pretty story of the origin of the moss-rose.",
"The angel who cares for the flowers and drops the dew on them in the quiet night, was sleeping one spring day in the shade of a rose-bush.",
"I thank you for your sweet perfume and cooling shade.",
"If you could ask for something more for yourself how gladly I would grant it to you.",
"Then adorn me with a new charm,",
"And the angel of the flowers decked out the most beautiful of them all with simple moss, and there stood in modest dress the grandest of her class, the moss-rose.",
"A soldier in the army of Charles XII was condemned to death by the king, because he had stolen a chicken from a peasant.",
"The condemned man was very angry at this sentence, and in a voice full of rage, accused the king of having also committed a theft, and declared that as he had taken a kingdom instead of merely a chicken, he was much more guilty.",
"The king was very much confused at first by the soldier's accusation, but quietly explained to him that there was a difference between the two cases, inasmuch as he had taken possession of Poland for the sake of his people, while the soldier had taken the chicken from the peasant only for his own use.",
"That the king, however, recognized a degree of justice in the man's comparison, is proved by the fact that he simply ordered the soldier to withdraw and did not have him punished in any way for his breach of discipline.",
"This seems to indicate that Charles XII was a man of larger mind than Frederick the Great",
"Less than your Majesty and with less glory",
"The story of Joseph II. and his minister Kaunitz somewhat resembles that of Louis XVI. and Count Grammont.",
"In both cases the servant was cleverer than the master.",
"With Count Grammont the cleverness consisted in reading from the silence of the other courtiers the judgment they had made, and thus deciding correctly without knowing the facts of the dispute.",
"At the same time he ran less risk of offending his master than as though he had decided against him after hearing all the circumstances.",
"There was also a certain subtle flattery in his proof of how greatly opinions and judgments are influenced by the personalty of a king.",
"With Kaunitz the cleverness consisted in so reading and accenting the emperor's written judgment that the latter could not but see how ridiculous his criticism was.",
"Of the two Kaunitz was the bolder, and quite rightly, because Joseph had been very foolish in his criticism.",
"We can imagine how astonished the emperor was at this striking example of how entirely a change of accent may change the whole meaning of a sentence, but he showed his real good feeling and common sense by laughing heartily.",
"Another emperor of Austria might have accused him of high treason.",
"Lessing's \"Minna von Barnhelm\" is one of the finest comedies in the German language, and must have been a welcome surprise to the theatre-goers of that time.",
"We may well believe the story of the officer who was so pleased with the soldier-piece that he tried to hunt up the author, to thank him personally for the great pleasure he had experienced when he saw the play performed.",
"It must have been, therefore, a very great surprise to the officer when Pastor Gotze, who was Lessing's bitterest opponent, showed him out of the door with no very complimentary words.",
"Of course the officer recognized at once that the friend, who told him Gotze was the author, had been joking with him, and so determined to punish him for it.",
"The latter, too, doubtless took the officer's box on the ear so very good-humoredly because he expected some punishment for his joke and knew he deserved it as well.",
"All who were present must have expected a great scene, probably a challenge to a duel.",
"Oh, you've been there!",
"In many old towns in Europe are to be seen curious objects, such as buildings, towers, walls, which do not seem to have any connection with the life of to-day, but which, on investigation, are found to be very interesting as relics of the past.",
"Now-a-days these old remains are being done away with, much to the disgust of those who like to keep up a connection with former times.",
"Some curious customs are also to be explained in the same way.",
"How strange it would seem to us to visit a town where all the clocks were an hour ahead of time!",
"And yet we are told in old books of travel that this was the case years ago in Basel.",
"Some five or six centuries ago Basel was besieged by a large army and the leader of the enemy decided to make the attack just when the great town bell should strike one in the morning.",
"A faithful guard heard the bustle in the enemy's camp and also by accident the hour when the storming was to begin.",
"What could he do to prevent the attack?",
"Why, if the enemy should not hear the clock strike one, of course they would not make the attempt.",
"So he at once set the clock so that it would strike two.",
"The plan succeeded perfectly:",
"the enemy thoroughly deceived withdrew, and the town was saved.",
"In memory of this deliverance the clocks were always kept an hour too fast, and moreover, a statue of the guard was set up in the marketplace.",
"It is a very interesting study to compare the customs of different peoples, and also to trace the changes in customs among any one people from century to century.",
"Even to-day the little children who attend the schools for the poorer classes in Germany have to be in their places at 7 a.m.",
"In the universities, too, lectures are often given at the same hour, though generally only in summer.",
"Eight o'clock in winter is, however, a regular hour for all university classes.",
"In the Middle Ages work began even earlier, as we learn from history, and no one was allowed to lie in bed until eight or nine o'clock in the morning, as so many do now-a-days.",
"If scholars had to go to six o'clock classes, they would of course have to have their breakfast still earlier, and we are told that a light breakfast was in fact eaten before six a.m., then a good meal was taken about ten, and the principal one about four p.m.",
"These would then correspond to our breakfast, dinner and supper.",
"Getting up early and early meals compelled early retiring, so that eight in the evening was quite late in the opinion of our forefathers.",
"Students who are fond of such studies will also find plenty of interesting material to engage their attention in the history of the theatre.",
"For instance, why is a matinee given in the afternoon?",
"These and all such questions belong to what the Germans call \"Kulturgeschichte\" the study of which is indeed very attractive.",
"When a person in high position, such as a governor or prince of the church gives a dinner, the invitation is generally accepted, for it is almost equivalent to a command.",
"Not only is the invitation not declined, but it is necessary to appear punctually at the hour named.",
"No wonder then, that the guests of Napoleon's uncle, Cardinal Fesch, wondered very much one day when they were kept waiting a long time.",
"At last one ventured to ask the cardinal if other guests were expected.",
"The answer was in the affirmative.",
"Of course they tried to wait patiently, but at last some one suggested that the expected guest must be ill or have met with an accident.",
"Count Boville would send an excuse in such a case",
"Oh, but, your eminence, Count Boville has been dead six months.",
"Why, that is really too bad!",
"Let us go to dinner at once, and imagine that our friend is in our midst.",
"How did the cardinal make that mistake?",
"Well, he lived in retirement and never read a newspaper.",
"Perhaps when we think of the newspapers of those days, we will not blame him.",
"The peasants in Holland are noted for their sharpness, and the landlady mentioned in the preceding anecdote was no exception.",
"She made the pretended artist, who came to her inn, prove to her that he was able to play the flute well enough to earn money before she would consent to make him the tart his servant had ordered from her.",
"It would seem that the king, for so he was, was travelling incognito, and it is quite possible that the good woman had been cheated out of her money by some unknown traveller, so that she was unwilling to be deceived again.",
"At any rate, for some reason or other, she was very distrustful.",
"It is said that the king was greatly amused at her request, and he knew as well as anyone how to appreciate her caution, for he had also learned to try people before trusting them.",
"Princes and rulers have in all ages taken great pleasure in travelling around disguised, and in this way getting the opportunity of laying aside the burden of court etiquette.",
"Of no one are more stories told in this regard than of the late Emperor Frederick, who seems to have been the soul of kindness and was always helping some unfortunate just at the right moment, and without the latter knowing from whose hand the help really came.",
"It is therefore easy to understand why \"Unser Fritz\" was so popular among the people.",
"O you most perverse creatures, when I piped you would not dance, but now that I have ceased you do so merrily.",
"If you would only spare my life, I would be sure to repay your kindness.",
"You ridiculed the idea of my ever being able to help you, not expecting to receive from me any repayment of your favour",
"now you know that it is possible for even a Mouse to confer benefits on a Lion.",
"You foolish old fellow!",
"If you had as many brains in your head as you have hairs in your beard, you would never have gone down before you had inspected the way up, nor have exposed yourself to dangers from which you had no means of escape.",
"The Physician, time after time, applied his salve to her eyes, and on every visit taking something away, stole by little and little all her property",
"The old woman, when she recovered her sight and saw none of her goods in her house, would give him nothing.",
"This man here speaks the truth in what he says; for I did promise to give him a sum of money, if I should recover my sight",
"Now he declares that I am healed.",
"I on the contrary affirm that I am still blind",
"when I lost the use of my eyes, I saw in my house various chattels and valuable goods",
"though he swears I am cured of my blindness, I am not able to see a single thing in it.",
"My master gives a feast;",
"you will have unusually good cheer;",
"come and sup with me to-night.",
"How glad I am that I came!",
"I do not often get such a chance as this.",
"I will take care and eat enough to last me both to-day and to-morrow.",
"Why, to tell you the truth, I drank so much wine that I remember nothing.",
"I do not know how I got out of the house.",
"Uninvited guests seldom meet a welcome.",
"Why do you howl so fearfully?",
"I will tell you, but first let me ask you to hold my clothes, for I wish to leave them in your hands.",
"I know not, sir, when I got this habit of yawning, nor whether these attacks of howling were inflicted on me as a judgment for my crimes, or for any other cause",
"but this I do know, that when I yawn for the third time, I actually turn into a wolf, and attack men.",
"Pray wait, sir, and hold my clothes, or I shall tear them to pieces in my fury, when I turn into a wolf.",
"you live here the life of the ants",
"while in my house is the horn of plenty.",
"I am surrounded with every luxury, and if you will come with me, as I much wish you would, you shall have an ample share of my dainties.",
"Although you have prepared for me so dainty a feast, I must leave you to enjoy it by yourself.",
"It is surrounded by too many dangers to please me.",
"I prefer my bare plough-lands and roots from the hedge-row, so that I only can live in safety, and without fear.",
"Shall I get to hear some stories now?",
"To-night we have no time for that",
"Just look at the Chinese!",
"We must have the whole world finely brushed up for to-morrow",
"To-morrow is Sunday, you know",
"I want to visit the church towers to see whether the little church-elves are polishing the bells, that they may sound pretty.",
"I want to go out into the fields and see whether the wind is blowing the dust from grass and leaves, and, what makes me most work, I want to take down all the stars to polish them.",
"I take them in my apron",
"Here!",
"do you know, Mr. Sandman?",
"I am Frederick's great-grandfather",
"I thank you for telling the boy stories, but you must not spoil his ideas.",
"The stars cannot come down and be polished!",
"The stars are great globes just like our earth, that is just what is fine about them.",
"you are of course the head of the family, you are the ancient head, but I am still older than you!",
"I am an old heathen.",
"The Romans and Greeks called me the dreamgod.",
"I have gone into the most distinguished houses, and go yet.",
"I know how to get along with the small as well as the great.",
"How you can tell!",
"Now one won't dare to tell his opinion any longer at all, I suppose",
"Some one is dying",
"O take me with you;",
"I know you will go away when the match burns out",
"you will vanish like the warm stove, the roast goose, and the large, glorious Christmas-tree",
"She tried to warm herself",
"I am already aged, and my death is nigh, and I have wished to take thought for you before my end",
"money I have not, and what I have now given you seems of little worth, but all that is wanted is that you should turn it to account with good sense.",
"Only seek out a country where such things are still unknown and your fortune is made.",
"Look!",
"what a proud creature!",
"it has a ruby red crown upon its head, and wears spurs like a knight;",
"it calls you at night three times at fixed hours, and when it calls for the last time the sun soon rises.",
"But if it crows by broad daylight, then take notice, for there will certainly be a change of weather.",
"A mere trifle for such a precious creature!",
"Well, I will go out and see whether I cannot get rid of my scythe as nicely.",
"Miou! miou!",
"No, no!”",
"Now, she must give way to force.",
"Cannon were brought out, and the palace was soon in flames.",
"I have a daughter who can spin straw into gold.",
"That is an art which pleases me well",
"if your daughter is as clever as you say, bring her to-morrow to my palace and I will try what she can do.",
"Now set to work, and if by to-morrow morning early you have not spun this straw into gold during the night, you must die.",
"Good evening, Miss Miller",
"why are you crying so?",
"Alas, I have to spin straw into gold, and I do not know how to do it.",
"What will you give me, if I do it for you?",
"What will you give me if I spin the straw into gold for you?",
"You must spin this, too, in the course of this night",
"but if you succeed you shall be my wife.",
"I could not find a richer woman in the whole world.",
"What will you give me if I spin the straw for you this time also?",
"I have nothing left that I could give,",
"Then promise me, if you should become Queen, your first child.",
"Who knows whether that will ever happen !",
"Now give me what you promised.",
"No, anything living is dearer to me than all the treasures in the world.",
"I will give you time for three days,",
"if before then you find out my name then shall you keep your child.",
"That is not my name.",
"Perhaps your name is Shortribs, or Sheepshanks, or Laceleg?",
"To-day I take, to-morrow brew,",
"The next I'll have the young Queen's child.",
"Ha!",
"So, Madam, Queen, what is my name?",
"Is your name Conrad?",
"Is your name Harry?",
"Perhaps your name is Rumpelstiltskin?",
"A witch has told you that!",
"Tin soldiers!",
"That is the wife for me,",
"she is too grand, and lives in a castle, while I have only a box to live in, five-and-twenty of us altogether;",
"that is no place for her.",
"Still I must try and make her acquaintance.",
"don't wish for what does not belong to you.",
"Very well;",
"wait till to-morrow, then,",
"Here I am",
"Look, there is a tin soldier.",
"He ought to have a boat to sail in.",
"Where am I going now?",
"This is the black goblin's fault, I am sure.",
"Ah, well, if the little lady were only here with me in the boat, I should not care for any darkness.",
"Have you a passport?",
"give it to me at once.",
"Farewell warrior!",
"I declare!",
"here is the tin soldier.");

function firstGermanLine()
{
	global $german1lines;
	return $german1lines[array_rand($german1lines)];
}

?>