<?
// https://archive.org/details/firstyeargerman03collgoog/page/n6
// First year German
// 1905

	$german2lines = array(
"Drink, pretty creature, drink",
"Stand not upon the order of your going, but go at once.",
"How sweet the moonlight sleeps upon this bank!",
"Birds sing;",
"you read.",
"My sister's small birds sing sweetly in the morning.",
"I fold the paper.",
"he gave me the book",
"George is a farmer;",
"Lincoln was elected president",
"the workmen are busy;",
"those men are reputed wise.",
"the sun shines by day",
"The boy bats the ball",
"It rains and the wind is never weary.",
"We hastened home when the clouds began to gather.",
"A man who is honorable is respected;",
"We go in when it rains;",
"That my friend has lost his watch is certainly true.",
"He throws the ball.",
"John throws his ball;",
"see the queen's crown.",
"John throws the ball to him.",
"I am loved, I shall love, I shall have been loved,",
"James struck John",
"John was struck by James.",
"Roses bloom;",
"why do you smile?",
"Though he slay me, yet will trust in him.",
"Draw your swords",
"Give me oh thy bark, O birch-tree.",
"Seeing is believing",
"to see is to believe.",
"I love, I loved, I shall love.",
"I shall have loved.",
"Knowing the candidate intimately, we shall not hesitate to vote for him.",
"You are loving, he was loving.",
"My brother has found my ring.",
"Has thy brother lost his ring?",
"His brother has found my ring.",
"His brother has lost and found his ring.",
"His brother has found the cane.",
"Thy brother has not found his cane.",
"The brother has found the cane.",
"Has thy brother found my ring or my cane?",
"My brother has found thy ring, not thy cane.",
"His brother has lost his cane and my brother has lost my cane.",
"Hast thou lost thy ball to-day?",
"Have you lost your ball to-day?",
"No, I have not lost it.",
"I did lose it yesterday, but I found it again.",
"Did he see this ring or that one?",
"Who bought and ate an apple to-day?",
"Have you received a letter to-day?",
"No, but I received one day before yesterday.",
"Charles, what have you received?",
"Have you received a letter?",
"Yes, I have received this one.",
"I have looked for you and your brother.",
"I have not looked for anything.",
"My brother Charles found your ball yesterday morning.",
"Has your tailor already made your coat?",
"No, he has not yet made it.",
"Who bought this dog?",
"My father or my brother bought it this morning.",
"Did you find or lose a cane to-day?",
"I lost a cane yesterday, but to-day I found one.",
"Where did you see a bird yesterday",
"Yesterday I saw a bird on a tree in the garden; to-day I looked for it again, but I have not yet found it.",
"Have you brought something for me this morning?",
"Yes, I have brought you an apple; the gardener gave it to me.",
"Day before yesterday he gave me one",
"I ate it on the playground with my brother",
"I gave him a part.",
"Where did you see the gardener?",
"I saw him in the garden with the tailor.",
"I have been looking for Charles's friend this morning.",
"Yesterday I bought something for him and his brother.",
"Where hast thou been playing to-day, Karl?",
"I often looked for thee, but did not find thee.",
"I have been playing in my father's forest with my cousin.",
"I saw a bird there on a tree.",
"I have seen one on a tree in my uncle's garden.",
"To-day I looked for it again, but no bird did I see there.",
"Have you the bread and the water?",
"No, I have no bread and no water.",
"I have eaten the bread and drunk the water.",
"This girl has my knife, that man has my ring.",
"From the window of my house I saw a child in the garden.",
"I played with him and lent him a book.",
"He has not yet returned it to me.",
"Has he given it to that girl?",
"My mother lost her watch in the street yesterday, but Mrs. Brown's daughter found the watch and returned it to her.",
"Where is that woman's child?",
"It is still in the street",
"it has been in the street this morning.",
"The child and its mother are in the street of the town.",
"To whom does this knife belong?",
"It belongs to my sister; her friend gave it to her.",
"Does this book belong to you?",
"No, it belongs to my sister's friend; but Mrs. Brown lent it to me.",
"Your friend has a flower in her hand;",
"her brother found it yesterday and gave it to her.",
"the woman talks kindly with the child and praises his work.",
"Do this hat and cane cost very much?",
"Yes, they cost just as much as that ring.",
"Henry, where do you live?",
"I am living in yonder a village not far from the city.",
"What are you looking for?",
"You are always looking for something.",
"I am looking for my hat.",
"Here it is; I found it on the playground.",
"I always play there.",
"The child is playing here.",
"Henry, what do you give this child?",
"I am giving him a glass of water.",
"What does he give you?",
"He has given me a pear; you see, I am eating it already.",
"Where has your neighbor been?",
"He has been in the forest or in the market.",
"He works in the village and he always sleeps there too.",
"My neighbor is making a chair for me in yonder room.",
"You speak of your neighbor's work.",
"Please give the child a slice of meat or a piece of bread and butter to eat, and fetch him also a glass of water, for he is hungry and thirsty.",
"What are you bringing the child to eat?",
"Do not give him an apple, for he is not hungry.",
"Make haste, Charles, and bring the child something to eat",
"Have the goodness to see where your brother is.",
"See, there he is;",
"speak kindly to him.",
"Please give him this book.",
"Praise his work and his kindness.",
"Look for his ball; he lost it in the street.",
"Please have the kindness to look for it.",
"Whither does the brooklet hasten?",
"It hastens through the valley and the forest",
"Why is it not willing to stay and play with the child?",
"It has to work",
"accordingly it cannot stay with the child.",
"It is obliged to water the flowers.",
"It must turn the mill-wheel.",
"The little sheep are thirsty.",
"We are to bring water from the spring.",
"Make haste and bring the water.",
"Yes, we are just going to fetch it;",
"we have to work as hard as the brooklet.",
"Bind your foot to my foot and I will swim over.",
"Mouse, do not bind your foot to the frog's foot.",
"Frog, do not drown the mouse.",
"O break not, bridge, that tremblest so!",
"O fall not, rock, that threat'nest woe!",
"Earth, sink not down; thou Heav'n, abide",
"Until I reach my loved one's side",
"Yesterday I saw the sons of my cousins;",
"they came out of the house with their dogs and went to the playground.",
"They had rings, balls, and sticks.",
"Where were their coats, hats, and books?",
"My brothers saw apples on trees in the gardens where girls were playing.",
"They saw birds in the woods and fields, and men, women, and children in the villages.",
"We were accustomed to make excursions into the valleys.",
"The count's soldier has given the boy a raven.",
"remain at home",
"so far as I know",
"They came on foot, so far as I know, for they have no horses.",
"But we saw boys on the street on horseback.",
"Are those boys your sons?",
"No, those boys are the sons or nephews of the count's messengers.",
"They are going with the soldiers to the count's castle.",
"These boys are allowed  to play with Mr. N's nephews.",
"The brothers of those gentlemen are my friends;",
"are they your friends also?",
"Your mother gave my friends flowers to carry in their hands.",
"These watches belong to my sisters' friends.",
"Many men were in the streets of the city with their sons, many mothers were at home with their daughters.",
"Soldiers were coming through the streets of the city on horseback, boys were coming on foot.",
"The messengers of the count and of the prince were hastening on foot and on horseback.",
"Give me an apple or a pear to eat.",
"I have no pears, but here are apples.",
"The mice wanted to swim, but they could not.",
"Accordingly they begged the frogs for help.",
"How did you boys come into this village, on foot or on horseback?",
"We were obliged to come on foot, for we have no horses.",
"Whither are you going, into the country or into the mountains?",
"We are making an excursion into the country.",
"The mountains are too far from here.",
"I see you have there a knapsack.",
"Did you carry it in your hand?",
"What have you in the knapsack?",
"something to eat and drink?",
"Something to eat, but nothing to drink.",
"We intend to drink water, but we are not thirsty yet",
"Good luck to you!",
"she was with her mother.",
"Money rules the world",
"I accustom myself to country life.",
"We accustom ourselves to city life",
"They accustom themselves to their tasks.",
"The mother called her daughters to her.",
"We called our sons to us",
"Have you hurt yourself, William?",
"No, I have not hurt myself, but Henry has hurt himself.",
"Do not hurt yourselves, my children.",
"Are the boys in the house?",
"No, they are not in it.",
"Are the books on the tables?",
"Yes, they are on them.",
"Mr. Smith is very rich, but his nephews in this city are poor; therefore he is ashamed of them and pretends not to remember them,",
"Be ever true to thyself",
"the horse has trodden on the boy's foot.",
"I rejoice that you are well",
"We rejoice that he is well.",
"Did you remember me?",
"Does she remember him?",
"Do you remember them?",
"I remember you very well, but not them.",
"We rejoiced to be there",
"I myself saw the king and queen on horseback.",
"Were you yourself there, and did you see the king and queen themselves?",
"Do you still depend upon your servant?",
"No, I depend upon myself.",
"This woman is ashamed of her friend and pretends not to see her.",
"My hands and feet ache.",
"somebody knocks",
"the bell rings",
"I am sorry",
"it causes me sorrow",
"there were once three brothers.",
"it is my sister.",
"they are my brothers.",
"this is my sister",
"those are my brothers",
"his nephews were poor but they are so no longer.",
"the mouse wanted to swim, but could not do it.",
"if you please",
"Take a glass of water.",
"With pleasure, for I am thirsty.",
"Take another cup of tea.",
"No, I thank you, I have already had two.",
"Do you prefer a cup of coffee?",
"No, give me another glass of water, if you please.",
"These are their three friends.",
"There were once three kings.",
"Two kings are now in the city.",
"How are you, my friend?",
"It was you; it was she.",
"He was sorry.",
"William goes into the room.",
"William remains in the room.",
"William goes to and fro in the room.",
"where?",
"whither?",
"Emma, seat yourself before the table.",
"I am going to place myself behind it.",
"There she sits before the table.",
"Here I stand behind it.",
"Where am I to lay these books?",
"Lay them on the chair or on the table.",
"Two are lying on it already.",
"Go to the door, Louisa, the bell rings.",
"No, somebody knocks.",
"Louisa went out of the room.",
"Mr. Smith comes into the room.",
"He has a book in his hand.",
"He has been reading in it, has he not?",
"Place the chair between the window and the table.",
"The dog lies under the table.",
"Charles and Louisa are sitting at the window.",
"I stand beside them, beside him, beside her.",
"Go into the country.",
"In winter it is too cold, but in June it is glorious.",
"On Monday William was sick, and had to remain in bed.",
"we live on Frederick Street.",
"To-day is Saturday; on Sunday we must go to church.",
"Were you at church a week ago?",
"We went to school on Thursday and on Friday.",
"Emma and Louisa, when do you intend to go into the country?",
"We intend to go there at the end of April or the beginning of May.",
"How beautiful it is in the country in summer!",
"Then one hears the singing of birds.",
"I like better to be in the country in spring and autumn; in spring one finds so many flowers; in autumn how beautiful the mountains and woods are!",
"As early as the beginning of April William had found flowers.",
"I shall find some flowers.",
"I shall have found some wood before winter.",
"it does not matter",
"We had seen;",
"you will have read;",
"they had eaten.",
"It is getting late, isn't it, Henry?",
"No, William, it is not yet late.",
"I think we shall come home too late.",
"I am getting hungry and soon I shall be thirsty.",
"Mother will give us something to eat.",
"Have you much wood?",
"It is getting cold.",
"We shall be a long time away from home.",
"In a week we shall have made the journey and shall be at home again, tired and hungry.",
"he had already gone to the city before the concert",
"before the beginning of November all the birds will have gone.",
"A brook flowed not far from our house through the village.",
"It flowed through the fields from the foot of a mountain.",
"It had been only a brooklet; it became a brook.",
"William, whither did you journey a week ago?",
"I traveled to Boston and remained there eight days.",
"Had you already been in Boston?",
"I had been there and had stayed a long time with friends.",
"The hares have run into the woods.",
"The bird has flown into a tree.",
"The father has come home.",
"The boy will have become a man.",
"I remember neither the king nor the queen.",
"I depended upon myself, you depended upon yourselves.",
"The man is ashamed of his sons.",
"The boys went into the country a week ago.",
"A week from to-day I shall be in the country.",
"At the end of summer the birds will have flown away.",
"At the beginning of summer we shall hear the singing of birds.",
"On Saturday the girls went to the theater, on Monday they went to school.",
"Those men are accustoming themselves to country life.",
"A boy fell from a tree and hurt himself.",
"I am fond of coffee, but I prefer tea.",
"Are these your sisters?",
"It is my dog;",
"it is his pear;",
"it is her knife.",
"You have hurt your finger.",
"That doesn't matter.",
"Just see!",
"a hawk has caught a sparrow and is going to eat it.",
"A dove flies on to the roof of a house.",
"I like sparrow, but this one is too lean, I prefer dove.",
"I will catch the dove and eat her.",
"Away he flew to catch the dove, but she hid under the roof, and no dove could Mr. Hawk find.",
"He had lost the sparrow, for a cat had eaten it",
"Sparrow is very good.",
"I have received fine long letters from your friend's daughter.",
"These books are old, not new.",
"Do you buy only old books?",
"No, I buy new as well as old ones.",
"I am fond of reading in old books; I read old books with pleasure.",
"Do you often write long letters?",
"No, but I like to receive long letters.",
"I am sorry that your eggs are not fresh;",
"you have neither fresh eggs nor good bread.",
"I can bring you a glass of cold water.",
"Thank you, I should like something to eat.",
"Here are two fine pears; there are more ripe pears on the table.",
"The son of the old gardener has broken his left leg.",
"A poor boy, the son of our old gardener, has lost his new knife.",
"I am sorry for him.",
"This house is large and splendid.",
"This house is a large and splendid one.",
"These are large and splendid houses.",
"Does your friend live in a large, splendid house?",
"He lives in a large but not a splendid one.",
"Who lives in those large, splendid houses?",
"Those big houses belong to rich men.",
"I don't want to live in them.",
"Here is a sad letter from your dear mother.",
"We are sorry for her.",
"Have you read your dear father's long letter?",
"the old man spoke",
"the people spoke.",
"the young should listen to the old.",
"nothing pretty.",
"No relatives of ours live here.",
"That is a foreigner; I think it is a German.",
"There are many strangers here.",
"That pretty lady is a stranger.",
"The parents of those strangers are said to be rich.",
"Has your mother given you anything pretty as a present?",
"She is going to give me a new knife as a present;",
"I have only an old one.",
"I have not much good bread;",
"you have said much good of him",
"this house has eight beautiful windows.",
"I have nothing new or fine.",
"What have you in your hand?",
"I have a small, sharp knife in my hand.",
"My knife is small and sharp.",
"Two relatives of mine are going on foot to a small village.",
"Are there friends of yours in the inn?",
"No, there are only strangers in the inn.",
"Your hat is black, mine is brown.",
"This hat is mine.",
"To whom does this hat belong?",
"It is mine.",
"Are your brothers ill?",
"No, no one of them is ill.",
"I have lost a pretty book; have you found one?",
"No, I have not seen one.",
"Max has lost his also.",
"Emma is reading in hers.",
"We shall all read in ours soon.",
"Accordingly all read in theirs.",
"My pen writes badly; may I write with yours?",
"Certainly, write with mine;",
"here are my pens, where are yours?",
"I have found ripe pears under this tree.",
"I find none; I find neither pears nor apples.",
"my aunt will make a warmer dress for the oldest daughter of this poor woman.",
"The tree in front of our house is higher than the one behind it.",
"It is also bigger and handsomer.",
"Your coat is thicker and warmer than mine, isn't it?",
"It is thicker, but not so warm; Max has the thickest and warmest coat.",
"Is Max the most diligent boy in the school?",
"No, but he is the oldest boy in the school and also the tallest;",
"he is much taller than Edward.",
"William is the youngest boy, Emma the youngest girl.",
"She is younger than her sister.",
"This mountain is higher than that tower.",
"the weather is finest in June.",
"Charles writes well, William writes better, but Emma writes the best.",
"please",
"This lady sings beautifully; she sings the most beautifully of all.",
"The days are already too short; they are shortest in winter.",
"In spring the days are shorter than in summer.",
"I can work best in summer.",
"This tree is as tall as that one.",
"Your brother is older than I.",
"you know.",
"surely.",
"What time is it?",
"it is one o'clock.",
"What day of the month is it to-day?",
"It is half past two;",
"it is 20 minutes to 3.",
"It is more than a quarter to five o'clock.",
"It is already ten minutes to six.",
"How much is 11 times 17?",
"What day of the month was yesterday?",
"To-day is the 16th of the month, isn't it?",
"No.",
"What is it then?",
"Comrade, get up; it is already late.",
"I cannot get up yet; I am too sleepy to get up.",
"But the train leaves at eight o'clock;",
"I got up an hour ago.",
"thank you very much",
"The wind and the rain are ceasing.",
"The wind and the rain have ceased; they ceased yesterday at half past three.",
"Charles, please open the door.",
"He opened the door;",
"he has opened the door.",
"Thank you, Charles.",
"Get up, my son, you must start for school.",
"It is time to start for school.",
"The boy washes his face and starts for school.",
"He started for school at ten minutes to nine,",
"Open the book and read to me, if you please.",
"The boy was to have learned his lesson, but he was too lazy and did not want to; in the end, however, he was obliged to learn it.",
"well, no doubt",
"Miss M. sings very beautifully.",
"Have you heard her sing?",
"We saw you run across the field yesterday.",
"You were to give me a mark day before yesterday.",
"Yes, I wanted to give you one, but I was not able to;",
"I could not get any money.",
"We are to learn our lesson this evening;",
"they will learn theirs now.",
"The boys were to have learned their poems by heart, but they did not wish to.",
"We have not been well and so have been obliged to remain at home.",
"Who will help that boy learn his lesson?",
"My brother helped him do his lesson yesterday.",
"My brother Fritz has not been allowed to put his new hat on to-day, because it is so windy",
"I did not like to put mine on, because the wind blew it off my head yesterday, so that I could scarcely catch it again.",
"I am not allowed to put my new hat on, and he must not put his on.",
"Why must he not put his on?",
"Because it is so windy.",
"I have not been allowed to",
"because I have not been allowed to.",
"You have not put your new coat on; why not?",
"I did not like to.",
"Because I did not like to.",
"I did not like to put it on.",
"Because I did not like to put it on.",
"It fits me so badly that I cannot put it on.",
"Your boots are quite wet, Charles; take them off at once.",
"Is there no book on the table?",
"No, there is none there.",
"I value this man highly;",
"I value another more highly;",
"I value you most highly.",
"You speak very wisely;",
"you speak more wisely than others;",
"you speak most wisely.",
"I have helped him do his lesson.",
"turn round",
"A great king once had a prying page.",
"I will try a pinch,",
"But the king had heard a little noise.",
"My mother has had a warm winter dress made for this poor woman, because she is dressed so poorly",
"she will be obliged to get warmer clothes made also for her eldest daughter, for she is clothed still more poorly than her mother.",
"Who has had a warm dress made for this poor woman?",
"My aunt has had a warm dress made for her.",
"For whom has your aunt had a warm dress made?",
"For the eldest daughter of this poor woman.",
"What has your aunt had made for the woman's eldest daughter?",
"Why has your aunt had a warm dress made for this woman's eldest daughter?",
"Because she is dressed most poorly.",
"Because it is so cold now, my mother has had warm clothes made for this poor woman and her two eldest daughters.",
"I went into the kitchen and had some bread and butter given to this poor boy;",
"he thanked me",
"I shall enjoy it very much, for I am hungry.",
"are you fondest of, black or green?",
"There lies a thimble under the chair.",
"Indeed!",
"what kind of one?",
"have you any news?",
"why need he tell lies?",
"which picture do you admire most?",
"with which of these pens do you write?",
"What a difficult lesson my teacher has given me!",
"What sort of one has he given you?",
"What a beautiful long letter you have written to me!",
"What color has the rose?",
"What book did you read yesterday?",
"Whose eye watches over men?",
"What feelings did you have?",
"I rejoice to be rid of my lazy servant.",
"With what horses do you drive to the town?",
"Which are your things and which are mine?",
"You are rid of him.",
"My nephew will answer the long letter, the contents of which have given him so much joy, before I have returned from my walk, which I am just going to take.",
"I cannot tell you the name of the lady who inquired after you to-day.",
"that is the knife with which I cut my hand.",
"this is the carriage in which we came to-day.",
"Before we have returned, our nephews will answer the long letters, the contents of which have given them so much joy.",
"Has he answered the long letter?",
"Not yet, but he will answer it before you have returned from your walk.",
"She did not answer me, when I called her.",
"The hat which pleased you so much I bought at a bargain.",
"My parents, whose letters I have read to you, will return soon.",
"Give me some paper on which I can write, if you please.",
"Here is the book of which I spoke.",
"All I have shall be thine.",
"This is the best we can do.",
"He brought me the book, a circumstance which gives me much pleasure.",
"nothing he has heard",
"he who will not hear must feel.",
"what you can do to-day, do not put off till to-morrow.",
"I cannot tell you who asked after you to-day.",
"do you know who lives in this house?",
"That which he has related is true.",
"The room you slept in is too cold.",
"Everything that lies on the table is mine.",
"I will give you the prettiest I have.",
"He told me a secret which he had just heard.",
"He told me what he had just heard.",
"The singer does not remember her song, which is very strange.",
"He told me whom he became acquainted with on the journey.",
"I praise him",
"he is praised by me",
"I praised him",
"he was praised by me",
"he had been praised by me",
"I shall praise him",
"he will be praised by me",
"he will have been praised by me",
"praise him",
"he must be praised by me",
"This palace was sold in the year 1845.",
"It had been built by Prince B.",
"An older palace, which had been destroyed by fire, once stood in the same place.",
"These new houses will be sold, because the owners are now poor men.",
"After the old palace had been destroyed by fire, a new one was built in the same place.",
"The palaces which were sold had been built by Count A.",
"The palaces had to be sold.",
"The exercises had been improved by the teacher.",
"stop",
"this house was furnished in 1870.",
"the clock is always wound up by him.",
"the house was well furnished.",
"the clock is already wound up.",
"My watch is broken, because my brother let it fall.",
"This mirror was broken the other day;",
"do you know by whom it was broken?",
"These clocks are generally wound up after breakfast, are they not?",
"Here is the key;",
"shall I wind them up?",
"No, thank you, they are already wound up.",
"Letters must be written to your mother at once.",
"My letters home are already written, which gives me great joy.",
"The house which is now occupied by Mr. S. was built by his grandfather in the year 1802.",
"It was afterwards greatly improved by the present owner, who had become a rich man.",
"It was surrounded by him with a very beautiful garden.",
"It is surrounded by a very beautiful garden.",
"it is a great pity",
"He was ordered to go.",
"The ring has been found.",
"Nothing can be done.",
"There is much buying and selling.",
"The money will be found.",
"The boy was not helped.",
"Will the poor woman be helped?",
"Pieces of money were picked up in the woods.",
"The robber must be obeyed.",
"It may be hoped.",
"Much can be said about the boy and the robber.",
"An old house is not easily sold.",
"Although I have now been a week in this place, I could go out only yesterday for the first time.",
"While my brother was writing letters for me, I took a walk through the town and then went to the Museum;",
"to-morrow I shall return home.",
"Who has arrived?",
"It is probably your sister.",
"we shall skate next winter.",
"How long has he been in the town now?",
"He has now been here a week, but he has not as yet seen very much.",
"Have you been writing letters for him the whole morning?",
"I have been writing letters now for four hours.",
"Did they take a walk through the town or into the fields?",
"They took a walk into the fields and went as far as the village.",
"When I was in Italy, I saw many beautiful pictures.",
"I suppose the poem is known to you.",
"To-morrow I shall go to town to see the Museum;",
"will you go with me?",
"The books you lent me are extremely interesting.",
"Where is the pen you wrote with?",
"What can be believed of all that he relates?",
"What have you been playing with this whole morning?",
"What sort of flowers shall I buy for your cousin?",
"The worst the soldiers told us of the battle is true.",
"Tell me which are friends and which are enemies.",
"it was cold",
"Has it been cold?",
"It will be cold tomorrow",
"it would be cold tomorrow",
"I asked a gentleman what time it was.",
"He replied that he did not know, for he had lost his watch.",
"A gentleman asked me if I knew when the train left.",
"I asked my friend if she had been in Berlin; she replied that she should go soon.",
"I asked him if he were going to-morrow.",
"He replied that he was very sorry, but he should be obliged to go,",
"they thought the man was rich,",
"people feared the city had been taken,",
"he hoped still his son would return,",
"I know that he has a watch,",
"it is known that Fritz will come,",
"he says that he is sick",
"I do not vouch for the fact",
"what he says is, I believe, true.",
"We fear that you are not well;",
"we feared that you were not well.",
"I hear that a boy has been stopped by a robber.",
"My sister heard yesterday that the robber had been found.",
"The parents hoped their son would not become a soldier.",
"We knew that their son became a soldier.",
"I think the boy has lost his book.",
"The boy thought he had lost his book.",
"He says he has found your ring.",
"We thought he could work, but he cannot",
"The fellow did not want to pay and cried out that he would carry the ass on his back.",
"Therefore the toll-gatherer got nothing.",
"They answered",
"We have only picked a few strawberries,",
"if you like",
"wake up",
"If he were well he would go out",
"If he had been well he would have gone out",
"Would Captain B. be in better health if he lived in a healthier house?",
"Would you be in better health if you had always lived in a healthier house?",
"If Captain B. had had better water, he would have been in better health.",
"Had Captain B. lived in a healthier house, he would have been in better health.",
"Captain B.'s family would not have become ill if they had lived in a healthier house.",
"If the family had removed out of this unhealthy house half a year ago, they would not have become ill.",
"How is the family of Mr. N. to-day?",
"Mr. N. and his family are in better health now, because they have removed from that unhealthy house.",
"Your brother ought to practice more diligently; he could then make greater progress in music, and if you yourself had been inclined to practice more diligently you also could have made good progress.",
"It is not enough for one to say, \"I should like to be able to play well\"; one must also take pains.",
"if only the weather were fine",
"I should be obliged",
"I should have been allowed.",
"I should have been inclined.",
"You should practice more diligently, then you could make greater progress.",
"If you had practiced more diligently, you could have made greater progress.",
"You should have practiced more diligently, then you would have made greater progress in your music.",
"If they were inclined to practice more diligently, they could make good progress.",
"If they had been inclined to practice more diligently, they could have made good progress.",
"She will soon be able to play well, if she takes pains.",
"She would soon be able to play well, if she would take pains.",
"He would like to be able to play well, but he will not take pains.",
"If your sister wanted to make progress, she would be obliged to take pains.",
"would I were at home",
"let us go home.",
"not that I am aware of.",
"is it possible that you are Mr. Z.?",
"I have a foreboding",
"it is my pleasure",
"I dream",
"As the cat constantly threatened the lives of the mice, they once held a general assembly.",
"The poor mice can neither resist the cat, nor escape from her.",
"They knew they could neither resist her nor escape from her.",
"By whom were the mice advised to hang a bell upon the cat?",
"Why did she not do it herself?",
"Because she lacked courage.",
"The advice, to be sure, pleased all, but no one wanted to carry it out.",
"Either the old mouse or one of the others should have carried out the plan.",
"the cat threatened their life.",
"their life was threatened by the cat.",
"a father who loves his children.",
"a letter written in Italy by Goethe.",
"the horse to be sold, or that is to be sold, at the fair.",
"the boys came running",
"He lent me a book containing many tales.",
"The umbrella standing in the corner belongs to me.",
"The task given him by his teacher is hard.",
"This is the poem which is to be learned by heart.",
"The story told by your friend was very entertaining.",
"The children came riding upon donkeys.",
"The soldiers came marching past.",
"to read books is easier than to write books.",
"it is hard to read German.",
"the reading of books is a pleasure to me.",
"this book is hard to read.",
"the love of reading is common.",
"he sleeps instead of reading.",
"I insisted on reading the book.",
"I believe him to be honorable,",
"My nephew has a lesson to learn.",
"He is too lazy to study.",
"She has gone to fetch a glass of milk.",
"Smoking in this room is forbidden.",
"We heard them singing and laughing.",
"They went out without saying a word.",
"They wish neither to read nor to study.",
"Do not cease reading.",
"He would like to be able to read well.",
"We bade him leave the house and go home.",
"Why do you remain standing in the same place?",
"They addressed me without my knowing them",
"They addressed me without knowing me",
"I insisted upon my brother's getting up",
"I insisted upon getting up",
"Considering the reading of such a book a waste of time, I took it away from him",
"After finishing his work he took a ride",
"Finding my lazy brother lying on the sofa, I insisted on his studying.",
"He, however, insisted on lying there.",
"He said he was tired and could not study any more.",
"Instead of studying he had been sleeping.",
"Before going out of his room I took the book away.",
"After insisting that he go on with his studies I went out.",
"He remained lying where he was.",
"There remained nothing else to be done.",
"he succeeded in everything.",
"Have you seen a lion sleeping?",
"I have seen a lion lying with his muzzle on his paws.",
"What will it benefit your mighty maw, to gulp me down?",
"You will not be aware of it.",
"Would a camel notice a single drop of water in his stomach?",
"The lion did not revenge himself on the poor mouse, because he was a lion.",
"You did right, great lion, in letting the mouse go free.",
"And he kept his word.",
"He had fallen into a snare and could not rend it",
"Poor lion, how fearfully you roared!",
"They might have caught you.",
"Yes, you could have been caught.",
"But out of his hole comes the little mouse.",
"You owe your life to the little mouse whom you let run away.",
"Who would imagine that a mouse would save a lion's life?",
"Slip away now, mouseling, into the hole from which you came",
"The moon relates what it saw yesterday.",
"A great city was lying in the morning twilight and no chimney was yet smoking.",
"The moon was looking at houses and chimneys, when out of one of the latter crept a small head.",
"Then the arms and half the body appeared.",
"It was a little chimney-sweep.",
"Hurrah!",
"He looked up at the moon and away to the green fields and the woods.",
"How dark and narrow it was in the chimney through which he had crept.",
"For the first time in his life he had to-day crept through a dark, narrow chimney.",
"While his arms rest on the border of the chimney, the big round sun rises and shines right into his face.",
"Although his face is blackened with soot, it beams with happiness.",
"See!",
"he is swinging his broom for joy",
"This is what the moon saw very clearly in a little town.",
"He had tied his bear behind a wood-pile, and there the poor creature had been standing a long while.",
"One need not be afraid of such a bear",
"He was big and shaggy, but a big, shaggy bear is not always fierce.",
"Bruin had nothing to eat and he was bored.",
"He got free and found his way up into the attic, where three children were playing.",
"They were little children; the oldest was not more than six years old.",
"They were frightened when the door sprang open and they saw the great, shaggy animal.",
"Although they crept into corners, the bear discovered all three.",
"Now, see!",
"he snuffs them, but does no one of them any harm.",
"The children thought it was a great dog, because he did them no harm.",
"But it is most charming to see how the bear raises himself upon his hind feet and dances, when the oldest boy takes his drum and begins to beat upon it.",
"You ought to have seen how they played soldiers.",
"Each one had a stick for a gun, and the bear had one too, which he held in his fore paws.",
"The mother did not know where the children were, so she went up the stairs and opened the door.",
"At first, when she saw the children and the bear, she was speechless from fright.",
"Her face was white as chalk, her mouth, was half opened, and her eyes were fixed.",
"Children, children, what are you doing?",
"We are playing soldiers.",
"See what a splendid comrade we have!",
"A poor little mother, who is sick and infirm, lies in bed.",
"The whole city, old and young, are celebrating a great festival.",
"She alone has remained at home, because she can no longer use her feet.",
"Outside some are dancing, others are skating.",
"From the bed in the little house she can look out upon the sea.",
"In the west there rise small white clouds;",
"in an hour a storm will burst forth.",
"The little mother knows all about wind and weather.",
"She would go to the sea, where the neighbors all are, but she cannot use her feet.",
"A poor cobbler has leather only for a single pair of shoes.",
"At evening I will cut out the pair of shoes, and when morning comes, I will set to work on them.",
"Now I will set to work on the shoes.",
"What could he say to such a miracle?",
"For a long time the man and his wife did not know who lent them such a helpful hand.",
"If we want to know, we must remain up one night.",
"Let us hide behind the clothes which we have hung up in the corners of the room.",
"Let us then give heed.",
"At midnight two little naked men appeared.",
"What a wonder to see the little men sew and hammer!",
"Now the man and the woman have hidden themselves.",
"Just see, the little men come springing along.",
"They are about to set to work at once.",
"But there are no shoes cut out and no leather.",
"At last they dance out of the door never to come back again.",
"From this time on everything that the cobbler undertakes succeeds.",
"Charles the Great was born in 1747.",
"He cared much for the education of boys and youth.",
"Now he wanted to know what the boys had done in his absence.",
"Some exercise-books were full of excellent work; some showed proofs of ignorance.",
"Then he had the industrious stand on his right, the lazy on his left.",
"He praised the boys who had been earnest to carry out his commands.",
"He said that he would always honor them and give them good places.",
"On those who had not cared for their own good he turned an angry face and spoke angry words.",
"For they had not striven to the best of their powers to learn something sound.",
"When Hans had served seven years he wanted to go home to his mother.",
"He received a big chunk of gold and started for home.",
"But the chunk of gold weighed down poor Hans's shoulder.",
"Ah!",
"What a fine thing it is to have a horse!",
"Why do you go afoot?",
"I see you have a chunk of gold, as big as your head.",
"Give me your chunk of gold and take my horse.",
"Luckily the horse did not run away, because a peasant stopped him.",
"Hans would have lost his horse, if a peasant had not stopped him.",
"It happened that a peasant came along that way, driving a cow before him.",
"After Hans had lain some time in the ditch, where he had been thrown, he pulled himself together again.",
"One is liable to be thrown off and break one's neck.",
"The cow is the thing for me",
"What wouldn't I give if I had such a cow as yours!",
"I'11 tell you what, I'11 exchange my horse for your cow.",
"Though his tongue stuck to the roof of his mouth from thirst, he could do nothing to relieve his thirst.",
"Perhaps the cow gave no milk because she was an old animal.",
"Just heft it by the wings",
"I'm afraid that pig is the one which has just been stolen from a magistrate.",
"I just now came through the village where it was stolen.",
"If they should catch you, you would be clapped into the lockup.",
"Oh, yes, as often as I put my hand into my pocket, I find money in it.",
"What more can one desire?",
"But where did you buy that beautiful goose?",
"What a lucky exchange you have always made",
"Become a scissors-grinder; you need nothing but a whetstone.",
"The stones which he was carrying on his shoulder weighed him down miserably.",
"What a good thing it would be, if I did not need to carry these stones!",
"Now I have to stop every moment, because I am so tired.",
"But I see a spring, where I can rest and refresh myself with a drink.",
"for what reason?",
"be afraid of the creature",
"she is proud of her beauty");

function secondGermanLine()
{
	global $german2lines;
	return $german2lines[array_rand($german2lines)];
}

?>