<?
//https://archive.org/details/cainntnandaoinei00lauoft

	$irishlines = array(
"How rough the sea is to-day, John, I dare say we are near a storm;",
"the sea is dreadfully choppy.",
"How the spray is dashed over the rocks;",
"what a crest of foam on the waves!",
"How beautiful the white horses (or Neptune's horses as they used to be called long ago).",
"See, there is a beautiful ship at the horizon.",
"I can't see it.",
"Sarah, girl, bring me the telescope.",
"Now I see her;",
"she is a beautiful steamer.",
"She's got three funnels.",
"I pity the poor sailors.",
"The storm is abating, thank God;",
"come along the strand.",
"Take care, Tim, do not walk on the seaweed;",
"It is very slippery;",
"it is amazing what a lot of dilisk there is on this strand.",
"And look at the cockles, the mussels, and the perriwinkles.",
"How plentiful the cockles are;",
"we must pick some for they are splendid food.",
"There are numbers of pretty shells to be found on the sands;",
"we shall gather some of them before going home.",
"Do you know who is living in that house yonder, the pretty slate-roofed house on the side of the hill?",
"Indeed, Maurice, he has a fine place;",
"the dwelling house is nice and cosy anyway.",
"He has a good farm of land and fine stock;",
"would you like to come and chat with him;",
"John and myself are very friendly;",
"we can take the short cut through the field?",
"His crops are in perfect condition;",
"it is a long time since I saw the crops so green at this time of the year.",
"I suppose some of the stalks were burnt by the frost at the end of Spring?",
"They were, but though they were burnt they didn't suffer much harm, and I don't see any sign of the blight on them.",
"How many acres of land has he?",
"Up to a hundred acres of fine rich land, and there is some of it under bog, and I promise you he has no lack of fuel from one end of the year to another.",
"I suppose he has fine turf?",
"It is cut with a turf-spade",
"Did you ever see a turf spade?",
"I don't think I did, for it is very little recourse I have to the country.",
"We are at the house now, and I hear something like the barking or yelping of a dog.",
"You are right, I hear the snarl, and I would be afraid to go in.",
"Do not be afraid, for I think they are not vicious.",
"Their bark is worse than their bite.",
"They are good and faithful watches.",
"All the same I wouldn't trust them.",
"Did you ever hear tell of the four things that one must be on his guard against: a dog's mouth, a horse's hoof, a bull's fore-head, and an Englishman's laugh?",
"I wonder is the gate locked?",
"I don't think it is.",
"I imagine it is a latch or loop that is on it, or maybe a bolt.",
"We needn't be afraid now, for I hear the girl quietening (or threatening) the dogs.",
"We must knock at the door;",
"there is no knocker on it;",
"I will knock with my knuckles.",
"The greater part of that farm below is in tillage;",
"a great many crops are sown in it.",
"here's flax sown in it now and again, although flax is seldom seen in the district.",
"And why isn't flax sown more frequently?",
"Because a great deal of trouble must be taken with it before 'tis spun.",
"What are the men doing below at the foot of the field?",
"Don't you see that they are digging and grubbing.",
"There is a fine ploughing team at work in the northern side of the field.",
"They are ploughing and harrowing at present.",
"Do you see the ploughs and the harrows at work?",
"I remember, Maurice, there used to be a farmer living on the south side of the bog, and that he used to be very reckless now and again.",
"I wonder is he living there still or how did he fare?",
"He is no longer there, Tim.",
"He went to ruin;",
"he used to spend the greater part of his time in the public-house.",
"I am told that his family family are wretchedly poor, and that he himself is working for his daily wage in the city.",
"Unless you shun the public-house, poverty and hunger will be your portion.",
"your food will be barnacles",
"Who is the owner of that farm below, the greater part of which is on grazing?",
"That farm belongs to John McSwiney, and it is a crying shame for him to have that beautiful land a cattle ranch instead of cultivating it.",
"I suppose, Michael, you are very busy at present preparing the land for the crops?",
"Just now we are manuring it;",
"the workmen are spreading manure and oar weed to-day and the women will be soon cutting potatoes",
"we have excellent seed potatoes this year.",
"We shall soon be sowing the wheat and the rye, and I shall have about nine acres under oats.",
"I shall leave a field or two fallow this year.",
"How quickly the potatoes are growing on the other side of the fence.",
"I dare say they will soon have to be earthed.",
"Quite true, for the weather is beautiful;",
"the rain and dew are coming in good season.",
"I don't remember such beautiful weather.",
"Not like last year;",
"the blight came very early in the gardens;",
"we had only wretchedly small potatoes, and some of them black.",
"See, Maurice, how nice and thick the young corn is in that field above.",
"Not so with the field on the side of the hill; 'tis looking very ugly.",
"The land must be poor.",
"It's amazing what a quantity of weeds are in it — thistles, corn weed and dockleaves in abundance, and I don't think I ever saw the corn kale so thick in any field.",
"What is growing in the field below near the road?",
"Barley was sown in it, but it is scarcely growing;",
"it is poor, cold, wet land.",
"If the farmer would only drain it, it would be a great benefit to the land, and the nettles and the other weeds would not be growing so thick and choking the crops.",
"There is a fine field of clover here at the foot of the hill;",
"do you not perceive the fine fragrant smell from the blossoms?",
"I do indeed, and I hear the humming of the bees also as they go from blossom to blossom sucking honey.",
"It is amazing what a quantity of furze is growing on the north side of the hill.",
"There is heather in abundance there also",
"It is not a good sign of the land, for furze does not grow in any good land.",
"However, they make use of it.",
"It makes good warm litter, and wholesome food for horses.",
"How nice the vegetable garden behind the house looks.",
"What splendid cabbage!",
"See the big heads!",
"What a pity not to weed out the ragweed and the butter-bur.",
"Those men below are very busy cutting the hay.",
"They will shortly have it made into cocks and saved, seeing how dry the weather is.",
"I dare say they will be drawing it into the haggart next week.",
"I see Tim Crowley is not yet cutting his hay;",
"but Tim was always a good-for-nothing fellow.",
"Though the fine weather continued till November, some one would be in a sorry plight.",
"Do you see the thatched house below?",
"There is a man living there who is generally behind hand in his work.",
"His horse and driver met with a terrible accident the other day.",
"A load of hay was being brought in from the field, and the cart was upset at the corner of the lane",
"and to crown misfortune the driver was nearly killed.",
"Och, God and Mary help us, my goodness, who was the driver?",
"George Walsh is his name, a little man without sense, although he fancies himself that he is the best driver to be found.",
"Do you think he'll recover?",
"I don't think he will, but if he does it will tax him to the utmost.",
"I am told that he raves dreadfully at present.",
"Look over at that fine field of wheat yonder;",
"don't you think it is ripe and ready for reaping;",
"it has got a fine heavy head, golden yellow, and the straw fine and long.",
"That farmer will certainly have great produce this year",
"He will have a large team of reapers on Monday",
"There is scarcely any place where they haven't machines now for every kind of farm work.",
"Quite true;",
"they have reaping, binding and threshing machines;",
"they are not depending on the scythe now to cut down the corn as they did long ago, and it is a long time since I saw anyone handling a flail.",
"Look, the women are working after the reapers in that field south;",
"they are gleaning, and I assure you it is not very nice work to be gathering ears in the stubble field considering how sharp the stubbles are.",
"I dare say they will be soon threshing the corn in that farm.",
"I hope there won't be drinking at the threshing as there used to be.",
"There is an end of that bad habit, thank God.",
"The threshers and winnowers are quite satisfied with the ordinary food",
"I dare say they make some use of the chaff that is got out of the corn?",
"Certainly.",
"Many a poor family that has no better bed than a little chaff.",
"See some of that barley below is still in swath;",
"what a pity not to make stacks or stooks or even sheaves of it before the rain comes.",
"The day doesn't look at all well.",
"I dare say he was depending on sickles or the scythe to cut the barley.",
"I fear very much that we shall not have good early potatoes.",
"Have they been second earthed yet?",
"Yes, long ago",
"they will soon be ripe.",
"The stalks are withered in that garden north, but I suppose it is time for them.",
"I hope we shall have potatoes in abundance this year.",
"They were very small last year.",
"See, they are digging in this field here, and thank God, I see no sign of blackening on them;",
"they are fine, and large, and floury.",
"I dare say a good quantity of them will be put into a pit, and that they will be well covered with straw to save them from the frost.",
"Aren't those fine cattle that are grazing in the field by the river?",
"See, the brindled cow is trespassing in clover field.",
"Isn't she a great villain?",
"it would be a good job if she fared as that brindled cow fared that was killed by the fierce days borrowed by March from April.",
"God forbid!",
"Even though she is breachy, she is the very best milch cow I have.",
"There is scarcely a day that she does not give four gallons of milk.",
"the heat is very severe on some of the cattle",
"they are being annoyed and tormented by the flies and the midges",
"They are gadding and the bull is bellowing",
"I dare say you would be afraid of the bull?",
"Of course, I would;",
"it is well I remember the day I was crossing that field, and that the bull bellowed so that he might be heard a mile off.",
"You must have been dreadfully frightened.",
"I was never so frightened in my life, and I assure you that I wasn't slow in getting to the other side of the fence.",
"Those cows below are lowing;",
"I suppose they are aware that it is milking time.",
"I wonder it it true that they give their milk quite freely provided a tune is being sung for them as they are milked?",
"Why are some of the poor animals tied up in that manner?",
"What a fine flock of sheep there is in this field, and the dog minding them.",
"The dog is a faithful shepherd.",
"See the pretty lambs as they frisk about;",
"some of them are bleating;",
"I suppose they are calling for their mothers;",
"what a pity to have those gags on them.",
"But I dare say it is time to wean them.",
"What fine wool there is on that ewe.",
"She has got a beautiful fleece, but the shears will soon be at work, and the wool shorn.",
"Later on they will be spinning and weaving it.",
"that reminds me of the olden times when we had a large number of weavers and weaving industry carried on in almost every parish.",
"Would it not be a grand thing if we had them back again if the spinning wheel and the loom, the  and the distaff busy as they used to be of old",
"What a pity that the snails and the caterpillars are eating the herbs in that garden.",
"Nearly all the plants arc ruined by them.",
"George, do you see the goat and the nice little kids below at the end of field near the sheepfold?",
"They are in the field where the cows are lying and chewing the cud",
"I see the goat and the kids;",
"there are few animals so quiet and gentle as the goat provided you don't interfere with her;",
"but if she suffered any interference, I wouldn't like to be near her;",
"even the dogs themselves don't like to approach her.",
"I suppose it is the horns they are afraid of, or perhaps the whisker",
"See below, the little donkey",
"I suppose the man coming up the road on horseback is the man of the house?",
"It is surely a spirited horse.",
"I think there is something annoying him, seeing that he is shaking his head in that manner.",
"Perhaps it is the bit that's annoying him.",
"Do you hear the bees buzzing around us?",
"There must be a swarm somewhere near us.",
"I expect there is a hive at the far side of the house.",
"It is often I think of the bees and the work they do.",
"It is perfectly wonderful how neatly and exactly they spread the wax and put the honeycomb together.",
"There are three things very difficult to understand : the mind of a woman, the work of the bees, and the flow and ebb of the tide.",
"Look! There is a wasp behind you.",
"Beware lest he might sting you",
"A sting from a wasp is a very poisonous thing.",
"Come on south towards the wood.",
"There is a nice, clean avenue here, with a fine laurel hedge on each side.",
"We can go down the path through the wood, and we shall have the short cut on our way home.",
"Do you hear the grasshoppers as they are chirping in the sun?",
"How merry they are.",
"The sunshine must give them real delight.",
"This is certainly a beautiful wood.",
"I dare say they fell some of the trees to provide fuel for the winter, instead of depending on coal.",
"There is scarcely any kind of tree that is not to be met with in this wood.",
"See the beautiful elms, and the horse-chestnuts with their abundant fruit.",
"The beech and the hazel, the seer's trees, are growing here beside the old lios.",
"I have seldom seen the birch and the ash so fine and tall as they are here.",
"I notice that there are a great many burrows all round, but I see no rabbit.",
"They must have taken fright when they heard us coming.",
"No blame to them, for the creatures know well that they are being watched in order to shoot or ensnare them.",
"It is many a fine hunt I witnessed near this wood and I remember well when I used to hear the sound of the horn, I could not help running after the huntsmen.",
"I thought at that time there was no music in the world so delightful as the cry of the pack and the blast of the horn.",
"I often heard my father, God rest his soul, say that there used to be badgers below in that dark corner at the bottom of the wood, but I never saw a badger nor a badger warren.",
"they went off with themselves long ago.",
"May they never return! For they are ugly animals.",
"I dare say all that ivy which is growing on the trees does not serve them?",
"Indeed it does not.",
"I don't think I have yet seen any sycamore, or willow, or cypress, or rowan tree here.",
"Come along northwards in this direction and I will show it to you.",
"I thought that tree could not be found outside Killarney; but I see it is growing beautifully here, and that it has \"Cain apples\" in abundance.",
"How thick the honeysuckle is on the side of this fence!",
"And see the beautiful white-thorn.",
"I love the smell of the white-thorn.",
"There is no smell more fragrant.",
"They say that Druids used to meet in that grove long ago.",
"The foxes are still in the district, but it is seldom a hunt is to be seen now;",
"but, nevertheless, we have plenty of sport, for we have a pair of big dogs, and we kill otters with them.",
"You never saw such battles as they have under the water.",
"I assure you the otter is no contemptible foe.",
"I sometimes hunt with a little ferret.",
"He is splendid for killing weasels and rats.",
"Come along this way towards the moor.",
"Immense numbers of wild birds frequent the place.",
"I dare say the wood abounds woodcock, grouse and in pheasants.",
"So it does",
"But we shall cross the river now.",
"There are very handy stepping-stones here below.",
"There is no danger of getting wet as we cross.",
"Look, there is a large flock of stares flying southwards.",
"Do you see the plovers?",
"What a number of them are there.",
"Wild duck come here also and they are shot during the winter.",
"Snipe are seldom seen on this moor.",
"Batt, do you see the lad below in the bushes?",
"I wonder who is he?",
"I think it is little Garret O'Neill is there, picking haws, or perhaps looking for nests.",
"Call him or whistle at him",
"Here he comes whistling;",
"he is as merry as a cricket",
"Little Garrett is a wonderful lad for talk, but 'tis a pity he is such an idler;",
"nothing pleases him better than to be catching butterflies or moths or looking for nests",
"God bless you, Garrett",
"My goodness what happened to your foot?",
"'Tis bleeding.",
"What have you got in the sack, Garrett?",
"It's only a clover sod for the lark, I am in the habit of cutting a sod for her every day.",
"There is also a handful of groundsel.",
"How many birds have you got now?",
"Wait till I count them:",
"there is a blackbird, a yellow hammer, a gold finch, a linnet, a thrush, a lark, and I had a little robin also, but I let it go, for I was told that it wasn't a lucky thing to catch a robin.",
"they say there is something holy about that little bird, and that everyone should be kind to Mary's robin.",
"I don't like some of them.",
"I'm not fond of of the jackdaw because he makes such a row early in the morning in the top of the chimney, and keeps me awake.",
"How do you like the parrot?",
"I think he is an ugly, cross bird, and 'tis wonderful how he imitates any bad language he hears.",
"Have you heard the cuckoo yet this year, Garrett?",
"Yes, indeed, and I had the good luck to hear her in the right ear;",
"they say it is not lucky to hear her in the left ear.",
"Are all your birds singing at present?",
"Some of them are moulting, but they will soon be singing again.",
"Which do you prefer, the song of the lark or the song of the thrush?",
"It's hard for me to answer that question",
"Do you remember you promised me a lark?",
"Yes indeed, and I'll keep my promise, but you must be patient, for it is only a nestling yet.",
"I dare say you seldom succeed in catching a swallow or a wagtail.",
"They are not worth the catching, nor is a sparrow either, because they can't sing.",
"I suppose it is hard to find the nest of swallows or wagtails?",
"Quite true, for they generally make them on the side of the cliff.",
"Tom, how do you occupy yourself after you have finished the day's work?",
"I occupy myself in many ways",
"Will you come fishing this evening?",
"I shall be free from work.",
"I have not a fishing rod nor line, but perhaps you would lend them.",
"I broke the wheel of the fishing rod yesterday.",
"You don't require any rod.",
"I have a strong fishing line for you and a good strong folding frame and lead.",
"We shall have sufficient bait also;",
"I was digging it in the sand early this morning.",
"What kind of bait do you use?",
"The sand-worm is better than any other bait, for it is tough.",
"I use cockles and sprats, occasionally, but they are too soft, and the fishes carry them off with them.",
"They are easily broken on the hook.",
"I was told that there is a fine shoal of fish on the northern side of the sand bank.",
"We shall go out the harbour presently, and we shall catch a good quantity, please God.",
"We ought to take the gaff with us, for the fish is sometimes very heavy there.",
"I dare say you seldom fish in the river.",
"I was fishing in it recently for a considerable time, but I caught very little",
"I failed to get good flies.",
"At last I lost patience and went off home.",
"Four men will come with us — Bill Fluke and three others.",
"It is a six-oar boat.",
"And who is Bill Fluke, pray, or is that a nickname he has got?",
"You have just got it; it is a nickname.",
"His name is William McSwiney, a decent fellow, and, in my opinion, there is not a stronger man in the parish, and so it is kind for him to be.",
"Have you ever heard of his grandfather — Phelim McSwiney?",
"Phelim of large means, and of large and generous heart, who loved the dance, the worthy beloved son of the true McSwiney clan, the man who could dig the fallow field from the very bottom, and who, when making the stack, required no pike, but could fling the sheaves even to the top",
"I dare say it was a \"keening\" woman that composed that pretty poem.",
"Come, come, let us be going.",
"the boys are waiting for us on the strand.",
"The evening will be fine and calm and pleasant, please God;",
"but at the same time I don't like those dark storm clouds to the east.",
"that explains why there is such a scarcity of fish in the harbours.",
"Do you see the two boats outside the wood?",
"Cormac, we must make haste: the day is slipping from us.",
"I invited John Collins and his boy, Colm, to come with us.",
"Here they come!",
"The other boys are waiting for us on the strand, and we shall have help enough to shove down the boat.",
"I'm afraid, Tim, 'tisn't an easy job to get her afloat considering how shallow the water is and how soft the slob is.",
"Is it how you are afraid that your boots will get soiled?",
"Now, boys, let us shove together.",
"That's splendid:",
"we have got her afloat.",
"I hope the evening will be fine and calm, and that the waves won't be too high, for I am not much of a sailor.",
"I get sea-sick from the tossing of the boat, and besides I get rather afraid of the waves.",
"there's not a boat on the sea that cares less for a storm than she does.",
"the higher the waves the better she goes;",
"though there are good boats going out the harbour, there is none of them is a match for this one.",
"I suppose we have everything ready now.",
"The oars are all in the boat;",
"the thole pins are in the row-locks;",
"the anchor is up on the prow, and the fishing lines and frames are in the boat, and our oarsmen are the very best.",
"I don't think we are short of anything.",
"Captain, I don't see the helm.",
"Bless my soul, Cormac, I nearly forgot it, and what a dreadful piece of forgetfulness;",
"the captain forgetting the helm would be just as bad as the clerk of the church forgetting to ring the bell.",
"Colm, my boy, go in all haste up to the house;",
"you will get the helm in the kitchen, and bring it down",
"Peter, you may as well take the mast thwart.",
"Declan, you sit on the well thwart, and Dan, you take the back thwart.",
"Colm, you come back here to the stern-sheets, and keep nice and quiet there, and don't sit on the gunwale.",
"If she lets the water in, you have a saucepan here, and you can bail her.",
"Out with her now, in God's name, and row together.",
"Back water, Tim;",
"back water all of you! For I see a boat right in front of us.",
"My goodness, there's no boat there, captain;",
"bless my soul, you have got us on the buoy.",
"What defective sight you must have that you could not distinguish a boat from a buoy.",
"Hold your tongue, Tim, there's no fear of us.",
"Look at the boat coming towards us, and the big cargo of oar-weed she has got;",
"she is full from to stern.",
"What are these things outside of us that are floating on the surface of the water?",
"I dare say there is a net of some kind in that place.",
"I fancy there is a herring net there, and those are the floats that are attached to it.",
"Take care, captain, there is a hidden rock to your right, and I don't think there is even half a fathom of water over it.",
"Colm, do you remember that night last year when we went fishing a little distance outside the Barrels, and the big shoal of fish that was there?",
"We kept catching them late into the night until the the boat was almost full as far as the top plank.",
"I remember it distinctly.",
"Wasn't that the night that the accident occurred to Paddy, Tim, on his way home with his pannier full of fish on his back?",
"I remember well that the poor man was a laughing stock amongst the neighbours for a long time afterwards.",
"He thought the eel was dead, for he put the gaff through her before he hauled her into the boat.",
"He was going along the road towards his own house, quite delighted with himself and with his fine take of fish and no wonder",
"The poor man himself nearly dropped dead on the spot.",
"You could hear him roaring a mile off.",
"When he recovered himself you may rest assured that he really killed the conger.",
"John, would you like to have some boating this evening?",
"Three or four friends of mine will come with me.",
"I would have no objection as I have some leisure today;",
"but don't you think the day is too threatening, too wild?",
"You needn't be in the least afraid, for although there is a high wind blowing, there is nothing bad about the appearance of the weather.",
"The wind is south-east now, and I remember I saw a rainbow in the heavens early this morning, and isn't a rainbow in the morning a sign of bad weather?",
"Don't mind that;",
"I promise you that we shall have a splendid day.",
"I fancy the wind is changing to the north, and that the evening will be fine and calm and pleasant.",
"My goodness, have patience dad!",
"What a fuss you are in!",
"I dare say you would prefer some sailing to rowing.",
"were it not for that assistance it would have been in vain for us to try to land",
"I fear the wind will be dying down, for it is changing again;",
"'tis blowing from the northwest.",
"Now Maurice, all aboard, and we shall be soon in full sail,",
"We shall be able to have a swim a little later on when we get outside the point of the wood;",
"there is a nice sandy cove to the west of the wood, and we can anchor and go for a swim.",
"I regret that I cannot swim, but I suppose I can go bathing if the water is shallow enough.",
"Maurice is a good swimmer, and he will show you how to swim;",
"he will support your chin.",
"Look, they are going out towards Horse Rock fishing.",
"Are not those fine, vigorous men who are in the boat next to us?",
"She has got an excellent crew, and they are rowing splendidly.",
"How nice the whitewashed houses north of the beach look — the houses that are nicely situated facing the sun on the hillside.",
"I wonder whose is the lovely house at the bend of the road with the fine fuchsia hedge in front of it?",
"I think that is Jerry Michael Larry's house.",
"He is a wonderful man.",
"He never ceases working and putting things in order; and, as a result, he has a beautiful place and considerable means.",
"It would be well if all farmers were as diligent as he is.",
"I don't think I ever saw the fuchsia or privet so abundant anywhere as they are here.",
"What beautiful hedges!",
"They grow wonderfully beside the sea.",
"See the curlews and the storks and the big cormorant.",
"Have you the gun, John?",
"Yes, Kitty, but I cannot shoot any of them, for they are not within range",
"We must have patience for a while.",
"I shall fire a shot at the cormorant presently.",
"Boys, the wind is changing again.",
"It was with us a while ago, but now it is almost against us;",
"I must tack.",
"Take care, captain, or you will soon have us stuck in the slob.",
"There is not a fathom of water under the boat.",
"I did not notice how shallow the water was.",
"My sight is failing.",
"I am afraid that I am getting cataracts, and that I shall soon be as blind as a bat.",
"We have got the deep water again.",
"I don't think the channel is far from us, it we had better keep a little distance outside it, as the flood is very strong.",
"My goodness, Kitty, what happened your sleeve?",
"you have got it all daubed with tar.",
"Why did you not remain quite as you were told and not be rubbing your hand to the side of the boat?",
"That is nothing, I can wash it to-morrow.",
"See, dad, the boat is leaking.",
"The plug must be loose in the hole.",
"Perhaps you are the cause of it.",
"If you only kept from fiddling with the plug we would not have the well full of water.",
"You are the most mischievous girl that can be found.",
"It is always like that;",
"whatever mischance occurs I am blamed for it.",
"I will give you some pocket money when we get home.",
"I dare say a whale or a shark is never seen in this harbour?",
"I was told that a whale was seen here two years ago.",
"Jimmy the hens and Davy Brigid were fishing one day, and they saw a whale or some sea monster following them, as they thought themselves, and spouting water 20 feet high.",
"And, Maurice, did he attack them?",
"No: though he kept following them a good while, he turned away to the north from them without interfering with them.",
"I heard that a whale never attacks fishermen provided they don't interfere with him;",
"but such is not the case with the shark, the villain.",
"Don't you think, Dan, that there is a shoal of mackerel there to the west?",
"You are probably right, and they are also very plentiful there.",
"There is something putting its head out of the water; perhaps it is a seal?",
"Not at all but a porpoise, for the seals do not come so near the land.",
"Now, Dan, that you are a good hand at singing, we'd like to hear a song from you on our way home.",
"It's nice to hear a sweet song on the sea.",
"Give us an Irish song please.",
"Perhaps if the police heard us they might suspect us at once, and they might imagine that we were engaged in some treason or underhand plotting against the Empire.",
"Perhaps they might be in pursuit of us on our landing, and how do we know what might happen us in consequence?",
"My goodness, Dan, don't be making a fool of yourself;",
"the police of this district have sense;",
"begin now.",
"That is beautiful;",
"you have acquitted yourself magnificently.",
"To listen to a fine Irish song sung by a good singer is a real joy and delight;",
"it is the very triumph of melody.",
"Now, boys, we are on land again. Be patient, Kitty my dear;",
"take care and don't jump out;",
"wait till we put out the plank for you.",
"We must haul her up a good distance on the strand, for we have spring tides at present;",
"let us get the spars under her;",
"in that way it is easier to haul her up",
"Ned, I am told there will be a competition hurling match in the Brookfield in the evening, and that the match will be very good.",
"Who will be playing, Tim?",
"You never saw teams better matched than they are.",
"As we have leisure, it is as good a thing as we can do, to go and see them.",
"In all probability we shall have good sport to-day, for hurling is the finest game that can be seen.",
"We can go the pathway beside the wood;",
"it is a great short cut.",
"It is time for us to be going, for the match will soon begin.",
"The people are gathering quickly already.",
"I hope there will be no disturbance or quarrelling between them.",
"There is not the least fear of that, for there is no longer any drinking.",
"It is a long time since I saw any one intoxicated in the parish.",
"Such was not the case twenty years or even ten years ago.",
"And what is that great change chiefly attributed to?",
"I have been noticing that the young people are turning against drink.",
"and besides drink is expensive and very scarce now.",
"That is one good thing, at all events, that has resulted from the war.",
"It is a bad wind that does not blow good to somebody.",
"Lloyd George has done his own part to prevent the people from drinking.",
"We shall be in the field in a quarter of an hour's time now.",
"Do you hear the cooing of the pigeons in the wood beside us?",
"See the convolvulous, how wonderfully it spreads around the plants.",
"We are at the field now, and what a gathering;",
"see all the boys and girls around the field, and it is they are bright and gay and well dressed.",
"They must take a great interest in the match.",
"Some are hoping that the boys of the Cross will win and others hoping that the boys of the Rock will be victorious.",
"See! they are commencing now;",
"here comes the two teams.",
"I see they have John O'Hea as referee and there is no fear that John will do an injustice to either side.",
"Andy Julia is the goalkeeper for the Rock team and Tim Mickey is the goal-keeper for the other team.",
"Up with the ball now!",
"By jove!",
"How fast they are running and how vigourously they are playing.",
"See, the Rock boys have got the ball very nearly into the goal.",
"Did you ever see anything neater than the way Foxey Jack stopped it?",
"Bravo, Jack!",
"Well, I knew that you wouldn't let it pass you.",
"Do you hear the cheers?",
"These cheers give them double courage.",
"I wonder what happened to him?",
"He met with an accident last evening as he was cycling towards his own house.",
"Just as he was rounding the corner at the fall of the road the cycle ran down headlong and he couldn't possibly stop it as he had no brake.",
"The poor boy was thrown against the fence and his hip was severely injured.",
"What is the meaning of all the uproar?",
"What shouting !",
"They are urging on their own friends.",
"Strike the ball quickly, Declan!",
"How slow you are, man!",
"Denis, don't lift the ball like that.",
"leave it on the sod.",
"See the tall man and the red-headed athletic chap running against one another with the ball between them",
"The foxey lad is trying to knock him down, but I don't think he can bring that giant down.",
"But neither can he bring down the brawny fellow, who is so firm on his feet, although he gave him a hip and shoulder.",
"I wonder is that fair?",
"I think so.",
"Have you seen the foul that man yonder did to the man who was pucking the ball?",
"He tripped him, and that is by no means lawful;",
"it was a low mean act.",
"See, Johnny, the goalkeeper allowed the ball to pass him, and 'twas badly done by him.",
"The Rock team has got a goal.",
"'Twill soon be half-time now and they will be changing sides, and it is a good thing for the boys of the Cross, for they will have the wind with them.",
"Courage, lads, the difference is nothing.",
"I never saw anything finer or neater than the combination shown by the boys of the Cross.",
"In my opinion they will not be beaten, because they are wonderful stuff, and they know their business well.",
"They have got the ball into the goal now.",
"How is the score on each side?",
"I believe the time is up;",
"the count is even on both sides — three goals and a point.",
"Well done, boys of the Cross.",
"You will win the championship next year.",
"There goes the whistle.",
"The match is a draw.",
"It will be played over again.",
"By Jove, it is four o'clock.",
"How time flies.",
"It is too early yet to go home, wait till we see the football match.",
"The football teams are very good, but you seem to be tired.",
"You are quite right.",
"I walked to Midleton the day before yesterday and walked home also.",
"I thought a good walk would do me good.",
"I assure you I was quite exhausted after the journey.",
"I am not surprised that you are yawning.",
"Thank you, and may God rest the souls that left you!",
"It is good strong snuff;",
"it is making me sneeze.",
"God bless us!",
"Here is Rusty Tim coming up.",
"We shall go to speak to him.",
"Tim is a peculiar individual and it is hard to please him;",
"he never ceases finding fault.",
"Good morrow, Tim.",
"How did you like the hurling match?",
"It was middling;",
"but there were two or three from whom I expected better things.",
"The man on the fence is always a good hurler.",
"We may as well return through the glen, beside the stream, for the plants and flowers are beautiful there.",
"I knew very little about herbs or trees.",
"I could scarcely distinguish the trees from one another.",
"I myself don't know very much about them, but nevertheless I will point out some of them to you and give you their names.",
"Stop a moment, I see you have got an earwig and ants on your coat;",
"there must have been an anthill where you were sitting.",
"Let me brush them off with my handkerchief.",
"See that fine plant on your right.",
"Marigold it is called.",
"It has gold-coloured flowers.",
"The high plant to the inside of it is mullein.",
"It is also called the \"big herb\" in certain places.",
"Later on we shall see plants called Rosemary and Centaury.",
"Look to the other side of the stream.",
"The plant nearest to us is Foxglove (or Lady's Fingers), and the herb below it is called Lady's-mantle;",
"Do you see the small plant with the white little flowers?",
"The stalk contains white sap, which does a great deal of harm.",
"People kill the fish with it.",
"I see wormwood there also.",
"There are many cures in wormwood.",
"These opposite you is a little tree which is very common.",
"Everyone knows the elder, and it is a pity that everyone does not also understand the cures that are in it.",
"I notice the Veronica everywhere in this district",
"Although the Veronica is not very beautiful, it is an evergreen, and we all like evergreen plants and trees",
"Look into this garden",
"Are not the sun-flowers and holly-hocks beautiful?",
"The camomile is also growing there, and there are poppies in abundance.",
"I don't know at all how the accurate, perfect knowledge our forefathers had of trees and plants, and of all that appertained to them, came to be lost.",
"It is not very difficult to solve that question.",
"You know how the Irish language was forbidden and how it was trampled under foot.",
"In consequence of that the people of Ireland had to give up the speaking of Irish to their children.",
"According as the language was disappearing, the knowledge of the plants and the cures they contained was also gradually disappearing until it was almost altogether lost.",
"It is only an odd individual here and there who knows anything now about herbs.",
"The older people could not possibly impart that knowledge to the young in English, for they themselves did not know the names in English.",
"I understand the whole story now. and certainly it is a sorry story.",
"We must hurry on, for the day is growing late, and see.",
"She is a wonderful little girl.",
"Though she is young she is always sensible and precocious, and she is always pleasant, and the best of it all is, she is the best housekeeper in the Parish.",
"Bless you, Moreen!",
"God bless you, kindly!",
"I dare say the lady of the house has something for us to eat, my pet.",
"The tea is ready, and we have a nice cake for you also.",
"I made it myself.",
"Long life to you, my dear!",
"It was very thoughtful of you.",
"He told me there will be a dramatic performance in the Hall this evening, and that the artists are wonderfully good.",
"Would you like to come with me to see them?",
"I shall be delighted to go with you.",
"I have often heard about that Hall.",
"I suppose the boys have great amusement there.",
"There are over sixty singers in it, and it would be well worth your while to hear them.",
"There is great credit due to the musician who trained them.",
"They play many games — draughts, chess, billiards, and cards.",
"Do you go there often yourself?",
"Yes, certainly, for I like a game of cards now and again, though I am not an adept at them.",
"We have great fun, and no one loses or wins much, for we play for only a halfpenny a game.",
"There is a fine gymnasium there also, and every kind of gymnasium apparatus, horizontal bar, parallel bars, climbing ladders, and so on.",
"I am more in the library than engaged at games, for the room is very cosy, and exceedingly nice.",
"There are special rooms for the girls, in which good and useful work is being done.",
"They learn needlework, knitting and cooking from splendid teachers.",
"I am delighted to come to the Hall after the day's work and talk with the boys, or join in their games, and I feel all the better for it.",
"I don't think I ever saw anywhere else so many happy, joyous faces gathered together.",
"The football and hurling teams are splendid.",
"It would be difficult to excel them.",
"Many a fine game they play, and many a time we feel proud of them.",
"I am told the Irish also is being taught in the Hall.",
"I trust you are succeeding.",
"The students who are in earnest are succeeding, but those whose hearts are not in the work are not succeeding, and they do not deserve to succeed.",
"There are people who imagine that they ought to be able to learn Irish without taking the least trouble with it, and then, when they don't succeed, their excuse is, that the Irish is too difficult.",
"That brings to my mind the story of the cat that was fishing on the dry strand.",
"As you are aware a cat is very fond of fish, but he does not wish by any means to wet his paws.",
"That is precisely the case with a great many people who talk about the Irish;",
"they would like to know it, but they don't like to cause themselves the smallest inconvenience in the world to learn it.",
"Nevertheless don't you think the Irish Language movement is advancing?",
"Are there not a great many people everywhere through the country who are able to understand, write, and speak it?",
"Such was not the case twenty years ago.",
"That is quite true, but things would be far better if conversation were carried on more frequently than it is.",
"We are glad to hear that the readers and writers are growing more numerous, but we should much prefer the speakers to be increasing in numbers.",
"Perhaps so;",
"but no matter how little or much of it they know they ought to speak it and get accustomed to the conversation.",
"As the proverb says: \"Practice makes perfect.\"",
"They will soon acquire fluency of speech and a command of words, provided they speak a little Irish every day.",
"I am convinced that we shall strive in vain to revive the Irish throughout the country unless it be taught in the schools, and especially in the National Schools.",
"The school teachers should take the greatest care to have conversation in the classes every day;",
"and also to teach the children the pronunciation, the correct accent, and the proper construction of the language.",
"With regard to some of the Gaelic League branches, I notice that they have but very little conversation in the classes.",
"That is a great mistake.",
"They should occupy the greater part of the time with conversation.",
"I often hear people say that the Irish spoken in the provinces of Ireland is not the same, and that a Munster man cannot understand a man from Ulster.",
"Don't mind those people.",
"It is the same Irish that is spoken in all the provinces, only that there is a little difference in the accent and pronunciation I believe there is greater difference in the English spoken in the provinces.",
"The Connacht man thinks he himself speaks Irish most accurately and with the best accent.",
"It must have been a Connacht man that invented that old saying.");

	function firstIrishLine()
	{
		global $irishlines;
		return $irishlines[array_rand($irishlines)];
	}
?>