<?

// https://www.gutenberg.org/files/50419/50419-0.txt

	$italian1lines = array("I love, thou acquirest, he respects, we salute, you speak, ye pass, they walk.",
"I did call, thou didst prattle, he did command, we did begin, you did buy, they did confess.",
"I confirmed, thou didst deliver, he preserved, we considered, you advised, they contended.",
"I have declined, thou hast courted, he has cured, we have crowned, you have dedicated, they have supped.",
"I had wished, thou hadst declared, he had dispensed, we had assembled, you had undeceived, they had wasted.",
"I will expect, thou shalt arrive, he will assault, we will assure, you will wish, they shall increase.",
"Dance, let him change, let us walk, sing ye, let them certify.",
"That I may fast, that thou mayest besiege, that he may ride, that we may punish, that you may pass, that they may cause.",
"That I might caress, that thou mightest burn, that he might stoop, that we might accept, that you might embrace, that they might mend.",
"I should accompany, thou shouldst accuse, he should baptize, we should mistrust, you should venture, they should administer.",
"That I may have lamented, that thou mayest have invented, that he may have governed, that we may have tamed, that you may have asked, that they may have experienced.",
"That I might have formed, that thou mightest have taken away, that he might have sent, that we might have prepared, that you might have deprived, that they might have resembled.",
"I should have prolonged, thou shouldst have tried, he should have remedied, we should have refused, you should have carried back again, they should have prayed.",
"I shall or will have warmed, thou shalt have transferred, he shall have judged, we shall have fortified, you shall have inflamed, they shall have failed.",
"I believe, thou receivest, he sees, we repeat, you beat, they drink.",
"I did yield up, thou didst owe, he did cleave, we did groan, you did feed, they did hang up.",
"I enjoyed, thou pressedst, he reaped, we shone, you repeated, they sat down.",
"I have sold, thou hast crept along, he has shrieked, we have feared, you have beaten, they have received.",
"I had fallen, thou hadst pleased, he had held, we had grieved, you had appeared, they had pleased.",
"I shall or will persuade, thou shalt lie down, he shall be able, we shall remain, you shall know, they shall be accustomed.",
"Be silent, let him see, let us hold, be ye pleased, let them fall again.",
"That I may have, that thou mayest owe, that he may fall, that we may lie down, that you may be able, that they may grieve.",
"That I might appear, that thou mightest lie down, that he might please, that we might persuade, that you might be able, that they might know.",
"I should be silent, thou shouldst be accustomed, he should be worth, we should hold, you should see, they should be willing.",
"I hear, thou followest, he opens, we boil, you consent, they convert.",
"I did cover, thou didst sow, he did sleep, we did fly, you did lie, they did die.",
"I departed, thou didst suffer, he repented, we ascended, you served, they went out.",
"I have dressed, thou hast heard, he has consented, we have slept, you have covered, they have boiled.",
"I had appeared, thou hadst uttered, he had buried, we had dared, you had abolished, they had understood.",
"I shall or will abhor, thou shalt enrich, he shall blush, we shall banish, you shall whiten, they shall pity.",
"Conceive thou, let him digest, let us finish, approve ye, let them bloom.",
"That I may suffer, that thou mayest grow mad, that he may languish, that we may dispatch, that you may unite, that they may obey.",
"That I might colour, that thou mightest flourish, that he might sharpen, that we might animate, that you might harden, that they might bellow.",
"I would strike, thou wouldst banish, he would abhor, we would abolish, you would enrich, they would comprehend.",
"I belong, thou kindlest, he takes, we perceive, you kill, they burn.",
"I did hide, thou didst oppress, he did sprinkle, we did divide, you did absolve, they did absorb.",
"I assumed, thou offeredst, he demanded, we plucked up, you shut, they engraved.",
"I have granted, thou hast run, he has decided, we have believed, you have boiled, they have decided.",
"I had deluded, thou hadst oppressed, he had defended, we had expressed, you had sprinkled, they had known.",
"I shall, or will grieve, thou shalt erect, he shall exclude, we shall require, you shall expel, they shall extinguish.",
"Melt thou, let him drive in, let us feign, break ye, let them reflect.",
"That I may lie down, that thou mayest fry, that he may join, that she may imprint, that we may hang up, that you may see, that they may include.",
"That I might soak, that thou mightest intrude, that he might read, that we might put, that you might bite, that they might plunge.",
"I would move, thou wouldst milk, he would conceal, we would neglect, you would foresee, they would hurt.",
"That I may have offended, that thou mayest have oppressed, that he may have struck, that we may have lost, that you may have pleased, that they may have wept.",
"That I might have painted, that thou mightest have presented, that he might have curtailed, that we might have taken, that you might have presumed, that they might have protected.",
"I should have sat down, thou shouldest have returned, he should have reduced, we should have laughed, you should have answered, they should have suspended.",
"When I shall have scattered, thou shalt have shaken, he shall have risen, we shall have killed, you shall have conquered, they shall have lived.",
"I write three hours every day.",
"Thou art too troublesome to my friends.",
"He speaks like a Roman orator.",
"We go out of town every Spring.",
"You shew your probity very plainly.",
"They think it is very fine weather to walk out.",
"I was extremely glad to see him again.",
"Thou wert generously rewarded.",
"He bought many things to send abroad.",
"We encouraged all arts and trades.",
"You baffled their wicked designs.",
"They tempted our faithful subjects.",
"I have enriched his numerous family.",
"Thou hast many accounts to settle.",
"He has renewed his promises to us.",
"We have seen the chief curiosities.",
"You have examined them carefully.",
"They have declared their last will.",
"I had resolved to get rid of them.",
"Thou hadst determined to say it plainly.",
"He had fixed on that sort of diversion.",
"We had sworn to love each other eternally.",
"You had forsaken his acquaintance.",
"They had implored the king's clemency.",
"I shall ever commend prudent people.",
"Thou shalt publish this news every where.",
"He will return from France next week.",
"We shall travel day and night till we arrive.",
"You will do yourself immortal honor.",
"They will disgrace their noble family.",
"Bring me that bottle and a glass.",
"Let him gather all his things, and then go.",
"Let us walk in the garden before dinner.",
"Go and meet all our friends on the road.",
"Let them answer all my questions.",
"The study of belles lettres has always been recommended to the youth of both sexes.",
"Great events and revolutions followed the death of Caesar.",
"The fear of torments made him fly his country.",
"Poland was for many years the seat of domestic divisions",
"Portugal is a despotic kingdom",
"Avarice is despicable.",
"My lord the archbishop, visited all the clergy.",
"My lord the president, decreed it in his behalf.",
"Madam the countess has ordered it.",
"The gentlemen are not yet come to see us.",
"Women are very fair in the northern countries.",
"It is forbidden to do evil.",
"It is not always convenient to speak the truth.",
"It is permitted to a sick person to complain.",
"It is not polite to interrupt any one who speaks.",
"It is right to correct boys whilst they are young.",
"It is a great satisfaction to people of feeling to hear that their friends are in perfect health.",
"It is a great pleasure to see brothers well united together",
"but it is a great grief to see them disagree.",
"It is not always proper to correct children for the faults they commit",
"but it is very necessary to make them sensible of them.",
"It is easy to give advice, but difficult to execute.",
"It is easy to perceive you neglect your business.",
"It was ever commendable to study languages.",
"A dutiful child is a great comfort to his parents.",
"A good wife is an inestimable treasure.",
"A diligent master instructs attentive scholars.",
"A good action deserves great praise.",
"A rash counsel is productive of fatal consequences.",
"My father and mother are very compassionate.",
"Their brother and sister are industrious.",
"Your house and garden are excessively beautiful.",
"My exercise and my lesson are difficult.",
"Our man-servant and our maid-servant are good, and therefore they shall be rewarded.",
"You, your master, and your mistress, have been civil to me, and merit my greatest thanks.",
"France is larger and more powerful than Italy.",
"Virgil wrote more than any other poet.",
"Horace was much more satirical than Juvenal.",
"Your countrymen are much richer than mine.",
"This water is much clearer than crystal.",
"Your sister's hands are whiter than alabaster.",
"The English are more studious than their neighbours.",
"Milton was much more learned than Dante.",
"The Russians behaved more bravely than the Turks.",
"Cicero was less happy than Diogenes.",
"Lewis the Fourteenth was much less admired than Henry the Fourth.",
"London is far better paved than Paris.",
"Venice is much less populous than Naples.",
"Lend me three thousand pounds for a month.",
"I have inherited five hundred guineas a year.",
"I have seven brothers and two sisters alive.",
"The tenth of next month I will pay you.",
"Judas was one of the twelve apostles.",
"William the Third was a great conqueror.",
"Henry the Fourth of France was a matchless warrior.",
"Pope Sixtus the Fifth was a great man.",
"Your master has a fine country-house.",
"Your brother has six fine dapple-bay horses.",
"Your uncle and aunt are my dear friends.",
"Our general was ever reputed a gallant man.",
"Solomon was a wise king.",
"King George is a religious monarch.",
"Nero was a wicked man.",
"Croesus was reckoned a rich prince.",
"The duke of Richmond has six fine grey horses.",
"Spain is a hot country, but Germany is a very cold one.",
"Give me some cold water, and red wine.",
"I like cold weather better than hot.",
"The English ladies are handsomer than the Italian.",
"I always thought he was a troublesome man.",
"This poor man has crooked legs.",
"Will you have a round hat or a cocked one?",
"There is a sickly man, methinks.",
"You are a thoughtful philosopher.",
"The industrious are praised, but the slothful are despised.",
"The righteous find peace but the wicked feel torment.",
"The covetous despise the poor, but the generous cherish them.",
"The merciful shall find mercy, but the cruel shall be punished.",
"The wise man seeks wisdom, but the fool despises understanding.",
"Give me some bread, some wine, some butter, some cheese, some boiled beef, some mutton, some veal, some pork, some pie, some fish, some mustard, some salt.",
"Go and fetch me a bit of the white bread.",
"Send to market to buy me ten pounds of fresh butter",
"Bring directly six pounds of black cherries.",
"Seven hundred of fresh walnuts, and five pounds of hazle nuts.",
"Have you been at Paris?",
"No, but I have been at Rouen:",
"it is a fine city",
"Did you see it?",
"Did you give your brother the book I lent you?",
"No, I gave it to my sister, and she will return it to you when she has read it.",
"Did you tell your father I was in the country?",
"No, sir, but I told my mother, it is all one.",
"God demands the pureness of our hearts.",
"We ought to die for the service of our princes.",
"Those who are desirous of honour, are studious of learning and of good manners.",
"He who is not mindful of his own business, cannot be mindful of other people's.",
"Thou and I are guilty of the same error.",
"I am ignorant of the fact you mention.",
"He whose purse is empty of money, has a house empty of friends.",
"The court which is full of flatterers, is pernicious to a prince, though he be rich in substance and loaded with honours.",
"A journey of twenty miles wearies a horse that is very hungry",
"for while he is wanting food, he goes slowly.",
"Laziness has need of spurs.",
"Those are unworthy of the glory of Heaven, who do not think virtue worthy of love, nor are contented with the pleasure it gives.",
"A son endowed with excellent qualities rejoices his father, whose good example he imitates, whose commands he observes",
"he is never in fear, for he provokes not his father's anger",
"he is always mindful of his own duty, and is like a staff to his father's old age.",
"He who is endowed with fine qualities, and does not behave himself well, is unworthy of men's society",
"Those who are contented with their own condition, are worthy of the name of good Christians",
"but such are very rare.",
"If the city of Naples were encompassed with walls, it would be stronger than it is.",
"England is adorned with the fairest ladies in the world.",
"Our country is surrounded with the strongest bulwarks.",
"Few people are satisfied with the lot that Providence has granted them.",
"Virtue is pleasant to the righteous, and profitable to those who love it.",
"Adoration is due to God, the King of all the world.",
"Honour is due to kings, because God has commanded us to be obedient to them.",
"It is a lamentable thing to see some men of great abilities prone to wickedness.",
"A man who suffers himself to be led by the corrupted pleasures of this world, is not like a Christian.",
"Children are not always like their parents, they are sometimes quite different from them.",
"My father is like my uncle as to his features, and the colour of his hair, but he is not like him in his manners.",
"The most noble of all virtues is charity.",
"The most ingenious people are not always the most learned.",
"The most pernicious of all crimes is slander, it ruins very often the reputation of the most honest people",
"it puts discord between the most intimate friends",
"in short, it is the most abominable crime in the world.",
"The best quality a man can have, is to be civil and obliging.",
"The best friend we can have is money.",
"The best soldiers in the world are sometimes conquered.",
"Buy me the best grapes you see in town.",
"The greatest men in the kingdom confess it.",
"The richest people are not the happiest.",
"The most virtuous women have been guilty of coquetry.",
"We should pay a most particular attention to the moral conduct of our children of both sexes.",
"I entreat you to grant me that favour.",
"What do you desire of me, madam?",
"What do you say?",
"I do not understand you.",
"Don't you speak Italian and French?",
"I understand them pretty well, but when you speak so very fast, I cannot understand you.",
"I ask you if you will do me a favour.",
"With all my heart, if I can conveniently.",
"Have you an Italian Dictionary?",
"Yes, I have Baretti's Dictionary.",
"Will you lend it me for two or three weeks?",
"It is at your service, if you will send for it.",
"Did you see the castle St. Angelo at Rome?",
"Yes, it is very fine, very rich",
"in short, I think it is the finest castle in Europe.",
"Do you think the city of Paris is finer than London?",
"No, it is not so large, nor so well built as London.",
"I love you with all my heart, and if you come tomorrow to see me, I'll give you what I promised you.",
"I will not fail, but I am afraid to be too troublesome to you and your family.",
"Did Mr. N. give you the book you lent him?",
"Not yet",
"but I believe he will give it me soon.",
"When you get it back, will you bring it me?",
"I will do it willingly to oblige you.",
"When will you go to see him at his country seat?",
"I think I shall pay him a visit next month.",
"Bring me your grammar to-morrow.",
"Here it is, sir, I brought it with me.",
"Shew me what you have written",
"That is not well, write it over again, and when you have done, give it to your brother.",
"I think you are very idle.",
"Forgive me, I will be more diligent in future.",
"Reach me that pen-knife, and a clean pen.",
"Write an exercise, and then read it to me.",
"This horse goes better than any of yours.",
"This man is more honest than you think",
"This woman is not so happy as she deserves.",
"This house stands in a most pleasant situation.",
"Those gentlemen seem to be very cold.",
"Those ladies are very modestly drest.",
"My brother is gone into the country for a month.",
"My mother is gone over to France for her health.",
"My countrymen are very great politicians.",
"My sister loves public diversions to excess.",
"My action is not so blameable as you say.",
"Your affection for me is false and deceitful.",
"Her history has made a great noise in the world.",
"Their clock is always out of order.",
"Our house is finer than yours.",
"Their affairs are more perplexed than you imagine.",
"The woman who has a fair face, is loved by all.",
"The girl who brought me my pen-knife, is lovely.",
"The man who bought my house is honest.",
"My brother's hat begins to be worn.",
"The man who struck my father is a butcher.",
"The rewards which are promised shall be given, if the work required, be done the day after to-morrow.",
"The horse which my father sold was very good.",
"The comedy which we acted was pleasant.",
"The wood we bargained for was too dry.",
"The wine which you drank yesterday was excellent.",
"The last lesson you gave me, was very difficult.",
"The company you keep is not honest.",
"I have found the book which I had lost.",
"He who does not fear God, does not deserve to live.",
"He who came this morning, has a great regard for you.",
"He who gave you that counsel, is not your friend.",
"He who lives honestly, is esteemed by all people.",
"He who told you that, did not tell you the truth.",
"He who sold you these boots, did not cheat you.",
"She who is the handsomest, is not always the most virtuous.",
"He who speaks continually, must be very troublesome.",
"She who told me the news, is your great friend.",
"She who is married to Mr. N. is the most lively.",
"She who gave me your letter, speaks Italian very well.",
"He whom you look for, is gone away this morning.",
"He whom you hate the most, is my intimate friend.",
"He whom you have recommended to me, is a great rogue.",
"He whom you saw yesterday, is my sister's lover.",
"He whom God loves, is very happy.",
"She whom you see, is my eldest brother's mistress.",
"She whom I have recommended to you, is modest.",
"She whom I loved most, is married.",
"I saw to-day the gentleman with whom we dined yesterday.",
"Here is the lady for whom I have great respect.",
"Let us go and see the lady with whom we played at cards in the country the other day.",
"The gentleman with whom we were the other day is very ill.",
"There is the horse for which I offered twenty guineas.",
"Shew me the watch for which you gave forty pounds.",
"There is the sword for which I offered six guineas.",
"I thought you could speak Italian better than you do",
"I fancy you are not yet twenty years old.",
"I hope you will not refuse me the favour to recommend me to your friends in town.",
"My uncle told me yesterday you were not well, but I am very glad to find you are better to-day.",
"You promised to write to me last week, but I am very sorry to observe you have forgot me.",
"I desired but one favour from you, and you refused it me.",
"If you would give me but one guinea at once, you would oblige me infinitely.",
"When one has little money, one ought to spend accordingly.",
"I ask you but what others give me.",
"You do nothing but laugh and play.",
"He does nothing but eat and drink.",
"When others laugh, you do nothing but cry.",
"I went yesterday to your house to see you, but your man told me you were not within.",
"Indeed I was there almost all the afternoon",
"at what time did you come?",
"I went there at six o'clock.",
"He was in the right to tell you that I was not within, for I was gone to visit a few friends in the square.",
"My brother and sister are gone into the country.",
"When did they go, I wish to know?",
"They went yesterday morning.",
"Is it long since you saw our regiment?",
"It is two months, if I remember well.",
"How long is it since you left France?",
"It is five and twenty years, or thereabouts.",
"You have three horses, lend me one of them.",
"I have but two, one for myself, and the other for my man.",
"I thought you had three of them.",
"To shew you that I have but two of them, come with me into the stable, and you will not see any more of them.",
"I do not doubt it at all, I believe you.",
"I see very fine flowers in your garden, give me some.",
"I have not many, but what there are, are at your service.",
"I have but fifteen or sixteen, as you see.",
"You may take a dozen, if you please.",
"What will you have me do with them?",
"You may give some to your daughters.",
"Do they talk of the war in your town?",
"They talk of it all over the island.",
"And what do they think of our neighbours' intentions?",
"They know very little about them here.",
"Sir, I come to have the honour to see you.",
"I am infinitely obliged to you for this favour.",
"How does the lady your mother do?",
"She is very well, sir, and presents her compliments to you.",
"I am her most humble servant, and am very glad to hear she is well.",
"Will you come and walk with me in the garden?",
"Pray excuse me, I cannot stay any longer.",
"You are always in great haste when you come to see me.",
"I beg your pardon, sir, I have been here above an hour, and my sister is all alone at home.",
"I am sorry you will not stay:",
"I entreat you to present my most humble respects to the lady your mother.",
"Sir, we were speaking of you, when you came in.",
"What were you saying of me, ladies?",
"We were saying that when you were in France, among the ladies, you were the most gallant, the most courteous, and the most complaisant gentleman in the world.",
"I did not think, ladies, I was so happy as to be the subject of your conversation",
"and what do you think I am now?",
"We believe that you are still very civil, and very complaisant",
"but not so gallant as you were then.",
"Louis the XIVth was one of the greatest kings in the world",
"he was a lover of fine sciences, he did not love flatterers, neither did he always follow his own inclinations",
"and if he could not get the victory over his enemies by the force of his arms, he would get it by the number of his louis d'ors",
"in a word, he was a great politician.",
"Where did you go yesterday, that you were not at home, when I went to see you?",
"I went to see Mr. N. who is not well.",
"Did you meet with any company there?",
"Yes, sir, I met with his uncle and three of his sisters.",
"What was the subject of your conversation?",
"We spoke of many different things.",
"Did you speak Italian with them?",
"Did they say you speak it well?",
"They said nothing about it.",
"Did they not ask you of whom you learn?",
"The emperor, Julius Caesar, after he had conquered Britain, built a tower at London, but he continued not there",
"he appointed rulers in his stead, and returned from London to Rome.",
"Henry the VIIIth, king of England, regarded not the bulls and threatenings which came from Italy",
"he violently shook off the papal power, though he retained the Roman religion.",
"I am very glad to see you, for your brother told me you were gone to France.",
"'Tis true I was resolved to go there, if my father had given me money enough to make that journey.",
"Had he given you leave to go there?",
"Yes, and he gave me fifty guineas to make my journey.",
"If he had given me thirty more, I should have gone to Paris to pass the summer.",
"If you had come to see me, I would have lent you some.",
"I am much obliged to you for it.",
"When you had a mind to go to France, were you resolved to set out without taking leave of your friends?",
"No, sir, I had already taken leave of several.",
"Very well, but you had forgotten me.",
"I am sorry you have so bad an opinion of me.",
"When will you go into the country?",
"I believe I shall go there to-morrow.",
"Will you stay long there?",
"No, sir, I shall stay but two or three weeks.",
"How will you spend your time when you are there?",
"I'll go and see my friends, and I will divert myself with those who receive me kindly.",
"Will you not carry some books with you?",
"No, for I am sure while I am there, I shall have no time to read.",
"You will forget all your Italian.",
"I am certain I shall not, for I will not stay long there.",
"When once you are there, your friends will not permit you to leave them so soon.",
"You shall see that I'll be here next Sunday, and that my friends will not have so much power over me as you think.",
"What will you bring me from the country?",
"I'll bring you some partridges, a hare, and some pheasants.",
"I shall be obliged to you for them.",
"Go from me to my lady",
"present my respects to her:",
"give her this letter, and bring me an answer",
"should she not be at home, stay till she comes back.",
"Speak Italian with me, pronounce well, begin again, read softly, repeat your lesson, go.",
"You have a son who has the finest qualities in the world",
"he has a sweet countenance, a great deal of civility, and very obliging manners",
"in short, he has the love of every body, and you are happy in having such a son.",
"A man is very happy who has the fear of God and the love of his neighbours, though he should not have the riches of fortune.",
"Those who have wealth, and have no charity for the poor, shall not share God's mercy.",
"A man that has wit, and no behaviour, is despicable.",
"I have scholars who have sense, and are diligent",
"but I have others who are dull, and very idle.",
"If you have good manners, civility and complaisance, you will be loved by every body.",
"I was very cold when I came, but am very warm now.",
"You eat as if you were not hungry.",
"I beg your pardon, I eat heartily",
"for I was very hungry.",
"Are you not thirsty yet?",
"Yes, sir, I am very thirsty, but I won't drink yet",
"for if I drink when I am hungry, it prevents me from eating.",
"How old is your uncle?",
"He is not yet seventy years old.",
"You surprise me, I thought he was eighty.",
"And you, sir, how old are you?",
"I am not twenty yet.",
"Our master is diligent",
"but I have been hitherto very idle",
"I have done as the drones.",
"I have lost my parents' love, who always provided all things necessary for me:",
"I have been unworthy of their care",
"but I will deserve to be called the most diligent of all our scholars for the time to come.",
"The lion is accounted the most generous of animals, because he is more placable than the others.",
"The sanguinary minds of some men are more barbarous than wild beasts",
"Man is a creature of upright body:",
"when he is old, his body bends towards the earth",
"and his soul ascends to heaven, which is his habitation for ever.",
"How are you this morning?",
"I am very well, thank you.",
"How do your father and mother do?",
"I hope my father is well",
"He was well the last time I saw him, but my mother has not been well these two or three days",
"And how are you, sir?",
"I should be well enough, if I had money.",
"I hope your lady is well.",
"She is perfectly well, at your service.",
"I am very glad to hear she is so well.",
"What weather is it to-day, I wish to know?",
"It is the finest weather in the world.",
"Is it hotter in Spain than in Italy?",
"It is hotter there in summer, but it is very cold in winter.",
"If it is fine weather to-morrow, we will go in the country.",
"I believe it will not be fine weather, for it is very dark to-night.",
"I have no pity on the misery of those, who being young and strong, love better to beg from door to door, than to work for their bread",
"but I pity much the blind, and old people, who are incapable of doing any thing for their living.",
"I pity my brother, I pity his folly, for he has wasted all the fortune my father left him.",
"Men are often inclined to laugh at others' misfortunes, instead of having pity on them.",
"Those who call themselves Christians, and do not live according to their religion, mock God and his doctrine.",
"Do not jeer at others' poverty, for you do not know how long fortune will be favourable to you",
"and if you should become poor, every one would laugh at you.",
"It is a great mark of folly to laugh at every thing.",
"If you repent sincerely for the fault you have committed, God will forgive you",
"for he does not love the death of a sinner, but he will have him to repent of his sins.",
"It is not enough to say, I repent of my ill conduct, and of my bad life, if you do not shew the effects of your repentance by a new and better life.",
"A good Christian ought never to rejoice at others' misfortunes.",
"I rejoice at the good success you had in your business.",
"Come and rejoice with me at the good news I received to-day.",
"How will you have me rejoice at a thing I do not know?",
"Tell me first of all what news I must rejoice at.",
"Do you remember the promise you made me yesterday?",
"I do not remember it at all",
"Do you not remember the sum of money you said you would lend me?",
"I assure you I had forgotten it, I remember it very well now.",
"He who languishes with thirst, gives greater thanks to the man who offers him water, than if a prince gave him a crown.",
"The man who languishes for love ought to be pitied.",
"We ought not only to obey our parents, but also our superiors, if we would obey God's commands.",
"One sees very seldom a child prosper in this world, who does not obey his father and mother.",
"When God commanded Abraham to sacrifice Isaac, his only son, he immediately obeyed the Lord's voice",
"but the angel of the Lord did not permit him to slay the child, and told him his obedience had been agreeable to God.",
"God speaks to sinners sometimes most gently, that he may draw them to obedience",
"he speaks to them of the blessed life which he has prepared for his servants",
"sometimes he speaks to them of the abyss which shall be the reward of sin",
"yet his promises and threatenings move not stubborn minds.",
"All those who call themselves Christians pretend to everlasting life",
"but few are they that would suffer the least thing to deserve it",
"but if it is a point to aspire to some employment, or dignity, there is none but would suffer a great deal of fatigue, labour, and pain to obtain it.",
"I do not love to play at games of chances, as at cards, or at dice, but I love to play sometimes at bowls, at billiards, at tennis, or at nine-pins.",
"Do you never play at cards, at chess, or draughts?",
"I play sometimes at piquet to please the company.",
"One boy accuses another of idleness",
"the master hears their tales, but punishes him only whom he thinks guilty and deserving of punishment.",
"Every one blames you for your negligence and ignorance.",
"I often admonished you of your duty",
"if you do not improve as well as others, it is not my fault.",
"When a judge acquits a man of a crime he is guilty of, if he commits again the same fault, he deserves a double punishment.",
"Every one condemns you very much for the action you committed the other day.",
"During the persecution in France, many brave gentlemen were condemned, some to the gallows, and some to the galleys, for the defence of their religion.",
"A scholar who obtains his master's favour is more happy than he who is idle, who loses his honour, wastes his time, and continues a blockhead, though play be pleasant to him for a little while.",
"God invites sinners to eternal happiness, he calls them to repentance, he speaks most graciously to them.",
"He has prepared for penitent sinners all that belongs to blessedness, all that they can desire.",
"Remember your master's words",
"he exhorts you to industry, which is beneficial to yourselves",
"your pains shall produce a great advantage",
"he uses his best endeavours for your benefit",
"be not your own enemies.",
"If we compare the longest life to eternity, it is very short.",
"If we compare the happiest condition of this world to everlasting life, it is miserable, and not worthy our desire",
"If we compare the number of good men to the multitude of wicked, it is small.",
"I will soon give my mother the money she entrusted me with.",
"God will give a reward to those men who please him, and to those whom he has set up governors of the world.",
"I returned my master the book which I borrowed",
"he lent it to me, and it was my duty to read it, and not to keep it",
"though books delight me very much, I ought to restore them to those whom they belong to.",
"I owe him money, because I promised to pay him another man's debt",
"but at present I have myself need of money, that I may pay what I owe to my creditors.",
"When will you pay me what you owe me?",
"I promise you I will pay it to you next week.",
"I have been twelve years in this country, during which time I have had the honour of teaching several ladies and gentlemen the Italian language",
"Masters ought to teach children not only the things which concern science",
"but they ought also to teach them things which concern their soul and their salvation:",
"for science without religion is an unprofitable thing.",
"Rash men often propose to do things which are above their capacity",
"A man that abstains from eating and drinking to excess, from swearing, and keeping bad company, may be called an honest man.",
"I thought of going this morning to see Mr. —— but a friend of mine advised me not to go there.",
"I had a mind to advise you not to keep company with that man who brought this trouble upon you",
"but I since resolved to say nothing about it, for fear of disobliging you.",
"I have a mind to compel Mr. —— to pay me the money he owes me",
"nevertheless I should be very glad not to put him to trouble, because he has always been my friend:",
"what do you advise me to do in this case?",
"I beg of you to have a little patience",
"I take the charge to get you your money.",
"God forbids us to sin, nevertheless we never desist from offending him, we always defer obeying his voice",
"we seem to strive to disobey him in every thing",
"If we hope to share in the merits of our blessed Saviour's sufferings, let nothing hinder us from beginning this day to use all our endeavours to deserve it",
"let us make haste to begin the great work of our salvation",
"let us not feign to be converted, but let us convert ourselves in good earnest, for nobody can deceive God.",
"Never meditate to do any wrong to your neighbour",
"When you speak of undertaking some great thing, permit me to tell you, that you ought to consult your friends before you begin it.",
"Never promise to do any thing, unless you are sure to do it.",
"Never presume to have more understanding than those who have the care of your conduct.",
"Do not pretend ever to prosper in this world, if you have not the fear of God.",
"If you protest to God with an humble and sincere heart to amend your life, he will receive you among his children.",
"Never refuse to do a good office to your friends, when it is in your power.",
"Do you desire to pass for an honest man?",
"Endeavour to do all you can to oblige every body.",
"I believe you have a mind to play",
"but I will not give you leave to go out till you have done your exercise",
"You are in the right, sir, to forbid me to go out, and I am in the wrong to desire it—I have no cause to be angry with you, for it is not your custom to be idle.",
"When I have an opportunity to see your father, I will tell him how much you deserve to be praised for your uncommon diligence.",
"Whilst we have it in our power to acquire knowledge, let us improve such precious opportunity.",
"I wonder how men have the heart to hate one another.",
"God has given to kings power to command, and to judges authority to judge.",
"I am very glad to hear that you overcame your enemies, and I should have been sorry to have heard the contrary.",
"I return you many thanks for your friendship, for I was in danger of losing my suit.",
"I was anxious to know what had happened to you",
"and if you had not come, I was on the point of going to see you.",
"We ought to employ the days of our life in preparing ourselves for the other world.",
"Masters who use mildness in teaching their scholars, encourage them more to learn well than those who use too much severity",
"An honest man takes always pleasure in obliging his friends.",
"The love of God invites us to love one another.",
"Let us keep ourselves in readiness to appear before the living God.",
"Let us labour continually to obtain eternal life.",
"There is nothing to fear in serving God.",
"There is nothing to say to what you have done.",
"There is nothing to do in that at present.",
"There is nothing so easy to learn as the Italian language.",
"There is a great deal of satisfaction in teaching diligent boys, but there is a great deal of trouble in instructing idle scholars.",
"There is a great deal to say against the conduct of wicked people",
"but there is nothing to say against the conduct of honest people.",
"He who goes a hunting or visiting his friends, when business requires his care and time, shows by his conduct that he prefers his diversion before his profit, the company of his friends before the advantage of his family.",
"The boy who goes a playing with his school-fellows, when he ought to be diligently employed at the task his master gave him, evinces, by his neglect, that he prefers play to his master's love, and his own profit.",
"The providence of God keeps us from perishing",
"the power of God hinders us from doing those things which displease him",
"the grace of God prevents us from sinning",
"the goodness of God preserves us from suffering afflictions.",
"He who leaves off doing praise-worthy actions, and plunges into vice, was never truly good.",
"A wise man never leaves off learning whilst he lives",
"for he who has great wisdom, has still need of more knowledge.",
"A diligent boy is always learning, not only while the master is instructing, but also while other boys are playing.",
"Apelles was daily drawing some excellent pictures with wonderful art",
"no day passed without a line.",
"Those who do not employ their time well in the beginning of their lives, will be perpetually lamenting their folly",
"they will be incessantly condemning themselves, and saying, Ah!",
"at what a price would I not purchase the time past!",
"I received the books which my brother sent me",
"I read them all, they are very good, and well written.",
"The letter which my father wrote to me is very severe",
"I showed it to my mother, and she is very sorry for it.",
"My dear friends, I have always loved you like my children, I have often admonished you for your own good",
"I have several times exhorted you to practise virtue",
"if you are not truly virtuous, it is not my fault.",
"I met your brother this morning, we embraced one another like good friends, and I rejoice that we are reconciled.",
"The books which I have seen you reading are not good.",
"These are all the copies which you have given me to write.",
"Your brothers have done quite the contrary of what I had advised them to do.",
"It is a lamentable thing to see youths with much wit, and a good disposition to learn, take but little pains to answer the expectations of their parents.",
"Where did you come from?",
"Why did you not stay for me?",
"When will you have done laughing at your friends?",
"Why did you say, I had promised you to go in the country?",
"Where is your father?",
"Is he in town?",
"Where did you buy this fine horse?",
"I bought it at the last country fair.",
"Where are the ladies your sisters?",
"I believe they are gone out to take an airing.",
"Whither are you going so fast?",
"You are in great haste.",
"I go to Mr. Clement's house, for I heard my brother is there, and I have some business with him.",
"You are mistaken, he is not there",
"for I met him just now, and he told me he was going to his sister's house.",
"I was going to your house",
"but since I met you, we will go to my house, where we shall dine.",
"I beg you will excuse me, indeed I cannot",
"for I must go to my lady Arabella's, to pay a visit to her children.",
"They are not at home, for I saw them going into the park.",
"Let us go then and see if your brothers are at home.",
"They are not, I know they are gone a hunting.",
"What is the matter with you, sir?",
"You seem to be grieved.",
"O no, sir, I am not, but I come from Mr. Vincent's, who is very ill.",
"You surprise me, for as I was coming from my house, I met his brother, who did not mention it to me.",
"Do you know from whence he was coming, when you met him?",
"I believe he was coming from his own house.",
"Can you tell me where he is gone?",
"I was assured that he is set out for his uncle's country-house.",
"Which way did you pass, in your way to Italy,",
"I passed by Rouen, Paris, Orleans and Lyons.",
"Which way did you come back to England?",
"I returned by Germany and Holland.",
"Sir, if I knew where you live, I would take the liberty to go and pay you a visit.",
"Sir, you would give yourself too much trouble",
"however, if you do me that favour, you shall be very welcome",
"I live near the Temple, opposite Chancery-lane.",
"I believe my best way to go to your house is to pass by London-bridge",
"You are in the right, sir, since you live behind the Tower.",
"A poor labourer that works from morning till night lives more content and satisfied, than those who have great riches.",
"He who shall be constant even to death, shall have the crown of glory.",
"You will speak Italian well, provided you take pains",
"I tell you so, that you may take courage, and learn well.",
"I remember I told you several times that you will never write Italian correctly, unless you study the rules.",
"I will take so much pains, that I hope I shall write it well before next summer.",
"You will soon perceive the effects of it, provided you follow my directions, though you think the Italian tongue is very difficult.",
"Please God it may be as you say",
"for it would be a great satisfaction to me.",
"I esteem a man very unhappy that has not the fear of God, though he should possess all the treasures in the world, even though he should have all the other fine qualities that can make a man perfect.",
"I always praised you very much before you became so idle",
"and I told you several times that you would lose the good opinion every one had of you, unless you should be as diligent and careful as you were before.",
"When I corrected you for your faults, it was not because I did not love you",
"on the contrary, it was to the end that you should employ your time well, and that you should be more diligent than you are now.",
"Though you began to learn Italian before me, I hope I shall speak it soon as well as you.",
"I do not believe so, unless you have learned all the rules of the grammar.",
"Though I did not learn them, yet I will take so much pains, that what I told you will prove true.",
"It will be some time before you have read them.",
"Would to God I had known you sooner, I should speak Italian well now:",
"and although I had learned when I was young, yet I knew but very little of it, when I began with you.",
"Perhaps it was not your master's fault",
"for before I composed my grammar, I found but few that would learn grammatically.",
"It is true I had a very good master, and if I had believed him, I should have learned by rules, but I found them too tedious",
"and would to Heaven I had followed his advice, for I have a great desire to speak Italian.",
"I will leave you to do that.",
"I wish you may be as honest as your father.",
"I ordered dinner to be ready immediately.",
"That must be done quickly.",
"God permitted it should happen.",
"I am afraid you were mistaken.",
"I believe I shall go into the country this day, but I hope I shall come back this day fortnight.",
"I am sure that when once you are there, you will not return so soon to town.",
"I give you my word that this day fortnight I will come to see you.",
"When will your brother go to Germany?",
"He expects to go this day, if it is fine weather.",
"The French had the name of being the most civil people in the world.",
"I should not like to live among the Spaniards, for they are very jealous people",
"but I should never be tired of living among the English, for I believe they are the most civil the most courteous, and the most obliging people in the world.",
"A good prince should prefer the happiness of his people to his own",
"Happy are the people who have a good prince to govern them.",
"I was told that you speak Italian very well.",
"They do me more honour than I deserve",
"I wish it were true.",
"They say you are going to be married.",
"They say so, indeed",
"but they are much mistaken.",
"I was assured that the lady's father and yours had concluded the articles of marriage.",
"If they say so, it is without any foundation.",
"I am very glad to see you, for I was told you were gone to France.",
"Pray who told you such a falsehood?",
"No matter",
"and we were also told, you were to go to Italy.",
"He who forgets those things which he desires to remember, must use helps to cultivate his memory, or use the greatest diligence and attention when he is reading, that he may retain profitable instructions",
"for when they have once slipt out of the memory, there is need of fresh reading to recall them.",
"All men desire riches, but all do not use riches rightly",
"when they are come to honours and wealth, they are still greedy to heap up more",
"He who desires nothing, wants nothing:",
"it is a wise man's part to restrain his desires.",
"It much concerns young people to avoid bad company, as they would beware of the plague",
"it is more hurtful to the mind, than the most contagious disease to the body.",
"It concerns me, and all men to look to ourselves",
"the world is full of knaves and knavery",
"It is hard to be known, and he is hard to be found, who is fit to be trusted.",
"The greatest caution is to be used in the presence of children",
"masters must behave themselves very warily, lest scholars learn evil of them",
"and it greatly concerns boys to imitate their master's virtues.",
"You promised me several times you would be diligent, and that you would never keep bad company",
"I perceive that you do not speak always the truth, for I met you to-day with a man whose company I forbade you",
"A man who does not delight in speaking always the truth, is unworthy of enjoying the society of honest people.",
"I wish I could serve you, I would do it with all my heart.",
"I wish I could see your sister, I would give her something that was sent to me for her.",
"I wish I could speak Italian as well as you do, it would be a great satisfaction to me.",
"I wish I could do what you desire of me, I would not refuse it you.",
"I wish I could be reconciled with your brother, for he is an honest man.",
"I wish I could go into the country with you, I would not return soon to town, for I would visit all my friends who are there.",
"I wish I could follow your example, I would live better than I do.",
"At church people ought to sit still, and not to talk.",
"At saying lessons, none ought to speak but he who is appointed by the master, whose leave ought to be asked, before the scholars betake themselves to play.",
"The boy who is chastised on account of his slothfulness, has no cause to accuse his master of severity",
"he ought to blame himself, and resolve to shake off idleness for the future.",
"The soldier must fight valiantly, that has a mind enflamed with a desire to conquer the enemy",
"his arm must procure him the honour which his heart wishes for",
"but sometimes secret stratagems and subtle policy defeat the most valiant warriors.",
"Children must be obedient to their parents",
"those that grieve them, purchase to themselves a curse",
"they provoke God to deny them that length of life which he has promised to the dutiful.",
"Children are not always like their parents",
"they are sometimes quite different from them.",
"My brother is not like my father, who is of a mild disposition, and rich in the endowments that adorn the mind, though poor in estate.",
"Every man loves those who like him, and hates those who are hurtful to him:",
"nature teaches us to love our friends, but religion teaches us to love our enemies.",
"I entreat you to be so kind as to tell me how you call that in Italian.",
"If you will be so kind as to grant me that favour, there is nothing but I will do to acknowledge it.",
"If your brother will be so kind as to lend me a horse for two or three days, he would oblige me infinitely.",
"I was this morning with your friend Mr. —— and he was so kind as to offer me his purse.",
"I hope you will be so kind as to recommend me to your friends.",
"Be so kind as to tell me when your sister will return from the country, for I make no doubt but she will bring me news from my uncle.",
"There is nothing but I would do to deserve the honour of your friendship.",
"There is nothing but what I would undertake to oblige my friends.",
"There is nothing but what I would suffer willingly, if I were so unfortunate as to have disobliged you.",
"There is nothing but what an honest man ought to do, to deserve every body's esteem.",
"There is nothing but what a good prince ought to do, to make his subjects happy.",
"You often promised me to do me service, but I will never believe you",
"it is a very dishonest thing not to be as good as one's word",
"for nobody will credit you afterwards.",
"You have often promised me to amend your manners, but you are seldom as good as your word",
"I confess that I have not been as good as my word, but I promise that, for the future, I will behave better than I have hitherto done.",
"Your brother seems to have had a better education than you, though I am sure your father did not spend so much money upon him as he did upon you.",
"If we would love God as much as He loves us, we should not offend him so often.",
"If we would love our neighbour as much as we love ourselves, there would not be so much enmity in the world.",
"As or so long as you are not obedient to your parents, God will not bless you.",
"As long as you are idle, you will never learn any thing, and you will be ignorant while you live.",
"As long as you are rich, you will not want friends.",
"As long as it is in your power to oblige your friends, do not refuse to do them service.",
"I had rather lose some small thing, than go to law with a litigious man.",
"I had rather die than disoblige you.",
"I had rather live all my life-time with you, than stay one day with your brother.",
"I had rather endure a slight injury from a friend, than to fight with him, though I would sooner die than pass for a coward.",
"Pray, friend, what is your name?",
"My name is John Baptist.",
"What is your brother's name?",
"His name is George Frederic Augustus.",
"What was the late king of France's name?",
"He was called Lewis the Sixteenth.",
"What was the queen of France's name?",
"Her name was Mary Antoinette.",
"What was the late regent's name?",
"He was called the duke of Orleans.",
"If you will come with me into the country, I will entertain you very well.",
"You see I do not entertain you like a stranger, but I treat you like a friend.",
"I am sure, if we were lords, you could not entertain us better.",
"It lies in your power to be a good scholar, for you have as much wit as any of your school-fellows.",
"It is in our power to be for ever happy.",
"It is in his power to do me that service.",
"It is in your power to go abroad",
"for your father told me several times he would be very glad to see you go on your travels.",
"It lies in their power to recommend me to their friends.",
"Sir, I come to beg a favour of you, which I hope you will not refuse me",
"I heard your uncle will come to-morrow to town",
"you will oblige me infinitely, if you will lend me your horse to go and meet him, and I assure you that I will take great care of it.",
"Sir, I am very sorry I cannot oblige you, for I must go myself to meet my wife, who is coming from the country",
"but any other time it will be at your service.",
"I am sorry for the misfortune that has befallen you.",
"We ought to be concerned at our friend's misfortunes.",
"I was very much concerned at your loss.",
"I long to see your father to tell him how much you deserve to be praised for your diligence.",
"I long to go into the country, to settle a dispute that arose amongst my farmers.",
"I long to pay what I owe you, for I do not love to be in any body's debt.",
"I long to know the Italian language perfectly well.",
"I long to go and see Mr. George, to ask him for the money he owes me, but I will put it off till next week, that you may go with me.",
"I long to go to Italy, for I do not love to live in England.",
"I long to tell you something, though I do not know how to tell it you, for fear of disobliging you.",
"I long to learn Italian, and for all that I do not know what hinders me from beginning.",
"Be so kind as to hear me a moment, and you will see that what they told you of me is a false report.",
"Be so kind as to grant me that favour, and I will not trouble you any more.",
"I can hardly believe what you tell me of Mr. Gregory, for I always took him for a very sober honest man.",
"I could hardly believe my eyes when I saw you, for I thought you were in America.",
"I have got such a cold, and my head is so heavy, that I can hardly read a word.",
"Scarce were you gone out last night, when your friend, sir William Henry, came to see me, and was very sorry you did not stay a little longer.",
"There are men in the world who are so much used to do mischief, that they are hardly out of trouble, but they immediately fall into another.",
"Scarce have you done a good action, but you seem to repent it",
"for were it not so, you would not so soon again fall into your former ill courses.",
"I had much ado yesterday to persuade your brother to stay with me",
"he would go and sup with Mr. Horace, who came to town last night.",
"I had much ado to make peace with your mother, she was fully resolved not to forgive you, therefore take care for the future not to offend her any more.",
"I had much ado to engage your uncle to pass his word for a hundred pounds I owe Mr. Clement.",
"You will not be quiet till you have done some mischief.",
"Be quiet, or else I will make you repent it.",
"You would not be quiet when I bid you, you see now what you suffer for it.",
"When you speak to a person of great quality, you ought not to stare at him, but you ought sometimes to look down to show him the respect you have for him.",
"From whence had America its name?",
"From Amerigo Vesputio, a Florentine, in 1497",
"though Columbus was the first discoverer of it in 1492.",
"How large is that country?",
"How is that empire divided?",
"What are the productions of it?",
"What is there worthy of notice in that country?",
"Are there any European colonies in that part of the world?",
"Who subdued the greatest part of the world in twelve years time?",
"Alexander, king of Macedonia.",
"To whom do the Canary Islands belong, how many are there of them, and how do they lie?",
"Most men worship love, to it they sacrifice their finest days, and from it they expect their greatest happiness.",
"Glory makes the whole ambition of heroes",
"they thirst after nothing, they seek nothing else",
"they apply to it alone, it is to it alone they make vows.",
"Self-love is our primum mobile",
"it is that which rules our passions, and to it are men indebted for most of the services which they reciprocally render one another.",
"Is that the tree you were speaking of?",
"Yes, that is it.",
"It looks very fine, but its fruit is good for nothing.",
"This, on the contrary, has no appearance",
"it is a peach-tree, and the peaches are delicious.",
"When general G. saw himself pursued so close, he, reaching the river, threw himself in it, with a design to cross it over, rapid as it was",
"when he came to the stream, for all he did to resist it, he could not get the better of it",
"he then resolved to go down with it, and let himself be carried away",
"but his horse was too tired to be able to swim long",
"and as he endeavoured to quit the stream, the animal, which had now lost all its strength, sunk under him",
"he expected it, therefore resigned himself to his fate",
"he still swam with the stream, but not being able to get out of it, he was drowned.",
"The water which you have recommended him to drink is not fit for him",
"I know all its qualities, and will never recommend it in such a case",
"Of these two rivers, one has its spring in the Alps, and the other in the Pyrenees.",
"I have bought a new sword, the hilt of it is silver, but I do not like its shell",
"I will not part with the old one",
"it has done me much service",
"I have twice owed my life to it",
"only I will get it cleaned, and get a new hilt to it, and it will still be of service to me by night.",
"Keep from the wall, do not lean upon it.",
"If you sit in that arm-chair take care you do not hurt yourself, for the back and elbows are broken.",
"His house is fine, I like its situation, but the rooms are not well contrived:",
"he has spent a great deal of money upon it",
"he has altered the roof, and made a stately stair-case",
"it costs him much, but he owes his health to it",
"he lives there the whole year",
"The gardens are very fine",
"he has added groves and water spouts to them",
"there are fine meadows all around:",
"he designs to make still greater alterations.",
"Do you never play at cards?",
"I play sometimes at piquet, and at quadrille, to oblige the company.",
"Let us play for a crown",
"I never play so high",
"I do not like to play for so much money:",
"I do not love to play at games of chance, as at dice, or even at cards",
"but I like to play sometimes at bowls, at billiards, at tennis, or nine pins",
"We play at chess every night, my cousin and I",
"Can you play on any instrument?",
"I can play a little on the flute",
"I thought you could also play on the fiddle",
"No:",
"but I know that you play very well on the bass-viol:",
"if you please to come to our house, we will make a little concert:",
"my sister will play on the piano-forte, you on your bass, and I will sing.",
"You eat as if you were not hungry",
"Excuse me, I eat well enough, but I am not very hungry",
"I am more dry than hungry",
"I have been thirsty all day.",
"I am very cold, and very hungry.",
"Are you cold?",
"On the contrary I am very warm, but I am tired.",
"My hands are so cold that I cannot write.",
"I believe your head is always cold, for you seldom pull off your hat.",
"How old is your sister?",
"She is not fifteen yet.",
"I thought she was twenty",
"and you, sir, how old are you?",
"I was very cold this morning when I came:",
"but I am very warm now.",
"You do not look so.",
"You eat as if you were not hungry.",
"I am more cold than hungry.",
"I have been thirsty all the day.",
"To make war plenty of money must be had.",
"Men must love virtue to be happy.",
"One must be mad to think that men can be happy without loving virtue.",
"Men should learn first the duties belonging to human nature.",
"A woman must have a good deal of circumspection not to speak of herself.",
"One must not hope to see men cured of the ill-habit they have of speaking always of themselves, their adventures, and wealth",
"for nothing is more tiresome.",
"One should impose upon one's-self a law never to speak of one's-self neither one way, nor another.",
"We must not easily believe those who flatter us:",
"neither must we reject entirely the compliments that are paid to us, when we think we deserve them",
"that mistaken modesty is hardly less displeasing, than a foolish vanity.",
"Much art and nicety are requisite to season praises well:",
"but there is also a way of receiving them, when they are merited, that does not displease modesty.",
"Praises are like a sort of tribute paid to true merit:",
"we must neither reject them through affectation, nor hanker after them too eagerly.",
"No one knows the sufferings of lovers, unless he himself has loved.",
"I have always loved her very much.",
"To court with respect and attention, is the best means of being loved again.",
"I have found nobody of your opinion.",
"I by no means believe what he says",
"nor I neither.",
"She always comes unseasonably, as well as her sister.",
"He has not yet received an answer.",
"Is there any thing more wonderful, than the virtue of the loadstone?",
"Did he ever mention it?",
"We have done nothing that ought to make you angry.",
"I am going there, lest he should come.",
"I tell you, that, if henceforth I perceive that you attempt to play any trick to hinder me from marrying my son, I will complain to the magistrate, and get you punished severely.—I promise you I will never do it.",
"She is indifferent to me",
"and I neither love, nor hate her.",
"Now that they are under my care, they behave very prudently.",
"She has neither relations, nor friends.",
"I will never forgive you, unless you promise to see her:",
"she is so ill that she can take nothing, neither can she have any rest.",
"I will not take any physic before the winter is quite out.",
"Why does he not boldly tell her his reasons?",
"He knows not where to meet her now.",
"I ask nothing but what is just",
"I cannot pay others, if I am not paid what is due to me.",
"Although I have no money, I cannot resolve to borrow any of my friends.",
"Obey, or else you shall be whipped.",
"When I punish you for your faults, you think I hate you",
"whereas it is only because I love you, I take that trouble.",
"Your brother came to see me yesterday as soon as you were gone.",
"If he come again, be so good as to tell him that I have waited for him till now.",
"Though I used my utmost endeavours, and neglected nothing to please him, yet he was constantly scolding me.",
"That Adriana, whether she is Pamphilus's wife, or whether she is but his mistress, she is always with him.",
"Either through reason, or caprice, she has married him.",
"Wars are not so bloody since the invention of gunpowder.",
"Unless a book be instructive or entertaining, I do not wish to read it.",
"Whether she is writing, or reading, she will have her parrot with her.",
"Since you have forbidden him, he does it no more.",
"If he should call at my house, while I am out, my people would tell him where I am.",
"Whether he wins, or loses, he is always the same.",
"I will not go there, unless you go along with me.",
"You must not play before you can say your lesson.",
"Why do you not learn it then, instead of losing your time?",
"He is so far from being forward, that he knows nothing at all.",
"Far from following my advice, he does not mind what I say to him.",
"I will rather consent to lose all, than give up my right.",
"Though you were a king, I would not marry you.",
"Would to God I still were under his tuition, and my father had never removed me from his school.",
"It avails nothing to a girl to be young, without being handsome, nor to be handsome without being wise.",
"After you have done your exercise, you must read it over two or three times, to correct the faults you may have made in it.",
"Remember what I told you several times, that you will never be able to speak, or write Italian, unless you are master of the rules.",
"I will take so much pains that I hope I shall speak it before it is long",
"though I am convinced it is very difficult to learn the Italian tongue perfectly well.",
"You will not find it so hard, if you learn the rules well.",
"The narrowness of the mind, ignorance and presumption produce stubbornness",
"because obstinate people will believe nothing but what they understand, and they understand but very few things.",
"I rather choose to live in the country than in town, especially at Florence:",
"therefore I intend to set out to-morrow for my country-house, and then I will send my eldest son to Sicily for the summer.",
"Where will you go to-night?",
"To the play.",
"When shall I dance, sir?",
"You shall dance in your turn, and not before.",
"Where do you live, sir?",
"I live in St. James's street, near a fruiterer's, opposite a tailor's.",
"The best way to go to my house, is to pass through the Park, since you live in Westminster.",
"I intend to travel first all over England, and France, and then to Germany, and Italy",
"from Italy to Spain, where I shall embark to return to England.",
"I shall go to Scotland in six months, or thereabouts.",
"I will call upon your partners within twelve days",
"and I will wait upon them as far as their seat, which is magnificent",
"were you ever there?",
"Yes.",
"The walls are inlaid with marble",
"the stair-case is painted in oil",
"all the furniture is worked with the needle",
"in short, nothing richer can be seen.",
"I should be very glad to spend a few days at that wonderful seat.",
"How far is it?",
"It is a great way:",
"it is about a hundred and twenty miles off.",
"The most uneasy situation is between fear and hope.",
"Heroes formerly sacrificed themselves for their country and their mistress",
"now-a-days nothing is done but for fortune and pleasure.",
"A woman can please without beauty, but she can hardly do it without sense and amiability.",
"There is no less eloquence in the tone of the voice, the eyes, and the countenance, than in the choice of words.",
"Europe, in relation to the other parts of the world, lies northward",
"it is bounded on the east by Asia, and the Black Sea, which communicates with the Mediterranean by the Straits of Constantinople",
"on the south by Africa, from which it is separated by the Mediterranean Sea",
"on the west by the Atlantic ocean",
"and on the north by the Frozen Sea:",
"its extent taken from Cape St. Vincent to the frontiers of Asia, is about 3,600 English miles:",
"and from Cape North to Greece is about 2,200 miles.",
"France has Spain towards the south, from which it is divided by the Pyrenean mountains, which are of a surprising height, and extend from the ocean to the Mediterranean",
"a tract of about 220 miles.");

	function firstItalianLine()
	{
		global $italian1lines;
		return $italian1lines[array_rand($italian1lines)];
	}
?>