<?
// https://archive.org/details/englishitalianph00walluoft/page/16
// English-Italian phrase book for social workers
// Edith Waller
// 1916


	$italian2lines = array(
"What is your name?",
"What is your last name?",
"What is your address?",
"On what street do you live?",
"What is the number?",
"I live at 62 James Street.",
"On what floor do you live?",
"I live on the fifth floor,",
"How old are you?",
"In what year were you born?",
"I am thirty years old.",
"I was born in 1883.",
"Are you an American citizen?",
"Have you your papers?",
"When did you obtain your First Paper?",
"When were you married?",
"I was married in 1905.",
"I was married in 1907.",
"What was your name before you were married?",
"My name was Nina Pellegrino before I was married.",
"How many children have you?",
"I have four children.",
"Is this your boy?",
"How old is this little girl?",
"She is three years old.",
"He is four months old.",
"How old is the youngest?",
"Will you please give me their names and ages?",
"When was he born?",
"He was born the eighth of March, 1912.",
"In what parish was he christened?",
"Have you his birth certificate?",
"No, but I can get it from the priest.",
"When did she die?",
"She died July eleventh, 1908.",
"Of what did she die?",
"She had tuberculosis.",
"What undertaker did you have?",
"Have you paid all the burial expenses?",
"How many of your children are married?",
"Two of them are married.",
"Where does your married daughter live?",
"Does she live with you?",
"She lives in New York.",
"On what street does he live?",
"Where were you born?",
"When were you born?",
"I was born in Naples in 1888.",
"What church do you go to?",
"I go to the Catholic Church.",
"To what parish do you belong?",
"Do you belong to any church?",
"Are you a Protestant?",
"Do you go to the Catholic Church?",
"Have you asked help of your church?",
"How long have you been in this country?",
"I have been here three months.",
"Have you relatives here?",
"Yes, my brother is here.",
"Does he live with you?",
"Who else lives with you?",
"My mother lives here with us.",
"Where does he live?",
"Where do they live?",
"Are there no others?",
"Have you anyone to help you?",
"I have an uncle and an aunt.",
"Have you been to them for money?",
"Can't they help you?",
"Perhaps they could, if you asked them.",
"You should ask them to help you.",
"Why don't you ask them to help you?",
"How much do you earn a day?",
"I earn a dollar and a half a day.",
"How much a week does your husband earn?",
"About how much does it cost you to live each week?",
"We spend about ten dollars a week.",
"How much do you have to spend a month for food?",
"Do you need help?",
"Can I do anything for you?",
"What is it that you need?",
"What is the matter?",
"Let me know if I can help you.",
"Have you any money?",
"Have you food in the house now?",
"How long will it last?",
"Here is an order for two dollars' worth of groceries.",
"Present this at H.O. Smith's, and he will give you what you need.",
"What kind of coal do you burn?",
"We will send you a ton of coal today.",
"You must pay a small amount for the clothes.",
"We do not give them away.",
"Have you shoes?",
"These are worn out.",
"What size do you wear?",
"We can give you work splitting wood.",
"Show this ticket to the superintendent.",
"We can give you work in the laundry.",
"Do you know how to sew?",
"We can give you some sewing to do.",
"You can leave the baby at the Day Nursery.",
"He will receive good care there.",
"They will give him dinner there in the middle of the day.",
"You must call for him before six o'clock.",
"How much rent do you pay a month?",
"We pay twelve dollars a month rent.",
"How many rooms have you?",
"That is very dear for rooms like these.",
"You pay too much.",
"Who is the landlord?",
"Does he keep your rooms in good repair?",
"When do you pay your rent?",
"Do you have to pay in advance?",
"How much do you owe now?",
"We shall owe seven dollars at the end of the week.",
"Has the landlord served a dispossess notice yet?",
"He cannot put you out until he has given you a three days' warning and five days besides that.",
"Different places are governed by different regulations",
"He cannot put you out just because you have not paid advance rent.",
"We will lend you the money to pay your advance rent.",
"Please give me a receipt.",
"Sign your name here.",
"Be sure to get a receipt from the landlord.",
"Without a receipt you might have to pay twice over.",
"How long have you lived here?",
"Do you like it?",
"We have lived here nine months.",
"We do not like it.",
"We should like to find better rooms.",
"Can't you find better rooms?",
"Where have you tried?",
"Have you tried on Fourth Street?",
"Is there no place for the children to play except on the street?",
"Are these rooms damp?",
"Is there water in the cellar?",
"You should notify the Board of Health.",
"This is very unhealthy.",
"You will all be sick.",
"If you stay here, you will have malaria or rheumatism.",
"These rooms are too dark.",
"How many windows are there?",
"There are only two windows.",
"Can you open them at the top?",
"No, they stick so that we cannot open them.",
"If the windows are open at the top, you will have fresh air and you will not be in a draught.",
"Have you closets to put your clothes in?",
"Have you running water?",
"Have you hot and cold water.",
"Is the plumbing in order?",
"Does this pipe leak?",
"Yes, it leaks badly.",
"What is the matter?",
"Does the gas escape?",
"Won't the landlord have it fixed?",
"He should do so.",
"Have you asked him to do it?",
"Why does that fire smoke so?",
"Can't the pipe be fixed?",
"Are you paying for this furniture by the week or by the month?",
"It does not pay to buy furniture on the installment plan.",
"What you get is usually cheaply made, and it wears out soon.",
"Besides you pay more than double what it is worth.",
"How much do you owe now on this sewing-machine?",
"Do you take boarders?",
"How many boarders have you?",
"We have four men boarding here.",
"Where do they sleep?",
"How many extra rooms have you?",
"How much do they pay for the room?",
"Do you give them their meals as well as a room?",
"How much do they pay for meals?",
"Do they pay promptly?",
"Does he pay at the end of each week?",
"Do you board there?",
"With whom do you board?",
"I board with Mr. Scala.",
"You must try to be independent.",
"I am sure that you want to be self-supporting.",
"Are you in debt now?",
"How much do you owe?",
"You must save your money for the time when you will need it.",
"Put by something each week, then you will have it when you are in need.",
"Do you put your money in the bank?",
"You can get 3 per cent, interest on it.",
"Are you insured?",
"In what company are you insured?",
"Are the children insured?",
"How much do you have to pay each week?",
"What will your family receive in case of your death?",
"What will you receive when he dies?",
"Will you let me see your policy and your insurance book?",
"Do you belong to a Lodge?",
"Are you a Mason?",
"Do you belong to the Union?",
"What society do you belong to?",
"What are the dues?",
"How often do you have to pay them?",
"How does it benefit you to belong?",
"Is there a sick benefit?",
"How much will you get each week, and for how long?",
"How much have you had already?",
"What reform school is your son in?",
"Why was he sent there?",
"How long has he been there?",
"When will he be allowed to come out?",
"What is the name of the institution to which he has been sent?",
"The judge has put him on probation.",
"If he does not behave, he will be sent to the reform school.",
"If you are kind to him, I am sure that he will do better.",
"If you keep telling him how bad he is, he will become indifferent.",
"Gain his confidence, and he will do what you want him to.",
"You must not make him work so hard.",
"He is too young.",
"Let him have some of the money that he earns himself, even if it is only twenty-five cents a week.",
"See that he has good companions.",
"When did your husband leave you?",
"How long has he been away?",
"Don't you know where he is?",
"Where do you think he is?",
"Why do you think he went?",
"Have you tried to get him to come back to you?",
"Didn't he treat you well?",
"How much money was he giving you before he left?",
"How much was he earning?",
"He can be compelled by law to support you.",
"You will have to go to Court to make a complaint against him.",
"He will have to pay you a certain amount each week for the support of the children.",
"Food here is different from that in Italy.",
"Some foods are much more nourishing than others.",
"Children (over eighteen months old) should have plenty of good milk, cereals, stewed fruit, vegetables, soft-boiled eggs and soup.",
"A good breakfast for a child is milk, a cereal cooked at least an hour, and stewed fruit.",
"A good dinner for a child over three is broiled or roasted meat, potatoes or rice, bread and butter, fresh vegetables and stewed fruit.",
"A good supper for a child is milk, cereal and stewed fruit.",
"Coffee and tea are very bad for children.",
"They are not nourishing, and they only make them nervous.",
"Wine and beer are not good for children.",
"Milk is what they need to make them strong; but it must be fresh, pure milk.",
"Pastry, hot bread and fresh bread are very bad for children.",
"Bread for children should be two days old.",
"Food fried in grease, especially grease that is not fresh, is very bad for children.",
"Do you give these children pennies for candy?",
"It will spoil their teeth and ruin their stomachs.",
"These cheap candies are almost like poison, and some of them are poisonous.",
"They are colored with all kinds of dangerous material.",
"Can't you give them fruit instead?",
"It is much better for them.",
"Be careful that they eat only ripe fruit.",
"It is very important to have their meals at regular times during the day.",
"It is bad for them to eat between meals, as this gives the stomach no chance to rest.",
"Children should eat slowly and chew their food thoroughly.",
"It is a good thing to drink plenty of pure water between meals.",
"It is best to keep food covered all the time.",
"When food stands around, the flies get into it.",
"Doctors have found out that flies carry disease.",
"They go from a person who has some terrible disease and carry that disease to people who are well.",
"This settlement is not connected with any one church.",
"It is a home for people of the neighborhood to come to.",
"We want especially to help the young people; to teach them, to strengthen them morally and physically.",
"We want to give them a wholesome good time, to help make their daily lives better and happier.",
"We are going to have a Mothers' Meeting today at four o'clock.",
"Can't you come?",
"We want all the mothers.",
"Bring the baby if there is no one to look after her.",
"Some one is coming to talk to us about how to bring up children.",
"We are going to have some magic lantern pictures and music",
"Can't your daughter come to the cooking-class?",
"What one likes, one can always do best.",
"Can you do anything else?",
"What did you do in Italy?",
"I was a cabinet-maker.",
"Can't you get the same kind of work here?",
"I don't know where to go to find it.",
"Where can I get work of that kind?",
"Have you tried to get anything else to do?",
"Yes, I have tried, but I have not succeeded.",
"Can't you find work with someone else?",
"I should like to, if possible.",
"Didn't you learn a trade?",
"Can't you learn a trade?",
"I am afraid it is too late now.",
"If you learn a trade, you can earn more and you will be brought in contact with more intelligent men.",
"It will pay you in the long run.",
"Have you put a notice in the newspaper, stating that you want work?",
"No, I had not thought of doing that.",
"Have you tried to get work on a private place?",
"There are many people here, who have large places outside of town, who have need of just such men as you.",
"Have you a reference from your last employer?",
"No, he did not give me any.",
"He would not give me any.",
"Can't you get one?",
"I don't know.",
"I will try.",
"A recommendation from a former employer is always a good thing to have.",
"Won't Mr. B. give you a reference, if you ask him?",
"Your reference should state that you are honest, sober and a good worker.",
"Didn't Mr. B. pay you all that he owed you?",
"No, he still owes me for two weeks' work.",
"Are your parents living?",
"Are they in this country?",
"Have you any brothers and sisters?",
"Have you had breakfast?",
"Have you a brush and comb?",
"You must comb your hair.",
"Ask your mother to fix your hair.",
"You must come here clean.",
"You must be clean all over.",
"Ask your mother to put clean underclothes on you.",
"You cannot come unless you are clean.",
"You must clean your teeth.",
"Have you a tooth-brush?",
"The Boy Scouts learn to take care of themselves, whatever happens, and to help others.",
"They are always gentle and courteous toward women and children.",
"They are kind to animals.",
"They try to do at least one kind deed every day.",
"They are honorable.",
"How are you?",
"How do you do?",
"I am glad to see you.",
"Won't you sit down?",
"I am well, thank you.",
"How are you?",
"Very well.",
"Please.",
"Thank you.",
"You are welcome,",
"It is nothing.",
"I am sorry.",
"You are right.",
"You are wrong.",
"No matter.",
"Be quiet.",
"Pay attention.",
"Take your time.",
"Good morning.",
"Good evening.",
"Good-bye.",
"Preserve for Italy a faithful love and remember that you come from a glorious land, and in doing well you honor your forefathers and fellow-countrymen.",
"Become a citizen of your adopted country.",
"Take out your first paper at once and your naturalization paper as soon as you can, so that you may become a real part of this great land.",
"Learn the English language.",
"No man unable to read or write the English language can become an American citizen.",
"Go to night-school and learn to write, read and speak English.",
"Vote honestly and carefully.",
"Never sell your vote, but vote for the man who you think is best fitted to govern.",
"Go into the country.",
"For the sake of yourself and your children, try to get work in the country and make your home there.",
"Save your money and put it in a savings bank.",
"It is dangerous to carry money in your pockets or to keep it at home.",
"Send your children to the public school.",
"The law requires you to keep your children in school until they are at least fourteen years old; their welfare requires that you keep them there as long as you can afford it.",
"Do not put your children to work while too young.",
"It is against the law for a child to work in a factory or shop.",
"Parents who put their children at work too young, sacrifice them.",
"Respect the laws of health.",
"Try to keep your house and your street clean.",
"The law forbids spitting in public places.",
"America welcomes men of every race and religion; try to live in harmony with your brothers of races and religions different from your own.",
"Do not forget that here all men have to consider them- selves as brothers to each other.",
"Why don't you send Joseph to school?",
"I kept him home because he was sick.",
"What was the matter?",
"Is anything the matter with him now?",
"He had a cold, but he is better now.",
"Did the doctor see him?",
"No, I did not call a doctor.",
"This boy has been absent for three days.",
"Why do you keep him away from school?",
"He has no shoes to wear.",
"You must get him a pair of shoes and some rubbers when your husband is paid at the end of the week.",
"You must send your boy to school.",
"It is against the law for him to work.",
"It is against the law for him to work until he is fourteen.",
"I can have you arrested for not sending him, and you will be made to pay a fine.",
"He must go to school regularly or he will not learn anything.",
"If your boy has a good education, he can obtain better work than digging ditches.",
"He will be better paid, if he is well trained.",
"He will get along better.",
"You should be glad that he can have an education without expense to you.",
"He looks like a bright boy.",
"He should be given every opportunity to make something of himself.",
"Don't you like to study, Joseph?",
"What do you like best.",
"Do you like your teacher?",
"Your teacher speaks well of you.",
"What are you going to be when you grow up?",
"You must study hard and do your best.",
"How old is this girl?",
"She is seven years old.",
"She is old enough to be sent to school.",
"Children must go to school from seven to fourteen.",
"What do you do?",
"I am a gardener.",
"What is your occupation?",
"What is your trade?",
"I work in a greenhouse.",
"Where did you work before?",
"I worked for a gas company.",
"What did you do?",
"I dug ditches and laid pipes.",
"How long did you work there?",
"I worked there three years and two months.",
"What firm did you work for?",
"I worked for the Public Service Gas Company.",
"In what factory did you work?",
"I worked at Brown's Hat Factory.",
"Who was the foreman?",
"For whom do you work now?",
"Do you like your employer?",
"Is he fair with you and considerate?",
"No, he is always taking advantage of the men under him.",
"How many men does he employ?",
"He has fifty under him at present.",
"When does he pay them?",
"They are paid every Saturday.",
"Are they paid by the day or by the week?",
"Does he pay his men regularly or does he make them wait for their money?",
"He usually pays on time.",
"How much do you earn a day?",
"I earn $1.75 a day.",
"Are you well paid?",
"No, I am trying to get something that pays better.",
"Can't you find something that pays better?",
"I don't know.",
"Do you like your work?",
"No, I should like to be with a carpenter instead.",
"She will make a good housekeeper, if she learns what is the best food to buy and how to prepare it.",
"Everyone must have a ticket to belong to this club.",
"It costs ten cents a month.",
"Only those who have tickets will be admitted.",
"Won't you let Maria come?",
"We will take good care of her.",
"Someone will go home with her afterwards.",
"She needs to have a good time once in a while.",
"She will be a better girl for it.",
"Do not let her go to the public dance hall without you.",
"This child is too young.",
"Children must be three years old to come to Kindergarten.",
"Why don't you keep these children clean?",
"Can't you bathe them every day?",
"They will be sick, if they are not kept clean.",
"You must send this child clean to Kindergarten.",
"His whole body should be clean as well as his hands and face.",
"He must have a clean suit and clean underclothes.",
"He cannot come unless he is thoroughly clean.",
"These children should brush their teeth night and morning.",
"They will suffer with toothache, if they do not.",
"It is very important to keep the mouth clean.",
"A dirty mouth causes indigestion.",
"Perhaps I can help you.",
"Come to see me.",
"Come any time that you like.",
"You must not come so early.",
"Come up one at a time.",
"What is your father's name?",
"What does your father do?",
"How much more does he owe you now?",
"He doesn't owe me anything more now.",
"Can't you refuse to work for him until he pays you?",
"No, if I do, he will discharge me.",
"Isn't there someone who will speak to him in your behalf?",
"I don't know of anyone who would do so.",
"Can't you get another man to work with you?",
"Don't you know of someone else who needs work?",
"If you really wanted work, you could get it.",
"Will you take any job offered you?",
"Have you been to the foreman to ask if there is some work on the railroad?",
"No, I have not been to him.",
"I have heard that he needs men.",
"He is usually to be found near the station.",
"Ask for Mr. K.",
"It is work that does not pay very well, but it is steady.",
"The men work every day that it is clear.",
"If it rains hard, they cannot work.",
"They earn $1.75 a day.",
"What experience have you had?",
"I have worked at gardening for the past three years,",
"Do you know the names of the different plants and the care that each requires?",
"Have you your own tools?",
"No, I have no tools with me.",
"Do you know what each tool is for?",
"Do you understand how to run this machine?",
"No, I have never run one like this before.",
"Do you know how this works?",
"No, will you please show me?",
"All ready?",
"All right!",
"All together!",
"Be careful.",
"Be careful where you step.",
"Be quick.",
"Be quicker.",
"Bring it here.",
"Call out when you are ready.",
"Can you do it?",
"Yes, I can.",
"No, I can't.",
"Clear the edge of the car when you lower the bucket.",
"Come here.",
"Cover this up.",
"This is crooked.",
"Make it straight.",
"Dig this out here.",
"Do it this way.",
"Don't do it that way.",
"That is not the right way to do it.",
"Don't do it alone.",
"Don't push so hard.",
"Drive close to the car.",
"Drop it.",
"Dump this out.",
"That's enough.",
"Fill this hole with dirt.",
"Find the foreman.",
"Find out what he wants us to do.",
"Fix it right.",
"Get out.",
"Get out of the hole.",
"Get a pick.",
"Get ready.",
"Get someone to help you.",
"Get up.",
"Get down.",
"Go over there.",
"Go right away.",
"Go slowly.",
"Grab hold of it.",
"Grip the rope high up.",
"Hammer that in.",
"Harness the horse to the yellow wagon.",
"Haul those stones away.",
"Hit it hard.",
"Hit it here",
"Hoist it up.",
"Hold on tight.",
"How shall I do it?",
"Hurry up!",
"You'll get hurt, if you don't look out.",
"Jump off.",
"Jump on.",
"Knock it off.",
"Give it a quick blow.",
"Let go.",
"Let it fall",
"Let it slide.",
"Let out the rope.",
"Let me know.",
"Level it off.",
"Lift it up there.",
"Load up the car.",
"Look out!",
"The dynamite is going off.",
"Look out for the men below.",
"Look what you are doing.",
"Lower the bucket.",
"Make a heap of stones here.",
"Make sure you do it right.",
"Make way for the wagon.",
"Manage it carefully.",
"Mix this sand and cement with water.",
"Never mind just now.",
"Pay out the rope.",
"Pick up that shovel.",
"Pour out this water.",
"Pull this chain.",
"Pull that down.",
"Push hard.",
"Put it further up.",
"Put it where belongs.",
"Put your crowbar under it.",
"Quit work.",
"Raise this up.",
"Ready!",
"Pronto!",
"That's right.",
"Run away.",
"Screw this up.",
"Shove hard.",
"Stamp it down.",
"Steady the rope as it comes down.",
"Stick your crowbar under the rail.",
"Stop!",
"Straighten it.",
"Stretch it out.",
"Take care.",
"Take out these tools.",
"Take these stones away.",
"Tie it tight.",
"Tighten the knot.",
"Try again.",
"Try the rope to see if it is secure.",
"Turn it around.",
"Turn the water on.",
"Turn it off.",
"Turn it to the right",
"Turn it to the left",
"Turn it over.",
"Twist it in this direction.",
"Do you understand?",
"No, I don't.",
"Yes, I do.",
"Undo this string.",
"Watch for the signal.",
"What do you want?",
"What do you say?",
"What is it?",
"When do you want it?",
"Which shovel do you like?",
"Which tool do you need?",
"Who is calling?",
"Wind it up so.",
"On what day were you hurt?",
"At what time of day?",
"How did it happen?",
"Was it your fault?",
"Whose fault was it?",
"Was the machinery protected?",
"Did you understand how to run it?",
"Were the rules of the shop posted where you could see them?",
"Did you have any agreement with your employer beforehand as to what he would do if you were hurt?",
"What did he promise to do?",
"Was the agreement written or verbal?",
"How long have you been disabled?",
"Can you work at all?",
"How long at a time are you able to work?",
"Just what are you able to do?",
"Has a doctor examined you?",
"Did you get a written statement from him as to just what is the matter with you?",
"Your employer must pay for this examination.",
"You should have an X-ray taken in order to find out if any bones are broken",
"What has your employer done for you since you were hurt?",
"How much of your wages did he pay you?",
"For how long?",
"When did he begin?",
"When did he stop?",
"Did he pay the doctor's bill?",
"Did he pay for your medicine?",
"Did he pay the hospital bill?",
"How long were you there?",
"Have you seen a lawyer?",
"What lawyer?",
"Do you know who he is?",
"Be sure to go to a good lawyer, I can recommend one if you like.",
"If you are totally disabled he must pay more.",
"You must have a doctor.",
"Call him at once.",
"I will telephone him now.",
"Do you want a doctor?",
"Yes, I should like to have a doctor see him.",
"If he does not feel better by tomorrow, you should have a doctor see him.",
"What doctor do you have?",
"Shall I telephone him to come?",
"Why don't you try Dr. B.?",
"I will telephone him to come as soon as he can.",
"He will probably not get here till this afternoon.",
"You will have to pay him a dollar for his visit.",
"His office fee is seventy-five cents and he charges one dollar for a visit to the house.",
"Good morning.",
"Who is sick?",
"Where is he?",
"What is the matter with him?",
"What is the matter with you?",
"How do you feel sick?",
"What hurts you?",
"Where is the pain?",
"When were you first taken sick?",
"When did you first notice the rash?",
"Show me.",
"Tell me.",
"Is it here?",
"Does it hurt when I do this?",
"Have you a headache?",
"Yes, I have a bad headache.",
"Are you feverish?",
"Let me take your temperature.",
"Let me put the thermometer under your tongue.",
"I won't hurt you.",
"Open your mouth.",
"Close your month.",
"Let me look at your tongue.",
"Stick out your tongue",
"Have you a good appetite?",
"Do you eat very heartily?",
"Have you a cold in your head?",
"How long have you had it?",
"Do you have night-sweats?",
"Have you a sore throat?",
"Say \"Ah.\"How long has your throat been sore?",
"Does it hurt you to eat?",
"Do you vomit?",
"Do you cough much?",
"Where does it hurt you?",
"It hurts me to breathe.",
"Does your heart beat fast?",
"Let me feel your pulse.",
"Have you a pain over your heart?",
"Do not walk up and down stairs.",
"Do you ever become dizzy?",
"Do you have backache?",
"Please get me some warm water.",
"I must have it at once.",
"No, this will not do.",
"That is enough.",
"Do as I tell you.",
"Do as he tells you.",
"You will not get well if you don't do as you are told.",
"Raise his head.",
"Lower his head.",
"That is too high.",
"That is too low.",
"Be gentle.",
"Not too fast.",
"Keep quiet.",
"Do not move.",
"Lie still.",
"Do not cry.",
"Be brave.",
"Be careful.",
"Roll over to the right",
"Roll over to the left",
"Roll over on your face",
"Roll over on your back",
"Roll over on your side",
"Tell me later, not now.",
"I will explain it to you later",
"Do not tell him what is the matter.",
"It is better for him not to know.",
"Open the window top and bottom.",
"Let him get all the air he can.",
"Do not touch it.",
"Leave it alone.",
"Taste it to make sure it is right.",
"Empty this out.",
"Throw this away.",
"Burn it",
"Burn them",
"Heat a plate.",
"Wrap it in a piece of flannel.",
"Put it on his stomach",
"Do not make him drink till he becomes conscious.",
"He cannot swallow now.",
"This woman must be kept quiet.",
"She needs fresh air.",
"She cannot breathe with so many people near her.",
"Keep away.",
"You must all go out.",
"To make a mustard plaster, mix a teaspoonful of mustard, four teaspoonfuls of flour, and enough cold water to make a paste.",
"Spread between two thin pieces of muslin.",
"Warm before applying to the body.",
"On removing the plaster, grease the skin with vaseline.",
"Have you medicine?",
"Take two teaspoonfuls of this medicine every half hour",
"Take two teaspoonfuls of this medicine every half hour before going to bed at night",
"Shake well before using.",
"Be sure to take this medicine regularly.",
"Take only one pill at a time",
"It is very strong.",
"It will hurt you if you take more.",
"Dissolve this powder in half a glass of water.",
"How did the medicine affect him?",
"How many doses did you give him today?",
"Have this prescription filled at the drug store.",
"Have you the money to pay for it?",
"Can't you borrow some?",
"I will see that it is paid for.",
"You can repay it later.",
"Never mind, I will look after it.",
"Be calm.",
"Everything will soon be all right.",
"I will call the ambulance.",
"We will take her to the hospital.",
"If the baby is sick, send for a doctor at once.",
"Did the doctor or the midwife wash the baby's eyes when he was born?",
"I will wash his eyes or he may become blind.",
"Do not let your baby lie with a strong light in his eyes.",
"It will make them weak.",
"Is it a boy or a girl?",
"How many teeth has he?",
"He has two teeth.",
"How many months old is your baby?",
"He is ten months old.",
"How is your baby?",
"He is sick.",
"He cries all the time.",
"Often a baby cries because he is thirsty, and he needs only a drink of water to quiet him.",
"This baby needs a change of air.",
"You must take him away to the seashore,",
"You must take him away to the country,",
"I know a place where you can send him.",
"I will give you a permit so that you can go.",
"This band is too tight.",
"Loosen it.",
"He has on too much clothing.",
"He needs to be cooler.",
"Take off these swaddling clothes.",
"They make him too hot.",
"He is suffering from the heat.",
"It is not good for the baby to have his legs bound.",
"He will grow stronger if you leave him free to move.",
"Don't let this young baby sit up yet.",
"His back is not strong enough.",
"Don't urge this baby to walk yet.",
"His legs are not strong enough to bear his weight.",
"Don't let the baby sleep in the same bed with you.",
"You might roll over on him.",
"Make a bed for him in a clothes basket.",
"If the floor were cleaner, it would be easier to keep the children clean.",
"A child needs a bath every day to keep him healthy.",
"This baby should have a bath every morning before his breakfast.",
"Bathe him in warm water.",
"You must not bathe him directly after feeding him.",
"Wait an hour after feeding and then bathe him.",
"Have you some soap?",
"Ivory soap is very good.",
"It is only ten cents for a large cake.",
"Have you plenty of milk?",
"Do you nurse the baby regularly?",
"He will be much better if he has his food at certain times each day.",
"Nurse him every two hours.",
"Nurse him only twenty minutes.",
"Most babies should be weaned when they are nine or ten months old.",
"They should not be nursed at all after they are a year old.",
"Do you get fresh, clean milk?",
"Where do you get it?",
"How much is it a quart?",
"Are you careful to keep it covered so that no dust gets into it?",
"Do you keep it cool?",
"Put the milk on ice.",
"Condensed milk is not so good for babies as fresh milk.",
"Fresh milk makes them much stronger.",
"Don't give the baby the kind of food that you eat.",
"Don't give it raw peaches, apples and bananas.",
"Don't shake a baby up and down after eating.",
"Don't give the baby food every time he cries.",
"How is your child?",
"What is the matter with him?",
"Has he always walked like that?",
"He is very bow-legged.",
"Was he born so?",
"Yes, he has always been like that.",
"Have you ever had him examined by a good doctor?",
"What did he say?",
"Why don't you have the doctor see him?",
"If you let the child grow up like that, he will not be able to walk at all.",
"He is getting worse.",
"He is worse than when I saw him before.",
"He has not had enough nourishing food.",
"He should have a diet of cereals, eggs and plenty of milk.",
"He needs meat once a day, and plenty of stewed fruit and fresh vegetables.",
"While the child is young, is the best time for an operation.",
"His bones are soft now and his legs can be straightened without much trouble.",
"The doctors will not operate unless they are pretty sure they can make him better.",
"They will give him ether.",
"He will not feel any pain until it is all over.",
"If he were my child, I should have it done.",
"You do not want him to grow up deformed.",
"He will be no use to himself or to anyone else.",
"The doctor at the hospital is a specialist.",
"He is one of the finest in the country.",
"You can take him yourself to the hospital.",
"He will have to be examined first before he is admitted.",
"They may have to keep him there several weeks, perhaps more than a month.",
"Be sure to send him clean.",
"Be sure that his head is clean.",
"Wash it with kerosene.",
"Be sure that his clothes are clean.",
"Dress him in warm enough clothing.",
"I will go with you.",
"You and your husband had better go.",
"Can he leave his work for one day?",
"Can he get off for a few hours?",
"Spread a paste of baking soda and water on a thin piece of linen and put it on the burn to keep out the air.",
"Keep the burn wet with this paste.",
"It will heal soon if you take care of it.",
"Vaseline will help it after three or four days.",
"When do you expect to be confined?",
"When will your wife be confined?",
"Have you everything you need?",
"Are you going to have a midwife?",
"Who is she?",
"Are you sure that she is good?",
"Have you engaged her?",
"I know a good trained nurse who can attend you when the baby is born.",
"She will come every day for ten days afterward to look after you.",
"I will ask her to come to see you at once.",
"Do you want her to come?",
"She charges a week.",
"You will not have to pay anything.",
"Have you someone to look after the housekeeping and the children while you are unable to do so?",
"When your baby is born, be sure to have his birth registered at the office of the Board of Health.",
"It is most important to do so.",
"The law requires it.",
"Is he constipated?",
"Give him a dose of caster oil.",
"Give him oranges or stewed fruit.",
"Drink plenty of water.",
"This disease is contagious.",
"I will notify the Board of Health.",
"You must report this case at once to the Board of Health or I will do so.",
"You must keep this child away from the others or they will get it from him.",
"He must not be with any other children.",
"This disease is infectious.",
"You must take every precaution to keep others from getting it.",
"You must not be careless in such a case as this.",
"Do not let the patient cough in your face.",
"Do not get his breath.",
"Keep the patient in a room by himself.",
"Do not let him go out.",
"Do not allow anyone else to come in.",
"You are quarantined.",
"Do not send any of the children to school until the officer from the Board of Health takes down the sign",
"Be careful to change your dress before you go among other people.",
"Wear a cap or a towel tied close around your head.",
"Wash your hair thoroughly.",
"Hang a sheet wet with \"electrozone\" in the doorway.",
"Wash everything: clothing, bedding, towels, dishes, spoons, etc., with this disinfectant.",
"This child is peeling.",
"Grease his body with cocoa butter.",
"This room must be fumigated.",
"Shut the doors and windows, stop up the cracks, and burn a sulphur candle for five hours.",
"The Board of Health will fumigate.",
"Put all your soiled clothes in boiling water and boil them for an hour on the stove.",
"You must take this wall-paper off and put on fresh paper.",
"These walls should be washed down and repainted.",
"If the baby has convulsions, send for the doctor.",
"Meanwhile put the baby into a hot bath.",
"Test the heat with your elbow to be sure that the water is not too hot.",
"Then wrap him in a warm blanket.",
"Send for a doctor.",
"Give a teaspoonful of syrup of ipecac or two or three teaspoonfuls of kerosene oil.",
"Put the feet in hot mustard water",
"Keep the child very warm until the doctor comes.",
"Instead of putting his feet in hot water, wring out cloths in very hot water.",
"Place on child's chest and throat and protect with dry cloths in order to keep in the heat.",
"To stop the bleeding, bathe the cut with very hot or very cold water.",
"You must keep this cut clean.",
"Wash it with cold boiled water and bind it up.",
"Some physicians advise against putting water on wounds, as they state that it drives the infection further in.",
"Instead, squeeze the cut on either side in order to press out any germs.",
"Then bind up with a perfectly clean bandage.",
"What has he eaten?",
"Has he diarrhea?",
"How many movements has he had today?",
"Does he vomit?",
"This baby should have barley water.",
"Give him this instead of milk.",
"Give this older child rice and warm milk until he is better.",
"Boil the milk.",
"Put a mosquito net over him.",
"Keep him in the air.",
"Add to a pint of boiling water and boil twenty minutes.",
"Strain and add enough boiled water to make a pint.",
"Do you have pain in your ear?",
"Yes, sometimes.",
"Do you hear well?",
"Yes, usually.",
"Can you hear this?",
"How far away can you hear it?",
"Can you hear it now?",
"Tell me when you can hear it.",
"Let me examine your ear?",
"Your cold makes your hearing worse.",
"Can you hear better now?",
"Does your ear discharge matter?",
"You must not put water in your ears.",
"Wash your ears with boric acid.",
"To make a solution of boric acid, dissolve a teaspoonful of boric acid powder in a pint of boiling water.",
"Use it warm.",
"What is the matter with this child's eyes?",
"Does she see well?",
"Do you see well?",
"Let me look at them.",
"Do they pain her?",
"Do they pain you?",
"Do you bathe them thoroughly every day?",
"Bathe them three times a day.",
"Do they discharge pus or water?",
"Buy a ten cent package of boric acid powder.",
"Dissolve a spoonful of the powder in a pint of boiling water.",
"When it becomes lukewarm, bathe the eyes with it.",
"I should take her to an oculist.",
"Perhaps something can be done for her.",
"I will take her.",
"Perhaps she needs glasses.",
"The oculist will have to put drops in her eyes first before he can examine her, so as to enlarge the pupils.",
"Don't be afraid, it won't hurt you?",
"Perhaps a slight operation would cure her.",
"It is not right to let her grow up like that, if something can be done for her.",
"She is getting worse all the time.",
"She has strained her eyes",
"What is the matter with this child?",
"There seems to be something wrong with his mind.",
"Has he always been so?",
"Was he born so?",
"When did you first notice anything wrong?",
"What do you think caused it?",
"Was it an accident?",
"What happened?",
"When did he begin to walk?",
"To talk?",
"Does he understand orders?",
"Can he carry out orders?",
"Can he feed himself?",
"Can he use tools?",
"Can he make change?",
"How high can he count?",
"Can he carry a tune?",
"Has he a good memory?",
"What does he like best to do?",
"How does he usually spend his time?",
"Have you ever had feeblemindedness, epilepsy, or insanity in your family?",
"Has your husband ever had feeblemindedness, epilepsy, insanity in his family?",
"What did your father die of?",
"Your mother?",
"His father?",
"His mother?",
"Your grandmother?",
"Your grandfather?",
"Does your husband drink to excess?",
"Is he healthy?",
"Are you healthy?",
"I want to ask him some questions.",
"Do not help him answer them.",
"I want to test his blood",
"I want to take some measurements",
"I want to give him a thorough examination",
"He should go to a school for children like this.",
"There he will be taught everything that he is capable of learning.",
"He will be kindly treated.",
"He will be very happy there.",
"You can go to see him.",
"It will cost nothing.",
"You will have to pay something.",
"You will have to pay what you are able.",
"You will have to go before two freeholders and swear what you are able to pay.",
"Two physicians will have to sign this certificate.",
"You must sign this before a notary public.",
"He has a fever.",
"He must be kept quiet.",
"Bathe him with warm water and rub him with alcohol.",
"Keep him in bed.",
"He can sit up a little while.",
"This child is weak from the fever.",
"Rub his body with olive oil.",
"Give him plenty of water to drink.",
"Bathe him with water cold from the faucet.",
"Are you willing to let him go to the hospital?",
"He should go.",
"It is the best place for him.",
"He may not recover if he does not go.",
"At the hospital he can have everything that he needs.",
"The doctors and nurses will give him the best of care.",
"You cannot take proper care of him here.",
"You must have a written permit from the doctor.",
"Get it from him when he comes.",
"I will get it for you.",
"I will send it to you.",
"Do you have pain in your neck?",
"Which side hurts you?",
"Does it hurt you to turn your head?",
"How long has your neck been swollen?",
"Do you have pain around your nose?",
"Do you breathe easily through your nose?",
"Do you breathe through your mouth?",
"Do you snore at night?",
"Does your nose run?",
"To one who has swallowed poison give an emetic; that is, plenty of warm water, salt water or mustard water.",
"Continue until vomiting results.",
"Open your mouth wide and say, \"Ah!\"",
"Does it hurt you to swallow?",
"Is it hard for you to swallow?",
"How long has your throat been sore?",
"Do you cough?",
"Do you raise much mucous?",
"Do you ever raise blood?",
"Is it hard for you to talk?",
"How long is it since you lost your voice?",
"Rub your throat with this salve.",
"Spray your throat with this liquid.",
"Your ankle is sprained.",
"Put it in very hot water or very cold water, rub and bind tightly.",
"Keep it in an elevated position.",
"Do not walk around on it.",
"You have bad teeth.",
"You should go to the dentist.",
"Hold a hot salt bag against your cheek.",
"It will ease the pain.",
"How long have you had a cough?",
"Do you cough much?",
"Do you cough at night?",
"Do you raise much?",
"Do you cough up blood?",
"Does much come up at a time?",
"Or is the sputum just streaked with blood?",
"Does it hurt you when you cough?",
"Where?",
"Put your hand where it hurts you.",
"Do you get short of breath when you go upstairs?",
"When you lie down?",
"Do you have \"night-sweats\"?",
"Have you lost flesh and strength?",
"Are you feverish at night?",
"When does the fever begin?",
"Let me test your lungs.",
"Take a long breath.",
"Let the air out slowly.",
"Please save some of the sputum which you cough up in the morning.",
"Put it in a clean bottle and cover it tightly.",
"Rinse the bottle out with boiling water to be sure it is clean.",
"I will send it to be examined.",
"Buy paper napkins.",
"You can get them at ten cents a thousand.",
"Use them when you spit.",
"Put them in a paper bag and burn them.",
"It is the dried sputum that spreads this disease.",
"You must sleep alone with your windows open wide.",
"Is there a place where you can sleep out-of-doors?",
"You must stay out in the air and sunshine all day long.",
"You must have some nourishing food.",
"You should have plenty of milk, raw eggs and soup.",
"If you go to a sanatorium now, you may get well.",
"If you stay here, it is doubtful if you will recover.",
"Will you go if I get you a permit?",
"You will have to be examined first at the clinic.",
"If you remain here, you will expose all the rest of your family to the disease.",
"You don't want them to get it, do you?",
"Think it over.",
"I will come again tomorrow.",
"Let me know then what you decide to do.",
"Are you comfortable where you are?",
"How many men have to sleep in this room?",
"Do you keep the windows open?",
"Night air is just as pure as that which you breathe in the day time.",
"Don't they give you enough blankets to keep you warm?",
"Fresh air is necessary if one would keep well.",
"If you breathe the same air over and over again, it becomes impure.",
"It is harder to heat impure air than fresh air.",
"People don't want to drink dirty water, but to breath air that is impure is just as bad.",
"Much consumption is caused by too many people living together in close, stuffy rooms.",
"Don't live in dusty air.",
"Keep your rooms clean.",
"Get rid of dust by cleaning with damp cloths and mops.",
"Don't sweep with a dry broom.",
"KEep at least one window open in your bedroom at night, and air the room two or three times a day.",
"Don't eat with soiled hands.",
"Wash them first.",
"Don't put your hands, pencils, or any candy or chewing gum that other persons have used, in your mouth.",
"Don't keep soiled handkerchiefs in your pockets.",
"Take a warm bath with soap at least once a week.",
"Don't neglect a cold or a cough, but go to a doctor or a dispensary.",
"Don't waste your money on patent medicines or advertised consumption cures, but go to a doctor or a dispensary.",
"If you go in time, you can be cured; if you wait, it may be too late.",
"Don't drink whiskey or other forms of liquor.",
"Don't sleep in the same bed with anyone else, and if possible, not in the same room.",
"Good food, fresh air and rest are the best cures.",
"Keep out in the fresh air and in the sunlight as much as possible.",
"Keep your windows open winter and summer, day and night.",
"If properly wrapped up you will not catch cold.",
"Go to a sanatorium if you can and before it is too late.",
"A person who has pulmonary tuberculosis or consumption is not dangerous to those with whom he lives and works, if he is careful and clean.",
"Many grown people and children have pulmonary tuberculosis or consumption without knowing it, and can give it to others.",
"Don't spit on the sidewalks, playgrounds, or on the floors or hallways of your home or school.",
"It spreads disease, and is dangerous, indecent and against the law.",
"When you must spit, spit in the gutters or into a spittoon half filled with water.",
"Don't cough or sneeze without holding a handkerchief or your hand over your mouth or nose.",
"Has she been vaccinated?",
"No, she has not been vaccinated yet.",
"She must be vaccinated at once.",
"It is a protection against smallpox.",
"Did the vaccination \"take\"?",
"If it takes, she will not have to be vaccinated again.",
"It did not take.",
"We must do it again.",
"Even a meager knowledge of English may mean an opportunity to work in a factory versus non-employment",
"What is your name?",
"With whom do you board?",
"I board with Mr. Scala.",
"I am a tailor by trade.",
"What part of Italy do you come from?",
"I come from a small town near Naples.",
"How many years did you go to school in Italy?",
"I went to school three years.",
"I did not go to school at all.",
"Can you read?",
"Yes, I can read Italian.",
"No, I do not know how to read.",
"Can you write?",
"Yes, I can write.",
"Do you understand what I say?",
"I understand a little, but not everything.",
"No, I do not understand at all.",
"You must come to school regularly or you cannot learn English.",
"If you learn English, it will be of great help to you in this country.",
"You can get work that will pay you better.",
"You will not easily be imposed on.",
"If you cannot understand our language and be understood by us, even if you are educated, you will often be misjudged and considered illiterate.",
"You can never get ahead in this country, if you cannot make yourself understood when you want to.",
"Can't you come on time?",
"No, I cannot get here any sooner, because I have to work late.",
"Yes, I will try to be more prompt.",
"When you are late, you lose some of the lesson yourself and you disturb the others.",
"You make it very hard for the teacher.",
"Please pay attention.",
"Please be more quiet.",
"I cannot hear the answers of the others.",
"Answer these questions.",
"Answer only when I ask you a question.",
"You must not answer when I speak to someone else.",
"Do you think that Giovanni answered correctly?",
"No?",
"Why not?",
"What should he have said?",
"Look at the board.",
"Go to the board and write what I tell you.",
"From where you sit can you see what is written on the board?",
"Is this correct?",
"That is correct.",
"No, it is wrong.",
"Correct it, if you can.",
"Correct your mistakes,",
"I have corrected my mistakes.",
"Copy from the board.",
"Copy in pencil.",
"Copy in ink in your note-book.",
"Try to keep your book clean.",
"It is a pleasure to look at a tidy book.",
"Be ready for dictation.",
"Write as I dictate.",
"Please do that work again.",
"Do the best you can and I will help you in a moment.",
"Am I speaking too fast?",
"Yes, a little too fast for me.",
"Do not speak so fast.",
"This is an idiom.",
"What do you say in Italian for?",
"Look up the word in the vocabulary at the back of the book.",
"Look at what he has written.",
"What do you mean?",
"I mean this",
"They mean the same thing.",
"Open your book at page fourteen.",
"At the bottom of the page you will see what I mean.",
"Look at the opposite page in about the middle.",
"What is the number of the page?",
"Turn to page six.",
"Point to sentence three.",
"Pronounce this word more clearly.",
"What is the plural of the word, knife?",
"The plural of knife is knives.",
"Give me this noun in the singular.",
"Read more slowly.",
"Where shall I begin to read?",
"Begin the paragraph at the top of the page.",
"Try to read this.",
"Don't you remember what we studied yesterday evening?",
"Yes, I remember it.",
"No, I have forgotten it.",
"Repeat what you have just said.",
"What did you say?",
"Please explain this to me.",
"Please show me how to do this.",
"Try again.",
"You are improving.",
"Use these words in sentences.",
"What is it that you do not understand?",
"What are the words that you do not know?",
"Is this vowel long or short?",
"Write the exercise on a piece of paper.",
"Hold your pen so, above your knuckle.",
"Try not to keep your fingers so stiff.",
"Try to write more freely.",
"Can't you keep your writing straighter?",
"It is all \"going down hill\".",
"Do you have to bend over so when you write?",
"It would be better if you could bend from your waist.",
"You will have very crooked shoulders if you write in that position.",
"Have your money ready",
"Count your change",
"Wait until the car stops",
"Do not touch",
"Hands off",
"I am fifty years old.",
"What time is it?",
"It is twenty minutes past ten.",
"It is half past ten.",
"It is five minutes of eleven.",
"At what time?",
"What day of the month is it today?",
"It is the fifth.",
"Have you a house, Mr. Fiore?",
"I am in England.",
"We are going to Paris.",
"He lives at Pisa.",
"He is no longer in Florence.",
"This is Mary's pen.",
"That is Henry's.",
"I have heard a good deal said about Florence.",
"She has the best room in the house.",
"Give me something good to eat.",
"There is nothing beautiful here.",
"He does it by himself.",
"We have nothing to do.",
"My poor sister has been ill for two days.",
"There is no time to lose.",
"What is to be done?",
"The mother loves her son.",
"The father loves his daughters.",
"My hat is better than yours.",
"Better today than tomorrow.",
"He is more studious than my brother.",
"This table is better than that.",
"You are taller than I.",
"These hoes are less useful than the others.",
"The streets are worse than the sidewalks.",
"She is more polite than Lucy.",
"There is less gold than silver.",
"Practice is worth more than grammar,",
"He is more fortunate than intelligent.",
"It is better now than tomorrow.",
"You talk more than you act.",
"There is as much happiness as unhappiness in the world.",
"There are as many boys as girls.",
"Our son is as strong as yours.",
"This carpenter is as good as he is clever.",
"We talk to you, to him, to her, and to them.",
"I write of them and of her.",
"They have received some letters from me.",
"We have listened to you.",
"He does it by himself.",
"You yourselves are kind.",
"Where did you go?",
"What have you?",
"Allow me to present my friend, Mrs. Loda.",
"I am glad to see you; but at the same time I cannot recall your name,",
"You see me.",
"They trust us.",
"We greet you.",
"I do not know it.",
"Look at him.",
"We see them.",
"You talk to me.",
"They write to us.",
"I tell you.",
"I do not tell him.",
"I will write to her.",
"I see the boys and tell them the news.",
"Tell it to me.",
"Help her for me.",
"Can you give them to me?",
"Give me some of it.",
"They will tell it to us.",
"Recommend her to us.",
"Bring them to us.",
"He has given some to us.",
"I send him to you.",
"I forward it to you.",
"We give them to you.",
"He takes some to you.",
"I will tell it to him.",
"You should send her to him.",
"I am grateful to him for it.",
"I have many of them.",
"I have six of them.",
"Have you any?",
"I have some, but he has not any.",
"They have not any, and we are glad of it.",
"We have some good books; have you some also?",
"I have given them six.",
"He has sent several of them to us.",
"There are twelve of them.",
"There are others",
"Is there an office?",
"No, there is none.",
"There are some people who say that the water in Rome is not pure.",
"What is there to be seen?",
"There are some words that I do not understand.",
"Do not go there.",
"There were many ladies at the theatre.",
"There is no need of talking so loud.",
"In many buildings there are not enough exits in case of fire.",
"We have no flowers.",
"I have no friend.",
"No, I am not an Italian.",
"It is good for nothing.",
"Do not do so.",
"There is nothing to be ashamed of.",
"I want nothing.",
"No one knows you.",
"There is nothing else.",
"It is neither light nor dark.",
"What boy is this?",
"I do not know what to do.",
"I want the book that you have.",
"You dared to say what you thought.",
"I want what I have asked for.",
"What is there for me?",
"I think that he has come.",
"The man who said so is here.",
"Who is coming?",
"Who is to blame?",
"With whom did you speak?",
"Whose knife is that?",
"Whose gloves are these?",
"He who has health is rich.",
"I have seen the house.",
"The house which I have seen is large.",
"I have met her.",
"My brother has gone.",
"My sister has gone.",
"The boys have gone.",
"The girls have gone.",
"My father and mother have arrived today.",
"I like that book.",
"I do not like this one.",
"I like those books very much.",
"He likes the garden.",
"He likes the gardens.",
"Do you like the newspapers?",
"Do they like the church?",
"Do me the favor to bring my coat here.",
"I am very sorry.",
"We are sorry to hear it.",
"I was sorry not to be able to go.",
"My head aches.",
"My eyes ache.",
"It seems to me to be too late to set out.",
"He seems foolish to us.",
"I lack everything.",
"I lack nothing.",
"We fell short of provisions.",
"He does not owe me much.",
"I must go home.",
"What am I to do?",
"Is he to take all these things?",
"We shall have to call you.",
"I ought to hurry.",
"I am reading aloud.",
"How are you?",
"I am well, thank you.",
"I must come.",
"He ought to have written.",
"You must go there quickly.",
"We need a strong man.",
"There is no need of coming.",
"What do you want?",
"She needed some shoes.",
"Do you need anything else?",
"I need many things.",
"Time and money are needed to do this.",
"My head aches.",
"It disgusts me.",
"It makes no difference.",
"What kind of weather is it?",
"It is fine weather.",
"Do me a favor.",
"I have had a coat made.",
"There is still much to be done.",
"I have some questions to ask you.",
"To do so is not right.",
"It had already become night.",
"Let me know something.",
"Show us the gloves.",
"They took a walk.",
"We have packed our trunks.",
"Do you know how to write?",
"She does not know how to sew.",
"He knew nothing.",
"No one knows you.",
"I know her by sight.",
"Do you know Germany?",
"I want to learn Italian.",
"He wants to talk with you.",
"It is evident that it will rain soon.",
"I should like to see you.",
"I wonder why Louis is not here.",
"It will take time to do this.",
"It took ten months to grow.",
"What does this mean?",
"I wanted you to come with me.");

function secondItalianLine()
{
	global $italian2lines;
	return $italian2lines[array_rand($italian2lines)];
}

?>