<?

//https://archive.org/stream/norwegiandanishe00stev/norwegiandanishe00stev_djvu.txt

	$norwegianlines = array(
"Yes",
"no",
"nay",
"indeed",
"surely",
"quite",
"how?",
"Come here!",
"Come back!",
"Come with me!",
"Wait a little!",
"Be quick!",
"Go on!",
"Follow me!",
"Call him!",
"Let him know!",
"Listen!",
"Listen to me!",
"I say",
"Answer me!",
"Be done!",
"Leave that alone!",
"Wait for me!",
"Do not forget!",
"Who is there?",
"Is it you?",
"Has he come?",
"What is it?",
"Have you it?",
"Will you tell me?",
"What are you doing?",
"Why do you do that?",
"Whose is this?",
"Is that yours?",
"May I take it?",
"Did you not hear?",
"What is your name?",
"Where is it?",
"Where are you?",
"Where do you live?",
"I am angry",
"Don't be angry",
"I am very much vexed",
"That is provoking",
"It is a shame!",
"You must not do that again",
"You ought to have told me",
"It is very wrong",
"That is your fault",
"Is breakfast ready?",
"Come to breakfast",
"Does the water boil?",
"This water has not boiled",
"Is the tea made?",
"Give me a cup of coffee",
"Do you drink tea?",
"No, give me coffee, please",
"This cream is sour",
"Another lump of sugar?",
"Pass me the butter",
"Will you have an egg?",
"Give me the salt",
"To what may I help you?",
"Will you have some soup?",
"Yes, if you please",
"Help yourself",
"I like Norwegian cookery",
"Do you use pepper?",
"It is late",
"It has struck ten",
"Are you tired?",
"It is too early to go to bed",
"It is a fine evening",
"The Summer evenings are very light",
"One cannot go to sleep",
"What time is it?",
"It is one o'clock",
"It is a quarter past",
"It is half-past two",
"It is a quarter to five",
"Ten minutes past six",
"Call me at seven",
"How is the weather?",
"Is it fine?",
"There is a knock",
"It is Mr. A.",
"It is Mrs. B.",
"I am glad to see you",
"Pray be seated",
"Will you not take off your things?",
"Thank you, but I must not stop",
"I must go very soon",
"I am sorry",
"I am very sorry",
"It is a sad thing",
"It is unfortunate",
"How tiresome!",
"It is very disagreeable",
"I am glad",
"The laundress is here",
"I want to see her",
"Can I have my linen back on Friday next?",
"I like my collars very stiff",
"Be sure to bring the things in good time",
"You have not starched the collars enough",
"I miss a cuff",
"This shirt is not well ironed",
"You must take it back",
"A handkerchief is wanting",
"Have you brought your bill?",
"Do you know Mr. N.?",
"I do not know anybody by that name",
"Does he live here?",
"He lives in this house",
"On the second floor",
"On the third floor",
"Is he in?",
"Which is the best hotel?",
"There are several very good ones",
"Drive me to the Hotel Victoria",
"Can I have a room on the second floor?",
"I am very tired",
"Let us have supper soon",
"You will find it ready in the dining room",
"We wish to have supper a la carte",
"Are our rooms ready?",
"Show me the way, please",
"Is it far from here?",
"Is it difficult to find?",
"What time is the museum open?",
"What days is the National Gallery open?",
"Is the church open at this hour?",
"Where is the post-office?",
"Where is the bank?",
"I shall leave the town tonight",
"Into the country",
"Into the interior of Norway",
"One of the valleys",
"A mountain district",
"I am going to ascend the mountain",
"Are the roads good?",
"Are there many hills?",
"Can I have a horse?",
"Shall I have to wait?",
"When does the train start?",
"Is it an express?",
"An ordinary train",
"A freight train",
"Will I have to pay for excess baggage?",
"Is this the train for Drammen?",
"Will I have to change cars?",
"At what hour do we start?",
"With the tide",
"Let us go down into the cabin",
"Where is my berth?",
"Your name is on it",
"I prefer a top berth",
"I am going on deck",
"The sea is rough",
"The wind is high",
"It is a head wind",
"I feel sea-sick",
"Steward, bring me some brandy",
"The sea is calm",
"We have had a good passage",
"Shall we take a walk?",
"Yes, let us take a walk",
"Where shall we go?",
"On the high road",
"There is a good deal of dust",
"Is there any fishing to be had near here?",
"Must I first obtain permission to fish?",
"To whom must I apply?",
"What is the rent for fishing in this river?",
"Can I get the sole right of fishing?",
"Can I have a boat and man to row?",
"What do you charge for the hour?",
"Are you an experienced fisherman?",
"Can I depend on you?",
"Can I buy it at the store?",
"Good morning!",
"Good day!",
"Do you keep note paper?",
"I want a quire of paper",
"A stick of sealing wax",
"A packet of envelopes and some pens",
"I also want a ball of string",
"We eat to live, but we do not live to eat",
"It is cold to-day, although it rained last night",
"we are industrious and frugal",
"I don't know whether it is right or wrong",
"I hear that you are going to leave us",
"He said nothing to me",
"She went to the country yesterday",
"It is cold",
"We like to meet you",
"You must not forget it",
"Nearer to thee, my God!",
"They said I should stay with them",
"She told me so herself",
"It speaks for itself",
"We don't understand it ourselves",
"Take care of yourselves",
"They like it themselves",
"Look at these flowers",
"That old man has lost his son",
"These shoes cost more than those",
"Who has given you that necktie?",
"Whom did you speak of?",
"Of whom did you speak?",
"When one is tired one likes to repose",
"We should not praise ourselves",
"What is it?",
"That is what he told me",
"He made a visit to the Pope, whom we have heard of",
"He will soon be back",
"Then we were on the other side of the river",
"That man goes seldom to church",
"Whose ink is this?",
"Where is the postal card which the mail carrier brought?",
"Which of your teachers has gone away?",
"When spring comes, then the roses begin to grow",
"I often think of you",
"It was very dark",
"Think much, speak little",
"It is wrong altogether",
"This house is large enough for us",
"We are sufficiently supplied with food and clothing",
"I hardly believe what the report says",
"He was not quite done with his work",
"His will is too strong to bend and too proud to learn",
"His room is above ours",
"We lay a bridge across the river",
"We row against the waves",
"Give me a cup of tea",
"They sailed along the coast",
"This is my trunk",
"Yes, I have a few cigars",
"Have you any tobacco or cigars?",
"They pay no duty",
"Where is the railroad to London?",
"Give me a ticket for the first class",
"Show your tickets",
"Drive us to Regent Street",
"What is the fare?",
"I wish to dine",
"Give me the bill of fare",
"Good morning",
"How do you do?",
"Very well",
"I am hungry",
"I am thirsty",
"Good evening",
"Sit down",
"I thank you",
"The street is long",
"Yes, sir!",
"No, sir!",
"Pray tell me",
"What do you say?",
"What do you wish to say?",
"What do you mean by that?",
"What do you wish?",
"What do you want?",
"What shall I do?",
"I do not know what to do",
"You have chosen your time badly",
"What would you do in my place?",
"You must have patience",
"Walk slower",
"You walk too fast",
"I can not keep up with you",
"Let us rest a little",
"Follow me",
"Come this way",
"I will go with you",
"Come nearer",
"Go straight ahead",
"Turn to the right",
"Turn to the left",
"Make room",
"With whom do I speak?",
"Do you speak to me?",
"You speak too low.",
"Speak loud.",
"Why did you not speak before?",
"Do not speak to me.",
"Speak rationally.",
"I call that speaking.",
"He speaks very well.",
"Can you read German?",
"What do you read?",
"I am reading the newspaper.",
"I am reading Goethe's Egmont.",
"Where have you read that?",
"I read it in the newspapers.",
"Read aloud.",
"We always read aloud.",
"Continue to read.",
"I have read the whole of this work.",
"How do you do?",
"How do you feel?",
"Pretty well.",
"Very well, I thank you.",
"How is your wife?",
"You appear to be very well.",
"I am really very well.",
"I do not feel very well.",
"How old are you?",
"I am twenty years old.",
"I am only fifteen years old.",
"Still so young?",
"Already so old?",
"You are in your best years.",
"How old is your sister?",
"She is eighteen years old.",
"A few days ago.",
"A short time since.",
"One of these days.",
"It is scarcely two days since.",
"It is hardly three days ago.",
"Last week.",
"A week ago.",
"A fortnight ago.",
"Oh, dear me!",
"Oh, how infamous!",
"How vexatious!",
"How painful!",
"How sad!",
"What a misfortune!",
"How annoying!",
"What o'clock is it?",
"Tell me what o'clock it is.",
"Is it late?",
"No, it is yet early.",
"It is 2 o'clock.",
"It will soon strike six.",
"It has just struck five.",
"It is no longer early.",
"It is time to rise.",
"It is day.",
"It is yet early in the day.",
"It is five minutes after seven.",
"It is ten minutes past seven.",
"I regret that your visit has been so short.",
"I am glad to see you so well.",
"You are too kind.",
"I am very much obliged to you.",
"It always gives us a great pleasure to see you.",
"Is it possible you want to go out?",
"What kind of weather is it?",
"It is beautiful weather.",
"It is bad weather.",
"It is very windy.",
"The weather is mild to-day.",
"I fear it will rain.",
"It is very warm.",
"Is it windy?",
"No, it is quite calm.",
"The sky is overcast.",
"Perhaps the sky will clear.",
"I doubt it.",
"Well, that is right!",
"Very well!",
"What a pleasure!",
"What joy!",
"How pleasant!",
"How happy!",
"I am charmed.",
"I am very glad.",
"I am very much pleased",
"How charmed I am with this!",
"How glad I am!",
"How happy I am!",
"I thank you.",
"I am very much obliged to you.",
"Many thanks.",
"Thank you very much.",
"I thank you for your kindness.",
"I am greatly indebted to you.",
"I am very grateful for your kindness.",
"I accept it with thanks.",
"What news is there?",
"Is there anything new to-day?",
"What news is there?",
"What is going on in politics?",
"Have you not heard anything new?",
"Do you know the news?",
"I have heard nothing.",
"Have you read the newspapers?",
"What news is there in town?",
"I have heard nothing.",
"I cannot.",
"It cannot be.",
"It is impossible for me.",
"It cannot be.",
"Do not speak to me of it.",
"It is impossible for me to fulfill your wishes.",
"It is utterly impossible.",
"I will not hear of it.",
"I am very sorry, but I cannot do it.",
"I am exceedingly sorry, but I cannot do as you wish.",
"Yes, it is true.",
"Yes, certainly.",
"That is true.",
"I say yes.",
"It is but too true.",
"The fact is certain.",
"I have it from good authority.",
"You may believe me.",
"I am very certain of it.",
"I will lay a wager on it.",
"I can assure you.",
"No, most decidedly not.",
"That is not true.",
"That is false.",
"I say no.",
"It does not signify.",
"That says nothing.",
"I have it only from hearsay.",
"It is a falsehood.",
"It is a calumny.",
"It cannot be.",
"It is impossible.",
"I deny it.",
"It is an invention.",
"That is ridiculous.",
"He is my friend.",
"His my intimate friend.",
"He is my best friend.",
"I really love him.",
"I have a great regard for him.",
"We are very intimate.",
"We love each other like brothers.",
"We are inseparable.",
"I am right.",
"I am wrong.",
"Am I right?",
"Is my brother right?",
"You are right.",
"Is he right or wrong?",
"Is he not wrong?",
"Yes, he is wrong.",
"Your son is not wrong.",
"So much.",
"Very much, a great deal",
"Very little.",
"I have much salt.",
"I have but little bread.",
"I have great deal of sugar.",
"My brother has but very litle gold.",
"To be obliged to, to be forced.",
"To be compelled.",
"To be permitted, to be allowed.",
"Will you do that?",
"I am willing to do it, I will.",
"It is very provoking to be obliged to do a thing that we are not willing to do.",
"I have been compelled to do it, though I was very unwilling to it.",
"I have not been able to come before 5 o'clock",
"Are you permitted to do that?",
"I have been permitted to do it, but I have been unwilling to do it.",
"To ask permission.",
"To beg pardon.",
"I beg your pardon, sir.",
"We will not see him.",
"But you shall see him.",
"I would not buy it.",
"You should try it.",
"Will you take this letter to the post-office?",
"I will take it.",
"Much longer.",
"Not much longer.",
"How much longer?",
"Will you still write long?",
"I shall not write much longer.",
"How much longer will you remain here?",
"Can you speak English?",
"I can speak a little, but I cannot write it.",
"Do you understand English?",
"I do not know it thoroughly, but I know enough to make myself understod.",
"He has a thorough knowledge of the English language.",
"I am glad.",
"I am sorry to hear that your sister is ill.",
"My aunt will be sorry to hear that",
"Are you not sorry for it?",
"I am glad to hear that your brother has returned.",
"I am sorry I cannot come.",
"Having seen him, I will go to his father and tell him he is here.",
"Having seen him, I went to his father.",
"Wishing to see him and not being able to find him anywhere, I must write to him.",
"Not being able nor willing to lend him the money, I was obliged to tell him",
"I had none.",
"After having done this.",
"I am far from believing that.",
"You are right in doing so.",
"You ought to speak to him instead of writing to him.",
"Was he an honest man?",
"Was the lady gone already?",
"Was the store open?",
"Were we there when you came?",
"You have not been here before.",
"He has not seen you.",
"She has a nice dress.",
"It has been very cold.",
"We have heard the news.",
"Have you lost any money? *",
"Has the man been here?",
"Has your sister seen him?",
"Has the dog taken it?",
"He was very sick.",
"She was afraid of thunder.",
"It was a big stone.",
"We were there twice.",
"Do you see me?",
"Did he know you?",
"Do they go away to-day?",
"Did she speak about him?",
"I did not see the bird.",
"You did not believe me.",
"We do not want you.",
"It did not rain yesterday.",
"He is a European",
"She is my mother",
"It is not an animal",
"We are old",
"You are young",
"They are useful",
"He is a young boy",
"I shall come to you",
"They will find the boy",
"I should like a knife",
"They would make a fire",
"Have you seen the bird",
"He has had pepper and salt",
"You are a tall man",
"They have very large houses",
"It was a grand idea",
"The little boy caresses his good old father",
"The pupil goes to school",
"We admire fine teeth",
"He loved his mother",
"You are very obliging, sir.",
"It is a long time since we saw each other.",
"So it is, indeed.",
"What news?",
"Nothing of importance",
"Here is a letter for you, sir.",
"The postman has just brought it, there's two cents to pay",
"Why, there's a stamp on it, the postage is paid",
"Look at this stamp: insufficiently prepaid.",
"I must answer this at once",
"You can write your letters in the drawing-room, if you like",
"You will find everything you want there",
"What is the postage to Denmark?",
"Up to what time can one post letters which are to go by the evening mail?",
"What shall we do this evening?",
"Let us go to the play",
"I want two dress-circle tickets for this evening",
"Have you any left in the first row?",
"There are two, but they are not together",
"Oh, that's no use, they must be together",
"I have two in the third row, but they are right in the middle, so that you will see excellently",
"That will do very well!",
"How much is it?",
"Straight up the stairs, gentlemen, and then turn to the right",
"Your tickets, please",
"Numbers forty-eight and forty-nine",
"Will you please keep these checks; you will want them, if you go out during the intermissions.",
"Will you leave your hats and coats here, gentlemen?",
"What do you think?",
"had we better do so?",
"I think so, they will be in our way in the theater.",
"I am going out to do some shopping",
"I am afraid I shall be cheated, when the people see that I am a foreigner",
"Would you mind coming with me?",
"Not at all;",
"I shall be very glad",
"The cloth is extra good and the pattern most fashionable",
"In fact, it is the latest thing out",
"I don't think it is in very good taste, however.",
"Is that the lowest price you could let me have it at?",
"The very lowest, sir;",
"I couldn't possibly do it for less.",
"We never alter our prices for anybody, sir.",
"I don't think I can give as much as that",
"I did not intend to spend so much money on this purchase",
"Besides I know I could get it cheaper elsewhere.",
"There you are mistaken, sir;",
"you might get an inferior article at a lower price, but not what I have shown you",
"What shall I help you to?",
"May I help you to some soup?",
"I thank you;",
"I will trouble you for a little beef.",
"It looks so very nice",
"Which way shall I cut it?",
"As you please",
"Will you have it well-done or under-done?",
"I don't like it over-done",
"May I trouble you for an egg?",
"Do you not take another cup?",
"I thank you.",
"Will you be kind enough to pass me the ham?",
"Pray, help yourself",
"Will you not take some toast?",
"Do you wish potatoes?",
"May I give you some fish?",
"I shall only taste a bit of it:",
"I am no fish-eater",
"I find these shirts are not white enough, they are not well ironed, either.",
"Here are still some spots I could not get them out, they are ink stains.",
"Now, give me the bill, I will count my linen over to see if all is right",
"One dozen of shirts, four pairs of drawers, six pairs of socks, eleven handkerchiefs, six towels, six pairs of cuffs, sixteen collars",
"Here is a towel that does not belong to me",
"Nothing is wanting, all is right, here is your money",
"There's a knock at the door.",
"Come in",
"Good morning",
"Good day",
"Good evening",
"Good night",
"Good by",
"How do you do?",
"How are you?",
"Are you quite well?",
"Quite well, thank you",
"I am very well",
"Thanks, pretty well, and how are you?",
"Are all quite well at home?",
"Thank you, they are all well",
"You speak too fast",
"Please talk more slowly, if you wish me to understand you",
"Do you understand me?",
"With your leave, sir.",
"If you permit;",
"if you please",
"I take the liberty",
"How is that called in English?",
"I beg your pardon, sir",
"Excuse me, sir.",
"Shall I see if the light is on the table?",
"They will find the house",
"I should like to buy a new hat",
"I shall come to you",
"Will you do me the pleasure?",
"Yes, if I can",
"He might be the father of the girl",
"You must not drink wine and water",
"Where were you last night?",
"Pray, answer my question",
"I am waiting for an answer",
"Excuse me, but you are mistaken",
"Listen to me",
"Of course, it was only a misunderstanding",
"I believe you",
"I don't think you are right",
"I think you are wrong",
"I don't say that you are wrong, but...",
"That is the question",
"That is the point",
"There is no harm done",
"It is nothing to speak of",
"Thank you",
"No, thank you",
"Thanks.",
"Many thanks",
"I am much obliged to you",
"You are very kind",
"No trouble at all",
"I am really glad to see you this beautiful morning.",
"Where do you live now?",
"I live at my friend, the artist's, 158 W. Huron Street",
"Where shall I find a drugstore?",
"Am I interrupting you?",
"By no means",
"Not at all",
"Don't let me disturb you",
"We didn't know what had become of you",
"Take a seat, please",
"Pray, be seated",
"Will you take a chair?",
"Won't you sit down?",
"I have only a few words to say",
"I have plenty of time",
"I have no time to spare",
"I am in a great hurry",
"I hope to see you again",
"I wish you a very good morning",
"Remember me kindly to your brother",
"Give my kind regards to your father",
"The brave man has gone",
"There is no more conflict, only the calm of universal peace",
"We are not alone in our sorrow",
"This is a funeral service",
"The world to-day mourns his demise",
"Did you know him formerly?",
"I shall be at your service presently",
"Let us speak boldly",
"Never put off till to-morrow what can be done to-day.",
"Carelessness and idleness are the causes of great misfortune",
"As you study, you will make progress",
"Is every word in this dictionary, papa?",
"I believe not.",
"Time and again there comes a new word into the language.",
"What is the last word, papa?",
"Your mother will tell you, my son.",
"She always has the last word.",
"One of the happiest moments in a young man's life is when he for the first time notices that his mustache has grown so long that he wets it when he drinks.",
"If half what the witnesses testify against you is true, your conscience must be as black as your hair.",
"If a man's conscience is regulated by his hair, then your honor has not got any conscience at all.",
"An unfortunate man has obtained access to rich Baron Rapineau.",
"Put this poor fellow out into the street!",
"He is breaking my heart!",
"Never tell all you know;",
"for he who tells everything he knows, often tells more than he knows.",
"Never believe all you hear;",
"for he who believes all he hears, often believes more than he hears.",
"Never attempt all you can do;",
"for he who attemps all he can do, often attemps more than he can do.",
"Never lay out all you can afford;",
"for he who lays out all he can afford, often lays out more than he can afford.",
"Some persons find the first way the easier; others, the other.",
"Generally, a combination of the two is both the easiest, surest, and quickest way.",
"I cannot get any work here.",
"I can never get him to do anything.",
"I cannot get it into his head.",
"When people get old, they generally get very cross.",
"When did you get home?",
"How do you get along?",
"Why don't you get out of the way?",
"I have not got through with my lesson yet.",
"Nothing ever happens but once in this world.",
"What I do now I do once and forever.",
"It is over",
"it is gone, with all its eternity of solemn meaning.",
"Instruction ends in the school-room; but education ends only with life.",
"The price of liberty is eternal vigilance, and the price of wisdom is eternal thought.",
"What is mine, even to my life, is hers I love; but the secret of my friend is not mine.",
"God helps them that help themselves.",
"Heaven!",
"Man's conscience is the oracle of God!",
"Thinking is the talking of the soul with itself.",
"Prayer is not overcoming God's reluctance; it is laying hold of his highest willingness.",
"A penny saved is a penny earned.",
"A friends in need is a friend indeed.",
"Politeness costs nothing",
"Where there is a will there is a way.",
"Charity begins at home.",
"Cut your coat according to your cloth.",
"Empty vessels make the most noise.",
"Man proposes, God disposes.",
"Strike while the iron is hot.",
"No rose without a thorn",
"Rome was not built in a day.",
"Smooth waters run deep.",
"Do you sell notions?",
"No, sir; we sell books and stationery.",
"Who advised you to call here for notions?",
"The cigarmaker across the street.",
"He probably directed you to the dry goods store, next door.",
"O, yes; I thought this was the dry goods store.",
"Well, I believe I want some paper.",
"Note-paper or writing-paper?",
"What do you call note-paper?",
"The small sheets are note-paper, and the large ones are writing-paper.",
"Please to give me a quire of each kind.",
"What else, sir?",
"No pens, ink, or lead-pencils?",
"No, sir; not this time.",
"You are probably aware that there is no established church in America",
"those who are members of a church have no political privileges, although Sunday is by law set apart as a day of worship.",
"All Americans do not belong to a church;",
"still a majority of them observe Sunday as a holiday.",
"But many foreigners, who are brought up in some established church, work on Sunday as on other days.",
"The soul is the more important part because it is immortal.",
"The soul is sometimes called the mind, spirit, or ghost.",
"The faculties of the soul are intellect, will, and conscience.",
"The intellect is regarded as the most important faculty, and is generally called \"the mind\".",
"The most important faculty of the mind is the reason; it is sometimes called \"sense\".",
"One year has three hundred and sixty-five days.",
"A leap-year has three hundred and sixty-six days.",
"January, March, May, July, August, October, and December have thirty-one days each.",
"April, June, September, and November, thirty days each.",
"February has twenty-nine days every leap-year.",
"The year 1900 was not a leap-year.",
"The old gentleman is my grandfather, another of the gentlemen is my father-in-law;",
"the two young ladies are my sisters-in-law",
"the young gentleman is my cousin;",
"the little boy is my nephew, and the little girl is my niece.",
"I have quite a number of them, indeed;",
"and I am pleased to see them around me on this occasion.",
"Among the principal causes of disease may be mentioned unwholesome food and drinks, and an unhealthy climate.",
"Many kinds of food which are wholesome for a healthy man are unwholesome for an unhealthy man.",
"It is healthy to keep the head cool and the feet warm.",
"Mr. C. being obliged to start to-morrow for the country, requests Mr. G. not to give himself the trouble of calling.",
"Mr. C. will be very happy to see Mr. G. the day after tomorrow at the hour that suits him best.",
"Mr. and Mrs. P. present their compliments to Mr. and Mrs. Y. and request the honor of their company to dinner on Thursday, at 7 o'clock precisely.",
"Mr. and Mrs. Y. accept Mr. and Mrs. P.'s obliging invitation and will have the honor to be with them at the hour they mention.",
"Mr. and Mrs. Y. greatly regret being obliged to decline Mr. and Mrs. P.'s obliging invitation, owing to a previous engagement.",
"I take the earliest opportunity of replying to the enclosed advertisement.",
"We remain,",
"I remain",
"Referring to our last letter we beg to say...",
"Referring to your favor of the 4th inst, I...",
"In answer to your esteemed favor of the 24th ult, we beg to say....",
"If Mr. N. can dispose of a few moments tomorrow at ten, he will much oblige Mr. S, by favoring him with an interview. Mr. S. will wait for him, and then explain to him the motive of this request.",
"Your favor of the 4th inst. has been duly received and the contents noted...",
"Mr. ---- will be glad to know by return mail if he can have a bed-room and sitting-room at your hotel from July 29th to September 29th, and what the terms would be, including full board.",
"I beg you to accept my best thanks for the permission you have given me to shoot on your estate, and which you have so kindly communicated to me by your letter of today.",
"$1,000.",
"Three months after date I promise to pay Edith McNiff One Thousand Dollars, for value received.",
"A negotiable Note.",
"Three months after date I promise to pay Edith McNiff, or order, One Thousand Dollars, for value received.",
"My pipe was now out, and as I went towards a fire which I saw near one of the tents, I perceived something sparkling in the sand:",
"it was a ring.",
"I picked it up, but by ill luck I put it on my little finger, for which it was much too large, and as I hastened towards the fire to light my pipe, I dropped the ring.",
"I stooped to search for it among the hay on which a mule was feeding, and the cursed animal gave me so violent a kick on the head that I could not help roaring aloud.",
"My cries awakened those who slept in the next tent, and the soldiers, provoked at being disturbed, were ready enough to think ill of me.",
"The soldiers took it for granted that I was a thief who had stolen the ring I pretended to have found.",
"The ring was taken from me by force, and the next day I was bastinadoed for having found it.",
"All this was the consequence of my being in a hurry to light my pipe, and of having put the ring on a finger that was too little for it.",
"A dyer who should take an oath was ordered to hold up his hand which was all black.",
"Take off your gloves, friend",
"Put on your spectacles, sir",
"An old woman bought a young raven.",
"Her neighbor asked her what she would do with that ugly animal.",
"I will try if it be true that such a bird can live two hundred years.",
"A fox came to a place where there were some fine ripe grapes, but they were hanging so high that he could not get at them.",
"He leapt till he was quite spent and strove all he could, but it would not do.",
"Oh, they are but green and sour things, and so I will try no more, but leave them where they are.",
"Once upon a time a giant and a dwarf were friends and kept together.",
"They made a bargain that they never would forsake each other, but go and seek adventures.",
"The first battle they fought was with two Saracens, and the dwarf, who was very courageous, dealt one of the champions a most angry blow.",
"It did the Saracen but little injury, who, lifting up his sword, fairly struck off the poor dwarf's arm.",
"He was now in a woeful plight;",
"but the giant coming to his assistance, in a short time left the two Saracens dead on the spot, and the dwarf cut off the dead man's head out of spite.",
"They then traveled on to another adventure.",
"This was against three bloody-minded monsters, who were carrying off a damsel in distress.",
"The dwarf was not quite so fierce now as before, but for all that struck the first blow, which was returned by another that knocked out his eye;",
"but the giant was soon up with them, and, had they not fled, would certainly have killed them every one.",
"They were all very joyful for this victory, and the damsel who was relieved fell in love with the giant and married him.",
"They now traveled far, and farther than I can tell, till they met with a company of robbers.",
"The giant for the first time was foremost now, but the dwarf was not far behind.",
"The battle was stout and long.",
"Wherever the giant came, all fled before him;",
"but the dwarf had more than once a narrow escape with his life.",
"At last the victory declared for the two adventurers, but the dwarf lost his leg.",
"The dwarf had now lost an arm, a leg and an eye, while the giant was without a single wound.",
"My little hero, this is glorious sport;",
"let us get one victory more, and then we shall have honor for ever.",
"no, I declare off, I'll fight no more",
"for I find in every battle that you get all the honor and rewards, but all the blows fall upon me.",
"he saw at a distance a great cloud of dust which seemed to approach towards him.",
"I have been",
"it has been",
"We have been",
"They have been",
"I had been",
"it had been",
"We had been",
"They had been",
"I shall be",
"it will be",
"We shall be",
"They will be",
"I may be",
"it may be",
"You may be",
"They may be",
"I might be",
"it might be",
"They might be",
"I loved",
"We loved",
"You loved",
"They loved",
"I have loved",
"He has loved",
"She has loved",
"We have loved",
"You have loved",
"They have loved",
"I will relate a fatal circumstance which occurred in my youth, and of which I was almost the only witness.",
"There are few persons yet living who can recollect so far back as 1798, or the dreadful winter which has rendered that year remarkable in the annals of Auvergne.",
"The weather, which had been fine and clear, though remarkably cold up to the latter end of November, changed suddenly, and in the night of the twenty-fourth, a terrible snow-storm commenced, and continued for four days with but trifling intermission.",
"On the evening of the 29th a strong wind arose.",
"The roads became impassable from the tremendous drift, and all intercourse between the towns and villages was broken off.",
"The inhabitants kept as much as possible within their houses, for even in the broad day a stray wolf was occasionally seen prowling around the farm-yards, while, at night, they scoured the country in packs and, rendered furious by hunger, attacked every living thing that was left unprotected.",
"Their savage howlings, as they besieged the folds and other outbuildings where the cattle were lodged, were distinctly heard in the awful silence of the night, filling every heart with anxiety, and preventing the possibility of sleep.",
"curiosity overcame my terrors.",
"Suddenly checking his horse before the door, he shouted in the most heartrending manner for admission and assistance.",
"No answer was returned, no sound indicated that his appeal was heard, all appeared sunk in sleep, or, what is more probable, too much alarmed for their own safety to arise.",
"Just at this instant there arose from behind a fierce and hateful yell, as if a hundred demons had broken loose from those regions of torture where they are said to be confined.",
"The horse reared and plunged violently; and his unhappy rider, with a cry of despair, which still seems to ring within my ears, again spurred swiftly onward.",
"As I just observed, I was but a boy, scarcely eleven years of age, and my heart died within me, as, leaning forth my body from the window, I plainly distinguished the whole pack turning the corner of the church and advancing in full cry towards the spot above which I stood.",
"For a moment they appeared to have lost the scent, or were arrested by the hopes of a second victim",
"while some, with noiseless steps and noses to the earth, hurried to and fro before the inn-door, the greater number collected under my window, and rearing upon their hind legs, snuffed the air and barked and howled at the prey beyond their reach.",
"At length the scent was recovered, and the whole pack, with a fatal precision, again set forward in the direction taken by the unfortunate stranger.",
"I remained listening till the sounds were lost in the distance, and then crept trembling to bed, but not to sleep.",
"from time to time",
"the utmost consternation prevailed",
"a mingled cry of horror and pity burst from the listeners",
"The sun rises and sets.",
"I like to walk by moonlight.",
"Tomorrow we shall have a full moon.",
"When will there be a new moon?",
"We saw the comet last night by the help of a telescope.",
"There will be one eclipse of the sun and two of the moon this year.",
"Air is lighter than water.",
"The earth produces everything necessary to the welfare of man.",
"The sky is full of beautiful stars.",
"There is not a star to be seen.",
"It is said a new planet has been discovered.",
"The best water is that which has neither taste nor smell.",
"Fire is one of the four elements.",
"Of all animals the horse is perhaps the most useful to man.",
"The flesh of the ox is one of the foods which nature furnishes to man.",
"The ass though inferior to the horse is a very useful animal.",
"The ram is the male of the sheep.",
"Sheep supply us with wool, and from wool warm clothing is made to protect us from the winter's cold.",
"The bat is seldom seen in the day time;",
"it comes out to fly in the evening.",
"Of all domestic animals the dog is the most familiar and intelligent.",
"Cats attach themselves to the house, and dogs to the person of their master.",
"Squirrels are easily tamed.",
"The elephant it not only one of the largest animals, but also one of the most sagacious.",
"The camel has a hump on its back.",
"The stag casts its horns every year.",
"The bear lives in the mountains and woods;",
"it is chiefly an inhabitant of cold countries, and its skin forms a valuable article of commerce.",
"The lion, the king of animals, is found in the hot countries of Africa and Asia.",
"He fears no danger, but he never attacks man unless driven to it by hunger.",
"The wolf is a cruel and rapacious animal;",
"in shape it resembles the dog but is rather larger.",
"Wolves are much afraid of fire.",
"Mice and rats are very destructive and harmful in barns and granaries.",
"The cow supplies us with milk which forms a very wholesome and grateful part of our nourishment, and from which butter and cheese are made.",
"The flesh of the calf is called veal, that of the ox and the cow, beef.",
"The flesh of the hog is called pork.",
"The goat is a much hardier animal than the sheep but not so useful.",
"Monkeys, of which there are various species, are found principally in Africa;",
"some have a long tail, others none.",
"In shape they approach very nearly to the figure of a man.",
"They walk with great facility on their hind feet, making use of the fore feet as hands, with which they eat, and throw stones at their enemies.",
"They eat sitting, and imitate every action they see a man perform.",
"The fox is thought to be one of the most cunning of the four-footed race;",
"he lurks about the farmyard, and makes sad havoc amongst the poultry.",
"He also preys upon young hares and rabbits, eggs, honey, cheese, and apples.",
"The badger is common in Europe;",
"it lives in holes in the ground, or under the roots of trees, and its flesh is said to be good eating.",
"The tiger, the leopard, and the rhinoceros are principally found in Asia.",
"A female sheep is called a ewe, and a kitten is a young cat.",
"The cry of the owl is very disagreeable;",
"it makes its nest in barns or in some hollow tree.",
"The stork builds its nest on the top of houses.",
"The cuckoo, whose monotonous note is heard in May and June, makes no nest, but deposits its eggs in the nest of some other bird.",
"The swallow is the harbinger of spring;",
"it generally appears in England about the middle of May, and departs again in September.",
"It lays from four to six white eggs, dotted with red specks",
"the first brood is hatched about the end of June or beginning of July.",
"Sparrows build their nests under the eaves of houses;",
"as the weather becomes hotter they get out for coolness and nest in plum trees and apple trees.",
"Parrots are natives of tropical countries, and imitate the human voice with great facility;",
"they are supposed to live to a great age.",
"The hen, the most useful of domestic birds, generally lays an egg every day.",
"On the least appearance of danger she gathers her chickens under her wings.",
"The cock is superior to the hen in size, strength, beauty, and courage.",
"The pigeon has long been domesticated with us;",
"in its wild state it is a bird of passage.",
"The peacock is celebrated for the beauty of its plumage, but its voice is harsh and disagreeable.",
"The eagle is generally considered as the king of birds, from its strength of wing, by which it can sustain itself at a height that no other bird can reach.",
"Last summer I reared a nest of linnets;",
"they were very tame having been brought up by hand.",
"The nightingale, one of the finest songsters of the feathered race, visits England about the beginning of September.",
"Nightingales are particularly fond of ants and their eggs, for which they will leave any other food.",
"The canary bird is prized for its beautiful note and bright yellow plumage.",
"Though these birds pair and breed in confinement, they are not naturalized to the climate, and cannot support the rigor of the winter.",
"The goose furnishes us with down for our beds, pens for writing, and a delicious article of food in its flesh.",
"The duck is not less savory than the goose, though not so large.",
"The swan is of a beautiful white, and is much larger than the goose;",
"its long and graceful neck contributes not a little to its embellishment.",
"A female fox having swam into a pond to devour the geese was attacked by the gander, which, being the most powerful in its own element, buffeted the fox with its wings about the head till it was drowned.",
"Crows always fly in pairs the whole year.",
"A hen partridge came out of a ditch, and ran along shivering with her wings and crying out as if wounded and unable to get from us.",
"While she acted this distress, the boy who attended me saw her brood, that was small and unable to fly, run for shelter into a hole under the bank.",
"The markets of Vienna are well supplied with pheasants, principally from Bohemia.",
"Syria is celebrated for its turkeys and capons.",
"A goose will fly at a dog in defense of her goslings.",
"The most beautiful flowers bloom in the months of May and June.",
"In those months the tulip, lily, wallflower, pink, and rose are in the greatest perfection, and adorn the garden with their beauty, or their fragrance.",
"The meadows are enameled like a parterre with primroses, daisies, and other pretty wild flowers, and the modest violet is found beneath the hedge-rows or in the woods.",
"In autumn, the sunflower and the dahlia are in their greatest pomp.",
"The delicate snowdrop is the first that makes its appearance after the gloomy desolation of winter.",
"From the beauty of form and color, and its exquisite fragrance, the rose has always been considered as the queen of the garden.",
"The lily is the emblem of purity and innocence, the violet of modesty.",
"Roses are propagated by suckers or by seed.",
"The season for planting is from October till March, and they will mostly flower in perfection the following summer.",
"In a large town there are people of different trades and professions who make it their business to supply the wants of the townsmen.",
"Thus, a baker supplies them with bread which he makes from the flour that he has bought from the miller.",
"A butcher buys oxen, sheep, and lambs, kills them and cuts them up, and sells the joints to his customers for their dinners or suppers.",
"The tailor makes coats, waistcoats, and trousers to protect our bodies from the cold winds and to keep us warm.",
"The shoemaker supplies us with boots and shoes, which keep our feet warm and dry, and add to our comfort and convenience in walking.",
"The carpenter, bricklayer, mason, and blacksmith are equally useful, for without them we should have neither houses nor rooms, nor doors, nor windows.",
"A fishmonger buys fish from the fishermen who catch it, and sells it again in his shop, or in the market.",
"A cheesemonger is a dealer in butter and cheese.",
"A hatter sells hats, a linen-draper linen from which our shirts, table-cloths, towels, sheets, ladies' apparel, and many other articles of daily use are made.",
"After leaving their bedrooms the family meet at breakfast in the parlor, where they stay till dinner time.",
"The dinner is laid in the dining-room, and after dinner they sit in the drawing-room.",
"The garrets are rooms at the top of the house in which the servants sleep.",
"We let our rooms on the first floor for thirty dollars a month, and live on the second.",
"I inquired for the master of the house and was shown into the parlor.",
"His drawing-room was furnished elegantly.",
"Our cook keeps the kitchen very neat.",
"The pots and pans are mostly of copper, and, being arranged in bright rows against the wall, give it a very ornamental appearance.",
"The cellar is cool and very large.",
"The stairs are very steep;",
"in going down, take care you do not fall.",
"We have been buying new furniture for our dining-room.",
"There are twelve mahogany chairs, a sofa, a dining-table, and two small round tables.",
"He politely offered me the arm-chair.",
"Put out the card tables and bring the cards;",
"we will play a game of whist.",
"I saw nothing in the room but an old broken table and three or four pine chairs.",
"Put your clothes away neatly in the drawer, and then lock it, and bring me the key.",
"What have we got for dinner today?",
"A roast leg of mutton.",
"Will you take any boiled beef?",
"I prefer potatoes to any other vegetable.",
"The turnips are not well boiled.",
"Mix the salad.",
"The pork is not roasted enough.",
"On Christmas Day we had a fine piece of roast beef.",
"At this time of the year we seldom get good venison.",
"In Vienna the price of venison is very reasonable.",
"A breast of veal and asparagus is no bad dinner.",
"Take a little pepper and salt to the turnips.",
"Do you never eat sausage?",
"The price of pork is frequently higher than that of venison.",
"This ham is much too salty.",
"The Prague hams are very good, but scarcely salty enough.",
"You have kept the venison too long.",
"Our cook does not roast well.",
"There was no asparagus in the market;",
"the market is never well supplied with vegetables.",
"At what shop did you buy this ham?",
"We get very good beef at our butcher's.",
"In London, fifteen shillings is not an uncommon price for a turkey at Christmas.",
"Your cook boils better than she roasts.",
"I was very hungry when I sat down to dinner.",
"You have always a good appetite.",
"Which do you like best, tea, coffee, or chocolate?",
"He wore a black coat and waistcoat, and white linen trousers.",
"Your dress is very becoming.",
"The washerwoman has not sent home my drawers.",
"A rent in his boots showed a stocking not over-white.",
"In coming out of the theater my sister lost her glove.",
"The manufacture of gloves is carried to great perfection in Vienna.",
"My husband has made me a present of a new bonnet.",
"To wear tight stays must be injurious to the health.",
"The peasant-women wear a petticoat of coarse blue cloth.",
"The dressmaker has not yet sent home her new dress.",
"The sleeves of my new coat are too tight.",
"The lining of your bonnet is very pretty.",
"The tailor has brought home your silk waistcoat.",
"The waistcoat is very well made.",
"These shoes pinch me.",
"My sister has lost her bonnet, and my brother has lost his hat.",
"Her gown was made by my dressmaker.",
"She promised to send home the dress the day after tomorrow.",
"It is said that she never wears the same dress twice.",
"She had on a very dirty muslin dress.",
"My daughters never wear stays.",
"Will you put on the boots or the shoes?",
"If you go out today I wish you would buy me two pair of silk stockings.",
"How do you like that young lady's dress?",
"Shall I fetch your blue coat?",
"You always wear pretty caps;",
"who is your milliner?",
"Her cap is made of the finest Brussels lace.",
"Charles has a pain in his head.",
"My sister has a headache.",
"They struck him over the head with a thick stick.",
"My cousin has beautiful long black hair.",
"The Germans have mostly high foreheads.",
"Her cheeks are of a fine rosy red.",
"The ass has very long ears.",
"Your hands are very cold.",
"My little brother has chilblains on his fingers.",
"I bit my tongue.",
"The child is cutting its teeth.",
"In climbing up a tree after a bird's nest, he fell and broke his arm.",
"The man is lame on account of an injury to his hip.",
"Edward the First, King of England, was called Long Shanks, from the length of his legs.",
"Count Trenton has dark bushy eyebrows.",
"The young gentleman has hurt his arm and carries it in a sling.",
"Little boys ought always to have clean hands.",
"She has a very pretty face, but that is her only merit.",
"If you have the toothache why not go to the dentist's and get it taken out?",
"My sister has a swelled face.",
"If to her share some trivial errors fall, look in her face and you'll forget them all.",
"The weather is very bad, you cannot go out without an umbrella.",
"A flash of lightning illuminated the whole horizon.",
"Canary birds cannot endure the cold of our winters.",
"In consequence of England's being surrounded by the sea there is always a great deal of rain and mist.",
"The London fog is a mixture of smoke and mist.",
"Every pane of glass in the place was broken by the hail-storm.",
"A terrible storm arose on the third day after the ship had left the coast.",
"The rain fell in torrents, and not a building was there for miles in which we could take shelter.",
"The wind blew from the southwest and was accompanied by frequent showers.",
"In the afternoon the heat became greater, and every one suffered from the want of water.",
"The snow lay in some places more than three feet deep.",
"The night is not only dark but rainy;",
"we cannot let you go out sucn a night as this.",
"If the weather should be unfavorable he will not come.",
"The late warm weather will bring everything forward.",
"The present dry weather will be good for the harvest.",
"Make hay while the sun shines;",
"this fine weather will not always last.",
"The storm, I suppose, kept you at home this morning?",
"The flashes of lightning were very vivid.",
"We heard some thunder at a distance.",
"Thunder-storms are of very frequent occurrence with us.",
"It is not very usual to hear thunder in the winter.",
"Who has taken away my scissors?",
"If you are going out, buy me some thread of different sorts, some cotton, and some common black worsted.",
"I also want a few skeins of crimson silk.",
"Have you brought me any English needles from London?",
"Take all these pins out of the paper, and stick them into the pincushion.",
"I have upset the workbox;",
"help me pick up the things.",
"That thimble is too large;",
"here is one that will suit your finger better.",
"It is very seldom I have time to do any needlework.",
"You have not brought the worsted of the right color;",
"these shades do not match well.",
"My embroidery is almost finished, but I want some dark blue worsted to complete this flower.",
"How long is it since you began it?",
"I began it only last week.",
"My cousin made me a present of a pair of cutting-out scissors.",
"Your collar is unpinned;",
"let me pin it for you.",
"Do not let the child play with the pins, she will prick herself.",
"Are you fond of needlework?",
"Yes, I always make my own caps and dresses.",
"Indeed!",
"I did not think you were so capable a needlewoman.",
"Please help me to some bread.");

function firstNorwegianLine()
{
	global $norwegianlines;
	return $norwegianlines[array_rand($norwegianlines)];
}

?>
