<?
// https://archive.org/details/hossfeldsspanish41915gut
// Hossfeld's Spanish Dialogues, and Idiomatic Phrases Indispensible for a Rapid Acquisition of the Spanish Language
// 1915
// C. Hossfeld; W. N. (William N.) Cornett

	$spanish3lines = array(
"What is that?",
"What is this?",
"What is it?",
"What do you call that?",
"What is the name of this?",
"Tell me the Spanish for this word.",
"What do you want?",
"What do you wish to have?",
"Do you hear me?",
"Do you understand what I say?",
"Yes, Sir",
"No, Sir",
"Will you have the goodness to say it again?",
"What do you say?",
"What do you mean?",
"What do you say to it?",
"Does she understand what we say?",
"Did you speak to me?",
"Why do you not answer?",
"What did they answer?",
"When did you hear that?",
"Are you sure of that?",
"Who told you so?",
"What does it mean?",
"What is the matter?",
"What are you doing?",
"What are you asking for?",
"Whom do you ask for?",
"What do you think of it?",
"What are you thinking of?",
"Where are you going?",
"Are you going there?",
"Are you going home?",
"How far do you go?",
"Where do you wish to go?",
"Which way shall we go?",
"Has he gone?",
"Where do you come from?",
"Will you come with me?",
"Will you be at home to-night?",
"When will you come?",
"When do you leave for England?",
"Whose stick is this?",
"Will you have it?",
"Whose books are these?",
"Will you send them to me?",
"How much will you give?",
"How much do you want?",
"How much do I owe you?",
"What shall we do?",
"I do not know what to do.",
"What would you advise me to do?",
"What is to be done?",
"What is the news?",
"Is there any news?",
"Have you seen the newspapers?",
"Where is it?",
"Where are they?",
"What is the use of that?",
"For whom is it?",
"What do you want me for?",
"Is the door open?",
"Are the windows shut?",
"Will you allow me?",
"Will you do me a favour?",
"I have a favour to ask of you.",
"Will you render me a service?",
"Thanks.",
"Thank you.",
"Many thanks.",
"Thank you very much.",
"I am very much obliged to you.",
"I am giving you a great deal of trouble.",
"I am sorry to trouble you.",
"No trouble at all.",
"Do not mention it.",
"You are going the right way.",
"You are going the wrong way.",
"No, it is not far.",
"It is scarcely two miles.",
"It is only two steps from here.",
"It is only a short distance away.",
"One Spanish league.",
"One English mile.",
"Three miles are one league.",
"It is about one mile.",
"It is not quite a mile.",
"Which way am I to go?",
"Which way must I go?",
"Go straight on.",
"Turn to the right.",
"Go to the left.",
"You will turn to the right at the first corner, then to the left, and then keep straight on.",
"You are going a round-about way.",
"Pardon me, Sir, can you direct me to the hotel \"Four Nations?\"I have lost my way.",
"I have lost myself in these narrow streets.",
"Do you know which is the way to the Theatre Royal?",
"I am very sorry, Sir, I do not know, but this policeman here will be able to tell you.",
"How far is it from here to the Southern Railway Station?",
"Where can I find a cab?",
"Is there a ’bus from here to the Zoological Gardens?",
"Yes, Sir, there is the green ’bus which runs along the embankment.",
"There is a tramway.",
"How much is the fare?",
"Is there a museum in this town?",
"Can you tell me where the Picture Gallery is?",
"Could you show me the way to the Royal Square?",
"Is it far to the theatre from here?",
"Will you have the kindness to tell me in which part of the town is the Royal Palace?",
"If you follow this street until you come to the Cathedral, you will see the palace on the right.",
"The theatre is on your left, about fifty paces from here.",
"Where is the post-office?",
"It is not far from here;",
"you will get there in five minutes, if you follow the tram-lines.",
"Cabman, drive me to the Northern Station;",
"hurry up.",
"Drive faster.",
"Drive me to the Victoria Hotel.",
"I engage you by the hour.",
"Take me first to St. John Street, number four.",
"And now I want to go to the Botanical Gardens.",
"How much is your fare?",
"Three pesetas, if you please.",
"Where does Mr. B. live?",
"Do you know Mr. B.?",
"No, Sir.",
"No, Sir, I do not.",
"I do not know anybody of that name here.",
"Yes, Sir, I know him.",
"I know him very well.",
"I have the honour of his acquaintance.",
"Will you favour me with his address?",
"In what street does he live?",
"Is it far from here?",
"It is only a stone's throw.",
"Can you direct me to his house?",
"I am going that way myself.",
"I will show you his house.",
"It is very far from here.",
"In that case I will take a cab.",
"Call a cab.",
"Drive me to No. 4, ... Street.",
"Stop at this house.",
"On the right side going up.",
"On the left side going down.",
"At that brick house.",
"At that marble house.",
"Enquiries concerning a Journey.",
"Is the road good?",
"It is not very bad.",
"It is shocking in winter.",
"It is pretty good at this season.",
"Is the road sandy?",
"The road is wide.",
"I am going to book my seat at the coach office.",
"I prefer going by the mail.",
"I do not like the steamboat.",
"How much is the fare?",
"Three pesetas.",
"How many miles is it from here to B.?",
"I did not think it was so far.",
"When shall we start?",
"To-morrow morning at six o'clock.",
"And at what o'clock shall we reach B.?",
"At eight in the evening.",
"Where are we to breakfast?",
"Where shall we dine?",
"Where shall we have tea?",
"All the passengers are here.",
"Let us start then.",
"Driver, what prevents you from starting?",
"At last we have started.",
"Shut the door.",
"Where are we?",
"What is the name of this village?",
"Does the coach stop here?",
"Yes, Sir, to change the horses.",
"Shall we have time for refreshments?",
"At what hotel does the coach put up?",
"We have arrived at last.",
"Have you any baggage to carry, Sir?",
"Yes, take this trunk.",
"Yes, take this portmanteau.",
"I want a single bedded room.",
"At what o'clock shall we have supper?",
"At half-past eight.",
"I shall go to bed early.",
"I am very tired.",
"The road was very bad.",
"Why did you not choose the steamboat?",
"One travels by it much more comfortably.",
"I think I shall go by it another time.",
"Where is the railway station?",
"Show me the booking office.",
"I want a ticket to Paris.",
"What class?",
"1st cl., 2nd cl., 3rd cl.",
"Single or return?",
"Is there a ladies' compartment?",
"Is there a smoking compartment?",
"Is there a lavatory?",
"Can I get a seat reserved in advance from Calais?",
"Certainly;",
"what seat would you like?",
"A corner seat facing the engine.",
"My friend wants the seat opposite, with back to the engine.",
"There is an extra charge of 2/-a seat to pay.",
"Where is the luggage-office?",
"My luggage is in the cloak-room.",
"Have you the luggage-ticket?",
"What is the charge?",
"What luggage does my ticket entitle me to take free?",
"When does the train to Dover start?",
"From which platform?",
"Which is the departure platform?",
"The arrival platform.",
"Take your seats!",
"Tickets, please.",
"Do you object to my opening the window?",
"Is there a restaurant-car attached to this train?",
"Can I get sleeping-car accommodation reserved from Paris?",
"What extra is there to pay?",
"I hope I am not in the wrong train.",
"How long does the train stop here?",
"Is there a refreshment-room?",
"All change here!",
"Porter, take my luggage to the steamer.",
"Carry it down to the first-class saloon.",
"I shall remain on deck.",
"The sea is somewhat rough.",
"Are you a good sailor?",
"I have never been sea-sick, but I must say I have always crossed when the sea was calm.",
"There is Calais.",
"What do you intend doing in Paris?",
"I shall see the sights of the town.",
"Shall we hire a motor car for sight-seeing?",
"Where can we hire a motor car?",
"There are several large garages where motor cars can be had by the day or week.",
"What is the horsepower of this car?",
"What is your charge for a day or a week?",
"Does this price include the driver's expenses?",
"What is the average number of kilometres that can be done in a day?",
"What make is this car?",
"Is it in good condition?",
"Do you guarantee that it will not break down en route?",
"Is your driver reliable and experienced?",
"Where does the customs' examination take place?",
"Must I be present at the customs' examination?",
"Must we open our luggage at the customs?",
"Have you anything to declare?",
"No, nothing.",
"I have nothing but personal effects.",
"Would you like to see for yourself?",
"These are my things.",
"Here are the keys.",
"Must I open this?",
"Do you want to examine this?",
"All these things are for my own use.",
"Have you anything liable to duty?",
"Have you any tobacco?",
"I have some cigars and cigarettes.",
"What does the duty amount to?",
"Will this be refunded on my return?",
"You can close your boxes.",
"Are you up already?",
"At what time do you get up?",
"I get up at six o'clock.",
"It is too early.",
"You get up very early.",
"I like to get up early.",
"It is a very good habit.",
"It is very good for the health.",
"Get up!",
"You have been called twice.",
"How sleepy you are!",
"You go to bed too late.",
"Let me sleep.",
"It is too early to get up yet.",
"Too early?",
"Do you know the time?",
"It cannot be late.",
"It may be five o'clock.",
"Five o'clock?",
"It is half past eight.",
"I did not think it was so late.",
"I am going to get up directly.",
"Make haste and dress yourself.",
"I shall not be long.",
"How did you sleep last night?",
"I slept well.",
"I never woke all night.",
"I did not sleep well.",
"I could not sleep.",
"Let us go for a little walk.",
"Shall we have time before breakfast?",
"We shall have a good hour.",
"Tell me, waiter, is there a bath to be had here?",
"Yes, Sir, we have a cold and warm bath, and a shower-bath.",
"I want another towel and a piece of soap.",
"See that the water is not too hot.",
"Waiter, a little more hot water.",
"Enough! Thanks.",
"Dressing.",
"Give me my stockings.",
"Bring me my shoes.",
"Clean them better;",
"they are not properly cleaned.",
"My linen is damp;",
"air it a little.",
"Has the washerwoman brought my linen?",
"Pay her bill.",
"Give me some warm water.",
"Where is the soap?",
"Go and fetch me a towel.",
"Bring me my razors.",
"Do you want a pin?",
"Give me a needle.",
"Give me a collar and a necktie.",
"Where are my gloves?",
"I cannot find them.",
"They cannot be lost.",
"Brush my hat.",
"Breakfast.",
"Have you had your breakfast?",
"Not yet.",
"You come just in time.",
"You will breakfast with us.",
"Is breakfast ready?",
"It will soon be ready.",
"Everybody is up.",
"They are only waiting for you.",
"I am coming down directly.",
"I beg your pardon for having kept you waiting.",
"Do you drink tea or coffee?",
"Here is coffee.",
"There is tea.",
"You have your chocolate near you.",
"What do you prefer?",
"What do you like best?",
"I prefer coffee.",
"Will you give me some chocolate?",
"Is your coffee sweet enough?",
"It is excellent.",
"There are rolls.",
"There is toast.",
"Would you mind passing me the butter?",
"Pass me the bread, if you please.",
"The tea is rather weak.",
"I like it strong.",
"I drink it without sugar.",
"What may I offer you?",
"Nothing more, thank you.",
"Do you take cream with coffee?",
"There are some fresh eggs;",
"allow me to give you one.",
"Will you have some cold meat?",
"Will you have a sausage?",
"I have made an excellent breakfast.",
"What do you prefer—tea or coffee?",
"Will you be kind enough to give me a cup of tea?",
"Is it to your liking?",
"I should like a little more sugar.",
"What will you take—ham or a piece of roast chicken?",
"May I offer you a cup of coffee with milk?",
"Thanks, but I prefer my coffee without milk.",
"Please help yourself to a little more.",
"No, thank you, I have made a very good breakfast.",
"It will soon be two o'clock.",
"It is almost two o'clock.",
"It is nearly two o'clock.",
"It is half past one.",
"Let us return home.",
"What time shall we have lunch to-day?",
"The cloth will be laid presently.",
"Lunch is on the table.",
"Let us sit down.",
"No, not yet.",
"Do you expect company?",
"I expect Mr. and Mrs. B.",
"Have you ordered dinner?",
"What have you ordered?",
"What shall we have for dinner?",
"Shall we have any fish?",
"There was no fish in the market.",
"Mr. and Mrs. B. will not come.",
"Let us begin lunch.",
"What may I offer you?",
"Will you have some soup?",
"Will you take some soup?",
"If you please.",
"Thank you.",
"Kindly pass me a little beef.",
"It looks very nice.",
"This fowl is delicious.",
"Will you have a wing?",
"If you please.",
"I will thank you for some gravy.",
"Shall I give you some vegetables?",
"Will you have some salad?",
"I will take some salad.",
"Will you have a little sauce?",
"May I offer you a piece of this roast beef?",
"I will take a small piece.",
"Will you have it well done?",
"Will you have it underdone?",
"Rather well done.",
"I like it underdone.",
"Did I help you to your liking?",
"It is excellent.",
"It is as tender as a chicken.",
"Gentlemen, allow me to drink your health.",
"This claret is delicious.",
"Let us have a bottle of champagne.",
"How do you like it?",
"It has a very pleasant flavour.",
"Have you any good cheese?",
"Give me a small piece of cheese.",
"Which will you have?",
"English cheese.",
"You are giving me too much.",
"Give me only half of it.",
"Cut that in two.",
"Bring the dessert.",
"We have had a good lunch.",
"Let us taste these peaches.",
"These pears are delicious.",
"You may clear the table.",
"Bring us some wine.",
"Lunch is over.",
"Dinner is announced gentlemen;",
"let us go into the dining-room.",
"A little more soup, Sir?",
"I will take a little more if you please.",
"What wine would you like, claret or port?",
"Your health, Sir.",
"Yours, Sir.",
"Do you care for this wine?",
"I like this wine very much.",
"Allow me to help you to a little of this shoulder of lamb.",
"And what can I help you to?",
"I will take a little beef, it looks very good.",
"Will you kindly pass me the cruet?",
"A potato, if you please.",
"Which part of this duck may I help you to?",
"I will take a leg, please.",
"Will you kindly pass the mustard?",
"With much pleasure.",
"I shall be delighted.",
"Madam, allow me to help you to some of this whiting.",
"Madam, permit your servant to drink your health.",
"Yours, my friend.",
"Which cheese do you like best?",
"Give me a little bread and butter.",
"Do you like grapes, or would you prefer an apple?",
"These oranges are very sweet.",
"Let me offer you a cigar.",
"Do you prefer Havanas or Manillas?",
"This is an excellent cigar.",
"Take another.",
"Waiter, the bill of fare, please.",
"Here it is, Sir.",
"What would you like, gentlemen?",
"What time is table d'hôte?",
"Have you dinners at fixed price?",
"We will dine at fixed price.",
"We are going to order from the bill of fare.",
"Have you a table free near the window?",
"This is the only one disengaged.",
"What soup have you?",
"Bring us some vegetable soup.",
"Is there any fish ready?",
"Let us have some leg of mutton, with fried potatoes and cauliflower for two, and half a fowl with boiled potatoes.",
"Waiter, a bottle of English beer.",
"I am very sorry, Sir, we haven't any beer, but we have splendid wine.",
"Well then, a bottle of claret.",
"Waiter, two coffees.",
"Black coffee.",
"White coffee.",
"A cognac.",
"Nothing more for me.",
"Have you any good cigars?",
"Yes, Sir, we have superior Havanas.",
"I don't care for these;",
"they are too strong.",
"Let us have some cigarettes.",
"The matches, please.",
"You have forgotten to bring the sugar.",
"Waiter, the bill.",
"Here it is, Sir.",
"How much have we to pay?",
"Here is your account, Sir.",
"You may keep the change.",
"Tea.",
"It is five o'clock.",
"Tea will be ready in a moment.",
"Do you hear the bell?",
"Let us go down.",
"Sit down, Gentlemen.",
"I like tea without sugar.",
"And I without cream.",
"I like my tea strong.",
"I prefer it weak.",
"Allow me to give you another cup.",
"I never take more than one cup.",
"Will you have some milk?",
"Bring some more boiling water.",
"This water is not hot enough.",
"There is fresh butter.",
"This bread is good.",
"I will willingly take half a cup more.",
"Will you have some toast?",
"I shall come and take tea to-morrow at your house.",
"I shall be very glad to see you.",
"We take tea exactly at five.",
"Supper.",
"Will you stay and sup with us?",
"Have supper with us without ceremony.",
"Bring a plate, and a knife and fork for this gentleman.",
"No, really.",
"I never take supper.",
"Well, sit near the table.",
"We will talk.",
"You will take a glass of wine, will you not?",
"You cannot refuse that.",
"Do you like oysters?",
"I am very fond of them.",
"I will take a few.",
"How do you like them?",
"They are good and very fresh.",
"Will you take a slice of cold turkey?",
"No, thank you.",
"I am satisfied with my piece of bread and butter.",
"Will you take a glass of beer?",
"Willingly;",
"I do not like tea.",
"In England the beer is excellent.",
"I like beer.",
"It is an agreeable and wholesome drink.",
"Evening.",
"It is getting late.",
"It is almost time to go to bed.",
"Mr. A. has not come home yet.",
"Will he be late?",
"He generally comes home early.",
"I hear a knock.",
"Very likely it is he.",
"Go and see.",
"Yes, it is he.",
"I hope I have not kept you waiting.",
"Not in the least.",
"It is only ten o'clock.",
"We never go to bed before half-past ten.",
"How did you like your walk this evening?",
"Very much.",
"It is a charming evening.",
"Are you not tired?",
"Not very.",
"Will you not rest a little?",
"No, thank you.",
"I am going to bed.",
"Are you going already?",
"It is not late.",
"It is early yet.",
"It is time to go to bed.",
"I do not like to go to bed late.",
"I like to go to bed early.",
"I wish you good night.",
"I wish you a good night's rest.",
"Let me see the room I am to sleep in.",
"Will you show me my bed-room?",
"I should like a room on the first floor.",
"Give me a quiet room.",
"Your room is quite ready.",
"Well, show me the way;",
"I will follow you.",
"Nobody sleeps above you.",
"Close the window-shutters.",
"Bring my baggage up to my room.",
"Where have you put our things?",
"Are the beds well aired?",
"These sheets feel damp.",
"I must have others.",
"Warm my bed.",
"It is very cold.",
"I shall want another blanket.",
"This is too light.",
"Give me another pillow.",
"Put some water in my basin.",
"Will you have a nightlight?",
"No, that would prevent my sleeping.",
"Take away the candle.",
"I will put it out myself.",
"Before you go, draw the curtains.",
"Is there a bell in this room?",
"At what time do you wish to get up tomorrow?",
"When am I to call you?",
"Exactly at six.",
"I must set off early.",
"I will not fail to come and wake you.",
"You may rely upon me.",
"I should like to have my bill.",
"It is ready.",
"Tell your master to send me the bill.",
"I will settle with him to-night.",
"What have I to pay?",
"What do I owe you?",
"I have brought your bill.",
"It amounts to ten pesetas.",
"It is very high.",
"Here is your money",
"It is all right.",
"Now I am going to sleep.",
"Does the door shut properly?",
"Is there a lock?",
"Where is the key?",
"Is there a bolt?",
"Sir, I wish you a good night's rest.",
"This bed is very hard.",
"I don't think I shall be able to sleep.",
"A Meeting.",
"Good morning, Sir.",
"Good afternoon, Madam.",
"Good evening.",
"Good night.",
"I wish you good morning.",
"How are you?",
"How do you do?",
"Are you well?",
"I am very well, thank you, and you?",
"Quite well.",
"I am glad to find you in good health.",
"How is your mother?",
"How is your family?",
"They are all well.",
"You look very well.",
"You have never looked better.",
"You do not look well.",
"You look ill.",
"Are you unwell?",
"I am not very well.",
"I feel indisposed.",
"I suffer a great deal.",
"I have been obliged to keep my bed.",
"I have had a bad cold.",
"I have a very bad cough.",
"I have the toothache.",
"I have a headache.",
"I have a sore throat.",
"I did not sleep a wink.",
"I feel greatly relieved.",
"I am a little better this morning.",
"I hope it will be nothing.",
"I am very sorry to hear it.",
"I am sorry, but I hope it will not have serious consequences.",
"What! Is it you?",
"Is it really you?",
"You quite surprise me.",
"I did not expect to meet you here.",
"I am very glad to see you.",
"When did you return?",
"I came home last night.",
"How did you come?",
"I came by the express.",
"You came rather unexpectedly.",
"What made you return so soon?",
"Business called me here.",
"How did you like your journey?",
"I liked it very well.",
"I have had a very pleasant journey.",
"When shall I have the pleasure of seeing you at my house?",
"When will you come and dine with us?",
"I cannot say.",
"I will come one of these days.",
"Come to-day.",
"I cannot.",
"I have some business to do.",
"I will call on you.",
"I will call on you some time to-morrow.",
"We shall be very pleased to see you.",
"Good morning, Sir.",
"I hope you are well, Madam.",
"Very well, thank you, and how are you, Sir?",
"I am very well, thank you.",
"Be seated.",
"Please take a seat.",
"Take a seat.",
"I have not been very well lately, but I feel better now.",
"I have caught cold to-day.",
"I hope you will soon be better.",
"I am much obliged to you for your kindness.",
"Ah, here is Mr. C.",
"I am very glad to see you.",
"Allow me to introduce Mr. C. to you.",
"I am delighted to make your acquaintance, Sir.",
"Pleased to meet you.",
"How is your brother?",
"He enjoys excellent health, and does not know what sickness is.",
"Yes, doubtless;",
"but he must take care of himself.",
"We don't know the value of health till we have lost it.",
"He has not been well for a week, and was not able to go out all that time.",
"I hope he is not seriously ill.",
"I hope your father is well.",
"I have not had the pleasure of seeing him since his return from London.",
"He is first-rate.",
"I think he will be here directly.",
"How do you like my new rooms?",
"I think you very fortunate in having found such a splendid house.",
"What are you going to do this evening?",
"I have to take my sister to the theatre.",
"Are you coming too?",
"There is nothing I should enjoy more.",
"Very well, good-bye till then.",
"Good-bye.",
"A Visit.",
"There is someone knocking.",
"Go and see who it is.",
"Go and open the door.",
"It is Mr. B.",
"Good morning, Madam, how do you do?",
"Very well, thank you, and you?",
"All right, thank you.",
"I have not seen you for a long time.",
"You are quite a stranger.",
"Will you stay and dine with us?",
"No, thank you, I cannot stay;",
"I only came down to know how you were.",
"How is Mrs. B.?",
"Thank you very much, Madam",
"Mrs. B. is quite well, and she would certainly have accompanied me if her sister had not come from Paris to pay her a short visit.",
"I am sorry she did not accompany you;",
"I should have been very pleased to make Miss S's acquaintance.",
"Tell her how pleased I shall be to see her;",
"I am generally at home every day after four o'clock, except Thursdays, and never go out in the evening.",
"Have you been in the country with your family?",
"Yes, Madam;",
"we only returned a fortnight ago.",
"How was the weather while you were away?",
"We were very fortunate;",
"during the three weeks we remained at X. the weather was extremely fine.",
"Have you heard from your brother lately?",
"Yes, I had a letter from him yesterday.",
"Have you seen the last number of the Illustrated World?",
"Yes, Madam;",
"I am a subscriber to that illustrated paper.",
"Is there anything specially interesting in this number?",
"There are very good sketches from the correspondent at the seat of war.",
"I must go.",
"Are you going already?",
"You are in a great hurry.",
"Why are you in such a hurry?",
"I have a great many things to do.",
"Surely you can stay a little longer.",
"I am very sorry I cannot stay any longer;",
"I must meet Mr. T. at half-past four;",
"but I will stay longer another time.",
"I thank you for your visit.",
"Departure.",
"It is time to go.",
"I must leave you.",
"We must part.",
"I must take leave of you.",
"Shall I have the pleasure of seeing you again?",
"Shall we meet again?",
"Good-bye.",
"Good-bye.",
"Till we meet again.",
"Good-bye for the present.",
"Your servant, Sir.",
"Your servant, Madam.",
"Your humble servant.",
"I wish you good morning.",
"I wish you good evening.",
"I wish you good night.",
"My compliments to your brother.",
"Give my kind regards to your sister.",
"Present my respects to your mother.",
"Present my respects to your aunt.",
"Give my kind regards to your wife.",
"Remember me to all at home.",
"I will not fail to do so.",
"Where are you going?",
"I am going home.",
"I am coming from your house.",
"I came from him.",
"I am going to his house.",
"I shall be at home.",
"You will find him at his house.",
"I came from your father's.",
"I shall go to-morrow to my friend's.",
"Where do you come from?",
"I come from Mr. B's.",
"I was to go to Paris.",
"I shall perhaps go to Spain.",
"I am going away;",
"it is time.",
"I am going to take a walk.",
"I was going to church.",
"Will you come with me?",
"Where do you wish to go?",
"Where shall we go?",
"We will go for a walk.",
"Let us call on Mrs. F.",
"Let us rather go to the Museum.",
"Let us go this way.",
"Give me your arm.",
"Let us cross the road.",
"Mind the motor-cars.",
"Which way shall we go?",
"Any way you please.",
"Let us go for a walk.",
"I have no objection.",
"Let us call on your brother on our way.",
"Is Mr. B. at home?",
"Is Mrs. C. at home?",
"She has just gone out.",
"He has gone out.",
"He is not at home.",
"Can you tell me where he has gone?",
"I cannot tell you exactly.",
"I think he has gone to see his sister.",
"Do you know when he will return?",
"No, Sir, he did not say anything when he went out.",
"He may be back soon.",
"Tell him to come and see me.",
"I will come again to-morrow.",
"When must I call again to find him in?",
"Call again at four o'clock.",
"Did you return late?",
"How long will it be before you come back?",
"I shall come back at ten o'clock at the latest.",
"Will you come back again?",
"What will you gain by it?",
"You will get nothing by it.",
"When did you return from the country?",
"Come back as soon as you can.",
"Come back quickly.",
"How much does that come to?",
"I shall see you on my return.",
"I must return home.",
"I will not fail to go there.",
"I will go with you.",
"You go too fast.",
"I will go the first opportunity.",
"So far so good.",
"How far shall we go?",
"Go in front.",
"I will go there from time to time.",
"Do you believe that he will go there?",
"I intend going there.",
"I go there twice a week.",
"Will he go with you?",
"I believe he has gone home.",
"All goes well.",
"I am going away.",
"I went there twice.",
"She has gone into the country.",
"It will soon be time to start.",
"He has been gone an hour.",
"Come up here quickly.",
"Come as early as you please.",
"Do not fail to go there.",
"I shall come and see you to-morrow for certain.",
"I am hungry.",
"I am very hungry.",
"I am dying with hunger.",
"I am thirsty.",
"I am very thirsty.",
"I am dying with thirst.",
"I could drink with pleasure.",
"Give me something to drink.",
"Give me a glass of water.",
"I am very tired.",
"I am very much fatigued.",
"I am cold.",
"My hands are cold.",
"I am warm.",
"I am sleepy.",
"I think I shall sleep well.",
"I am overcome with sleep.",
"I wish I were in bed.",
"I have slept well.",
"I have slept badly.",
"I could not get to sleep.",
"I have not been able to close my eyes all night.",
"What a poor fire!",
"You have not taken care of the fire.",
"You have not kept the fire up.",
"You have let the fire out.",
"It is not quite out.",
"It must be lighted again.",
"Come and make up the fire.",
"What are you looking for?",
"I am looking for the tongs.",
"Here they are in the corner.",
"Where are the bellows?",
"Go and fetch the bellows.",
"Blow the fire.",
"Do not blow so hard.",
"Put a few shavings under.",
"Now put on two or three pieces of wood.",
"It will soon draw.",
"Is there any coal in the scuttle?",
"Take the shovel and put some coal on the fire.",
"Do not put on too much at a time.",
"If you put on too much, you will put the fire out.",
"You have almost smothered the fire.",
"Raise it up with the poker.",
"It will give it a little air.",
"The fire begins to blaze.",
"Now the fire is very good.",
"You have made it up again very well.",
"Which do you prefer—a coal fire, or a wood fire?",
"I prefer a wood fire.",
"I prefer a coal fire.",
"A wood fire does not give so much heat.",
"It is some trouble to keep up too.",
"Do you burn your coal in a grate?",
"No, in a stove.",
"I do not like stoves.",
"I like to see the blaze.",
"Marketing.",
"I must go to market.",
"I shall buy some chickens.",
"Perhaps a pair of ducks.",
"Here is a couple of nice ducks.",
"Have you fresh eggs?",
"How many pounds of butter do you want?",
"I have left something at home.",
"I must go back.",
"Mary, you will finish marketing.",
"Get three pounds of butter, if it is good.",
"As you come back, call at the butcher's.",
"What meat shall I order?",
"Tell him to send a sirloin for to-day.",
"For to-morrow two or three ribs of beef.",
"And for the day after, a leg of mutton.",
"I should like to have a breast of veal.",
"If there is none, take a loin of veal.",
"Do not forget a quarter of lamb.",
"A leg of mutton.",
"A calf's head.",
"A neck of mutton.",
"Ask him for a good sweet-bread.",
"See whether he has a nice ox-tongue.",
"Tell him to send all at once.",
"Tell him to send the bill with it.",
"Do you wish me to buy any fish?",
"Yes, I forgot to mention it.",
"Is there any fish at the market?",
"There is plenty of fish.",
"There is scarcely any fish.",
"What fish is there?",
"There are herrings and mackerel.",
"Buy a plaice.",
"Will you have a salmon?",
"I prefer fresh cod.",
"I have seen a fine turbot.",
"What is the price of soles?",
"Two shillings a pound.",
"Is there any shell-fish?",
"Shell-fish are now in season.",
"Buy also a dozen eggs",
"Shall we take a little walk?",
"With pleasure.",
"Allow me to go and fetch my hat.",
"I will be with you in a minute.",
"I am at your service.",
"We will go when you like.",
"The weather is very fine at present, and I think it will remain so all day.",
"Which way shall we go?",
"Let us go across the fields.",
"I do not like walking on the high road.",
"There is always a great deal of dust.",
"The rain has laid the dust a little.",
"Let us cross the meadow.",
"It is a very pleasant way.",
"Under this large oak we shall be sheltered from the sun.",
"Shall we cross this field?",
"Is there a thoroughfare across this field?",
"Let us take this path.",
"Is this the nearest way home?",
"It is not late.",
"Let us walk a little longer.",
"I should like to be home early.",
"We are not far from the house.",
"We shall be there in less than half an hour.",
"We shall be back at seven.",
"Are you going to stay indoors all day?",
"No, my friend, I was just thinking of having a walk in the park.",
"Will you come with me?",
"With pleasure.",
"We are having beautiful weather, and there is no doubt that all the fashionable people will be assembled there.",
"Let us go.",
"Well, then, let us go.",
"Let us be off, then.",
"Is this gentleman an acquaintance of yours—the one who took off his hat?",
"Oh, yes, he is a friend of mine;",
"I will introduce him to you with pleasure.",
"Your friend is a very agreeable man.",
"Yes, I like him very much;",
"he knows everybody and has travelled in all parts of Europe.",
"Then your friend must know several foreign languages.",
"He is reported to speak half a dozen languages.",
"What a fortunate man!",
"I should be very pleased if I could speak half as many.",
"Do you know this lady?",
"I much regret I do not.",
"Yes, she is a friend of my younger sister.",
"That is fortunate.",
"Mr. B., I am happy to see you.",
"I trust you are well.",
"Where have you been all this time?",
"When did you arrive?",
"I arrived yesterday, after a few weeks' travelling in Spain.",
"When will you be back?",
"In a few weeks.",
"Don't forget to look me up.",
"I shall have much pleasure in doing so.",
"Have you been away?",
"Only for a few days;",
"I was in Madrid.",
"And how have you been getting on?",
"Very well;",
"I met some friends.",
"I must go and see my uncle to-night.",
"Pardon me, I have a few words to say to my friend here.",
"Will you be kind enough to give my compliments to Mr. D.?",
"With the greatest pleasure.",
"I am going home to dinner.",
"Adieu, till we meet again.",
"Good-bye.",
"Would you like to take a walk in the garden?",
"With great pleasure.",
"I like gardens very much.",
"Let us go into the fruit-garden first.",
"There is a fine show of plums this year.",
"What a quantity of apples there will be!",
"Yes, if one may judge by the blossom.",
"The apricots will be very fine this year.",
"These peaches look well.",
"You will have plenty of apples.",
"Cherries and strawberries are now in their prime.",
"They will soon be over.",
"These grapes are quite ripe.",
"These pears are very juicy.",
"All fruit is very early this season.",
"The espaliers especially.",
"And how are the trees in your orchard?",
"They are laden with fruit.",
"Now let us go into the flower-garden.",
"You have not yet seen my flowers.",
"Come and see my flowers, they are beautiful.",
"The garden begins to look pleasant.",
"The flowers come in abundance.",
"The tulips have been in blossom some time.",
"The narcissus will soon come out.",
"What a fine bed you have of them!",
"The hyacinths are nearly over.",
"What do you call this flower?",
"What a beautiful double dahlia!",
"Here is a fine cactus.",
"Are you fond of carnations?",
"Yes, but I do not like the smell.",
"Here are some very fine ones.",
"I like the odour of the violet.",
"I prefer the scent of roses.",
"You have not seen my sweet peas.",
"They are astonishingly beautiful.",
"You have a very fine collection of flowers.",
"You keep your garden very neat.",
"Your garden is perfectly well kept.",
"Let us see your kitchen-garden.",
"How everything grows!",
"The rain has done a great deal of good.",
"There was a great need of it.",
"We need more.",
"What a quantity of cabbages!",
"What fine cauliflowers!",
"Here is a fine bed of asparagus.",
"I am very fond of it.",
"I like artichokes nearly as well.",
"These peas are in blossom already.",
"I have some in pod in another place.",
"Have you planted any beans?",
"You will have some very early.",
"What are these?",
"They are carrots and turnips.",
"What have you there?",
"They are truffles.",
"I had never seen any before.",
"Are these onions?",
"No, they are leeks.",
"They are very much like onions.",
"I see you have all sorts of salad.",
"Here is lettuce.",
"This is endive.",
"I do not see any celery.",
"It is in another part of the garden.",
"I think your garden is very well stocked.",
"You have plenty of everything.",
"It is better to have too much than too little, for store is no sore.",
"To write a Letter.",
"I have a letter to write to-day.",
"Is it for the mail?",
"Yes, it must leave to-night.",
"You have no time to write, it is very late already.",
"I shall not be long.",
"Do you want any note-paper?",
"I have a whole quire.",
"Lend me a sheet if you please.",
"Be good enough to bring me some envelopes, ink, pens and sealing-wax.",
"Here they are.",
"Do you require any stamps?",
"I shall want a shilling's worth of half-penny stamps to send some circular letters to my friends on the continent;",
"twelve penny ones, and four two pence half-penny ones, as I shall have to write to my brothers in Spain.",
"I also want some post-cards and two envelopes for registered letters.",
"What is the day of the month?",
"It is the third.",
"Now, I have only the address to write.",
"When does the mail start?",
"The letters must be posted before half-past five, if you want them to go by the evening mail.",
"Do you not think this letter is too heavy?",
"I do not think so.",
"Shall I get you the Post Office Order you mentioned last night?",
"Yes, please.",
"What amount do you want to send?",
"Two hundred and thirty-two pesetas twenty-five centimos.",
"I am just going out and shall get the money at my banker's.",
"Do you know whether Post Office Orders are issued after five o'clock?",
"Take this letter to the Post Office, and pay the postage.",
"Get it registered.",
"The mail was just going.",
"Will my letter go off to-night?",
"Yes, I arrived in time.",
"Your letter will be delivered to-morrow morning.",
"When does the mail for England leave?",
"It goes at six o'clock.",
"How much is the postage for letters to England?",
"Twenty-five centimos for every fifteen grammes.",
"Can you tell me when these letters will arrive at their destination?",
"They ought to arrive within three days, Sir.",
"This letter is too heavy, the postage will be fifty centimos.",
"I am expecting a letter from X today, do me the favour to send to the Post Office to enquire if there are any letters for me.",
"Here is my card.",
"Will you please tell me if there are any letters for me from Paris?",
"Must I seal the registered letter?",
"No, Sir, it is not necessary.",
"Take this letter to Madam E. and wait for the answer.",
"These envelopes are inferior, I want better ones.",
"Get me a dozen stamps of twenty-five centimos, and two foreign post-cards.",
"Very good, Sir.",
"Somebody is asking for you.",
"Who is it?",
"Who wants to speak to me.",
"It is the tailor.",
"Tell him to come up.",
"I have brought your coat, Sir.",
"I am glad you have come this morning.",
"I began to be impatient.",
"I have just finished it.",
"I hope you will be pleased with it.",
"Let me try it on.",
"Let me see whether it fits me.",
"It fits you like a glove.",
"It fits me very well.",
"Are not the sleeves too long and too wide?",
"They are worn so now.",
"It is too tight.",
"It will stretch.",
"I think it is too long.",
"It cuts me under the arms.",
"I do not see what alterations there are to make.",
"It could not fit you better.",
"Look in the glass.",
"What is your charge for this coat?",
"It is rather dear.",
"Is there no reduction?",
"This coat is out of fashion.",
"The waistcoat is not well made.",
"The waistcoat must be altered.",
"It is too short.",
"It is rather long.",
"I want another coat.",
"I want a suit of clothes.",
"Will you take my measurements?",
"How will you have it made?",
"As now worn.",
"In the latest fashion.",
"I like to be neatly and plainly dressed.",
"I want a waistcoat and a pair of trousers.",
"Will you show me some patterns?",
"Have you brought some with you?",
"I have a great variety.",
"Let me see them.",
"I like this fine blue pretty well.",
"It is a very fashionable colour.",
"Blue will become you very well.",
"What do you think of this blue?",
"This colour will soon fade.",
"What sort of buttons will you have?",
"Will you have covered buttons?",
"Do you wear your trousers very high?",
"Not very.",
"Neither too high nor too low.",
"Let them come up about so high.",
"I like them very low.",
"It is the fashion to wear them very low.",
"I do not like them too low.",
"I must have everything the day after to-morrow.",
"I shall be punctual.",
"When will they be ready?",
"You will have them next Monday.",
"At what time must I call, Sir?",
"At about ten.",
"Between ten and eleven.",
"Madam, I have brought your gowns.",
"Ah! Miss A..., is it you?",
"I was impatient to see you.",
"You have made me wait a long while.",
"How many dresses have you brought?",
"Are they of different styles?",
"This dress fits me well.",
"This one appears very short.",
"Morning gowns are now made so.",
"I do not like them so short.",
"Let me try this on.",
"Here is a French cambric dress to try on.",
"Here is a muslin one, and a cambric one.",
"Take that pin out.",
"Is all that sewn carefully?",
"What trimmings will you put on this evening dress?",
"Is this trimming fashionable?",
"They are much worn now.",
"Trim it with lace.",
"Is not this gown too full at the bottom?",
"I think it is;",
"I can easily remedy it.",
"The sleeves are too tight.",
"The sleeves are too wide.",
"The waist is too long.",
"The waist is too short.",
"The gown is not wide enough.",
"The plaits do not fall gracefully.",
"The last fits the best.",
"It fits my waist exactly.",
"Take it for a pattern, and all the others will fit well.",
"Remember, I expect my things in a few days.",
"I will pay you when you bring everything you have to make for me.",
"Be very punctual, please.",
"Madam, you shall have everything to-morrow morning.",
"You will oblige me.",
"I want to be shaved as quickly as possible.",
"Very good, Sir;",
"will you kindly take this seat",
"Ah, you have cut me!",
"I beg your pardon, it is not much, only a pimple I have taken off.",
"Shall I cut your hair a little?",
"No thanks, it does not require cutting yet.",
"Yes please.",
"Do you want it very short?",
"Not too short.",
"Take off a little only.",
"Quite short.",
"Middling.",
"A trim.",
"Give me a shampoo.",
"Part it on the left.",
"Would you like a little pomade?",
"No, but you may put on a little brilliantine.",
"Let me have a looking-glass.",
"Have you shoes ready-made?",
"Show me some of different sizes.",
"I will try these.",
"Give me the shoe-horn.",
"They hurt me.",
"I cannot walk.",
"They are too low.",
"They are too high.",
"They are too large.",
"They are too small.",
"The heels are too wide.",
"You had better make me a pair to measure.",
"Let me see some boots.",
"These are too narrow.",
"I think these will fit you very well.",
"The boot is narrow, but it will not hurt you.",
"In fact, they fit me very well.",
"Give me the boot-jack to pull them off.",
"Make me also a pair of slippers.",
"What colour?",
"Make them very wide.",
"Do not make the soles too thin.",
"Take care that the welts be well sewn.",
"I want to buy some cloth.",
"What sort of cloth do you want?",
"Show me the best you have.",
"What colour do you prefer?",
"I like this colour pretty well.",
"Is it fashionable?",
"Blue and black are always fashionable.",
"Show me some others.",
"Here are patterns of all the superfine cloth I have in my shop.",
"This colour will soon fade.",
"Excuse me, Sir, it will last very well.",
"This cloth is very thin.",
"Here is another piece.",
"It feels very soft.",
"It is substantial.",
"This will do.",
"How much do you ask for it?",
"How much a yard is it?",
"Five pesetas.",
"Is that the lowest price?",
"Cut me three yards.",
"Here is your money.",
"Will you show me some Irish linen of the best quality.",
"Here are several pieces.",
"Do you prefer it to fine Holland?",
"I will show you some.",
"It will cost you more.",
"Yes, but it is wider.",
"Here is a piece at one peseta, one at one and a half, and another at two pesetas.",
"This is rather fine.",
"I will unfold this piece.",
"I think you will find it fine.",
"This is a fine white.",
"What is the price of it?",
"That cloth seems to me very dear.",
"It will wear well.",
"Give me these two pieces.",
"Do you want any French cambric?",
"I have some fine French cambric which is not dear.",
"How many yards do you want?",
"Allow me to show you some fine tablecloths and napkins.",
"They are of a new pattern.",
"They are indeed very handsome.",
"But I do not want any.",
"Have you any good French cambric pocket-handkerchiefs?",
"Yes, Sir, and I am sure they will please you.",
"I will take four dozen.",
"Have them marked with my initials, and send me everything to-morrow.",
"Your shop has been recommended to me by Mrs. B.",
"Have you a good assortment of perfumery?",
"What articles do you keep?",
"I have everything you can desire.",
"My stock is as complete as it can be.",
"I want some powder.",
"Will you have it scented?",
"Yes;",
"show me some jessamine.",
"The scent is not very strong.",
"It will suit me.",
"I have also violet, rose, and orange-flower.",
"I want also some lavender-water and some eau de Cologne.",
"Have you any essential oils?",
"Yes, Madam, several sorts.",
"This is of a superior quality.",
"How much do you sell this oil of roses for?",
"That is very dear.",
"It is too dear.",
"It is excessively dear.",
"I can buy some elsewhere for less.",
"It is the usual price.",
"It is a fixed price.",
"Let me have a bottle of orange-flower water.",
"I have now all I want.",
"Give me my account.",
"Here is your money and my address.",
"Send me all these articles.",
"Have you any new books?",
"I should like to see the books you have just received.",
"With great pleasure, Sir;",
"they were unpacked just now.",
"They are books of history, mathematics, philosophy, divinity, physics and law.",
"Are all these new books?",
"No, Sir, some are new, some are old publications.",
"I hope you will find some to suit your taste.",
"Here is a list of the books I wish to have.",
"Have you now the Mariana that I asked you for?",
"I have only the 18mo. edition.",
"It is embellished with coloured plates.",
"Show me some volumes of Quevedo.",
"They will bring you some immediately.",
"Here are some.",
"This size suits me pretty well.",
"I should like to have them bound.",
"I will have them bound in calf, and lettered.",
"I wish to have the edges marbled.",
"Show me some of your most handsome books bound in Russian leather.",
"Here are the best we have at present.",
"I like this pattern exceedingly.",
"I wish this Virgil to be bound in morocco.",
"Is the price the same for all colours?",
"Exactly the same.",
"Then I will have it bound in green.",
"What is the cost for each volume?",
"Have you Moratin's works complete?",
"We have the best edition.",
"I wish to have the Travels of young Anacharsis.",
"I have one in octavo, but it is only in boards.",
"I will take it, but you must have it bound in Russia leather.",
"Here is a fine edition of Cervantes.",
"I see in your catalogue a great many splendid editions at a very high price.",
"Have you a Guevara in small size?",
"I have the stereotype edition, on four different kinds of paper.",
"This edition on large vellum paper is beautifully bound.",
"I think I had better take the large vellum paper.",
"Here is a very pretty copy.",
"It is bound in green morocco, with gilt edges.",
"I have romances and novels, plays, reviews, etc.",
"Oh! I will not have any.",
"Sir, do you want anything else?",
"I want a copy of Solis; but I do not see one.",
"I have several, but they are in sheets.",
"What sort of binding do you prefer?",
"Will you have it in calf or sheepskin?",
"Half-binding will do;",
"but it must be lettered like that Mariana.",
"I will take care that it is done as you wish.",
"I also want Hossfeld's English-Spanish Grammar, as well as Hossfeld's Spanish-English Grammar.",
"I also require Hossfeld's Spanish Reader.",
"Do you want anything else?",
"Have you a map of Madrid?",
"I wish to have the best and the most correct that is published.",
"Send me everything to-day.",
"I intend to leave Madrid to-morrow morning.",
"Will you show me some rings?",
"Are these set with fine stones?",
"What is the price of this ring.",
"It is much too dear.",
"That diamond has a beautiful lustre.",
"I like that ring very much.",
"I think it is rather too large for me.",
"Show me some others.",
"This fits me well.",
"Is it firmly mounted?",
"What do you ask for it?",
"I prefer the first.",
"Can you make it smaller?",
"Very easily, and without injuring the mounting.",
"I want a gold chain.",
"Mine is no longer in fashion.",
"I can take it in exchange.",
"What will you allow me for mine?",
"I will weigh it.",
"If I exchange my chain, I must exchange my seal too.",
"Here are several seals of the newest fashion.",
"I will take these two.",
"I should like to have my initials engraved on this seal.",
"Will you get it engraved?",
"I will give it to the most skilful engraver we have.",
"Show me some earrings.",
"Here are some of exquisite workmanship.",
"Here is a splendid necklace.",
"It is not for sale.",
"I have just sold it to a lady.",
"These bracelets are for the same lady.",
"What is the price of this pin?",
"Are these pins of the latest fashion?",
"This topaz surrounded with pearls I like much better.",
"It is very beautiful.",
"I think it is stronger.",
"I have something else to show you.",
"No, thank you; I will come another day.",
"I am not pleased with the watch you sold me.",
"Yet I took it on your word.",
"It does not go well.",
"It gains.",
"It loses.",
"I cannot regulate it.",
"It is a new watch.",
"It will require some time to regulate it.",
"I think so.",
"If you are not satisfied, I will change it.",
"Here is a very good watch.",
"It also shows the day of the month.",
"I do not like such complicated watches.",
"They are often out of order.",
"I want a good repeater.",
"I have an excellent one.",
"Do you warrant it?",
"Will you let me have it on trial?",
"I will only take it on those terms.",
"I agree to it with pleasure.",
"I will let you have it on trial.",
"Since I had it, it has not varied one minute.",
"You will be pleased with it.",
"I can warrant it.",
"How much do you want for it?",
"I have a watch at home which wants cleaning.",
"It is an old watch.",
"It has not gone for a fortnight.",
"I let it fall.",
"I think the mainspring is broken.",
"I will send it to you to-day.",
"I must keep it a few days.",
"When will you return it?",
"I cannot promise it you before a fortnight.",
"It is a long time.",
"If there is nothing broken you shall have it to-morrow.",
"Do not disappoint me.",
"You may rely on its being ready at that time.",
"Here are very beautiful clocks.",
"I want one.",
"You can select which you like.",
"Not to-day.",
"We will speak of it another time.",
"Do you sell spectacles?",
"I want an opera-glass.",
"Do you keep microscopes?",
"This glass magnifies too much.",
"That does not magnify enough.",
"That opera-glass is not good.",
"I want a better one.",
"Is there any collection of paintings in this town?",
"Is there an annual exhibition of paintings in this place?",
"Yes, Sir; I hope you will be pleased with it.",
"When will the exhibition take place?",
"It is open now.",
"Let us go there.",
"I have a passion for pictures.",
"That painting is a copy from Raphael.",
"This is from Poussin.",
"This is a copy from Titian.",
"Titian excelled in colouring.",
"And in drawing likewise.",
"There is a fine blending of colours in that picture.",
"Its composition is fine.",
"This is an historical picture.",
"This is a well executed painting.",
"The passions are well portrayed.",
"How do you like the foreground?",
"That picture requires to be seen in its proper light.",
"It is not in a good light.",
"That picture is deficient in colouring.",
"That painter draws better than he colours.",
"Those colours are too gaudy.",
"They should have been subdued.",
"There are fine tones of colour in that picture.",
"This valuable picture is in fine preservation.",
"How well the lights and shades are distributed!",
"That painter thoroughly understands the disposition of the lights.",
"It is in the style of Rembrandt.",
"That great master formed a style adapted to great effects.",
"A landscape forms the background to the figures in that picture.",
"This is a watercolour.",
"That drawing is from nature.",
"That artist understands very well the effect of light and shade.",
"These figures are painted in half tone.",
"That painter succeeds better in portrait than in historical painting.",
"Have you seen that pencil-sketch?",
"No, I was examining this drawing in Indian ink.",
"I like oil-painting better.",
"There are two very beautiful sea-pieces near the window.",
"The reflections in the water are admirable.",
"See those clouds, how skilfully the lights are managed?",
"I am delighted with all I have seen.",
"I think we have seen everything.",
"Let us go.",
"We will come again to-morrow.",
"Let us play a game at chess.",
"I like it better than whist, or even piquet.",
"I do not know the game well.",
"Where is the chess-board.",
"Here it is, with the chess men.",
"I want a bishop.",
"Your queen is not in its proper place.",
"Who begins?",
"Let us draw lots.",
"I have the first move.",
"It is a great advantage.",
"I will move this man.",
"Your pieces are well supported.",
"I am afraid I must exchange pieces.",
"I have lost a knight.",
"I must castle.",
"You cannot castle after having moved your king.",
"Check to the king.",
"I will cover this check with my castle.",
"I take it.",
"I cannot win.",
"It is a drawn game.",
"I was in hopes you would have given me checkmate.",
"I cannot play with you.",
"What odds will you give me?",
"If you will give me a castle, I will try another game.",
"It is more than I ought to give, but I will do it with pleasure.",
"On the Spanish Language.",
"Do you speak Spanish?",
"I speak it a little.",
"I speak it just enough to make myself understood.",
"He speaks Spanish fairly well.",
"Speak Spanish to me.",
"You pronounce it well.",
"What book are you translating?",
"I have translated P.'s Fables.",
"Now I am translating the extracts in Hossfeld's Spanish Composition and Idioms.",
"I afterwards compare my work with the translation in the key.",
"In order to know a language thoroughly, grammar is absolutely necessary.",
"In order to speak a language well, you must learn phraseology.",
"One may be able to read and write a language and yet be unable to speak it.",
"In Spanish the written language does not differ much from the spoken language.",
"What grammar do you use?",
"I am using Hossfeld's Grammar, and I find it invaluable, especially for commercial purposes.",
"How long have you been learning Spanish?",
"About ten months.",
"You have made a great deal of progress.",
"I would advise you to continue to apply yourself to it.",
"Spanish is a very important language; it is spoken not only in Spain, but also in parts of Africa, in Mexico, Central and South America, the West Indies, and in the Philippine Islands.",
"English and Spanish are two of the most useful languages that one can learn.",
"English is a language of great commercial value.",
"I learnt Spanish at school;",
"I took many lessons in classes and privately;",
"I know my grammar pretty well, and understand nearly everything I read, but cannot say two words in an intelligible manner.",
"What ought I to do?",
"Hear Spanish spoken;",
"have a master who speaks to you in Spanish—very slowly at first, and then more quickly,—on subjects which are familiar to you.",
"Is it then more useful to listen, and to try to understand what is said in a language, than to try to speak it one's self?",
"Both are useful and necessary.",
"Read aloud as much as you can.",
"Can you tell me if there are any apartments to be had in this street?",
"Yes, Sir, there are several, in this street and in the adjoining ones.",
"I have seen from your advertisement in the newspaper that you have some rooms to let.",
"Can I see them?",
"Certainly, Sir.",
"On which floor are they?",
"I have a sitting-room and a bedroom on the first floor, and a bedroom on the second.",
"These two rooms will suit you, I hope.",
"They are well furnished and decorated.",
"How much do you want for these rooms?",
"Fifteen pesetas a week, including attendance.",
"Could I have my meals here?",
"I should want breakfast, and sometimes dinner too.",
"Yes, Sir, I shall be happy to supply the meals you require, and have no doubt you will be satisfied with our table.",
"How much do you charge for breakfast and dinner?",
"Two pesetas for breakfast, and three for dinner.",
"Shall I have to pay any extras?",
"No, Sir, none except the gas, which is half a peseta a week.",
"I suppose you require some references.",
"Yes, Sir, it is usual with us to require and to give references.",
"Very good, Madam;",
"here are my references;",
"can I come in to-morrow?",
"Certainly, Sir;",
"I shall have everything ready for you.",
"I thank you very much, Sir;",
"I shall see you to-morrow.",
"Engaging a Man-servant.",
"Sir, I have heard you want a servant.",
"Yes, who sent you to me?",
"By whom are you recommended?",
"By Mr. B., with whom I have travelled.",
"I know him very well.",
"On his recommendation I shall not hesitate to engage you.",
"I suppose you possess the qualifications I want.",
"I shall stay in this town a fortnight longer.",
"Where have you travelled?",
"I have travelled in Germany and Italy.",
"Will you accompany me to Switzerland?",
"Have you performed that journey before?",
"Sir, I am a Swiss.",
"How old are you?",
"Are you a married man?",
"Have you been long in Germany?",
"Have you travelled much in France?",
"Can you ride a horse?",
"Can you write?",
"Yes, Sir.",
"What languages do you know?",
"I understand German and Italian.",
"I likewise know the coins, weights and measures of the countries in which I have travelled.",
"You may be very useful to me.",
"What wages do you ask?",
"I have always had £20 a year and my board.",
"I will give you the same.",
"I will give you £3 a month, without board.",
"When we travel, I will pay your expenses.",
"You must give me every evening an exact account of everything you have laid out for me.",
"I will pay you immediately.",
"I will call on your former master.",
"Engaging a Maid-servant.",
"Have you been long in service?",
"What was the last place you were at?",
"Do you understand cooking?",
"Are you acquainted with the management of a house?",
"How old are you?",
"You seem very young.",
"I am twenty-two.",
"Do you understand needlework?",
"Are you a good needlewoman?",
"Can you wash fine linen?",
"Could you occasionally replace my housemaid?",
"Have you been in many families?",
"Whose house have you just left?",
"Why did you leave your place?",
"How long did you remain with her?",
"Will Mrs. L. give you a character?",
"I have a written character from Mrs. L.",
"Let me see it;",
"I know her handwriting.",
"Do you like children?",
"What wages do you expect?",
"Mrs. L. gave me fifty pesetas a month.",
"It is a great deal.",
"But I think you will suit me.",
"I engage you from this moment.",
"You may come to-morrow.",
"We require two rooms with good beds.",
"Very well, Sir;",
"will you have the kindness to follow me?",
"On which floor have you rooms disengaged?",
"There are some on the second, consisting of a drawing and a bedroom.",
"I have two splendid rooms on the third floor.",
"Is there a lift?",
"Waiter, have a room with a good bed got ready for me.",
"See that the bed is well aired.",
"Be careful that they put clean sheets on.",
"The sheets are damp, I want some others.",
"I should also like another blanket.",
"I don't mind much what sort of room I have, but I want a good bed, and to be able to sleep quietly.",
"Have a drawing and a bedroom with two beds made ready for us;",
"have a fire lighted, too, as quickly as possible.",
"I shall take a warm bath afterwards.",
"Where is the bath-room?",
"On the same floor as your room.",
"Please have a cold bath made ready at once.",
"Let my luggage be brought up, and don't forget the towels.",
"We want dinner at six o'clock.",
"Will you dine at table d'hôte at seven, Sir?",
"No, I shall dine with some friends in town and return late.",
"It is very warm in this country.",
"Have you any cooling drinks?",
"Please reserve us two good seats at table d'hôte.",
"There is a bell at the side of the chimney-piece.",
"Is there no electric bell?",
"No, Sir, but we have electric light in all the rooms.",
"I notice that there is neither soap nor fresh water.",
"The servant will put everything in order directly.",
"Please let me have my bill.",
"Here is your account, Sir.",
"Very well, please receipt it.",
"Waiter here is something for you.",
"The Money-changer.",
"Where could I get my money changed?",
"Where is the nearest money-changer's?",
"Is there a money-changer's close by?",
"I wish to change some English money.",
"What do you give for a sovereign?",
"Can you change me a five-pound note?",
"What is the rate of exchange to-day?",
"I will take half in silver.",
"I should like a peseta's worth of coppers.",
"Could you cash me this cheque on London?",
"Is there a good theatre here?",
"Which is the best theatre?",
"Is there a performance to-night?",
"What are they playing?",
"What time does the performance begin?",
"What time is the performance over?",
"Is there a good orchestra?",
"What are the prices?",
"The boxes, the stalls, the circle, the gallery.",
"What time does the box-office open?",
"A ticket, a pass, a pass-out check.",
"Let me have a programme, please, and the book of words.",
"Can I hire a pair of opera glasses?",
"The interval.",
"Winter is over at last.",
"Do you like winter?",
"I like it as much as summer.",
"You are perhaps the only one of that opinion.",
"In winter one is not comfortable except by the fireside.",
"Can you skate?",
"Yes, a little.",
"Have you skated this winter?",
"The winter has been very severe this year.",
"I am glad to see the spring.",
"It is the season I like best.",
"It is the most pleasant of all seasons.",
"The season is very backward.",
"I fear we shall have a very hot summer.",
"One would think that the order of the seasons had been reversed.",
"Summer is the season of the harvest.",
"Summer is over.",
"After summer comes the autumn.",
"Autumn is the season of vintages.",
"Towards the middle of autumn the mornings and evenings are cool.",
"Which season do you like best, Sir?",
"Unquestionably, I like the spring best.",
"Is it as hot in England as in Spain in the summer?",
"Never.",
"It is not too warm in summer nor too cold in winter.",
"The winter in the north of Spain is almost as cold as in England.",
"No doubt, but for my part I should prefer the winter of Northern Spain to that of England, especially London, as it is very foggy there.",
"You are right;",
"it must be mentioned, however, that the fog is not so much due to the climate of that country as to the immense quantities of coal consumed daily in the dwellings and numerous manufactories.",
"I have read that as soon as a means of consuming the smoke is invented, London will have a very agreeable climate.",
"Let us hope that this will soon be the case.",
"How is the weather?",
"What sort of weather is it?",
"Is it fine?",
"Yes, it is fine.",
"It is beautiful weather.",
"It is charming weather.",
"It is most delightful weather.",
"The weather is settled.",
"The weather is unsettled.",
"The weather is very close.",
"It is getting cloudy.",
"It is cloudy.",
"It is bad weather.",
"It is very bad weather.",
"It is windy.",
"It is very windy.",
"The wind drops.",
"It is foggy.",
"It is very foggy.",
"It is mild.",
"It is cool.",
"It is warm.",
"It is cold.",
"It is very-hot.",
"It is very cold",
"It is piercingly cold.",
"It is dry.",
"It is damp.",
"It is going to rain.",
"I feel drops of rain.",
"It rains.",
"It is raining.",
"It rains very fast.",
"It pours.",
"It is pouring.",
"It is only a shower.",
"It does not rain.",
"It is not raining.",
"The weather is stormy.",
"We shall have a storm.",
"Do you hear the thunder?",
"It thunders.",
"It is thundering.",
"The thunder roars.",
"It lightens.",
"It is lightening.",
"It has thundered and lightened all night.",
"The weather is clearing up.",
"It freezes.",
"It is freezing.",
"It freezes very hard.",
"The river is frozen.",
"We shall have snow.",
"There is much snow.",
"It hails.",
"It is hailing.",
"It thaws.",
"It is thawing.",
"It is dusty.",
"It is very dusty.",
"It snows.",
"It is snowing.",
"I am very glad of it.",
"We shall go sleighing.",
"Have you a sleigh.",
"It is good sleighing to-day.",
"The rain has laid the dust.",
"The pavement is slippery.",
"It is very bad walking.",
"It is daylight.",
"It is night.",
"It is dark.",
"It is very dark.",
"It is moonlight.",
"It is starlight.",
"The days are drawing in.",
"The days begin to get shorter.",
"The days are very short.",
"The days are lengthening.",
"I am warm.",
"I am cold.",
"It is very cold.",
"Are you warm?",
"Are you cold?",
"Are you not warm?",
"Are you not cold?",
"I am quite wet.",
"I am wet through.",
"Dry your clothes.",
"We shall have a fine day.",
"The sun shines.",
"Look at that beautiful rainbow!",
"What is the weather like to-day?",
"It is clear.",
"It is very nice to-day.",
"What do you think of a walk in the fields, the weather being so fine?",
"It seems to me rather uncertain.",
"What sort of weather had you in London yesterday when you left there?",
"It was very foggy, as is usual during this month.",
"Is it true that in England the sun is invisible during a quarter of the year?",
"It is not so bad as that, but there are days, especially in November and February, when we cannot see the sun, nor even the lamps in the streets for the fog.",
"Is it possible?",
"I hope we shall not have bad weather to-morrow.",
"It rained the whole day when we went into the country.",
"It does not rain now, let us hurry back.",
"Has much snow fallen?",
"Yes, the roads are covered with snow.",
"Snow has been falling during the whole night.",
"There was no snow at all last winter.",
"Did you hear the thunder last night?",
"Yes, it was a terrible storm, and it rained in torrents.",
"Do you think the river will soon freeze over?",
"I have no doubt that we shall be able to skate to-morrow if this frost lasts.",
"Oh, yes, if it does not thaw meanwhile.",
"Come to-day.",
"Go there on Christmas-day.",
"It is broad day-light.",
"The day you are coming.",
"To-day will be fine.",
"I rise in the morning at six o'clock.",
"Send it to me this morning.",
"Come and spend the evening at my house.",
"I did it in the fore-noon.",
"I will do it to-morrow morning.",
"I shall see you this afternoon.",
"I shall go and see him the day after to-morrow.",
"I was there yesterday.",
"He sent it to me two days after.",
"The next day I went there.",
"The next day I saw him.",
"Two days ago.",
"A fortnight ago.",
"It is three weeks since.",
"About that time.",
"Last month.",
"Next month.",
"Last year.",
"Next year.",
"The year one thousand nine hundred and fifteen.",
"I shall see you at Easter.",
"I shall move at mid-summer.",
"At Michaelmas.",
"The quarter is ended.",
"The next quarter.",
"The first of next month.",
"The second of last month.",
"The fourth of the present month.",
"The last day of the month.",
"At the end of the month.",
"At the end of the week.",
"Towards the middle of the month.",
"Last week.",
"Next week.",
"In a week.",
"In a fortnight.",
"This day week.",
"This day fortnight.",
"This day week.",
"This day fortnight.",
"We shall go there some day.",
"One of these days.",
"He says he will pay you some day or other.",
"I do it daily.",
"Every day.",
"Every other day.",
"A weekly paper.",
"A daily paper.",
"Do you know what time it is?",
"What time is it?",
"I do not know.",
"Could you tell me the time?",
"I cannot tell you exactly.",
"Yes, Sir;",
"it is half-past six.",
"Will you kindly tell me the time?",
"What is the time by your watch?",
"It is one o'clock.",
"It is nearly two o'clock.",
"It is about two o'clock.",
"It is half-past two.",
"It is on the stroke of three.",
"It is ten minutes past five.",
"It is a quarter past seven.",
"It is twenty minutes past eight.",
"It is a quarter to eleven.",
"It has just struck twelve.",
"It is noon.",
"It is midnight.",
"It is early.",
"It is late.",
"It is very late.",
"Come about nine o'clock.",
"Is your watch right?",
"My watch is right.",
"My watch is not right.",
"My watch is too fast.",
"My watch is too slow.",
"It gains a quarter of an hour every day.",
"It loses half-an-hour every day.",
"It has stopped.",
"It stops now and then.",
"It does not go.",
"Look at your watch.",
"It is not wound up.",
"I forgot to wind it up.",
"It is out of order.",
"Something is broken in it.",
"The mainspring is broken.",
"I think the chain is broken.",
"Have it mended.",
"I am going to send it to the watch-maker.",
"He is a good watch-maker.",
"Yes, but he charges too much.",
"It is true, but you can rely on what he does.",
"I bought this watch in Switzerland.",
"Tell me the time the train for... is going to start.",
"It will start at half-past one.",
"I must leave at three o'clock in the afternoon.",
"My friend will arrive by the Northern Railway at four o'clock to-morrow morning.",
"What is the date of the letter you have in your hand?",
"His letter bears the date fifth of January, 1915.",
"What is the date to-day?",
"What day of the month is it?",
"What day of the month is this?",
"It is the fifteenth of March.",
"To-day is the sixteenth.",
"To-day is the nineteenth of February.",
"Is it the first of the month?",
"No, it is the second.",
"I think it is the fifth.",
"When will the races take place—in the morning or in the evening?",
"At noon.",
"When do you expect to return from your journey?",
"I shall return by the steamer \"Queen\" which is due on the first of April.",
"Is there any news to-day?",
"Is there anything new?",
"Do you know anything new?",
"What is the news?",
"What news is there?",
"What news do you bring us?",
"Have you not got anything fresh to tell us?",
"Have you not heard of anything new?",
"What do they talk about in the town?",
"What is the news in your neighbourhood?",
"I know nothing new.",
"There is nothing new.",
"There is no news.",
"I have not heard of anything.",
"There is nothing fresh talked about.",
"There is good news.",
"The news is good.",
"There is bad news.",
"The news is very bad.",
"This is good news.",
"This is bad news.",
"I did not hear of that.",
"Did you read the papers?",
"What do the papers say?",
"I have not read the papers to-day.",
"Did you see that in any paper?",
"It is only mentioned in a private letter.",
"Do they say who received the letter?",
"This news wants confirmation.",
"From whom have you had that news?",
"How do you know that?",
"I have it on good authority.",
"That news has not been confirmed.",
"That report has proved false.",
"That is no longer talked of.",
"Do they still talk of war?",
"Do they think we shall have peace?",
"It is not likely.",
"Have you heard from your brother?",
"Have you heard lately from your friend?",
"Is it long since he wrote to you?",
"I have not heard from him for two months.",
"He has not written for these three weeks.",
"I expect to hear from him.{324}",
"What does he say to you about Madrid?",
"He gives me a description of most of the curiosities of that city.",
"Is he pleased with Madrid?",
"He is enjoying himself so much there that he does not speak of returning.",
"How old are you?",
"What is your age?",
"What may be his age?",
"How old may he be?",
"He will be twelve the fifteenth of next month.",
"I shall soon be ten.",
"I am twenty-five.",
"How old is your father?",
"What is your brother's age?",
"How old is your brother?",
"He is not yet twenty.",
"He is not yet of age.",
"He is still under age.",
"How old may that child be?",
"He is only six years old.",
"He is tall for his age.",
"How old is your sister?",
"She is more than seven.",
"She is almost eight.",
"She is twenty.",
"She is in the flower of her youth.",
"Your uncle must be very nearly forty years old.",
"He is in his forty-second year.",
"He is in the prime of life.",
"Your grandfather looks very aged.",
"How old do you think he is?",
"How old would you take him to be?",
"He cannot be more than eighty.",
"He is eighty-four.",
"He is older than I.",
"I did not think him so old.",
"He carries his age well.",
"Is your father still living?",
"He must be very old.",
"He is just entering his hundredth year.",
"He has become quite childish.",
"Asking and Giving Advice.",
"What shall we do?",
"What must we do?",
"What are we to do?",
"What remains for us to do?",
"What is to be done?",
"We must decide something.",
"I am quite puzzled.",
"I do not know what to do.",
"I am greatly embarrassed.",
"We are very much perplexed.",
"If I were you.",
"If I were in your place.",
"I am of opinion that you should go there.",
"If you will take my advice you will do it.",
"An idea strikes me.",
"I have been thinking of that.",
"A thought has struck me.",
"Let me alone.",
"Let us do one thing.",
"I have changed my mind.",
"Let us do something else.",
"We must go another way to work.",
"What do you say about it?",
"What do you think of it?",
"I think as you do.",
"It is very well thought out.",
"It is very well imagined.",
"It is a good idea.",
"It is a very good idea.",
"I am of your opinion.",
"It is the best way.",
"It is the best we can do.",
"It is the only thing we have to do.",
"That is the only course we can take.",
"That I assure you.",
"That I can assure you.",
"You may rely upon what I tell you.",
"There is no doubt about it.",
"You are right.",
"You are quite right.",
"Yes.",
"No.",
"I say it is.",
"I say it is not.",
"I maintain that it is so.",
"I maintain that it is not so.",
"I suppose so.",
"I suppose not.",
"I should say so.",
"Certainly.",
"Certainly not.",
"Do you think so?",
"I think so.",
"I think so too.",
"I should think so!",
"I think not.",
"I do not think so.",
"I should think not indeed!",
"I dare say it is so.",
"What do you mean?",
"I do not know what you mean.",
"Yes, it is true.",
"It is quite true.",
"It is positive.",
"It is only too true.",
"It is a fact.",
"It is an absolute fact.",
"Are you sure of what you say?",
"I could believe it.",
"Do you believe it?",
"I believe it.",
"I believe so too.",
"That I believe.",
"Do not believe it.",
"I do not believe it.",
"I do not believe a word of it.",
"I emphatically deny it.",
"No such thing.",
"Are you quite sure of it?",
"Nothing is more certain.",
"I answer for it.",
"I could not answer for it.",
"You may believe it.",
"It cannot be true.",
"You are mistaken.",
"It is not true.",
"It is a fib.",
"It is a pure invention.",
"There is nothing more untrue.",
"I give you my word for it.",
"Upon my honour.",
"Upon my word of honour.",
"Is it really true?",
"I can hardly believe it.",
"I heard it said.",
"Everybody says so.",
"We must not always give credit to all we hear people say.",
"What!",
"Truly!",
"Really!",
"Is it possible!",
"Could it be possible!",
"Is it really possible!",
"How can that be!",
"How is that possible!",
"That is impossible!",
"It is not possible!",
"That cannot be!",
"I cannot think how...!",
"I am surprised!",
"I am quite astonished!",
"That surprises me!",
"You surprise me!",
"You astonish me!",
"This is what surprises me!",
"That quite astonishes me!",
"I wonder at it!",
"This is quite astonishing!",
"It is incredible!",
"It is a thing not to be conceived!",
"That is unheard of!",
"It is a thing unheard of!",
"It is strange!",
"That is very strange!",
"That is a strange sort of business indeed!",
"How strange!",
"What a strange thing!",
"That is probable.",
"That is very likely.",
"It is likely enough.",
"That is not unlikely.",
"That is hardly probable.",
"That is not probable.",
"That is very probable.",
"That is more than probable.",
"It is very possible.",
"There is nothing impossible in it.",
"That is not impossible.",
"I see nothing impossible in it.",
"Perhaps.",
"Perhaps so.",
"That may be.",
"That might be so.",
"I do not wonder at it.",
"I am not surprised at it.",
"That does not astonish me.",
"That does not surprise me.",
"It is not astonishing.",
"It is not surprising.",
"There is nothing surprising in it.",
"You do not surprise me.",
"I should not wonder at it.",
"That would not surprise me.",
"There would be nothing extraordinary about it.",
"It is quite natural.",
"Of course.",
"No wonder.",
"It is a matter of course.",
"That is understood.",
"I am sorry for it.",
"I am very sorry for it.",
"I am extremely sorry for it.",
"How sorry I am for it!",
"I am inconsolable.",
"It makes me quite unhappy.",
"It vexes me beyond expression.",
"It is a pity.",
"It is a great pity.",
"It is a real pity.",
"What a pity!",
"It is a sad thing.",
"It is a painful case.",
"That is very vexing.",
"That is very disagreeable.",
"It is very sad.",
"It is a cruel case.",
"That is very hard.",
"This is shocking.",
"That is very unfortunate.",
"It is a great misfortune.",
"It is very regrettable.",
"It is dreadful.",
"It is terrible.",
"I am very pleased.",
"I am very glad.",
"I am very happy.",
"I am delighted.",
"I am extremely happy to hear it.",
"They are very glad of it.",
"We congratulate you on it.",
"Shame!",
"Are you not ashamed?",
"Are you not ashamed of yourself?",
"You ought to be ashamed.",
"I am ashamed of you.",
"What a shame!",
"It is shameful.",
"It is a shameful thing.",
"It is very bad.",
"How naughty that is!",
"That is very wicked.",
"It is abominable.",
"How can you be so wicked?",
"How could you do so?",
"How came you to do so?",
"You are very wicked.",
"Why did you do that?",
"I am very angry.",
"I am not in a good humour.",
"He is very cross.",
"I am cross with you.",
"I am offended.",
"I am exasperated.",
"I am beside myself.",
"You see me in a terrible passion.",
"It makes me quite mad.",
"That is very wrong of you.",
"You are very much to blame.",
"You are quite wrong.",
"How did you dare to do so?",
"I am not satisfied with you.",
"I am quite displeased with you.",
"I shall be very angry.",
"Be quiet.",
"Will you soon have done?",
"Can you not be quiet?",
"I warn you of it.",
"Pay attention to what I say.",
"Mind what I have told you.",
"I will not have that.",
"I will not suffer that.",
"I will have it so.",
"I insist upon it.",
"Mind it does not happen again.",
"Do not do so any more.",
"Don't be impertinent.",
"Silence! Hold your tongue.",
"Will you hold your tongue?",
"No arguing.",
"Don't answer.",
"Get out quickly.",
"I will see you no more.",
"Your conduct is inexcusable.",
"This is not the first time you have annoyed me.",
"I do not like that man.",
"I detest that man.",
"I cannot bear him.",
"His manners are repellent.",
"He has not a pleasing countenance.",
"His looks are not prepossessing.",
"There is something displeasing in his manners.",
"I cannot restrain the aversion I feel for him.",
"He has no notion of propriety.",
"He has no regard for anybody.",
"That makes him hated.",
"He is hated by everybody.",
"I avoid him as much as I can.",
"He bores me much.",
"His language is offensive.",
"He talks most extravagantly.",
"He likes to dictate to everyone.",
"What an insupportable being!",
"What a tiresome person!",
"Shall we never be able to get rid of him?",
"I wish he would go.",
"At last he has gone.",
"I would rather have the word of an honest man than his oath.",
"The hatred of that man is less dangerous than you think.",
"He is my friend.",
"He is a friend of mine.",
"He is my best friend.",
"He is my intimate friend.",
"We are intimate friends.",
"I am sincerely attached to him.",
"Our friendship is reciprocal.",
"Our dispositions are alike.",
"We are closely united.",
"We agree perfectly well.",
"He has given me many proofs of his friendship.",
"I hope we shall never part.",
"I felt an attachment for him the first time I met him.",
"We love each other like brothers.",
"There is no secret between us.",
"We have no secrets from each other.",
"I would do anything for him.",
"He is very attentive to me.",
"Nobody esteems you more than I do.",
"He is the best of my friends.",
"Correspondence.",
"Sir, Dear Sir,",
"Dear Sirs, Gentlemen,",
"Madam, Dear Madam,",
"My dear Sir,",
"Dear father,",
"Dear mother,",
"My dear friend,",
"To begin a Letter.",
"Your favour of the 15th inst. duly reached us.",
"I have just received your letter of the 10th inst.",
"I had the honour of writing to you on the 12th ult.",
"The person who will hand you this letter is Mr. X. who lives in the same town as I.",
"Dear friend, I cannot make out your silence;",
"what has become of you?",
"To end a Letter.",
"I am, dear Sir, yours truly,",
"We remain, dear Sirs, Yours faithfully,",
"Without further, I remain, Yours truly,",
"Awaiting your reply, I remain, Yours faithfully,",
"Yours very truly,",
"Sincerely yours,",
"Your sincere friend,",
"Your affectionate son,",
"We beg to subscribe ourselves, Gentlemen, your most obedient servants,",
"He was caught in the very act.",
"Much ado about nothing.",
"Without more ado.",
"To be on the alert.",
"After all.",
"Grasp all, lose all.",
"Once for all.",
"When all comes to all.",
"I have an appointment with him.",
"Make an appointment with me.",
"Arm in arm.",
"On good authority.",
"Be it as it may.",
"As you make your bed so you must lie on it.",
"Early to bed, and early to rise, makes a man healthy, wealthy and wise.",
"The beginning is the difficulty.",
"Well begun is half done.",
"He betrayed himself.",
"Between you and me.",
"Birds of a feather flock together.",
"A bird in the hand is worth two in the bush.",
"To kill two birds with one stone.",
"A little bird told me.",
"To come to blows.",
"Without striking a blow.",
"We are in the same boat.",
"To blow out one's brains.",
"A bone of contention.",
"What is bred in the bone will never come out of the flesh.",
"To bribe someone.",
"New brooms sweep clean.",
"He does not beat about the bush.",
"To put the cart before fore the horse.",
"They lead a cat and dog life.",
"Changes are pleasant.",
"Charity begins at home.",
"A burnt child dreads fire.",
"Spare the rod and spoil the child.",
"He is a chip off the old block.",
"To carry coals to Newcastle.",
"Cut your coat according to your cloth.",
"It is not the coat that makes the man.",
"First come, first served.",
"Tell me your company, and I will tell you your character.",
"Too many cooks spoil the broth.",
"To pluck up courage.",
"Much cry and little wool.",
"There is many a slip 'twixt the cup and the lip.",
"To be at daggers drawn.",
"To look daggers.",
"The better the day, the better the deed.",
"None so deaf as those who won't hear.",
"To make ducks and drakes with one's money.",
"To put all one's eggs in one basket.",
"He is out of his element.",
"They find it very hard to make both ends meet.",
"He had a narrow escape.",
"Even or odd.",
"At all events.",
"Coming events cast their shadows before.",
"Don't get excited.",
"Like father, like son.",
"Fine feathers make fine birds.",
"It makes my flesh creep.",
"To take French leave.",
"Out of the frying-pan into the fire.",
"She has the gift of the gab.",
"Ill-gotten gain never prospers.",
"The game is not worth the candle.",
"To make game of someone.",
"God helps those who help themselves.",
"All is not gold that glitters.",
"To kill the goose that lays the golden eggs.",
"To bring grist to the mill.",
"Habit is second nature.",
"It makes one's hair stand on end.",
"To go halves.",
"As if nothing had happened.",
"To be hard up.",
"The more haste, the less speed.",
"Make hay while the sun shines.",
"Head or tail.",
"I cannot make head or tail of this.",
"They are over head and ears in debt.",
"Two heads are better than one.",
"You need not take it to heart.",
"To take to one's heels.",
"Honesty is the best policy.",
"Look not a gift horse in the mouth.",
"Spare hours.",
"A man's house is his castle.",
"Hunger is the best sauce.",
"There is no hurry.",
"Idleness is the root of all evil.",
"Joking apart.",
"Better late than never.",
"He is as thin as a lath.",
"They laugh best who laugh last.",
"He is laughing in his sleeve.",
"Lightly come, lightly go",
"Listeners never hear good of themselves.",
"Literally.",
"Every little helps.",
"Many a little makes a mickle.",
"Look before you leap.",
"To cast lots.",
"He has left me in the lurch.",
"Man proposes, God disposes.",
"One man's meat is another man's poison.",
"I do not like his manners.",
"He has no manners.",
"Tell that to the marines.",
"To hit the mark.",
"To miss the mark.",
"Like master, like man.",
"As a matter of fact.",
"It is a matter of taste.",
"He does not mince matters.",
"So many men, so many minds.",
"You are in a nice mess now.",
"They are in a mess.",
"In the very middle.",
"It is no use crying over spilt milk.",
"He changed his mind.",
"I gave him a piece of my mind.",
"To be bent on mischief",
"Spare moments.",
"Money begets money.",
"Money makes the mare to go.",
"He owes money to everybody.",
"To make a mountain out of a molehill.",
"There is some mystery here.",
"To hit the nail on the head.",
"Necessity knows no law.",
"To look for a needle in a bundle of hay.",
"A sleepless night.",
"Nothing venture, nothing win.",
"They gave him notice.",
"Now or never.",
"He looks after number one.",
"As old as the hills.",
"Opportunity makes the thief.",
"Patience works wonders.",
"To buy a pig in a poke.",
"To be on pins and needles.",
"The pitcher goes so often to the well that it is broken at last.",
"Let us return to the point.",
"The pot calls the kettle black.",
"Poverty is no crime.",
"Practice makes perfect.",
"The pros and cons.",
"There are two sides to every question.",
"He is quick-tempered.",
"It never rains but it pours.",
"Short reckonings make long friends.",
"Without rhyme or reason.",
"Right or wrong.",
"It served him right.",
"Rome was not built in a day.",
"To rough it.",
"To run away.",
"It is not worth a rush.",
"Safe and sound.",
"Everyone knows where the shoe pinches.",
"Out of sight, out of mind.",
"Silence gives consent.",
"He saved his skin.",
"To sleep over it.",
"No song, no supper.",
"Sooner or later.",
"To call a spade a spade.",
"To keep step.",
"A stitch in time saves nine.",
"Store is no sore.",
"He does not care a straw about it.",
"Little strokes fell great oaks.",
"He is in a brown study.",
"Better to be sure than sorry.",
"One swallow does not make a summer.",
"He is a swell.",
"There is no accounting for tastes.",
"He will never set the Thames on fire.",
"On second thoughts.",
"I am tired of it.",
"To give tit for tat.",
"A slip of the tongue.",
"To sleep like a top.",
"One good turn deserves another.",
"Up-to-date.",
"To make a virtue of necessity.",
"To have a voice in the matter.",
"Everything comes to him who waits.",
"To fish in troubled waters.",
"Still waters run deep.",
"On the way.",
"She does not know which way to turn.",
"Ill weeds grow apace.",
"All's well that ends well.",
"They are well off.",
"It's an ill wind that blows nobody good.",
"Good wine needs no bush.",
"A word to the wise is sufficient.",
"He is at his wits' end.");

function thirdSpanishLine()
{
	global $spanish3lines;
	return $spanish3lines[array_rand($spanish3lines)];
}

?>