<?
//https://archive.org/stream/newpracticaleasy00lensrich/newpracticaleasy00lensrich_djvu.txt

	$swedishlines = array(
"I have.",
"have you?",
"has the gentleman?",
"Yes Sir, I have",
"I have not",
"No Sir",
"something, anything",
"nothing",
"Have you anything?",
"I have nothing",
"I am",
"Are you?",
"Are you hungry?",
"I am hungry",
"Are you thirsty?",
"Are you tired?",
"Are you sleepy?",
"The little man is very conceited",
"He has five sons and four daughters,",
"they are boys and girls",
"Men are not all good.",
"I saw yesterday the workmen, servants and peasant women",
"We sat all Sunday afternoon with the book in our hands",
"The doctors are not all quacks.",
"The evenings become long",
"I like to read novels.",
"Have you mended my boots?",
"You know my habits",
"You preach to deaf ears",
"We do not know the reasons.",
"There were many counts and barons present.",
"Such men are my enemies.",
"Here are rooms to let.",
"I like apples.",
"The hearts are faithful",
"The offices are rare.",
"The seas and the islands.",
"The smiths lifted the hammer up.",
"The ladies are sisters.",
"A house of a prince.",
"Where are the servants?",
"The children's mother.",
"What?",
"For what?",
"What have you?",
"Is this my book?",
"Who has?",
"I am right",
"You are wrong",
"Am I right?",
"No Sir, you are wrong",
"He has the knife",
"He has it.",
"the man is honest",
"the woman is honest",
"the child is honest.",
"The sad girl.",
"The child is pale.",
"A despairing father.",
"I am quiet and cold.",
"The wind is cold.",
"The child is quiet.",
"The new fraud.",
"Great God.",
"he stands like stone",
"He goes out of the door at the right",
"He enters violently",
"The violent man.",
"The rough bear",
"The behaviour of prudent men.",
"The rational behaviour of prudent men.",
"The deck is clean.",
"The ripe ear.",
"I am better than he.",
"he is my worst enemy.",
"he is older than I, but I am calmer than he.",
"My eldest daughter is younger than his youngest son.",
"He is the most pious man",
"He is ruder than you.",
"The heaviest load",
"The highest price",
"Most men.",
"The noblest gentleman and the lowest workman.",
"The smallest fault",
"I saw more men in the street.",
"The worst scamp",
"The nearest house.",
"A more agreeable society.",
"The surest bail",
"The bravest soldier.",
"I gave the book to the most beloved friend.",
"We love him, but he does not love us.",
"Thou canst do it.",
"Did you take it from him?",
"I gave it to you.",
"That is nothing to us.",
"Fortune changes",
"Let her not hear it.",
"Fetch him, I will speak with him alone.",
"How will it go with us?",
"I heard their children.",
"I have wronged my friend.",
"His resolution is taken.",
"Come my friends.",
"He and his daughters.",
"Your mother is still alive",
"Your child will hide from your eyes.",
"She leaned her head on his shoulder.",
"The father, who sees his dying daughter.",
"I will loosen your chains",
"In this house and in that garden.",
"God be praised for this joy",
"It is the first time that I call you by this dear name.",
"This heart is cold.",
"I saw him in the same town.",
"That man's wife is dead.",
"This one here is my friend, that one there is my enemy, and the other is indifferent to me",
"he who says so.",
"Those who believe this.",
"The general under whose command he stood",
"The name under which he serves",
"The princes under whose protection he stood.",
"Who has done this?",
"Whose son is this youth?",
"To whom did we give it?",
"What is that?",
"What do you say?",
"What man can believe such?",
"What cares have you?",
"I gave him all.",
"All men love him.",
"It is another boy.",
"The others are coming",
"Another child.",
"Every body knows him.",
"Every work is useful if one has an object with it.",
"I do not say it to everybody.",
"Nobody is happy",
"They have no child.",
"Many a name is forgotten",
"I saw many flowers",
"Is any one present?",
"There are some strangers coming",
"That is something new",
"The same man.",
"He comes himself.",
"I do not believe such things",
"Some people believe such fables",
"There were three boys, four girls, nineteen men, 25 women, 33 old men and 42 old women",
"The clock strikes six.",
"London has 3 millions, 8 hundred and 50 thousand inhabitants",
"It is the 24 of April.",
"I remained there 5 hours.",
"The clock strikes a quarter past four.",
"That is a double sin",
"Four times I warned him.",
"The first time.",
"The last time.",
"How many times?",
"Three times.",
"Several times",
"How often have you been in the theatre?",
"I was only there twice.",
"What have you done?",
"I have done nothing.",
"Are you ill?",
"No I am not.",
"Do you understand me?",
"I understand you.",
"Did you understand the man?",
"I have understood him.",
"I hear you but I do not understand you.",
"At 9 o'clock in the morning.",
"At 11 o'clock at night.",
"How long?",
"A day.",
"An hour.",
"A minute.",
"An instant.",
"A beautiful town.",
"The water was cold.",
"The fire burned the whole day.",
"He has compensated her for that",
"Mr. A. was an experienced man.",
"Was he alone?",
"He gave them a broad band.",
"They said that they had seen the bank.",
"Has he food?",
"A faint light.",
"Was he strong?",
"It was a custom.",
"He has seen the place.",
"To search for one.",
"The day was clear.",
"He was godfather.",
"Her father was at home.",
"The dew falls.",
"They seize him.",
"Give me a slate-pencil.",
"He caught three fishes.",
"They came in heaps.",
"Can he jump?",
"They consecrate the place.",
"It had been unwholesome to live there.",
"Take my book.",
"She took it away.",
"My card was not there.",
"He has beautiful roses.",
"This parish has only one clergyman.",
"A son.",
"The king was with him.",
"He was in this order.",
"To speak a word.",
"The table was of marble.",
"To the Lord's praise.",
"The most beautiful flower.",
"A flourishing town.",
"A short speech.",
"The cloud spreads.",
"My aunt was with her.",
"A heavy style.",
"A great wall.",
"Have you mortar?",
"Her uncle came into the room.",
"A virtuous woman.",
"The advice is good.",
"The island is very great.",
"To implore our Lord's assistance.",
"This house is higher than that.",
"The moon shone brightly last Monday.",
"She ate four oysters.",
"Eight thieves were taken.",
"She sold the horse.",
"They came before you.",
"The thunder struck the tree.",
"The hay is not dry yet.",
"The darkness increased.",
"It was God's word.",
"The new boot is ready.",
"The lock is new.",
"A Christian ought to act according to his great Master's doctrine.",
"The chief is not with us.",
"The child had the king's evil.",
"The fox took away my dove and killed it.",
"They were very poorly dressed.",
"Charles was very bold.",
"It is so rural here.",
"The choir is broad.",
"This charade is really amusing.",
"The cave was fifty ells deep.",
"She rode in a chaise with one horse.",
"Give him the letter-bag.",
"A spark fell on the floor.",
"The girl had a large collar.",
"This meat is very tough.",
"The man has not shot a single bird.",
"Mr. G. was born in Norway, but is now established in Sweden.",
"I can not approve of what he said.",
"The king favoured this religion.",
"They ascended the mountain.",
"I shot the wolf.",
"There was a whole legion.",
"A real genius.",
"A page came towards me.",
"Is this head cast?",
"Who has done it?",
"Man is mortal.",
"Captain H. has sailed round the world.",
"The colour is scarlet.",
"A beautiful gold chain",
"Can you drive?",
"The girl's petticoat was too long.",
"The stag stopped to rest.",
"She was out in the cold.",
"The heavenly vision which he saw.",
"The man was lame.",
"I saw a little lamb near the mill.",
"As it rains we shall drive home in a carriage.",
"He is a man who has seen the world.",
"The ladies said that there was too much dust.",
"The sweet sound of her voice.",
"The wind sounded in the branches and interrupted the calm.",
"The water was almost lukewarm.",
"Captain P. had a tame lion with him.",
"He is a good shot.",
"Now, while the stars are shining.",
"We were there till the seventh day.",
"The man has served me twenty years.",
"These are his initial letters.",
"How many shares have you?",
"They got only one plate each.",
"The road went in zigzag.",
"She has taken many lessons in music.",
"King Oscar ascended the throne.",
"They had no means of supplying themselves with clothes.",
"He should decide if he would accept this proposition.",
"The mother has punished her child.",
"The young lady had an agate on her finger.",
"K. sent a prohibition.",
"His brother-in-law would not engage to pay the account.",
"Within a short time he had lost all his property at cards.",
"This is a harbinger of evil.",
"He blew the trumpet very well.",
"That lady was so sullen.",
"They had a thermometer in the drawing-room.",
"I was at the theatre yesterday, it was Miss Lind's benefit.",
"Mrs. B's brother has gone through a complete academical course.",
"E. bought ground to build a theatre.",
"On the journey to Rome.",
"They drank only rum.",
"He took a rope with him in the boat.",
"Have you any cure for toothache?",
"Captain A. has been at court.",
"The horse's hoof was injured.",
"He only pretended to pilot the vessel.",
"He had such bad tools.",
"This inkstand is made of tin.",
"His works are published in six volumes.",
"He laid a pea on the card.",
"He had too much sense, to read your letter.",
"This clay is too dry.",
"The knife has a bad edge.",
"They ate eggs for breakfast.",
"This doctrine is false.",
"There was an empty glass on the table.",
"Send a messenger in advance.",
"A fine horse.",
"A great country.",
"A white tooth.",
"Once a week.",
"The industrious bee.",
"Good oysters.",
"A gracious answer.",
"An old idea.",
"A beautiful bridge.",
"The good son's reward.",
"The learned man's advice.",
"Narrow streets.",
"Five heavy swords.",
"Many rooms.",
"The girl's fate.",
"An instructive fable.",
"A beautiful voice.",
"He has my new book.",
"We were in their garden.",
"The boy took his hat.",
"Have you been there?",
"Was she in herself?",
"The dogs bit each other.",
"They exerted themselves.",
"This house is larger than that.",
"Has the soldier hurt himself?",
"Those books are more interesting than these.",
"Your chamber is smaller than mine.",
"John has lost his gloves.",
"Has Mr. N. his own horses?",
"Charles had taken his paper.",
"Whose carriage is this?",
"One of the two must go.",
"What has he there?",
"Whom did you see?",
"Which are the most beautiful?",
"What a beautiful prospect!",
"One must not expect too much from children.",
"What a beauty she is!",
"Have you any book to lend me?",
"It makes one laugh.",
"One must defend oneself.",
"Did you see any thing?",
"I go to him every day.",
"Which will you take?",
"Has she another pen?",
"They have other plans.",
"The girl took her money.",
"We have been there.",
"The captain has called us.",
"Mr. B. had honoured me.",
"Shall the man wail?",
"Where does your brother sit?",
"Is the king loved by his people?",
"Her mother lived then.",
"The boy was silent.",
"I laid the knife on the table.",
"It lies there still.",
"They went to town.",
"It was said in my presence.",
"He has made this frame well.",
"He dies of starvation.",
"The time approaches.",
"Where does your brother-in-law live?",
"We heard Miss Lind sing",
"The enemy has lied.",
"His sister plays well.",
"The servant leads the horse.",
"She had invited me.",
"They live in New Street.",
"He buys iron.",
"The girl is ashamed.",
"They read German.",
"The general says that it was done yesterday.",
"The dog stands out there.",
"We shall travel to London.",
"The ass drew the cart.",
"Have you found the book?",
"The pigeon flies over the roof.",
"The tree grows",
"The thief has stolen a coat.",
"The swan swam over the lake.",
"He obliges me to speak.",
"The horse bites him.",
"The officer commands.",
"He is feared.",
"The candle burns.",
"The coachman heals the horses.",
"It freezes to day.",
"It sounds so beautifully.",
"The wall falls.",
"The vessel sinks.",
"Mr. B. was at home.",
"They were in when I came there.",
"Where have you been?",
"He goes home willingly.",
"Her sister rode very slowly.",
"James rises early.",
"It is well done.",
"She can not come.",
"I have been here long.",
"The picture is painted by Professor S.",
"We went through three rooms.",
"The statue stood between two pillars.",
"You drove too quickly down the hill.",
"Shall we walk up this mountain?",
"This cloth was bought at Mr. B's.",
"At what time shall you start?",
"He has lived partly with me, and partly at my brother's.",
"The lamb came again to us.",
"If Robert comes, send him to me.",
"Neither he nor I can be there.",
"When can this be ready?",
"It was not my hat, but yours that he took.",
"We saw the ship as it sailed past.",
"He has concealed hundreds of ducats.",
"These heads are badly done.",
"She sat behind us.",
"Did he come when you called?",
"The enemy came against us.",
"This man has also been there.",
"He called upon us now and then.",
"The girl draws tolerably well.",
"The regiment marched forward.",
"Did the sound come from without or within?",
"I want a ticket for the first class.",
"I want a ticket for the second class.",
"What is the name of the steamer?",
"When shall we be in S.?",
"Do you know a good hotel there?",
"Yes, the hotel X.",
"I only remain here one hour and proceed at once.",
"I only stay here over night, and leave to morrow early.",
"The train is starting.",
"What is the name of the next station?",
"May one smoke here?",
"No; that is only permitted in the smoking coupe.",
"Can I offer you a cigar?",
"No thanks, I do not smoke.",
"What beautiful country we are passing through!",
"How far is it to the next station?",
"We are soon there.",
"We shall soon be at the station, where we dine.",
"What is the name of that pretty estate on the left?",
"What is the name of that pretty church on the right?",
"The train stops.",
"We are at the station.",
"Are you hungry?",
"I have a good appetite.",
"I am very hungry.",
"Eat something.",
"What will you eat?",
"What do you wish to eat?",
"You do not eat.",
"I beg your pardon,",
"I have eaten very heartily.",
"I have dined with a good appetite.",
"Eat another piece.",
"I can eat no more.",
"Are you thirsty?",
"Are you not thirsty?",
"I am very thirsty.",
"I am dying of thirst.",
"Let us drink.",
"Give me something to drink.",
"Will you drink a glass of wine?",
"Drink a glass of beer.",
"Drink another glass of wine.",
"Sir, I drink to your health.",
"I have the honour to drink your health.",
"Where are you going?",
"I am going home.",
"I was going.to your house.",
"From whence do you come?",
"I come from my brother's.",
"I am coming from church.",
"I have just left the school.",
"Will you go with me?",
"Where do you wish to go?",
"We will take a walk.",
"With all my heart; most willingly.",
"Which way shall we go?",
"Any way you like.",
"Let us go into the park.",
"Let us call for your brother on our way.",
"As you please.",
"Is Mr. B. at home?",
"He is gone out.",
"He is not at home.",
"Can you tell us where he is gone?",
"I cannot tell you precisely.",
"I think he is gone to see his sister.",
"Do you know when he will come back?",
"No, he said nothing when he went out.",
"Then we must go without him.",
"Come nearer; I have something to tell you.",
"I have a word to say to you.",
"Listen to me.",
"I want to speak to you.",
"What is it you want?",
"I am speaking to you.",
"I am not speaking to you.",
"What do you say?",
"What did you say?",
"I say nothing.",
"Do you understand?",
"Do you understand what I say?",
"Do you understand me?",
"Will you be so kind as to repeat...?",
"I understand you well.",
"Why do you not answer me?",
"Do you not speak Swedish?",
"Very little, Sir.",
"I understand it a little, hut I do not speak.",
"Speak louder.",
"Do not speak so loud.",
"Do not make so much noise.",
"Hold your tongue.",
"Did you not tell me that?",
"Who told you that?",
"They have told me so.",
"Somebody has told it me.",
"I have heard it.",
"What do you wish to say?",
"What is that good for?",
"What do you call that?",
"Do you know Mr. C?",
"I know him by sight.",
"I know him by name.",
"How old are you?",
"How old is your brother?",
"I am twelve years old.",
"I am ten years and six months old.",
"Next month I shall be sixteen years old.",
"I was thirteen years old last week.",
"You do not look so old.",
"You look older.",
"I thought you were older.",
"I did not think you were so old.",
"How old may your uncle be?",
"He may be sixty years old.",
"He is about sixty years old.",
"He is more than fifty years old.",
"He is a man of fifty and upwards.",
"He may be sixty or thereabouts.",
"He is over eighty.",
"That is a great age.",
"Is he so old?",
"He begins to grow old.",
"What o'clock is it?",
"Pray tell me what time it is?",
"It is one o'clock.",
"It is past one.",
"It has struck one.",
"It is a quarter past one.",
"It is half past one.",
"It wants ten minutes to two.",
"It is not yet two o'clock.",
"It is only twelve o'clock.",
"It is almost three o'clock.",
"It is on the stroke of three.",
"It is going to strike three.",
"It is ten minutes past three.",
"The clock is going to strike.",
"There the clock is striking.",
"It is not late.",
"It is later than I thought.",
"I did not think it was so late.",
"What kind of weather is it?",
"It is bad weather.",
"It is very cloudy.",
"It is dreadful weather.",
"It is fine weather.",
"We are going to have a fine day.",
"It thaws.",
"It is foggy.",
"It is rainy weather.",
"It threatens to rain.",
"The sky becomes very cloudy.",
"The sky is getting very dark.",
"The sun is coming out.",
"The weather is clearing up again.",
"It is very hot.",
"It is sultry.",
"It is very mild.",
"It is cold.",
"It is excessively cold.",
"It is raw weather.",
"It rains.",
"It has been raining.",
"It is going to rain.",
"I feel some drops of rain.",
"There are some drops of rain falling.",
"It hails.",
"It snows;",
"it is snowing.",
"It has been snowing.",
"It snows in large flakes.",
"It freezes.",
"It has frozen.",
"It begins to thaw.",
"It thaws.",
"It is very windy.",
"The wind is very high.",
"There is no air stirring.",
"It lightens.",
"It has lightened all night.",
"It thunders.",
"The thunder roars.",
"The thunderbolt has fallen.",
"It is stormy weather.",
"We shall have a thunderstorm.",
"The sky begins to clear up.",
"The weather is very unsettled.",
"It's very muddy.",
"It's very dusty.",
"It's very slippery,",
"It's bad walking.",
"It's daylight.",
"It's dark.",
"It's night.",
"It's moonlight.",
"Do you think it will be fine weather?",
"I do not think that it will rain.",
"I am afraid it will rain.",
"I fear so",
"Good day, Sir.",
"I wish you good day.",
"How do you do?",
"How are you?",
"Do you continue in good health?",
"Pretty good;",
"and how are you?",
"Are you well?",
"Very well, and you?",
"I am perfectly well.",
"And how is it with you?",
"As usual.",
"Pretty well, thank God.",
"I am very happy to see you well.",
"There is a knock.",
"Somebody knocks.",
"Go and see who it is.",
"Go and open the door.",
"It is Mrs. B.",
"Good day, Mrs. B.",
"I am happy to see you.",
"I have not seen you this age.",
"It is a novelty to see you.",
"Pray sit down.",
"Sit down if you please.",
"Give the lady a chair.",
"Will you stay and take some dinner with us?",
"I cannot stay.",
"I only came in to see how you are.",
"I must go.",
"You are in a great hurry.",
"Why are you in such a hurry?",
"I have a great many things to do.",
"Surely you can stay a little longer.",
"I will stay longer another time.",
"I thank you for your visit.",
"I hope to see you soon again.",
"Have you breakfasted?",
"Not yet.",
"You have come just in time.",
"You will breakfast with us.",
"Breakfast is ready.",
"Do you drink tea or coffee?",
"Would you prefer chocolate?",
"I prefer coffee.",
"What can I offer you?",
"Here are rolls and toast.",
"What do you like best?",
"I shall take a roll.",
"How do you like the coffee?",
"Is the coffee strong enough?",
"It is excellent.",
"Is there enough sugar in it?",
"If there is not, do not make any ceremony.",
"Act as if you were at home.",
"At what time do we dine today?",
"We shall dine at four o'clock.",
"We shall not dine before five o'clock.",
"Shall we have anybody to dinner to-day?",
"Do you expect company?",
"I expect Mr. B.",
"Mr. D. has promised to come if the weather permits.",
"Have you given orders for dinner?",
"What have you ordered for dinner?",
"Have you sent for fish?",
"I could not get any fish.",
"I fear we shall have a very indifferent dinner.",
"We must do as best we can.",
"To what shall I help you?",
"Will you lake a little soup?",
"No I thank you.",
"I will trouble you for a little beef.",
"It looks so very nice.",
"Which piece do you like best?",
"I hope you like this piece.",
"Gentlemen, you have dishes near you.",
"Help yourselves.",
"Take without ceremony what you like best.",
"Would you like a little of this roast-meat?",
"Will you have some fat?",
"Give me some of this lean, if you please.",
"How do you like the roast-meat?",
"It is excellent, delicious.",
"What will you take with your meat?",
"May I help you to some vegetables?",
"Will you take peas or cauliflower?",
"I have no choice.",
"I shall send you a piece of this fowl.",
"No thank you, I can eat no more.",
"You are a poor eater.",
"You eat nothing.",
"I beg your pardon, I do justice to your dinner.",
"You may take away.",
"Have you carried in the tea things?",
"Everything is on the table.",
"Does the water boil?",
"Tea is ready.",
"They are waiting for you.",
"Here I am.",
"We have not cups enough.",
"We want two more cups and saucers.",
"Bring another tea-spoon and a saucer.",
"You have not brought in the sugar-tongs.",
"Do you take cream?",
"The tea is so strong.",
"I shall thank you for a little more milk.",
"Here are cakes and muffins.",
"Do you prefer some bread and butter?",
"I shall take a slice of bread and butter.",
"Pass the plate this way.",
"Ring the bell, if you please.",
"Will you kindly ring the bell?",
"We want some more water.",
"Bring it as quickly as possible.",
"Make haste.",
"Take the plate with you.",
"Is your tea sweet enough?",
"Have I put sugar enough in your tea?",
"It is excellent.",
"I do not like it quite so sweet.",
"Your tea is very good.",
"Where do you buy it?",
"Have you already done?",
"You will take another cup.",
"I shall pour you out half a cup.",
"You will not refuse me.",
"I have already drunk three cups and I never drink more.",
"What have you to tell me?",
"You have the book which I had yesterday",
"I have never had it, and you will not have it either",
"I wish you had the ribbon",
"We would have had it.",
"To possess is better than to have had, or to expect.",
"He would be very happy if he were content.",
"Are you my enemy?",
"I have never been so, I am not now and shall never be.",
"You will be with me tomorrow.",
"You have already been there, but my brother has not yet been;",
"you were not at home.",
"I had been there when he came.",
"They will have all been there to-morrow",
"we would already have been there but it was impossible.",
"Be happy my children!",
"To be or not to be, that is the question.",
"That I might be loved.",
"I was heard.",
"I have been heard.",
"I had been heard.",
"I shall be heard.",
"I may be heard.",
"I might be heard.",
"I may have been heard.",
"I might be drawn.",
"This painting is by Mr. B.",
"The boy was sent by his father.",
"The work is of value.",
"The letter of the 6th.",
"He turned off to the left.",
"They were beside themselves with joy.",
"It did not take place.",
"Well, you will see him no more.",
"Can you not deduct a little?",
"He killed himself.",
"They undressed.",
"He forgot his part.",
"The rope broke.",
"He had his portrait taken.",
"I ran against him in the dark.",
"They were very kind to the child.",
"It was towards 12 o'clock when he came.",
"The girl went there contrary to my wish.",
"We went to meet him.",
"Mr. B. does not vote for me.",
"No human being is free from faults.",
"What is she about now?",
"He would be by himself.",
"That will surely succeed.",
"He cannot help it.",
"Beware of him.",
"I was very unfortunate.",
"I accused him of that.",
"The chill went through the room.",
"He gained his object by perseverance.",
"I heard of this through him.",
"They had a party at Mr. S's.",
"The printer was with him yesterday.",
"He lives at Mr. L's.",
"They have never been at my house.",
"He was apprenticed to Mr. B.",
"I send the accompanying letter.",
"He had no money about him.",
"We do not do so in our country.",
"Come and sit by me.",
"He envies virtue in others.",
"Captain S. has been in Rome.",
"At first I saw nothing.",
"The seamstress was here today.",
"The journeyman has twenty riksdalers a week.",
"The men set the house on fire.",
"I will pack up my things.",
"They came in one at a time.",
"You shall drink it all.",
"Next Whitsuntide I shall go there.",
"Last winter it was very cold.",
"Were you there last year?",
"The book lay among my things.",
"We read German sometimes.",
"Sometimes he came to us.",
"The officer had two soldiers with him.",
"The picture was full of holes.",
"Were you not also there?",
"The boy is related to them.",
"Good night to you.",
"I saw no fault in her.",
"He felled the ox at a blow.",
"He put his arms round his neck",
"What was it she was speaking about?",
"You must do this again.",
"They came at night.",
"What shall we play for?",
"You can come again in a week.",
"It lies on the table.",
"He was jealous of him.",
"As proof of the truth.",
"They had waited for the carnage.",
"I knew him by his walk.",
"Is it not in fashion now?",
"He said it in jest,",
"To be sure of any thing.",
"I was not prepared for that.",
"When were you at the theatre?",
"We are in the gallery.",
"The boy flung a stone al her.",
"He was soon tired of that.",
"The colonel sent him to me.",
"Will you not have another cup?",
"B. is a carpenter by trade.",
"I know him by sight.",
"Mr. B's son is at sea.",
"I am at your service.",
"He was on horse-back.",
"Wait until I come.",
"His estate bordered on mine.",
"We were there till eleven o'clock.",
"He kept his bed.",
"I shall get that book.",
"He did not exist then.",
"Oscar was crowned king.",
"How do you do?",
"I have done as he wished.",
"He made a memorandum of it.",
"We sat at the table.",
"He has become tired of that book.",
"I was separated from him.",
"The house stands near the river.",
"A person by name S.",
"On my honour.",
"At the beginning.",
"On the soldier's arrival.",
"He has lived under my roof.",
"She is not up to her sister in French.",
"It was beneath his dignity.",
"During the time of Georg IVth.",
"It was under pretence of.",
"The prisoner went beyond the walls.",
"He has two rooms besides this floor.",
"The man was beside himself.",
"We were walking outside the boundaries.",
"What the deuce!",
"God forbid!",
"Mercy on me!",
"Well!",
"Well, well!",
"Thanks!",
"Listen!",
"This way!",
"Silence!");

function firstSwedishLine()
{
	global $swedishlines;
	return $swedishlines[array_rand($swedishlines)];
}

?>